### ISSUE TITLE
StanHeaders 2.10.0 will slightly break multi_normal_sufficient.hpp

### ISSUE THREAD

**Issue by bgoodri** [OpenMx/OpenMx#10]
The StanHeaders 2.10.0 R package, which will be released on CRAN in a couple of days, moves a header file, which causes `R CMD check` to fail for OpenMx with
```
multi_normal_sufficient.hpp:15:54: fatal error: stan/math/prim/scal/meta/VectorViewMvt.hpp: No such file or directory
```
This can be fixed by changing
```
#include <stan/math/prim/scal/meta/VectorViewMvt.hpp>
```
 in multi_normal_sufficient.hpp to
```
#include <stan/math/prim/mat/meta/VectorViewMvt.hpp>
```

**Comment by bgoodri** [comment]
And StanHeaders 2.10.0 is on CRAN now.

**Comment by jpritikin** [comment]
Applied
