### ISSUE TITLE
mxPath error with connect="unique.bivariate" and single from= element

### ISSUE THREAD

**Issue by trbrick** [OpenMx/OpenMx#101]
mxPath throws a confusing error if you call it with a single string element in the from= argument, and connect="unique.bivariate".

Code to reproduce:
```R
mxPath(from="x", connect="unique.bivariate")
```
> Error: mxPath() call will generate 0 paths but you have specified 1 arrows with 'from' argument assigned to NULL and 'to' argument assigned to NA

The error is the same if you choose arrows=2, which makes the "you have specified 1 arrows" part of the error even more confusing.

**Comment by jpritikin** [comment]
v2.9.9-292-gdd0ae81b4
