### ISSUE TITLE
write a simple test for mxCompareMatrix

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#102]
We have 1 test in nightly, but it wasn't testing much since mxCompareMatrix was broken until v2.9.9-303-g6921f6bb6

**Comment by tbates** [comment]
asks for base (not a parameter)
```
mxCompareMatrix(base=fit1,models=fit2)
Error in mxCompareMatrix(base = fit1, models = fit2) : 
  mxCompareMatrix does not accept values for the '...' argument
```
asks about a ...
```
mxCompareMatrix(base=fit1,models=fit2)
Error in mxCompareMatrix(base = fit1, models = fit2) : 
  mxCompareMatrix does not accept values for the '...' argument
```

**Comment by tbates** [comment]
given two models in models, it asks for base

```
mxCompareMatrix(models= c(fit1,fit2))
Error in mxCompareMatrix(models = c(fit1, fit2)) : 
  object 'base' not found
```

**Comment by jpritikin** [comment]
Try with v2.9.9-303-g6921f6bb6 or newer

**Comment by tbates** [comment]
with version `2.9.9.304 [GIT v2.9.9-304-ga46f9c5]`, returns error:

```
mxCompareMatrix(models= c(fit1,fit2))
Error in mxCompareMatrix(models = c(fit1, fit2)) : 
  Available statistics are: 'base', 'comparison', 'ep', 'minus2LL', 'df', 'AIC', 'diffLL', 'diffdf', and 'p'
>

**Comment by jpritikin** [comment]
Add statistic=c("minus2LL",'p')

**Comment by jpritikin** [comment]
mxCompareMatrix <- function(models,
			    diag=c('minus2LL','ep','df','AIC'),
			    stat=c('diffLL','diffdf','p'), ...,

**Comment by jpritikin** [comment]
Try again with v2.9.9-305-g5eeb555e6

**Comment by mcneale** [comment]
Did v2.9.9-305-g5eeb555e6 fix it?  Seems like error messages specifically about which arguments are present, and which are required, are needed to make it easier to self-debug.

**Comment by tbates** [comment]
unhelpful error:
```R
mxCompareMatrix(base=fit1, models=fit2)
Error in mxCompareMatrix(base = fit1, models = fit2) : 
  mxCompareMatrix does not accept values for the '...' argument 'base'
```
Perhaps if given two models should say "please provide models in a vector, e.g. models = c(m1, m2)

something that did work is now broken:

```R
mxCompareMatrix(models= c(fit1,fit2), statistic=c('minus2LL', 'diffLL'))
Error in mxCompareMatrix(models = c(fit1, fit2), statistic = c("minus2LL",  : 
  mxCompareMatrix does not accept values for the '...' argument 'statistic'
```

**Comment by tbates** [comment]
OK to close?

This all seems OK now - it was mostly changes to the interface during development

1. set up some models

```R
require(umx); data(demoOneFactor)

manifests = names(demoOneFactor)
m1 = umxRAM("OneFactor", data = demoOneFactor,
	umxPath("G1", to = manifests),
	umxPath(v.m. = manifests),
	umxPath(v1m0 = "G1")
)

m2 = umxRAM("TwoFactor", data = demoOneFactor,
	umxPath("G1", to = manifests[1:3]),
	umxPath("G2", to = manifests[4:5]),
	umxPath(v.m. = manifests),
	umxPath(v1m0 = c("G1", "G2"))
)

m3 = umxRAM("AnotherFactor", data = demoOneFactor,
	umxPath("G1", to = manifests[c(1,2,5)]),
	umxPath("G2", to = manifests[c(3,4)]),
	umxPath(v.m. = manifests),
	umxPath(v1m0 = c("G1", "G2"))
)
```

## Now do some work

```R
mxCompareMatrix(models= c(m1, m2))
```

||OneFactor|TwoFactor|
|--|--|--|
|OneFactor|934.096|NA|
|TwoFactor|NA|2138.453|

```R
mxCompareMatrix(models= c(m1,m2, m3), diag='minus2LL', stat='diffLL')
```
||OneFactor|TwoFactor|AnotherFactor|
|--|--|--|--|
|OneFactor|934.096|-1204.36|-1259.86|
|TwoFactor|1204.36|2138.45|-55.50|
|AnotherFactor|1259.86|55.50|2193.96|
