### ISSUE TITLE
test defvar.row argument to mxComputeManifestByParJacobian 

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#103]

**Comment by tbates** [comment]
Can this be closed? I don't see any mention of `mxComputeManifestByParJacobian` in the code

**Comment by RMKirkpatrick** [comment]
I think `mxComputeManifestByParJacobian()` was the prototype name for `omxManifestModelByParameterJacobian()`, which does appear in OpenMx's frontend code: it's defined starting on line 542 of R/MxExpectationNormal.R .  It's also tested in models/passing/ContinuousOnlyWLSTest.R and tests/testthat/test-ModelIdentification2.R , the latter of which does use the `defvar.row` argument.

So I'd say yes, this can be closed.
