### ISSUE TITLE
better error for ULS DWLS SE error

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#106]
Models with DWLS or ULS data return the following error when the user tries to run an mxCI
```
Error in runHelper(model, frontendStart, intervals, silent, suppressWarnings,  : 
  Confidence intervals are not supported for units r'Wr
```

Might be nice to add something to note what rWr units are or rather to say not supported for data of type  <insert data type>. Might also suggest user try WLS, or look at the SEs ?

**Comment by jpritikin** [comment]
I don't think CIs are implemented for WLS yet. We could investigate an implementation once we have the chi^2 calculation in the backend.

Would it help to suggest mxSE?

**Comment by RMKirkpatrick** [comment]
CIs are implemented for WLS.  There's even a test: models/passing/WLS+CI.R .  But they can only be calculated with full WLS.

It might be better if the error message said that CIs aren't supported for DWLS or ULS.  Joshua's idea of suggesting `mxSE()` might be good, too.

**Comment by jpritikin** [comment]
@RMKirkpatrick Oh! Nice.

Anyway, the message to change is around line 108 of src/omxFitFunction.cpp. At that point in the code, we don't know what kind of weight matrix we are using. So we probably need to catch this situation in the frontend.

**Comment by tbates** [comment]
Makes sense, something like:
> CIs are not supported for DWLS or ULS. For now, perhaps try mxSE or switch your model to WLS for the CIs

Assuming that mxSE will work).

**Comment by mcneale** [comment]
The thing about the nanny-state approach - stopping people from doing something possibly stupid - is that we prevent them from testing how very stupid such a CI might be.  It might be pretty decent sometimes, and efficient to boot (pun intended).  I suppose they could substitute in the diagonal of a full weight matrix and get OpenMx to unknowingly do the wrong thing?

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Sep 11, 2018, at 4:13 PM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


Makes sense, something like:

CIs are not supported for DWLS or ULS. For now, perhaps try mxSE or switch your model to WLS for the CIs

Assuming that mxSE will work).

**Comment by RMKirkpatrick** [comment]
@tbates : Sounds good, except strike "For now".  I don't believe our kind of CIs can ever be implemented even in theory for DWLS and ULS, because those fitfunction values aren't asymptotically distributed as chi-square.

**Comment by RMKirkpatrick** [comment]
@mcneale :  ??  I don't follow.

**Comment by mcneale** [comment]
ML estimates have the nice properties that they are asymptotically unbiased, and have minimum variance of all such estimators with this property.  Ergo, alternative estimators that have less bias and the same or less variance for a given sample size cannot be asymptotically unbiased.  Some estimators might have greater variance, and be asymptotically unbiased; others may have less bias at most realistic finite sample sizes.  We are making it more difficult for people to use probably inappropriate CIs, which is good.  At the same time we are making research into the statistical properties of DWLS and other estimators more difficult.  Fortunately, such activities are likely to be confined to expert users, and they may figure out that this research can be done with OpenMx with user-defined fit functions.  Or manually swapping a full weight matrix for a diagonal one within an mxDataWLS object.

**Comment by jpritikin** [comment]
v2.11.3-4-g7083597df

**Comment by tbates** [comment]
PS: when you post something like "v2.11.3-4-g7083597df", what are we supposed to do to get to the commit that was made to fix the issue?

https://github.com/OpenMx/OpenMx/search?q=v2.11.3-4-g7083597df&type=Commits

reveals no matches in the repo for  that string.

**Comment by RMKirkpatrick** [comment]
@tbates Look for 7083597df.

I believe just typing the first 7 or so characters of the hash and posting the comment will create a hyperlink in your post, e.g. 7083597 .

**Comment by jpritikin** [comment]
On Thu, Sep 20, 2018 at 08:36:36AM -0700, Tim Bates wrote:
>    PS: when you post something like "v2.11.3-4-g7083597df", what are we
>    supposed to do to get to the commit that was made to fix the issue?

Search for the hex code after the '-g'. So search for 7083597df

>    [1]https://github.com/OpenMx/OpenMx/search?q=v2.11.3-4-g7083597df&type=
>    Commits
> 
>    reveals no matches in the repo for that string.

That's because I cheated and amended the commit. The revised commit is 
3b50b8c53

https://github.com/OpenMx/OpenMx/search?q=3b50b8c53&type=Commits

**Comment by tbates** [comment]
cool:  7083597 works great!
