### ISSUE TITLE
CSOLNP can still grind to a near-halt with MxConstraints.

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#108]
Per [this forums thread](https://openmx.ssri.psu.edu/node/4383).  I should have opened this issue a while ago...

**Comment by RMKirkpatrick** [comment]
Attached is an example, adapted from the scripts in the thread linked in the OP.
[180926--CSOLNP_hangs.R.txt](https://github.com/OpenMx/OpenMx/files/2424588/180926--CSOLNP_hangs.R.txt)

**Comment by RMKirkpatrick** [comment]
However, I'm pleased to say that none of the three models in this script cause CSOLNP to hang anymore.
[180209e.R.txt](https://github.com/OpenMx/OpenMx/files/2424601/180209e.R.txt)

**Comment by tbates** [comment]
should we close this will not fix?

**Comment by jpritikin** [comment]
In my opinion, no. It's a serious drawback to using the optimizer.

**Comment by RMKirkpatrick** [comment]
Agreed.  It is a serious drawback.  Unfortunately, I don't really understand why it happens.  Mahsa thought she had fixed the issue, and her fixes enabled CSOLNP to run all 3 models in 180209e.R (above).  But, CSOLNP still sometimes gets stuck with MxConstraints.

**Comment by RMKirkpatrick** [comment]
I think this issue has something to do with the issue of redundant equality constraints.  In fact, this issue may simply be a specific manifestation of that issue.  [180926--CSOLNP_hangs.R.txt](https://github.com/OpenMx/OpenMx/files/2424588/180926--CSOLNP_hangs.R.txt) does indeed contain redundant equality constraints.  There are 12 constraints in total, but only 9 of them are non-redundant.  That's because the set of constraints involves elements both above and below the main diagonals of covariance matrices, which elements are necessarily equal to each other by symmetry.

I attach [190315--CSOLNP_hangs.R.txt](https://github.com/OpenMx/OpenMx/files/2973175/190315--CSOLNP_hangs.R.txt), which is a modification of 180926--CSOLNP_hangs.R.txt .  It first fits the same model as before with both NPSOL and SLSQP,  NPSOL silently reaches a really bad solution; SLSQP reaches a half-decent but non-feasible (status code 3) solution.  The script doesn't try it with CSOLNP, because we already know it hangs.

Then, the script tries fitting the model without the redundant constraints, with all 3 gradient-based optimizers.  NPSOL reaches a poor but feasible solution.  SLSQP reaches a terrible solution that isn't even feasible (status code 3).  But CSOLNP reaches a feasible, _good_ solution!

For the sake of comparison, the script finally uses all 3 of the optimizers to fit the model with no MxConstraints.  All 3 reach a good solution that has a fit value about 120 fit units better than CSOLNP's good constrained solution.

I'm running what is currently bleeding edge:
```
OpenMx version: 2.12.2.169 [GIT v2.12.2-169-gb745620a-dirty]
R version: R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu
Default optimizer: CSOLNP
NPSOL-enabled?: Yes
OpenMP-enabled?: Yes
```

I must say, I'm really surprised how ineffective NPSOL and SLSQP are for solving this optimization problem.

**Comment by mcneale** [comment]
Kudos for CSOLNP though. A check for redundancy shouldn’t be too hard to implement, I think. What’s odd is that NPSOL, which handles underidentied models decently, gets tripped up. Could send it to NPSOL’s dev team perhaps.

**Comment by RMKirkpatrick** [comment]
@jpritikin Are you able to reproduce NPSOL's behavior here?

**Comment by RMKirkpatrick** [comment]
Also, I wonder if all 3 gradient-based optimizers can reach a good solution via `mxTryHard()`?

**Comment by jpritikin** [comment]
Here are results from gcc 7.3, [gcc7.log](https://github.com/OpenMx/OpenMx/files/2978796/gcc7.log)

**Comment by mcneale** [comment]
Doesn’t look like it: (SLSQP  first, not half as good in -2lnL  as NPSOL).

CSOLNP Indeed gets stuck for hours with this problem on my  system, the other two run in a few seconds.

![PastedGraphic-1-1](https://user-images.githubusercontent.com/2318093/54557576-dab6a800-4991-11e9-8118-1c8c65383b51.jpg)

**Comment by mcneale** [comment]
Removing the redundant constraints with vech() doesn't seem to help CSOLNP one bit; the other two do fine though:

> sat_modelNP <- mxTryHard(sat_model)
                                                                                 
Retry limit reached; solution not found.  Best fit=10246.32 (started at 48882.721)  (11 attempt(s): 11 valid, 0 errors)

Warning message:
In mxTryHard(sat_model) :
  argument 'checkHess' coerced to FALSE due to presence of MxConstraints
> 
> mxOption(NULL,"Default Optimizer", "NPSOL")
> sat_model <- def_sat_model(twinData, 'zyg2', vars)
> sat_modelCS <- mxTryHard(sat_model)
                                                                             
Solution found!  Final fit=10246.32 (started at 48882.721)  (1 attempt(s): 1 valid, 0 errors)

Warning message:
In mxTryHard(sat_model) :
  argument 'checkHess' coerced to FALSE due to presence of MxConstraints
> 
> mxOption(NULL,"Default Optimizer", "CSOLNP")
> sat_model <- def_sat_model(twinData, 'zyg2', vars)
> # wait for it... it will hang if you run it: sat_modelCS <- mxTryHard(sat_model)

**Comment by RMKirkpatrick** [comment]
@mcneale You should probably set the RNG seed to be the same before each call to `mxTryHard()`.

**Comment by mcneale** [comment]
True.  Did that, same results.  CSOLNP still DEFINITELY hangs with this one.  I end up with R not responding for hours (and not eating much cpu).  Even with vech() to eliminate redundant constraints across the diagonal of the covariance matrix.

**Comment by RMKirkpatrick** [comment]
@mcneale What was your RNG seed?

**Comment by mcneale** [comment]
@RMKirkpatrick set.seed(9875382)

**Comment by tbates** [comment]
Not sure if it's related, but this hangs with CSOLNP, and not with SLSQP.

```R
mData = matrix (1)
dimnames(mData) = list(c("X"), c("X"))

m1 = mxModel("one_is_the_loneliest_number", type="RAM",
	manifestVars = "X",
	mxPath("X", arrows=2, lbound=0),
	mxData(mData, type="cov", numObs = 10)
)
umx_set_optimizer("SLSQP")
m1 = mxRun(m1) # runs fine

umx_set_optimizer("CSOLNP")
m1 = mxRun(m1)
# will not get to here
```

runs fine without the lbound on variance at 0

**Comment by mcneale** [comment]
Is the other CSOLNP hang also when a parameter is at its boundary?

**Comment by jpritikin** [comment]
> runs fine without the lbound on variance at 0

I cannot reproduce this failure. Both optimizers seem to run fine.

OpenMx version: 2.12.2.225 [GIT v2.12.2-225-ga61aae17f-dirty]
R version: R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu
Default optimizer: CSOLNP
NPSOL-enabled?: No
OpenMP-enabled?: Yes

**Comment by jpritikin** [comment]
Ah wait, the starting values are important. I can reproduce the hang like this,

```
library(umx)

mData = matrix (1)
dimnames(mData) = list(c("X"), c("X"))

m1 = mxModel("one_is_the_loneliest_number", type="RAM",
             manifestVars = "X",
             mxPath("X", arrows=2, lbound=0),
             mxData(mData, type="cov", numObs = 10)
)

umx_set_optimizer("SLSQP")
m1f = mxRun(m1) # runs fine

umx_set_optimizer("CSOLNP")
m1f = mxRun(m1)
# will not get to here
```

**Comment by mcneale** [comment]
Is there some way we can see WTF it's doing?

**Comment by jpritikin** [comment]
Sure, use `gdb`

**Comment by RMKirkpatrick** [comment]
It's troubling that CSOLNP hangs while optimizing a single free parameter!

**Comment by RMKirkpatrick** [comment]
I tried running that 1-parameter script with CSOLNP under gdb.  CSOLNP appears to be getting caught in a closed 'while' loop, starting at line 1053 of src/asubnp.cpp .

**Comment by RMKirkpatrick** [comment]
If I add a call to `R_CheckUserInterrupt()` to line 1132 of src/asubnp.cpp , I can interrupt the backend when I run that 1-parameter script and CSOLNP hangs.  I don't know what that block of code (lines 1053 thru 1132) does exactly, but it seemed pretty clear when I ran it under gdb that the condition to end the loop would never be met.

So, that's one possible place where CSOLNP is getting stuck.

**Comment by RMKirkpatrick** [comment]
And, if I add a call to `R_CheckUserInterrupt(); at line 1317, which is at the end of a different 'while' loop, I can interrupt the CSOLNP backend while running 180926--CSOLNP_hangs.R .

**Comment by RMKirkpatrick** [comment]
Joshua explained to me his thread-safe API to `R_CheckUserInterrupt()`.  So, first of all, let's make the endless 'while' loops interruptable.  See d438254 .

**Comment by tbates** [comment]
Just to say that it's very nice that escape now works: nice!

**Comment by RMKirkpatrick** [comment]
Recall that, at the meeting last Friday, Tim Brick suggested that we see if Rsolnp hangs the way CSOLNP does.  See the attached script [190403--Rsolnp.R.txt](https://github.com/OpenMx/OpenMx/files/3039845/190403--Rsolnp.R.txt).  Rsolnp does indeed hang after its first major iteration.  Note what the 'trace' printing says about the first major iteration:
```
solnp-->Minor optimization routine did not converge in the 
solnp-->specified number of minor iterations.  You may need
solnp-->to increase the number of minor iterations.        

Iter: 1 fn: 32.5480	 Pars:  24.99816
```

I'm not sure yet if that has anything to do with the hang.

**Comment by RMKirkpatrick** [comment]
As of cd50601 , CSOLNP can successfully solve the one-parameter model.  We'll see if that commit breaks any tests; maybe there are cases where CSOLNP has to run its 'while' loops for more than a million cycles.

@tbates Do you know of any other instances in which CSOLNP hangs, and _not_ due to redundant equality constraints?

**Comment by tbates** [comment]
@RMKirkpatrick - good progress: not yet, I'll keep my edge-case eye open :-)

**Comment by RMKirkpatrick** [comment]
So, the user can now interrupt the loops in which CSOLNP used to get stuck, and those loops have an iteration limit now anyhow.  CSOLNP now solves the single-parameter example from upthread.  CSOLNP still behaves pathologically in [180926--CSOLNP_hangs.R.txt](https://github.com/OpenMx/OpenMx/files/2424588/180926--CSOLNP_hangs.R.txt) , but that case has redundant constraints, which is a known separate issue.  This issue can be closed.
