### ISSUE TITLE
automatically optimize definition variables located in between level rampart matrices

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#109]
Rather than trying to teach users not to use definition variables in between level matrices, we should just handle it automatically. An example of the appropriate transformation is available in `inst/models/nightly/univACErSEM.R`.

**Comment by mcneale** [comment]
Why are expected means so costly to compute in the multilevel case?  The algebra is somewhat less than half as complicated as that for covariances in the non-multilevel case at least.

**Comment by jpritikin** [comment]
Rampart uses a raw data approach. So we actually compute the mean vector for every row. However, we do have a sufficient statistic optimization coded that, when possible, uses the much more efficient formulae that just uses one row's worth of the mean vector. So i'm thinking that I can avoid most of the work to compute the mean vector if I can get these two parts of the code to cooperate.

**Comment by jpritikin** [comment]
@mcneale This is worth spending 1-2 weeks to implement, no?

**Comment by mcneale** [comment]
I think so, yes.  If there are knock-on effects that will help the impending ordinal multilevel implementation also, that would of course be excellent.

**Comment by jpritikin** [comment]
There are actually two distinct potential opportunities:

- Rotations at the lowest level with the same mean for every unit obtain a predictable outcome. The first unit has its mean multiplied by the rampart scaling factor and the remaining units have their means set to zero. This alone will save a ton of work.
- Units that are evaluated as part of a sufficient statistic do not need any model implied mean because they all use the same mean.

**Comment by jpritikin** [comment]
These optimizations are implemented for the lowest level in v2.11.4-19-g8d32ac209. I believe the optimization could be generalized to higher levels, but the gains would usually be less dramatic (depending on where the bulk of the data is).

Until there is a motivating application, I'll just write some notes down about how to take the next step and defer.

**Comment by jpritikin** [comment]
Looks like the optimization needs to be generalized. All the improvement in performance is lost going from 2 to 3 levels.

**Comment by jpritikin** [comment]
Please test with v2.11.5-2-g7ef03e3fe
