### ISSUE TITLE
StanHeaders 2.11.0 requires a new header file

### ISSUE THREAD

**Issue by bgoodri** [OpenMx/OpenMx#11]
A new StanHeaders is about to be uploaded to CRAN. In src/omxMLFitFunction.cpp , you need to
```
#include <stan/math/fwd/mat/vectorize/apply_scalar_unary.hpp>
```
to get R CMD check to pass again. CRAN will probably want a new OpenMx ASAP. Sorry for the non-existent notice but the default MCMC sampler in StanHeaders 2.10 was broken so we have to upload 2.11 now.

**Comment by jpritikin** [comment]
On Thu, Jul 28, 2016 at 02:53:42AM -0700, bgoodri wrote:
>    A new StanHeaders is about to be uploaded to CRAN. In
>    src/omxMLFitFunction.cpp , you need to
> #include <stan/math/fwd/mat/vectorize/apply_scalar_unary.hpp>
> 
>    to get R CMD check to pass again. CRAN will probably want a new OpenMx
>    ASAP. Sorry for the non-existent notice but the default MCMC sampler in
>    StanHeaders 2.10 was broken so we have to upload 2.11 now.

Thanks for letting us know exactly how to fix it.

**Comment by jpritikin** [comment]
Hm, Daniel Lee said we should just use `#include <stan/math/mix/mat.hpp>` and nothing else. That seems simpler and less prone to revision. I'm going to go with it.
