### ISSUE TITLE
Stan now utilizes the C++14 standard

### ISSUE THREAD

**Issue by bgoodri** [OpenMx/OpenMx#112]
StanHeaders and rstan 2.18.x are on CRAN now and Stan now utilizes as much of the C++14 standard as is implemented in RTools. It may or may not be necessary to update OpenMx immediately but when you next upload nlmixr you should probably change the line in Makevars* to CXX_STD = C++14 and put LinkingTo: StanHeaders (>= 2.18.0) in the DESCRIPTION.

**Comment by jpritikin** [comment]
Does StanHeaders 2.10 fail to compile with C++14? If not then we only need to add `CXX_STD=CXX14` to Makevars*

**Comment by bgoodri** [comment]
I think recent versions of StanHeaders should compile if `CXX_STD=CXX14` is in Makevars* but only OpenMx is using the forward-mode stuff, so you'll have to test it to see.

**Comment by mcneale** [comment]
@bgoodri - congrats on being on CRAN and many thanks for helpful suggestions!

**Comment by jpritikin** [comment]
Looks like we can no longer avoid this, v2.12.2-331-g8662039fb
