### ISSUE TITLE
Documentation for mxModel talks about mxFIMLObjective etc.

### ISSUE THREAD

**Issue by mcneale** [OpenMx/OpenMx#117]
"To be estimated, MxModel objects must include objective functions as arguments (mxAlgebraObjective, mxFIMLObjective, mxMLObjective or mxRAMObjective) and executed using the mxRun function. When MxData objects are included in models, the 'type' argument of these objects may require or exclude certain objective functions, or set an objective function as default."

**Comment by tbates** [comment]
fixed now
