### ISSUE TITLE
collect2 and/or ld is a linkage problem

### ISSUE THREAD

**Issue by b1azk0** [OpenMx/OpenMx#119]
Greetings 
Here is a problem, I can't find a solution for.
I'm working with R (MKL version) 3.5.1-2 compiled with intel-mkl 2018.3.222 on Manjaro Linux

`Linux bajzel-lap 4.19.2-1-MANJARO #1 SMP PREEMPT Tue Nov 13 22:35:25 UTC 2018 x86_64 GNU/Linux`

```
sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS/LAPACK: /opt/intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so
```
When I try to install OpenMx from source [following official instructions](https://openmx.ssri.psu.edu/wiki/howto-build-openmx-source-repository) or by sourcing an install script `source('https://openmx.ssri.psu.edu/software/getOpenMx.R')`

I always end up with errors while compiling the OpenMx package:

```

   g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -fopenmp -o OpenMx.so Compute.o ComputeGD.o ComputeNM.o ComputeNR.o ComputeSD.o FellnerFitFunction.o MarkovExpectation.o MarkovFF.o asa.o ba81quad.o dmvnorm.o fitMultigroup.o general.o glue.o matrix.o merge.o mvbvn.o nanotimer.o omxAlgebra.o omxAlgebraFitFunction.o omxData.o omxExpectation.o omxExpectationBA81.o omxExportBackendState.o omxFIMLFitFunction.o omxFitFunction.o omxFitFunctionBA81.o omxGREMLExpectation.o omxGREMLfitfunction.o omxHessianCalculation.o omxImportFrontendState.o omxLISRELExpectation.o omxMLFitFunction.o omxMatrix.o omxNLopt.o omxNPSOLSpecific.o omxNormalExpectation.o omxRAMExpectation.o omxRFitFunction.o omxRowFitFunction.o omxState.o omxStateSpaceExpectation.o omxSymbolTable.o omxWLSFitFunction.o optimize.o options.o sadmvn.o slsqp.o ssMLFit.o stop.o subnp.o -L../src -lnpsol -L/opt/intel/composerxe/linux/mkl/lib/intel64 -Wl,--no-as-needed -lmkl_gf_lp64 -lmkl_tbb_thread -lmkl_core -ltbb -lstdc++ -lpthread -limf -lm -ldl -lgfortran -limf -lm -lgomp -lquadmath -lpthread -lgfortran -limf -lm -lgomp -lquadmath -lpthread -L/usr/lib64/R/lib -lR
   /usr/bin/ld:../src/libnpsol.a: file format not recognized; treating as linker script
   /usr/bin/ld:../src/libnpsol.a:1: syntax error
   collect2: error: ld returned 1 exit status
   make[1]: Leaving directory '/home/bajzel/OpenMx/src'
   make[1]: *** [/usr/share/R//make/shlib.mk:6: OpenMx.so] Error 1
   ERROR: compilation failed for package ‘OpenMx’
─  removing ‘/tmp/RtmpBYMSV8/devtools_install_44c07b785d8/OpenMx’
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error
Calls: <Anonymous> ... with.default -> eval -> eval -> with_envvar -> force -> run
Execution halted
make: *** [Makefile:157: install] Error 1
```
My GCC version is:
```

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp --enable-cet=auto
Thread model: posix
gcc version 8.2.1 20180831 (GCC) 
```

This is really beyond my current linux experience and I would appreciate any help

**Comment by jpritikin** [comment]
Yeah, `libnpsol.a` has not been compiled with gcc 8.x yet. You'll need to use `make cran-install` instead of `make install`.

**Comment by b1azk0** [comment]
Worked wonders! :1st_place_medal: 
Thank you!

**Comment by RMKirkpatrick** [comment]
@b1azk0 , we now have a libnpsol.a that's compatible with gcc 8.  If you'd like to try `make install` again (instead of `make cran-install`), we'd appreciate any feedback you might have.

**Comment by bububox** [comment]
I have the same problem with gcc 10.2

`/usr/bin/ld:../src/libnpsol.a: file format not recognized; treating as linker script
/usr/bin/ld:../src/libnpsol.a:1: syntax error
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R//make/shlib.mk:6: OpenMx.so] Error 1
ERROR: compilation failed for package ‘OpenMx’
* removing ‘/home/leo/R/x86_64-pc-linux-gnu-library/4.0/OpenMx’
Warning in install.packages :
  installation of package ‘OpenMx’ had non-zero exit status`

**Comment by jpritikin** [comment]
Yeah, gcc 8 is the newest release that is supported for NPSOL. For gcc 10, we probably need to recompile NPSOL with gfortran 10.

**Comment by RMKirkpatrick** [comment]
@bububox Thanks for your report.  I expect the explanation is simply that libnpsol.a has not yet been built with gcc 10, so you'll need to use `make cran-install` instead of `make install`.

**Comment by dirkpelt** [comment]
I'm having the same issue using GCCcore-9.3.0. 

When I install using make cran-install does this mean the NPSOL optimizer is not available?

**Comment by mcneale** [comment]
Yes, I believe cran-install omits NPSOL, because NPSOL isn't open source.

**Comment by bububox** [comment]
any news on this?

**Comment by mcneale** [comment]
Mostly, if your version of gcc isn't compatible with libnpsol.a, leave out NPSOL by using make cran-install instead.  There seem to be many incompatible versions of gcc compilers so it isn't reasonable to expect that every single one will have a corresponding libnpsol.a.  I also recommend obtaining your own version of NPSOL from Stanford in order to compile it with compilers other than the ones we have been using.  If you do this, then contributions of libnpsol.a files would be appreciated as an act of giving back to the community.  Thanks, and sorry not to be of more help.

**Comment by RMKirkpatrick** [comment]
Once gcc 10 is in Debian stable, we'll have a libnpsol.a build compatible with it.
