### ISSUE TITLE
Holzinger & Swineford Data differs from other sources

### ISSUE THREAD

**Issue by Ewan-Keith** [OpenMx/OpenMx#12]
The Holzinger & Swineford abilities dataset packaged with OpenMx at `OpenMx/data/HS.ability.data.txt` differs from other sources for this data. Specifically:

1. The numbers of observations for each school differ from other sources. In the file, Grant-White has 156 observations and Pasteur has 145.  However, [Joreksog (1969)](http://www.helsinki.fi/~ranne/thesis/Joreskog-1969a/Joreskog-1969a.pdf) has these dimensions reversed, with Grant-White having 145 observations (p. 193). This difference is confirmed in [other sources](http://faculty.ucmerced.edu/sites/default/files/sdepaoli/files/docs/Muthen-Asparouhov%202012.pdf) (p. 318, table 3).

2. The data itself differs from other online sources, specifically it does not agree with the dataset packaged with the [MBESS package ](https://github.com/cran/MBESS/blob/master/data/HS.data.rda) or that reported on [the Mplus website](https://www.statmodel.com/examples/baysem/H-S%20Combined.txt). The MBESS and Mplus datasets match one another.

The dataset discussed is also an identical match for the packaged `OpenMx/data/HS.fake.data.txt`, with the R help call returning the documentation for `HS.ability.data.txt` in both cases. I'm not aware how these datasets are intended to relate to one another but this might help clarify why the H&S dataset differs from other sources?

**Comment by jpritikin** [comment]
Looks like someone ran fake data and overwrote the original. Anyone have the original?
-
Ryne Estabrook, PhD
Assistant Professor
Department of Medical Social Sciences
633 N. St Clair St, Suite 1900
Chicago, IL, 60091
312-503-1459

**Comment by Ewan-Keith** [comment]
It looks like the data was originally pulled directly from the MBESS package until it was hard copied over to remove the dependency.  Given that, it should be possible to just replace the current file with the correct data from that package without breaking anything (same var names and dimensions) . Will check if that's the case.

**Comment by tbates** [comment]
Updated now: will be checked, and pushed on the next CRAN release: Thanks for catching the change!

**Comment by tbates** [comment]
Correct data now in current repo-version, awaiting next release
