### ISSUE TITLE
mxRefModels() bug relating to multigroup ordinal models

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#122]
See [here](https://openmx.ssri.psu.edu/node/4439) for a script to reproduce the issue, and [here](https://openmx.ssri.psu.edu/comment/7936#comment-7936) for a description of the bug.  In short, the saturated model corresponding to the model of interest in the script should have 50 free parameters, but only has 35, because all of the thresholds are cross-group equality-constrained (by label).

Is issue #47 related to this issue?  Note that the use of a multigroup model in the script I linked is motivated by measurement invariance, not twin modeling.

**Comment by jpritikin** [comment]
Fixed in v2.11.5-105-gdc0df049d. Close this issue?

**Comment by RMKirkpatrick** [comment]
If I try to get better start values for metinbulus' model via `mxAutoStart()`, using `type="DWLS"` causes an error.  Internally, `type="DWLS"` is being passed to `mxDataWLS()` along with the incompatible `fullWeight=FALSE`.  `mxAutoStart()` works with `type="ULS"`, though.

**Comment by jpritikin** [comment]
Easy enough to fix v2.11.5-106-ge58b62e4f

**Comment by RMKirkpatrick** [comment]
OK, good.
