### ISSUE TITLE
default values for mxThreshold

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#123]
If you leave values unspecified then you get an error:
```
The thresholds you are attempting to specify has starting values that are not strictly increasing, but type='RAM' models require them to be.
An easy way to specify threshold starting values that are evenly spaced across a normal distribution is using:
mxThreshold(vars='x1', nThresh=3, values=mxNormalQuantiles(3))
See '?mxNormalQuantiles' and '?mxThreshold' for more details.FALSE
```

Why not use mxNormalQuantiles as the default values?

**Comment by mcneale** [comment]
It should be "...have starting values." 

Is this the only case that will trigger the error?   Do we test for positive-definite expCov  **first**? And give an error if it is not?  I think a negative definite covariance matrix can trigger 'apparent' disordering of thresholds ,  which could in principle occur even if mxNormalQuantiles() was used  to order them to be increasing.

**Comment by jpritikin** [comment]
`mxThreshold` is a front-end construct. It can't know anything about the model.

**Comment by jpritikin** [comment]
> Maybe we need a test for p.d. matrix in the front end for model sanity-checking, just prior to running?

Better to open a new issue to discuss

**Comment by tbates** [comment]
tangential to this issue, but I think the recent change to not equate thresholds across groups in `mxRefModels` will make this not be a useful function for twin models (where we don't expect MZ and DZ twins to differ in where thresholds are placed) and also **break** backward compatibility?

IMHO: We should add a parameter `equateThresholds = TRUE`  a default that  won't break existing code and allows users to control the behavior.

**Comment by jpritikin** [comment]
@RMKirkpatrick Thoughts?

**Comment by mcneale** [comment]
Breaking backward compatibility is ALWAYS bad.  It hurts users and co-developers.  Can't we avoid it?

**Comment by jpritikin** [comment]
From a code point of view, we could certainly offer something like `equateThresholds = TRUE`. The current change, v2.11.5-105-gdc0df049d, does indeed break backward compatibility.

**Comment by RMKirkpatrick** [comment]
@jpritikin I concur that sensible default values for `mxThreshold()` are a good idea.  I also concur that breaking backward compatibility is typically a bad idea.  New changes break scripts that end users run ought to be avoided.  New changes that break the API of reverse-dependencies also aren't desirable, but might be necessary sometimes.  I haven't used WLS enough to have an opinion about any specific aspects of the recent changes.  My impression is that the goal is to make WLS faster, more flexible and feature-complete, and compatible with more of OpenMx's other features; I'm in favor of all of those things.

**Comment by RMKirkpatrick** [comment]
@mcneale The error message Joshua quotes in the OP of this issue is thrown by `mxModel()`, not `mxRun()`.  Like Joshua said, this issue is completely orthogonal to the state of the model-expected covariance matrix.  There's no reason why a function that asks "are all of these columns of numbers sorted from least to greatest?" has to know anything about the covariance matrix.

**Comment by mcneale** [comment]
I understand that - I just note that we may need two tests if a negative definite covariance matrix can trigger the error later on.  Perhaps it won't - it would sometimes  happen like that in classic Mx, I recall.
