### ISSUE TITLE
add equateThresholdsAcrossGroups = TRUE option to mxRefModels

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#124]
As highlighted in #122, ref models make assumptions - currently that users would expect thresholds to be equal across groups.

This should be a settable option, defaulting to the behavior we've had for the last 3-5 years, which is to equate thresholds (as is used in twin models), but allowing easy access to `equateThresholds = FALSE`

**Comment by jpritikin** [comment]
v2.11.5-110-g8950793b4
