### ISSUE TITLE
mxFitFunctionWLS update for backend 

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#125]
Leaving `mxDataWLS` as it was and enhancing `mxFitFunctionWLS`

Models will be able to process data in the back end, and also to re-use already processed data (i.e., once it's been processed, it doesn't need re-processing on re-running the model, the data slot in the model will still need to hold the processed data.

Processed data are called type = "acov" as in old  `mxDataWLS`. 

`mxFitFunctionWLS` currently takes only one parameter ( `weights = "ULS"`, which is ignored).
 
Add add the following parameters to enable `mxFitFunctionWLS` to make choices about how to process the incoming raw data as the user desires:

```R
  mxFitFunctionWLS(
        type = c('WLS', 'DWLS', 'ULS'),
        allContinuousMethod = c("cumulants", "marginals"), 
        verbose=FALSE, weight = as.character(NA), 
        frequency = as.character(NA)
)
```

FYI, these are the params for `mxDataWLS`:

```R
    mxDataWLS(data, type = "WLS", 
    useMinusTwo = TRUE, 
    returnInverted = TRUE, 
    fullWeight = TRUE, 
    suppressWarnings = TRUE, 
    allContinuousMethod =   c("cumulants", "marginals"), ..., 
    silent=!interactive(),
    .oldMethod =  FALSE,
    verbose=0L,
    compute=FALSE,
    returnModel=FALSE,
    weight = as.character(NA), 
    frequency = as.character(NA)
)
```

**Comment by jpritikin** [comment]
I think I've got it figured out, but thanks for writing it up.

**Comment by jpritikin** [comment]
v2.11.5-118-g51760044b
