### ISSUE TITLE
Write function telling what WLS data will return

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#129]
This function will take the raw data and `allContinuousMethod` (either 'cumulants' or 'marginals').  It will return a description of what `mxDataWLS` will return.  Will it have means etc.?

**Comment by tbates** [comment]
Here's an R file of that function: can someone who can build (my current machine set up isn't building) test?
[mxDescribeDataWLS.r](https://github.com/OpenMx/OpenMx/files/2750581/mxDescribeDataWLS.txt)

**Comment by jpritikin** [comment]
And we probably need a few more,

   umx_has_been_run umx_has_been_run
   umx_has_CIs      umx_has_CIs
   umx_has_means    umx_has_means
   umx_is_MxData    Check if an object is an mxData object
   umx_is_MxMatrix  umx_is_MxMatrix
   umx_is_MxModel   umx_is_MxModel
   umx_is_RAM       umx_is_RAM

**Comment by mcneale** [comment]
This seems like the desired output (after uncommenting the stuff at the top of the script (minus all the @description bits - who are these people :)).  It was run with 2.12.1 under OS X 10.12.6 & R3.51

> 
> # =======================
> # = All continuous data =
> # =======================
> 
> mxDescribeDataWLS(mtcars, allContinuousMethod= "cumulants", verbose = TRUE)$hasMeans # TRUE
[1] "all continuous"
[1] TRUE
> mxDescribeDataWLS(mtcars, allContinuousMethod= "marginals")$hasMeans  # FALSE - no means with marginals
[1] FALSE
> 
> # =======================
> # = One var is a factor =
> # =======================
> tmp = mtcars
> tmp$cyl = factor(tmp$cyl)
> mxDescribeDataWLS(tmp, allContinuousMethod= "cumulants")$hasMeans # TRUE
[1] TRUE
> mxDescribeDataWLS(tmp, allContinuousMethod= "marginals")$hasMeans # TRUE - always has means
[1] TRUE
>

**Comment by tbates** [comment]
is there anything else (apart from has/doesn't have means) that varies in WLS data once it's processed out of raw data input? If not, this can be closed now that  `?mxDescribeDataWLS` exists in the current travis build

**Comment by jpritikin** [comment]
Okay with me
