### ISSUE TITLE
χ²(0) = 1e08,  p < .0001 for saturated model (should be p = 1)

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#131]
`pchisq(2.855847e-08,0)` = 1, but we report p of 0 for a saturated model

repro
```R
library(umx)
m1 = umxRAM("tim", data = mtcars,
	umxPath(c("wt",  "disp"), to = "mpg"),
	umxPath("wt", with = "disp"),
	umxPath(v.m. = c("wt",  "disp",  "mpg"))
)
summary(m1, refModels= mxRefModels(m1, run= TRUE))
# chi-square:  χ² ( df=0 ) = 2.855847e-08,  p = 0

tmp = summary(m1, refModels= mxRefModels(m1, run= TRUE))
tmp$ChiDoF   # =  0
tmp$Chi      # =  2.855847e-08
tmp$p        # = 0


```

**Comment by tbates** [comment]
Any thoughts on fixing this? Students in lab find it confusing once they see it. Should be p= 1, not p<.001

**Comment by RMKirkpatrick** [comment]
> `pchisq(2.855847e-08,0) = 1`

True, but that's the cumulative (i.e., lower-tail) probability.  The _p_-value would be the upper-tail probability, `pchisq(2.855847e-08,0,lower.tail=F)`, which is technically zero.

But pedantry aside, it's an easy change to make `summary()` report a reasonable value.  I'll push a commit shortly.

**Comment by RMKirkpatrick** [comment]
See b1a6a42 .

**Comment by tbates** [comment]
don't know: does summary for a saturated RAM model of cov input data report chi^2 = 1?

**Comment by mcneale** [comment]
Er, it is somewhat undefined with df=0. In the limit as chi^2 -> 0, reasonable to say p=1 but **not chi^2=1**

**Comment by tbates** [comment]
Yes, as of at least OpenMx version: 2.12.1.68 [GIT v2.12.1-68-ga544a00]

>  χ²(0) = 0, p = 1.000; CFI = 1; TLI = 1; RMSEA = 0

from a saturated model like 

```R
m1 = umxRAM("sat", data = mtcars,
	umxPath(c("wt", "disp"), to = "mpg"),
	umxPath("wt", with = "disp"),
	umxPath(v.m. = c("wt", "disp", "mpg"))
)

```
