### ISSUE TITLE
mxData error improvements

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#133]
```R
mxData(mtcars[1:2,1:2], type="cov", numObs= 77)
```
yields this non-informative error:

> Error in if (all.equal(covMatrix, t(covMatrix))) { : 
>   argument is not interpretable as logical
> In addition: Warning message:
> In if (all.equal(covMatrix, t(covMatrix))) { :
>   the condition has length > 1 and only the first element will be used
>

**Comment by tbates** [comment]
```R
> mxData(data.frame(cov(mtcars[,1:3])), type="cov", numObs= 77)
MxData 'data' 
type : 'cov' 
numObs : '77' 
observed : 
             mpg        cyl       disp
mpg    36.324103  -9.172379  -633.0972
cyl    -9.172379   3.189516   199.6603
disp -633.097208 199.660282 15360.7998
means : NA 

```

Is processed fine, but the resulting `mxData` object will generate a runtime error about the storage format for the data not being matrix.

Either we should coerce the data to matrix, or ask the user to do so.

Should report an error: 
> data must be type matrix. Try as.matrix(yourData)??

**Comment by RMKirkpatrick** [comment]
I guess we should ask the user to do so in the error message.

**Comment by jpritikin** [comment]
> I guess we should ask the user to do so in the error message.

How about this rule: If the data.frame is square and symmetric then we automatically coerce. Otherwise we complain.

**Comment by tbates** [comment]
I have a feeling (that's all) that that is what we used to do... the check for symmetry is still being done, but the data are being stored as data.frame instead of matrix after all that has been established (on a matrix converted version of the data).

So yes... auto-coerce
