### ISSUE TITLE
mxAlgebra interface

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#134]
I didn't realize that the `mxAlgebra` parameter `fixed =` that we've been discussing had been out for long enough to included in dependencies (like `umx`) and user's code. (how long I'm not sure, but I think about a year or more).

Given that, I think we shouldn't change the name of this parameter: doing so breaks user experience, and makes work for people who've invested time and trust in OpenMx.

**Comment by jpritikin** [comment]
OK. How about issuing a warning instead of an error?

**Comment by tbates** [comment]
That still forces the other users to change their code.

As a "modular framework" we should break things only in extremis, and then by supporting the deprecated parameter for a couple of years to give people assurance they'll have time to change and only be asked to when there are benefits to them from new features. In this case, the name change wasn't discussed in terms of breaking an existing interface. We shouldn't do it IMHO.

**Comment by jpritikin** [comment]
Well, we could accept both parameters and document `fixed` as deprecated.

**Comment by mcneale** [comment]
+1 for *never* breaking peoples’ scripts!

**Comment by jpritikin** [comment]
Still, I'm curious why `umx` uses `fixed=TRUE`. Due to bugs in prior versions, I don't think `fixed=TRUE` was actually useful for anything.

**Comment by tbates** [comment]
Hi,
I wanted a `umxAlgebra` so I just copied out the parameters of `mxAlgebra` to pass these through with the defaults from mxAlgebra - so blind faith :-)

**Comment by jpritikin** [comment]
You can't use `...` like the definition of `mxAlgebraFromString`?

```
mxAlgebraFromString <- function(algString, name=NA, dimnames=NA, ...) {
	eval(substitute(mxAlgebra(tExp, name=name, dimnames=dimnames, ...),
			list(tExp = parse(text=algString)[[1]])))
}
```

**Comment by tbates** [comment]
That means users have to guess at undocumented (in that function) parameter options, and the helper functions can't help the user as much.

**Comment by jpritikin** [comment]
v2.12.1-75-g5a7ccb574
