### ISSUE TITLE
Links broken (and not all informative) at openmx-features

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#135]
There's a problem on our main [openmx-features](https://openmx.ssri.psu.edu/openmx-features) page, namely most links are broken (they have openmx.psyc.virginia.edu urls)

Highlights the need for documentation work also

**Comment by tbates** [comment]
All links are now fixed (thanks @RMKirkpatrick !)

The following sections have no link to an example script or help page...

1. Missing Data 
2. Categorical Threshold Estimation -- Models with categorical outcomes can be estimated, including thresholds for the categories.
3. Multilevel Structural Equation Modeling -- Any arbitrary number of levels with latent variables are possible.
4. State Space Modeling -- Latent time series models in both discrete- and continuous-time
5. Mixture Modeling -- Finite mixture modeling is available.
6. Hidden Markov Modeling -- These are also called latent transition analysis and dependent mixture models. They are latent categorical time series models.
7. Item Factor Analysis -- Conventional multidimensional item response theory models are available.
8. Meta-analysis -- The metaSEM package implements meta-analysis in structural equation modeling using OpenMx.
9. GREML -- Analysis of genetic relatedness matrices with structural equation modeling
10. Weighted Least Squares -- Ordinal, continuous, and joint ordinal continuous data can be handled with the weighted least squares data type.
11. Parameter Equality Constraints -- Any two parameters can be constrained to be equal to one another simply by making their labels the same as each other. Parameters can be constrained to be equal across groups or between any two models in a hierarchical tree of models.
12. Parameter Algebraic Constraints -- Parameters in your models can be constrained to be the outcome of any matrix algebra calculation. In this way, OpenMx lets you constrain your parameters to be linear or nonlinear functions of other parts of your model. It is hard to overstate the power of this capability.
13. Nonlinear Inequality Constraints -- In addition to algebraic constraints, OpenMx allows the definition of boundary constraints with respect to constants and with respect to other parameters. For instance, one estimated parameter can be constrained to be greater than another estimated parameter, or functions of other parameters.
15. User Specified Functions for Model Specification -- Since R allows users to easily write their own functions, you can create OpenMx model functions. For instance, maybe you use a lot of Latent Growth Curve models. Write a function that builds LGC models. From then on, you can just call your own LGC model function...

**Comment by mcneale** [comment]
Maybe if we need a break from discussions at the retreat, we could divide and conquer these missing examples and documentation.   The range of things we can do is really impressive; letting the world know about them is important.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral GeneticsIPBG
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 MCV Richmond VA 23298-0126
Telephone: (804) 828-3369  Email: michael.neale@vcuhealth.org
________________________________
