### ISSUE TITLE
mxRefModels() should warn if there are definition variables

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#136]
See https://openmx.ssri.psu.edu/node/4456 and https://openmx.ssri.psu.edu/thread/3966 .  It's frustrating for users to be caught unawares that `mxRefModels()` doesn't do what they think if they provide an MxModel containing definition variables as value for argument `x`.

I just pushed a commit that hopefully will be adequate.

**Comment by RMKirkpatrick** [comment]
See f7939d3 .  Maybe this issue can be closed.  @mhunter1 , would you have put the check for definition variables anyplace else?

**Comment by mhunter1** [comment]
No, that looks good to me.
