### ISSUE TITLE
mxAvailableOptimizers() not updated?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#138]
according to the [release notes](https://openmx.ssri.psu.edu/node/4413), there's a [new optimizer](https://vipbg.vcu.edu/vipbg/OpenMx2/docs//OpenMx/latest/_static/Rdoc/mxComputeSimAnnealing.html?q=docs/OpenMx/latest/_static/Rdoc/mxComputeSimAnnealing.html) in OpenMx 2.11. However: 

```R
mxAvailableOptimizers()
# [1] "CSOLNP" "SLSQP"

mxVersion()
# OpenMx version: 2.12.2 [GIT v2.12.2]
# R version: R version 3.5.2 (2018-12-20)
# Platform: x86_64-apple-darwin15.6.0 
# MacOS: 10.14.4
# Default optimizer: CSOLNP
# NPSOL-enabled?: No
# OpenMP-enabled?: Yes
```

**Comment by jpritikin** [comment]
I agree that it is misleading. `mxAvailableOptimizers` really only concerns gradient descent optimizers that can be set in `mxComputeGradientDescent(engine=, ...)`

**Comment by RMKirkpatrick** [comment]
It is somewhat misleading, but the man page does say that "[s]pecial-purpose optimizers like Newton-Raphson or EM are not included in this list."  Should the function description be clarified to say that it only lists optimizers settable as the "default optimizer"?

**Comment by RMKirkpatrick** [comment]
Or maybe the output of the function should be more detailed.  It could print a character vector identified as those optimizers settable as "default optimizer", and second character vector identified as optimizers usable via custom compute plan.

**Comment by tbates** [comment]
If they can't be set without extra user knowledge, perhaps close this?

**Comment by tbates** [comment]
I think given the other optimizers are not ones which a normal user can use, we should close this as "by design" until such time as a simple toggle can activate the optimizer?

**Comment by RMKirkpatrick** [comment]
@tbates OK by me.

**Comment by mcneale** [comment]
Yes, but I strongly favor making the other optimizers available to 'normal' users.  A car that takes double-declutching five times to get it into second gear isn't going to help 'normal' people get where they want to go.  EM may be an exception, due to its need for two fit functions, but we could make that easier for people, while retaining maximum flexibility for the Lewis Hamiltons of modeling.

**Comment by tbates** [comment]
Especially now that F1 uses automated sequential gearboxes :-)
