### ISSUE TITLE
Label progress during optimization

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#139]
The user currently sees:
```R
CSOLNP 139 37885.1 -507.9
```

followed by

```R
MxComputeNumericDeriv 1745 37702.5 -1.193e-09
```

I had a student ask me "what's that mean?" I was not exactly sure, and it occurs that it would be helpful to say:

```R
Optimizer: CSOLNP; Iteration?: 139 -2LL?: 37885.1 Change in -2LL?: -507.9
```

followed by

```R
MxComputeNumericDeriv something: 1745; Something: 37702.5; Something: -1.193e-09
```

**Comment by RMKirkpatrick** [comment]
I kind of like it the way it is, since it's very easy to read.  Perhaps what each value means should be documented in the man page for `mxRun()` or something?

I'd be OK with adding labels to the values as long as the labels are minimal in length.

**Comment by tbates** [comment]
Sure: just adding  ". See ?mxRun for more info" to the progress would solve the user discovery issue (this info was added to mxRun help)

**Comment by jpritikin** [comment]
I like the label idea. I think pointing to documentation would be overkill. I'll assign this issue to myself.

**Comment by jpritikin** [comment]
FYI, MxComputeNumericDeriv now shows proportion complete like,

`MxComputeNumericDeriv 5/21
`

This means that 5 of 21 entries of the matrix are done.

**Comment by tbates** [comment]
Looks great @jpritikin ! Nice too that the numeric deriv is also now gives progress!

**Comment by tbates** [comment]
nice!
```R
MxComputeGradientDescent(CSOLNP) evaluations 710 fit 37705.5 change -0.05378
MxComputeNumericDeriv 197/528                                                  
```

OpenMx version: 2.12.1.92 [GIT v2.12.1-92-gc4386c9]

**Comment by jpritikin** [comment]
Could we shorten `evaluations` to `evals`? Or is that too cryptic?

**Comment by RMKirkpatrick** [comment]
@jpritikin Yeah, I like `evals` better.  It's more concise.

**Comment by mcneale** [comment]
I prefer evaluations.  A foreign language user could look it up in their dictionary, but would come up blank searching for "evals"
