### ISSUE TITLE
SLSQP's convergence criteria for constrained optimization

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#14]
When using SLSQP to optimize an MxModel that contains MxConstraints, it is possible for it to fail to find a local minimum but not warn the user.  The reason is that we are using NLOPT's stopping criteria of change in fit less than tolerance; NLOPT does not automatically check the KKT optimality conditions.  For unconstrained problems, our backend uses our own finite-difference derivative routine to check the objective's gradient and Hessian, but we do not do this for constrained problems (and correctly so, as the optimality conditions for constrained problems involve more than just the objective's derivatives).

**Comment by mcneale** [comment]
If NLOPT doesn't check KKT automatically, can we persuade it to do so manually?  Or slot in our own checks as needed?

**Comment by RMKirkpatrick** [comment]
That's what I've been trying to do.  But every bugfix I attempt breaks something different about the way SLSQP does confidence intervals (the default behavior for SLSQP is to use the inequality-constrained formulation).

**Comment by jpritikin** [comment]
On Thu, Apr 06, 2017 at 07:13:38AM -0700, RMKirkpatrick wrote:
>    That's what I've been trying to do. But every bugfix I attempt breaks
>    something different about the way SLSQP does confidence intervals (the
>    default behavior for SLSQP is to use the inequality-constrained
>    formulation).

Rob, if you're still stuck, I'll take a look at this next week.

**Comment by tbates** [comment]
Hi, I'm just pasting in here a couple of comments from the agenda: Best to tie discussion to this issue as a central repository of comment on this case?

Constraint function values, constraint Jacobian, Lagrange multipliers, and Hessian of the Lagrangian now extracted from SLSQP, and reported in model ‘output’ slot.

Checking first-order conditions not as complicated as it seemed at one point. Can’t use SLSQP final Hessian of the Lagrangian--it will always be PD(?).

**Comment by jpritikin** [comment]
Probably solved by v2.7.9-74-ga1ad9fa34. One of the tests obtains a code 6. We need to re-evaluate whether the gradient threshold is sane, but it gets the correct estimate for the bound so no need to hold back progress. It's not a regression.
