### ISSUE TITLE
searches of our site return broken links

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#140]
if a user searches on https://openmx.ssri.psu.edu using the built-in search box, e.g.

https://openmx.ssri.psu.edu/search/google/interaction

they get back links to forum posts on virginia. These (at least currently) are failing with a time out.

http://openmx.psyc.virginia.edu/thread/466

**Comment by RMKirkpatrick** [comment]
Isn't this a known issue we've told Ed about?  You need to do Content search instead of Google search.

**Comment by tbates** [comment]
If Ed can't fix it, we should remove the google search box. I don't know what "content search" is.

**Comment by RMKirkpatrick** [comment]
> I don't know what "content search" is.

Once a page of Google search results loads, click the "Content" button above the text box.  Content search works.  I somehow doubt Google search has worked since the changeover to PSU.

**Comment by RMKirkpatrick** [comment]
I just disabled Google search on our website.  Now, it defaults to the Content (i.e., "node") search described above.

**Comment by tbates** [comment]
perfect!! I bet this increases hits on the help pages
