### ISSUE TITLE
mxFitFunctionMultigroup: takes model names, not fit function names?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#141]
The docs for `mxFitFunctionMultigroup` say that the `groups` parameter takes "_vector of fit function names (strings)_". The docs also use `c("model1.fitfunction", "model2.fitfunction")` as an example input to `groups`.

Before I change those to "_vector of model names_" and `c("model1", "model2")`, just to confirm, the function actually wants a vector of model names, right? What is best practice: to use dot syntax to point to a component of the model, or just offer up the model name?

**Comment by RMKirkpatrick** [comment]
> What is best practice: to use dot syntax to point to a component of the model, or just offer up the model name?

I am pretty sure it suffices just to provide model names.

**Comment by jpritikin** [comment]
Both ways work. See `inst/models/passing/checkStandardizedLoadingsEtcetera.R` and `inst/models/passing/TwinAnalysis_Multivariate_Matrix_Raw.R`. I guess best practice is to mention only the model names.

**Comment by jpritikin** [comment]
This issue is addressed by v2.12.1-93-g25a03ecb8 ?
