### ISSUE TITLE
method to keep travis version ahead of CRAN version #?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#144]
I wonder if there's a process to bump the git version after we release, so that travis builds are seen as newer (mostly happens, but not always).

Currently (25 Feb 2019) , the CRAN version of OpenMX (2.12.2) is ahead of the travis version (2.12.1-106)

This means that installing packages uninstalls the newer version in favour of the CRAN version.

**Comment by jpritikin** [comment]
I added a merge with v2.12.2. Maybe that will fix it.

**Comment by tbates** [comment]
apparently not: still seeing CRAN as 2.12.2 (with current travis at 2.12.1.106 [GIT v2.12.1-106-gb336db1])

**Comment by jpritikin** [comment]
It's there now. There hadn't been a successful build since I pushed the merge.

**Comment by mcneale** [comment]
Seems that  the version number on travis is the culprit, right?   Shouldn't it  be 12.2.55 or something denoting development since the 2.12.2 freeze on CRAN?

**Comment by jpritikin** [comment]
This issue is solved.
