### ISSUE TITLE
mxTryHard with WLS model gives "Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x)"

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#146]
I've been working on enabling WLS in umx models...
mxTryHard gives the odd "Error in array" feedback when running this model...
The model (it's an ACE twin model) is attached here, and the output is pasted below that
[m1_odd_tryHard.txt](https://github.com/OpenMx/OpenMx/files/2916140/m1_odd_tryHard.txt)

(rename to .rda. Contains a model object "m1")

```R
m1= mxTryHard(m1)
Beginning initial fit attemptError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Beginning fit attempt 1 of at maximum 10 extra triesError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Beginning fit attempt 2 of at maximum 10 extra triesError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Beginning fit attempt 3 of at maximum 10 extra triesError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Beginning fit attempt 4 of at maximum 10 extra triesError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Beginning fit attempt 5 of at maximum 10 extra triesError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Beginning fit attempt 6 of at maximum 10 extra triesError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Beginning fit attempt 7 of at maximum 10 extra triesError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Beginning fit attempt 8 of at maximum 10 extra triesError in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Fit attempt 9, fit=13.573388564501, new current best! (was 13.573388964994)Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
Beginning fit attempt 10 of at maximum 10 extra tries                      Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'
                                                     
Retry limit reached; solution not found.  Best fit=13.573389 (started at 13.573389)  (11 attempt(s): 11 valid, 0 errors)
```

**Comment by jpritikin** [comment]
The problem is that `mxTryHard` with `checkHess==TRUE` expects the Hessian to be available from `fit$output$calculatedHessian`. For WLS, the Hessian is returned in `fit$output$hessian`. See `R/MxTryHard.R` lines 247-252. @RMKirkpatrick, what is the correct fix?

Also, do we want to add `silent=TRUE` to the try?

**Comment by RMKirkpatrick** [comment]
The fix will be implemented in the near future _en route_ to standard errors in the presence of constraints.  For now, let's pass `silent=T` to `try()`.  I'll do that now.

Also, @mhunter1 advises that there's no point in using `checkHess=T` with WLS, and that `checkHess=F` should suffice.

**Comment by tbates** [comment]
It would make sense for the `mxTryHard` family of functions to look at the mxFitFunction of the model and submodels they are trying hard with, and, if they are applying WLS to their model data, toggle `checkHess` to FALSE.

Can document that as the expected behavior, i.e., checkHess = TRUE (if not WLS)

**Comment by RMKirkpatrick** [comment]
> It would make sense for the `mxTryHard` family of functions to look at the mxFitFunction of the model and submodels they are trying hard with, and, if they are applying WLS to their model data, toggle `checkHess` to FALSE.

Makes sense to me.  Note that it will have to check the units of the fitfunction rather than the type.  I'll take care of it.

**Comment by mcneale** [comment]
It's a bit automagical and un-WYSIWWD.  Can such behavior be overridden, so we can allow the user to deliberately do something silly?

**Comment by RMKirkpatrick** [comment]
@mcneale We already coerce `checkHess` to `FALSE` if it is `TRUE` and the model contains MxConstraints.  The user can override a lot of the default behavior of `mxTryHard()` by using a cutom compute plan.

**Comment by tbates** [comment]
I wonder how much use it is to warn people that something they are not going to know exists has been coerced to a value they don't know is not relevant (i.e., the default assumes a Hessian that can be checked exists, this warning is only thrown when one doesn't exist or can't be checked.

I would make this just a `message` printed in the console. That would also mean that people running `mxTryHard` code inside `tryCatch` wouldn't need to turn off warning handlers  (I just did - otherwise the handler prevents the (perfectly good) model coming back to the user...).

PS: Probably defaults, inc this one, that can't be promised should be NULL and documented as "yes, If it makes sense" with the user explicitly saying T/F to force exactly what they want (and get an error when it's not impossible).

```R
In mxTryHard(model1) :
  argument 'checkHess' coerced to FALSE due to presence of MxConstraints
```

**Comment by RMKirkpatrick** [comment]
@tbates Good ideas.

**Comment by mcneale** [comment]
@tbates @RMKirkpatrick Agreed, we have a terse and somewhat incomprehensible warning that could be a note that is more generally understandable.

**Comment by RMKirkpatrick** [comment]
Commit bea760b changes the warning to a message.
