### ISSUE TITLE
accessible scripts

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#147]
scripts at [https://vipbg.vcu.edu/media/workshops/2015/ages](https://vipbg.vcu.edu/media/workshops/2015/ages) appear to be locked to outside viewing?

    You don't have permission to access /media/workshops/2015/ages/Gillespie_DOC_modelling.R on this server.

**Comment by tbates** [comment]
Thanks @mcneale  for getting this folder opened up!

FYI, this page https://vipbg.vcu.edu/workshops/ shows the current workshop as 2017, not sure if that's correct.

**Comment by mcneale** [comment]
That was the last AGES workshop; we are not funded for any more, as NIDA cancelled the R25 mechanism that funded it.  Will seek additional mechanisms as time allows.
