### ISSUE TITLE
error reporting from container models using an mxFitFunctionMultigroup

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#148]
If a submodel of a supermodel built with a `mxFitFunctionMultigroup` has a problem where its expectation doesn't match the column names of its data, this is reported as a problem with the supermodel (not which ever submodel had the issue).

```R
tmp = mxRun(supermodel)
Error: The column name(s) 'var1', and 'var2' in the expected covariance matrix of the expectation function in model 'supermodel' cannot be found in the column names of the data.
```

This should say
> Error: The column name(s) 'var1', and 'var2' in the expected covariance matrix of the expectation function in model 'whicheversubmodelisbroken' cannot be found in the column names of the data.

PS: it would also be super helpful to print the column names of the data in the error.

**Comment by jpritikin** [comment]
Try v2.12.2-117-g641c4c18b

I don't have a script handy to reproduce the error, but I think I improved it.

**Comment by tbates** [comment]
Cool! Here's a working example in umx.  The error, which used to direct the user to data in the super model, which was not the problem now (2.12.2.127 [GIT v2.12.2-127-g274ecea]) points to the correct model:

> The column name(s) 'mpg' and 'wt' in the expected covariance matrix of the expectation function cannot be found in the column names of 'model_with_problem.data'


```R
library(umx)

# 1. make a model
m1 <- umxRAM("model_thats_OK", data = mtcars, autoRun= F,
	umxPath("wt", to = "mpg"),
	umxPath(v.m. = c("wt", "mpg"))
)

# 2. make a copy
m2 = mxRename(m1, "model_with_problem")

# 3. Break model 2 by switching out variable names in dataset
names(m2$data$observed) = c("A", "B") # was wt, mpg

# 4. Place m1 and m2 into a supermodel and run
m3 = umxSuperModel('container_thats_fine', m1, m2)

# old error was:
The column name(s) 'mpg' and 'wt' in the expected covariance matrix of the expectation function in model 'container_thats_fine' cannot be found in the column names of the data.
```
