### ISSUE TITLE
improving usability of mxOption

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#150]
the `model` parameter of `mxOption` has no default, which means users must say
```R
> mxOption(NULL, key="mvnRelEps")
[1] 0.005
```
Suggestion: make NULL the default. Then this would work: `mxOption(key="mvnRelEps")`
Benefit: less confusion and less typing.

Second, let's add an input check on the first parameter: is needs to be a model, but currently, a user not knowing this can send it a string: `mxOption("optname")`

Let's error on that with "You likely meant `mxOption(key='optName')`"

**Comment by jpritikin** [comment]
> Second, let's add an input check on the first parameter: is needs to be a model, but currently, a user not knowing this can send it a string: mxOption("optname")

Well, this already doesn't work because `key` is a required argument. So I think we only need to complain if a non-model is passed as the first argument.

**Comment by jpritikin** [comment]
See v2.12.2-123-g3b4d67e90
