### ISSUE TITLE
compilation failed for package ‘OpenMx’

### ISSUE THREAD

**Issue by gianlucafilippa** [OpenMx/OpenMx#152]
I am getting the following error while installing OpenMx: 

/usr/local/lib/R/site-library/StanHeaders/include/stan/math/prim/arr/functor/integrate_1d.hpp:7:46: fatal error: boost/math/quadrature/exp_sinh.hpp: No such file or directory
compilation terminated.
/usr/lib/R/etc/Makeconf:168: recipe for target 'omxMLFitFunction.o' failed
make: *** [omxMLFitFunction.o] Error 1

on R version 3.4.4 and Ubuntu 16.04.6 LTS 64-bit

Any help will be much appreciated

**Comment by mcneale** [comment]
Perhaps try installing a newer version of the boost package?

**Comment by gianlucafilippa** [comment]
I successfully installed libboost - dev - all but it didn't help.

Il giorno gio 7 mar 2019, 17:49 Michael Neale <notifications@github.com> ha
scritto:

**Comment by jpritikin** [comment]
What about the BH package from CRAN? Can you ensure you have that upgraded?

**Comment by gianlucafilippa** [comment]
Indeed, upgrading BH to the latest version solved the issue! 
Thanks for your prompt help.

**Comment by mcneale** [comment]
Glad to be of assistance!
