### ISSUE TITLE
mxStandardizeRAMpaths Error in covParam dimensions

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#153]
Hi
I was playing with this minimal model "X<->X", and mxStandardizeRAMpaths errors on it when SE is TRUE.

Perhaps a case of R needing to told drop = FALSE in a select? e.g.m mtcars[,1, drop=F]?

```R
mData = matrix (1); dimnames(mData) = list(c("X"), c("X"))
m1 = umxRAM("varX", data = mxData(mData, type="cov", numObs = 10),
  umxPath(var = "X")
)
# yields an error from umxSummary, but the run model is still returned 
```

## Try standardising the model, requesting SE

```R
mxStandardizeRAMpaths(m1,SE=TRUE)
```

> Error in covParam[ifelse(is.na(out$label[i]), out$name[i], out$label[i]),  : 
> incorrect number of dimensions

**Comment by tbates** [comment]
traceback says this bug tripping up `.mxStandardizeRAMhelper` guessing that covParam gets reduced to 1 dimension earlier on...

```R
.mxStandardizeRAMhelper(model = model, SE = SE, ParamsCov = covParam)
```
This is with
> OpenMx version: 2.12.2.169 [GIT v2.12.2-169-gb745620]

**Comment by RMKirkpatrick** [comment]
> Error in covParam[ifelse(is.na(out$label[i]), out$name[i], out$label[i]), :
incorrect number of dimensions

Strange bug.  It appears that `covParam` somewhere becomes a scalar instead of a 1x1 vector, and therefore has no columns.  I bet no one's ever tried using `mxStandardizeRAMpaths()` on a RAM model fitted to a 1x1 covariance matrix before.  I think I have an easy fix.

**Comment by RMKirkpatrick** [comment]
See a2694d6 .

**Comment by mcneale** [comment]
That is really good going, especially for a weekend, Rob!

**Comment by tbates** [comment]
The fix on line 1500 would be to add `drop=FALSE` to the selector:
```R
covParam <- ParamsCov[paramnames,paramnames, drop=FALSE]
```
(an R oddity where the result of bracket selection is simplified unless requested not... about as annoying as the default of making strings into factors in read.table :-)

**Comment by RMKirkpatrick** [comment]
@tbates OK, that's a better fix.

**Comment by RMKirkpatrick** [comment]
See b45a3b3 .

**Comment by tbates** [comment]
Fabulous!
