### ISSUE TITLE
Check that warnings are not being raised in the course of normal user work.

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#155]
test suit items should check that warnings are not being raised in the course of normal user work.

@jpritikin notes that we display all warnings triggered if no tests fail, but AFAIK, this is just in the console and needs manual checking for every build,

1. We should wrap some basic building blocks in  `omxCheckWarning( ,message=NA)` so they are flagged as problems

_Originally posted by @jpritikin in https://github.com/OpenMx/OpenMx/issues/154#issuecomment-476217597_

**Comment by jpritikin** [comment]
> We should wrap some basic building blocks in omxCheckWarning( ,message=NA) so they are flagged as problems

Agreed. I just added one of these tests.

**Comment by mhunter1** [comment]
Is this resolved?  If not, what's the next action step and who is doing it?

**Comment by tbates** [comment]
close enough. The only other places we check a warning and tell the user, but might not need to are:

factorFitCI <- omxCheckWarning(
	mxTryHard(factorModel, fit2beat=-2863, extraTries=3, intervals=FALSE, checkHess=F),
	'the "Standard Errors" option is enabled and the "Calculate Hessian" option is disabled, which may result in poor-accuracy standard errors'
)

**Comment by jpritikin** [comment]
I think that one is needed. The Hessian from the optimizer could be wonky.
