### ISSUE TITLE
mxModel error when path added to model without type

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#160]
If the user adds a path to a base model, rather than just "does not recognize paths"  we should tell them:

> for path models, you need to add `type= "RAM"` 

Example and error below:

```R
data(demoOneFactor)
m1 <- mxModel("repro", mxData(demoOneFactor, type = "raw"),
 	mxPath("G", to = "x1)
)
```
> Error: The model 'MxModel' named 'One Factor' does not recognize paths.

Desired error = 
Error: The model 'MxModel' named 'One Factor' does not recognize paths. For path models, you need to add type= "RAM"

**Comment by mcneale** [comment]
Agreed.  Maybe be even more explicit: ... add 
, type=“RAM”
inside the parentheses of the mxModel() function, e.g., 
mxModel(“myBrilliantPathModel”, type=“RAM”, mxPath(from="G", to = "x1))

**Comment by jpritikin** [comment]
RAM or LISREL. LISREL works with paths too.

**Comment by mcneale** [comment]
Should we have a  type="Mplus" or a type="Lavaan" ?  Just to make it easier for people to switch to the most flexible and general open source software for XSEM, so they can do their part for open science and help ease the reproducibility issue?

**Comment by jpritikin** [comment]
How are Mplus and lavaan different than a subset of LISREL?

**Comment by tbates** [comment]
@mcneale are you meaning setting a type would put `mxPaths` into intermediate-lisrel-like matrices of lavaan/mplus? or setting type would allow people to add paths in the string syntax of the respective packages?

Not sure using different matrices would make moving between the packages easier.

**Comment by mcneale** [comment]
@tbates Possibly. The trouble with LISREL (unlike RAM) specification is that it isn’t 1:1 mapped onto path diagram. The same diagram has multiple equivalent representations in LISREL.  I don’t use Mplus, but I think its algebra is a subset of LISREL’s, with extensions in several directions for mixtures, LCA, multilevel etc.  We could play with LISREL’s GUI and see what defaults it picks for which matrices to use.  I imagine avoiding the Beta matrix except for feedback loops or models with more than two ‘layers’ (a->b->c) is done for computational efficiency. The LAVAAN representation is RAM, I believe. 

I figure we could parse LAVAAN scripts pretty easily; Mplus less so.

**Comment by tbates** [comment]
I think RAM uses the same 4 matrices as Mplus... I think adding a matrix for exogenous to allow distinguishing variances and residual variances (which RAM elides?)

**Comment by mcneale** [comment]
I don’t think adding an exogenous matrix is a good or necessary thing. I suspect that it was originally done in the 1960’s for computational efficiency in covariance matrix analysis.  If summary statistics (means and covariance matrices) are input, exogenous variances & means do not have to be estimated, which yields computational efficiency.  [I have thoughts about the development of LISREL from a program originally developed for multivariate multiple regression, prior to addition of Beta matrix etc, but won’t digress here].  If there are no missing data, the computational efficiency is also available, although no missingness almost never happens with real data (be skeptical if the collector says otherwise in anything other than a very small study, for which use of SEM is dubious anyway). Even so, it is not necessary to have the user identify which variables are exogenous; it can be done algorithmically by inspection of the A matrix, and estimation could be accelerated by fixing exogenous means, variances & covariances at their observed values in the S and M matrices.  However, if there are missing data, the observed means & covariances are not necessarily the MLE’s - unless missingness is completely random (and even then some drift away from Pearson calculated values will likely occur with finite N).  Nevertheless, with many covariances used repeatedly in different analyses - GWSEM for example - it could be useful computationally to estimate exogenous variables means and covariances at their MLEs once initially to avoid doing so repeatedly.  Things will go awry if the missingness mechanism is associated with the endogenous variables; the MLEs of the exogenous variables would again not be the same as when these statistics are estimated by ML, but excluding the endogenous variables).  I can see the utility in the case of regressing out exogenous variables such as principal components of ancestry as one walks along the genome modeling SNP by SNP, or in neuroimaging data to remove fixed effects of age or sex.  For continuous data this can be done up front without estimation, using e.g., lm(). But for ordinal endogenous variables, there are efficiencies to be had.

**Comment by SteveBoker** [comment]
I agree completely with Mike here.  I would also add that Timo's PPML algorithm does exactly what Mike is proposing at the end, if I understand his proposal correctly.  PPML might be particularly useful for genome modeling.

> On Apr 17, 2019, at 7:56 AM, Michael Neale <notifications@github.com> wrote:
> 
> I don’t think adding an exogenous matrix is a good or necessary thing. I suspect that it was originally done in the 1960’s for computational efficiency in covariance matrix analysis. If summary statistics (means and covariance matrices) are input, exogenous variances & means do not have to be estimated, which yields computational efficiency. [I have thoughts about the development of LISREL from a program originally developed for multivariate multiple regression, prior to addition of Beta matrix etc, but won’t digress here]. If there are no missing data, the computational efficiency is also available, although no missingness almost never happens with real data (be skeptical if the collector says otherwise in anything other than a very small study, for which use of SEM is dubious anyway). Even so, it is not necessary to have the user identify which variables are exogenous; it can be done algorithmically by inspection of the A matrix, and estimation could be accelerated by fixing exogenous means, variances & covariances at their observed values in the S and M matrices. However, if there are missing data, the observed means & covariances are not necessarily the MLE’s - unless missingness is completely random (and even then some drift away from Pearson calculated values will likely occur with finite N). Nevertheless, with many covariances used repeatedly in different analyses - GWSEM for example - it could be useful computationally to estimate exogenous variables means and covariances at their MLEs once initially to avoid doing so repeatedly. Things will go awry if the missingness mechanism is associated with the endogenous variables; the MLEs of the exogenous variables would again not be the same as when these statistics are estimated by ML, but excluding the endogenous variables). I can see the utility in the case of regressing out exogenous variables such as principal components of ancestry as one walks along the genome modeling SNP by SNP, or in neuroimaging data to remove fixed effects of age or sex. For continuous data this can be done up front without estimation, using e.g., lm(). But for ordinal endogenous variables, there are efficiencies to be had.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

----------------------------------------------------------
Steven Boker
University of Virginia
Department of Psychology
(USPS) POB 400400; Charlottesville, VA 22904
(Package) Gilmer Hall 102; Charlottesville, VA 22903
Office: 434-243-7275  Cell: 434-249-0624  
 Skype: 434-218-1248   Fax: 434-243-4939
http://people.virginia.edu/~smb3u
http://faculty.virginia.edu/humandynamicslab
http://openmx.psyc.virginia.edu
----------------------------------------------------------

**Comment by mhunter1** [comment]
@SteveBoker  I see a couple reasons to have special treatment of exogenous variables.

1. They're a special kind of definition variable which can thus be handled in more intuitive ways by users, and coded around more easily for developers
1. Unlike modeled variables, exogenous variables have no distributional assumptions.  MLEs, means, and covariances are not meaningful concepts here.
1. SEMs scale poorly in the number of modeled variables.  Add 5 exogenous variables to a model, and the number of covariances in the saturated model goes up by a factor of 21x to 1.10x.

@mcneale lavaan does not use RAM underneath.  It uses LISCOMP/Mplus matrices.  Also, LISREL does map 1-1 and onto path diagrams.  How else do you think we have `mxPath` to LISREL matrices in OpenMx?

@jpritikin LISREL is a different thing from Mplus/lavaan.  The difference is what they mean by exogenous variables.

**Comment by SteveBoker** [comment]
@Hunter

I don't agree with point 2.  Assuming independence of exogenous variables can lead to many kinds of misestimation when they actually covary.  In my mind it is better to take the computational hit and make the user think about these decisions.  However when, by "exogenous" you mean "residual", then just do away with the variable and put the double headed arrow directly on the predicted variable.

> On Apr 18, 2019, at 11:00 PM, Michael Hunter <notifications@github.com> wrote:
> 
> @SteveBoker I see a couple reasons to have special treatment of exogenous variables.
> 
> 	• They're a special kind of definition variable which can thus be handled in more intuitive ways by users, and coded around more easily for developers
> 	• Unlike modeled variables, exogenous variables have no distributional assumptions. MLEs, means, and covariances are not meaningful concepts here.
> 	• SEMs scale poorly in the number of modeled variables. Add 5 exogenous variables to a model, and the number of covariances in the saturated model goes up by a factor of 21x to 1.10x.
> @mcneale lavaan does not use RAM underneath. It uses LISCOMP/Mplus matrices. Also, LISREL does map 1-1 and onto path diagrams. How else do you think we have mxPath to LISREL matrices in OpenMx?
> 
> @jpritikin LISREL is a different thing from Mplus/lavaan. The difference is what they mean by exogenous variables.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

----------------------------------------------------------
Steven Boker
University of Virginia
Department of Psychology
(USPS) POB 400400; Charlottesville, VA 22904
(Package) Gilmer Hall 102; Charlottesville, VA 22903
Office: 434-243-7275  Cell: 434-249-0624  
 Skype: 434-218-1248   Fax: 434-243-4939
http://people.virginia.edu/~smb3u
http://faculty.virginia.edu/humandynamicslab
http://openmx.psyc.virginia.edu
----------------------------------------------------------

**Comment by mhunter1** [comment]
I'm noticing this issue has gotten off on a bit of a tangent.  Getting back to the original issue, we have support for the following types.

```
> mxTypes()
[1] "default" "RAM"     "LISREL"
```

The error message is easy enough to make more helpful as described.

```
data(demoOneFactor)
m1 <- mxModel("repro", mxData(demoOneFactor, type = "raw"),
 	mxPath("G", to = "x1)
)
# Error: The model 'MxModel' named 'One Factor' is of type 'default' and does not recognize paths.
#  Add one of type=setdiff(mxTypes(), 'default') to your model
```
