### ISSUE TITLE
RAM model with vector = TRUE

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#161]
In this [growth mixture model example](https://vipbg.vcu.edu/vipbg/OpenMx2/docs//OpenMx/2.12.1/_static/demo/GrowthMixtureModel_PathRaw.R?q=docs/OpenMx/2.12.1/_static/demo/GrowthMixtureModel_PathRaw.R), running the first model causes the following (actually pretty nice) warning:

> 1: In runHelper(model, frontendStart, intervals, silent, suppressWarnings,  :
  Class1.fitfunction does not evaluate to a 1x1 matrix. Fixing model by adding mxAlgebra(-2*sum(log(Class1.fitfunction)), 'm2ll'), mxFitFunctionAlgebra('m2ll')

I'm guessing the example should have an algebra and mxFitFunctionAlgebra added to the script?

But maybe also given RAM adds the FitFunctionML and ExpectationRAM automatically, we should have a vector = c(FALSE, TRUE), valid for models of type = "RAM" which would do this for the user?

then
```R
m1 = mxModel(... type = "RAM", 
    mxFitFunctionML(vector=TRUE)
    mxAlgebra(-2*sum(log(Class1.fitfunction)), 'm2ll'),
    mxFitFunctionAlgebra('m2ll')
```

becomes
```R
m1 = mxModel(... type = "RAM", vector = TRUE,
)
```

**Comment by jpritikin** [comment]
> I'm guessing the example should have an algebra and mxFitFunctionAlgebra added to the script?

Why are you running only the first model? Mixture models need per-row likelihoods. If you run only 1 component then OpenMx assumes that you want to optimize the sum of the per-row likelhoods. What is confusing?

> But maybe also given RAM adds the FitFunctionML and ExpectationRAM automatically, we should have a vector = c(FALSE, TRUE), valid for models of type = "RAM" which would do this for the user?

This seems crazy to me. Why do you think this is a good idea?
