### ISSUE TITLE
mxPath: tell user what values were offered up

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#163]
If `mxPath` gets bad values, it errors, but doesn't tell the user what it was offered.

```R
mxPath("alice", to = "bob", values = list(v=1)["v"])
```
> Error: The 'values' argument to mxPath must be a numeric vector of length > 0
> in mxPath("alice", to = "bob", values = list(v = 1)["v"])

Be nice to say
> Error: 'values' for mxPath must be a vector of numbers. In 
> mxPath("alice", to = "bob", values = list(v = 1)["v"])
> values was an object of class "list" of length 1

fyi, the list needed [[]] access.

**Comment by tbates** [comment]
same with from - the user can't tell what R thought they sent vs. what they intended.. Very helpful to say
> you offered up a 1*1 dataframe containing "A" 

at the end of:

> Error: The 'from' argument to mxPath must be a character vector of length > 0 in mxPath(from = from, to = to, connect = connect, arrows = arrows, free = free, values = values, labels = labels, lbound = lbound, ubound = ubound)

**Comment by mcneale** [comment]
Even better to provide examples of correct code.:

> Error: 'values' for mxPath must be a vector of numbers,  e.g., c(.5, .6, .7). In
mxPath("alice", to = "bob", values = list(v = 1)["v"])
values was an object of class "list" of length 1, and I'm not exactly sure what to do with that.  Keep any suggestions polite if possible!

**Comment by tbates** [comment]
An empty label in `mxPath` generates the following error from `generatePath` (which the user won't recognise) and doesn't identify the faulty parameter:

mxPath("bob", label="")
> Error: The reference '' in generatePath(from, to, connect, arrows, values, free, labels, lbound, ubound, joinKey) is illegal because references of zero length are not allowed

Should be caught prior to generate path so the user see that this is a problem with mxPath and may even see what the call was.

Error should say what parameter was faulty and what was offered up:

> label cannot be an empty string in mxPath

**Comment by mhunter1** [comment]
@tbates can you split these off into separate issues?  They are related in that they all involve `mxPath` but to my mind they're all separate fixes with separate tests.

**Comment by tbates** [comment]
nice!
```R
mxPath("alice", to = "bob", values = list(v=1)["v"])
```
> Error: The 'values' argument to mxPath must be a numeric vector of length > 0 in mxPath("alice", to = "bob", values = list(v = 1)["v"]) 'values' argument had class list and length 1
