### ISSUE TITLE
mxData: support type="cor"

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#164]
[here](https://openmx.ssri.psu.edu/node/4469) @mikewlcheung notes that `metaSEM::create.vechsR`  solves this for WLS and could readily meet our needs.

It creates a model-implied covariance matrix ensuring that the diagonals are always ones (no `mxConstraints` required).

[function code here](https://gist.github.com/tbates/13415f160a9de86243b8e60ffdfe6012). It is based on WLS so needs modifying for ML etc.

there's pdf detailing everything [here](https://openmx.ssri.psu.edu/sites/default/files/cor_structure.pdf)

**Comment by RMKirkpatrick** [comment]
I did see Mike Cheung's post.  I still don't understand its relevance to this issue.  RAM expectation has no slot for a model-expected covariance matrix.  Instead, it calculates it internally at runtime from _A_, _S_, and _F_.

As we discussed at the meeting on Friday, the idea is to automate the necessary constraints on the diagonal for models of `type="RAM"`, because using `type="RAM"` is intended for novices.  Users who want to analyze correlation matrices in other contexts are responsible for ensuring the diagonals are fixed to 1.  There, Mike Cheung's approach might be useful for them.

After thinking about it over the weekend, I think the way forward with `type="RAM"` is to automatically add the following to the model at runtime:
```
mxMatrix(type="Unit", ncol=1, nrow=length(manifestVars), name="toBeDetermined1")
mxConstraint(diag2vec(F %*% solve(I-A) %*% S %*% t(solve(I-A)) %*% t(F)) == "toBeDetermined1", name="toBeDetermined2")
```

If I understand correctly, that would suffice to get the correct df.  If that's not the case, then we'll have to debug the summary method for MxModels.

What should these objects be named, and should their names be reserved names?

**Comment by mcneale** [comment]
That sounds right to me - automatically add constraints if and only if the user declares the matrix as type='cor'.  If the user specifies type='cov' AND the diagonal contains nothing but 1's, we could issue a warning:

Warning:  Correlation matrix data were input, but data type='cov' was declared.  Appropriate analysis of correlation matrices should be done by declaring type='cor'.  Doing so in this model will automatically add constraints to ensure that the model will have an expected covariance matrix with  1's on the diagonal, within the numerical precision defined by mxOption() 'Feasiblity Tolerance'.   The default value of this option is .05, which is usually sufficient.  

I must say that I'm surprised (shocked, even) that we only use  .05; .0001 or less would seem a more appropriate default.   Was this  fiddled with to make issues with difficult constraint test problems go away?  NPSOL's default is the square root of machine precision, which is much smaller, yet that is what classic Mx used to use, iirc.

Ok, enough of my off-topic griping, names for the objects:
tbd1: 'vectorOfOnesForConstraintDiagonalsEqualOne'
tbd2: 'ConstraintDiagonalsEqualOne'

**Comment by RMKirkpatrick** [comment]
@mcneale FYI this is what the man page for `mxOption()` says:

> If the MxModel contains MxConstraints, OpenMx's interface to NPSOL scales “Feasibility tolerance” by multiplying it by 0.02 and dividing it by 0.05 before passing it to NPSOL; if there are no MxConstraints, OpenMx passes NPSOL a hard-coded value of 1e-5.

I guess "multiplying it by 0.4" would be less wordy than the current text.  AFAIK, SLSQP and CSOLNP use "Feasibility tolerance" as-is.  I know Nelder-Mead does.

**Comment by mcneale** [comment]
@RMKirkpatrick yes, but on a freshly opened R session & library(OpenMx) (2.12.0) I get:
<code>
> options()$mxOption$`Feasibility tolerance`
[1] "5e-2"
</code>
So the documentation seems wrong as well.  What's up with that?

**Comment by RMKirkpatrick** [comment]
@mcneale Huh?  The on-load default value for "Feasibility tolerance" is 0.05, which is exactly what you're seeing there.

**Comment by mcneale** [comment]
@RMKirkpatrick It depends what is meant by "OpenMx's interface to NPSOL scales “Feasibility tolerance” by multiplying it by 0.02 and dividing it by 0.05 before passing it to NPSOL" the "it" is not clearly defined.  NPSOL's default is what I thought the "it" meant, i.e., sqrt(machine precision).  This does speak to the rather impenetrable and ambiguous state of the documentation, which we should fix.  The On-Load default feasibility tolerance seems to be over 6 orders of magnitude larger than NPSOL's default, which around 3.162278e-08 for double precision systems.

**Comment by RMKirkpatrick** [comment]
@mcneale I think from the context in which that passage appears in the man page, it's fairly clear that the "it" is the value of mxOption "Feasibility tolerance".

You're correct that NPSOL's default feasibility tolerance is the square root of double eps.  But OpenMx's on-load default has been 0.05 for as long as I can remember.  I don't see that it's been a problem.

**Comment by mcneale** [comment]
Conversely, I've heard some grumbles that the constraints were not adequately satisfied.  A million times less stringent seems quite a bit poorer criterion choice to me.

**Comment by mcneale** [comment]
IMO, "If the MxModel containsMxConstraints, OpenMx's interface to NPSOL scales “Feasibility tolerance” by multiplying it by 0.02 and dividing it by 0.05 before passing it to NPSOL" should be changed to read: "Note that NPSOL is given 0.4 times the value of the mxOption "Feasibility Tolerance", and that OpenMx's default is about a million times bigger than NPSOL's.  Values of "Feasibility Tolerance" around 1e-5 may be needed to get constraint performance similar to NPSOL's default."

**Comment by tbates** [comment]
So need also to define `I` matrix (took a guess here).
And something else is up as adding those three objects breaks mxRun (see #166 )

```R
require(umx); data(demoOneFactor); manifests = names(demoOneFactor)
# make cor data and a 1-factor RAM model
myData   = mxData(cor(demoOneFactor), type = "cor", numObs = 500)
m1 <- umxRAM("OneFactor", data = myData,
	umxPath("g", to = manifests),
	umxPath(var = manifests),
	umxPath(var = "g", fixedAt = 1)
)

# Add I, unit_1_by_nVar, and constraintForCorData
m2 <- mxModel(m1, name= "cor_ekt",
	mxMatrix(name= "I", type="Iden", ncol=length(manifestVars)),
	mxMatrix(name= "unit_1_by_nVar", type="Unit", ncol=1, nrow=length(manifestVars)),
	mxConstraint(name="constraintForCorData", diag2vec(F %*% solve(I-A) %*% S %*% t(solve(I-A)) %*% t(F)) == "unit_1_by_nVar")
)
m2 = mxRun(m2)

**Comment by mcneale** [comment]
It's manifests, not manifestVars, and the I you need is dimension manifests+latents.   Then you get our sparkly new human-parseable error message:

`require(umx); data(demoOneFactor); manifests = names(demoOneFactor)
# make cor data and a 1-factor RAM model
myData   = mxData(cor(demoOneFactor), type = "cor", numObs = 500)
m1 <- umxRAM("OneFactor", data = myData,
	umxPath("g", to = manifests),
	umxPath(var = manifests),
	umxPath(var = "g", fixedAt = 1)
)

# Add I, unit_1_by_nVar, and constraintForCorData
m2 <- mxModel(m1, name= "cor_ekt",
	mxMatrix(name= "I", type="Iden", ncol=length(manifests)+length(latents)),
	mxMatrix(name= "unit_1_by_nVar", type="Unit", ncol=1, nrow=length(manifests)),
	mxConstraint(name="constraintForCorData", diag2vec(F %*% solve(I-A) %*% S %*% t(solve(I-A)) %*% t(F)) == unit_1_by_nVar)
)
m2 = mxRun(m2)`
which is:
In FUN(X[[i]], ...) :
  OpenMx does not yet correctly handle mxData(type='cor') standard errors and fit statistics. See Steiger (1980), "Tests for comparing elements of a correlation matrix".

The In FUN(X[[i]], ...) is still somewhat unfun for humans though.

**Comment by tbates** [comment]
Awesome stuff @mcneale  and @RMKirkpatrick !

**Comment by mhunter1** [comment]
Some TODO for anyone who cares about this issue.

1. Add a script that uses data with `type='cor'`
1. Notate what is wrong with model estimation in said example
1. Notate what is wrong with model reporting (e.g. `summary`) in said example
1. Describe what may need to be fixed or altered, and what approaches may or may not work.

Without this information, I strongly doubt anything will ever happen toward resolving this.

**Comment by RMKirkpatrick** [comment]
@mhunter1 This is the forums thread in which the issue was first raised: https://openmx.ssri.psu.edu/node/4469 .

**Comment by mcneale** [comment]
Seems to me that it would need a little blog or vignette to walk users through the logic.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Oct 18, 2019, at 10:53 AM, RMKirkpatrick <notifications@github.com<mailto:notifications@github.com>> wrote:


@mhunter1<https://urldefense.com/v3/__https://github.com/mhunter1__;!632Gf1zpPew!0DyV-mw-vp2qpu72JLewnEY319iSwmEDT1eSHgnRO4qQrtCjJpjggyRDdCfQQyMUGw$> This is the forums thread in which the issue was first raised: https://openmx.ssri.psu.edu/node/4469<https://urldefense.com/v3/__https://openmx.ssri.psu.edu/node/4469__;!632Gf1zpPew!0DyV-mw-vp2qpu72JLewnEY319iSwmEDT1eSHgnRO4qQrtCjJpjggyRDdCeAMuy0yQ$> .

**Comment by tbates** [comment]
Hi @mhunter1, the  comments up from here give a script with `m1` using type='cor' data, then `m2` incorporating a fix, along with a printout of the summary showing differences.

**Comment by mcneale** [comment]
Example of 2 variables, wls, making one binary causes acov to go non-pd.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral GeneticsIPBG
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 MCV Richmond VA 23298-0126
Telephone: (804) 828-3369  Email: michael.neale@vcuhealth.org

>

**Comment by mcneale** [comment]
Since the rate limiting factor in GREML analyses is inverting large but hopefully positive definite matrices, it seems that the paper at https://arxiv.org/pdf/1010.2000.pdfhttps://arxiv.org/pdf/1010.2000.pdf could be useful.  It talks about PLASMA<http://icl.utk.edu/plasma/software/browse.html?start=4&per=5> software, and notes some 100% improvement of variant 3 over variant 1 algorithm.  The number of threads for maximum gigaflop performance maxes out at 16 in some cases, 26 in others.  It seems that substantial gains over MKL/LAPACK can be had.



Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral GeneticsIPBG
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 MCV Richmond VA 23298-0126
Telephone: (804) 828-3369  Email: michael.neale@vcuhealth.org<mailto:michael.neale@vcuhealth.org>

**Comment by RMKirkpatrick** [comment]
@mcneale The arXiv link is broken.  Also, what is the relevance to this issue?  Did you mean to email the OpenMx list?

**Comment by jpritikin** [comment]
Per today's discussion:

- [ ] Expose the model expected distribution in the front-end by adding optional slots in the expectation that name matrices where the expected distribution will be stored.
- [ ] Change the documentation/warnings to recommend to expose the model expected covariance matrix and add a constraint on it.
- [ ] Add test to ensure that it works

**Comment by jpritikin** [comment]
Code-wise, this is a fairly simple change. We already allocate memory for the expected covariance in the backend so there should be essentially no performance impact. Here's what it would look like,

````
m2 <- mxModel(m1, name= "cor_ekt",
              mxMatrix(name="ecov", nrow=length(manifests), ncol=length(manifests)),
              mxMatrix(name= "unit_1_by_nVar", type="Unit", ncol=1, nrow=length(manifests)),
              mxConstraint(name="constraintForCorData", diag2vec(ecov) == unit_1_by_nVar)
)
# also could be set in the mxExpectation constructor:
m2$expectation$expectedCovariance = "ecov"
````

The nice thing is that it would look the same regardless of whether we're using RAM or LISREL specification.

Can I get a thumbs up or two before I finish it up?

**Comment by mcneale** [comment]
It looks like the solution - adding constraints - is correct.  I am confused about the level of automagic that will be used here.  Is it level 0 where the user has to explicitly put in the constraints themselves, or is it level 9 where OpenMx figures out that it's a correlation matrix (from user input or from the diagonal of the observed covariances) and automagically adds constraints to make its analysis correct.  I have a feeling it's the latter, in which case we should be careful that the semi-expert user doesn't do both manually and automagically (which should have perfectly correlated non-linear constraints and be problematic for the optimizer).

**Comment by RMKirkpatrick** [comment]
@mcneale It's level 9, but only in the case of `type="RAM"` or `type="LISREL"`.  Otherwise, the user is responsible for ensuring the diagonal elements are fixed to 1.0.

**Comment by jpritikin** [comment]
> Is it level 0 where the user has to explicitly put in the constraints themselves

That's the extend of my work so far.

> or is it level 9 where OpenMx figures out that it's a correlation matrix (from user input or from the diagonal of the observed covariances) and automagically adds constraints to make its analysis correct.

I guess we could do that now that it's easy to hack into the frontend. Rob said "level 9" so I'll update the TODO list above.

**Comment by jpritikin** [comment]
Does the level 9 automatic fix work on multigroup models? It seems like the `df` calculation could get complex if some parameters are constrained equal across groups?

**Comment by jpritikin** [comment]
Take a look at v2.15.5-19-g16245ac34 and let me know whether anything is missing.

**Comment by tbates** [comment]
Great stuff @jpritikin !

The `cor` and `cov` model have the same `ep` and `df`, and `AIC`. 

But is it the case that the `-2LL` for the **cov** data model has changed?

I the 1-factor example, -2LL is now `-3660.59` but I think prior to this fix, both cov and cor models had `-2LL` of `-1230.13` (so the cov model had relatively better AIC).

```R
require(umx); data(demoOneFactor); 

# 1. make two types of data: cor & cov
myCorData = mxData(cor(demoOneFactor), type = "cor", numObs = 500)
myCovData = mxData(cov(demoOneFactor), type = "cov", numObs = 500)

manifests = names(demoOneFactor)
corMod <- umxRAM("CorMod", data = myCorData,
	umxPath("g", to = manifests),
	umxPath(var = manifests),
	umxPath(var = "g", fixedAt = 1)
)

covMod = umxRAM("CovMod", data = myCovData,
	umxPath("g", to = manifests),
	umxPath(var = manifests),
	umxPath(var = "g", fixedAt = 1)
)

mxCompare(corMod, covMod)
```
| base       | comparison   | ep | minus2LL  | df | AIC        | diffLL         | diffdf | p  |
|:---------|:-------------|:---|:-----------|:---|:--------|:-----------|:------|:---|
| CorMod |                        | 10 | -1230.13  | 5  | -2.6049   |                   |            |      |
| CorMod | CovMod         | 10 | -3660.59 | 5  | -2.6062  | -2430.467 | 0        | NA |

Prior to this update, I think the results were:

| model   | ep | minus2LL  | df | AIC           |
|:--------|:---|:-----------|:---|---------:|
|old cor   | 10 | -1230.131  |  0  |  7.3938   |
|old Cov  | 10 | -1230.131  | 5   | -2.6062 |  


```R
OpenMx version: 2.15.5.19 [GIT v2.15.5-19-g16245ac]
```
