### ISSUE TITLE
Feasibility tolerance message

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#165]
We say
> If the MxModel containsMxConstraints, OpenMx's interface to NPSOL scales “Feasibility tolerance” by multiplying it by 0.02 and dividing it by 0.05 before passing it to NPSOL

Should be changed to read: 

> Note that NPSOL is given 0.4 times the value of the mxOption "Feasibility Tolerance", and that OpenMx's default is about a million times bigger than NPSOL's.  Values of "Feasibility Tolerance" around 1e-5 may be needed to get constraint performance similar to NPSOL's default."

_Originally posted by @mcneale in https://github.com/OpenMx/OpenMx/issues/164#issuecomment-483849086_

**Comment by tbates** [comment]
surprised we only use  .05; .0001 or less would seem a more appropriate default.   Was this fiddled with to make issues with difficult constraint test problems go away?  NPSOL's default is the square root of machine precision, which is much smaller, yet that is what classic Mx used to use, iirc.

Conversely, I've heard some grumbles that the constraints were not adequately satisfied. A million times less stringent seems quite a bit poorer criterion choice to me.

**Comment by tbates** [comment]
On old issue 164
@RMKirkpatrick  noted
"multiplying it by 0.4" would be less wordy than the current text (multiplying it by 0.02 and dividing it by 0.05) Also that Nelder-Mead, and (AFAWK) SLSQP and CSOLNP use "Feasibility tolerance" as-is.

@mcneale  noted the need to be clear that what is being modified is the online default, not NPSOLs own internal default (i.e., `sqrt(machine precision)`).

Given that the On-Load default feasibility tolerance is ~ 6 orders of magnitude larger than NPSOL's default (around 3.162278e-08), and some users have mentioned constraints not being satisifed precisely enough, that we might reduce the default feasibility tolerance.

@RMKirkpatrick  noted it has been 0.05 for as long as I can remember.

@mcneale suggested the working
> "If the MxModel containsMxConstraints, OpenMx's interface to NPSOL scales “Feasibility tolerance” by multiplying it by 0.02 and dividing it by 0.05 before passing it to NPSOL" should be changed to read: "Note that NPSOL is given 0.4 times the value of the mxOption "Feasibility Tolerance", and that OpenMx's default is about a million times bigger than NPSOL's. Values of "Feasibility Tolerance" around 1e-5 may be needed to get constraint performance similar to NPSOL's default."

**Comment by tbates** [comment]
I moved the comments about feasibility out of #164 to here, and implemented @mcneale 's suggested changes to the Rd file.

If there's a motivation to use the NPSOL precision for the other optimizers, or to keep the precision used with-contraints closer to the default for NPSOL then perhaps a new issue is needed?

**Comment by jpritikin** [comment]
NPSOL usually needs to be run twice to get a reasonable solution on constrained problems. I don't think the tolerance really matters. It's some algorithm issue. SLSQP is much better in this regard and can usually solve a problem in 1 invocation.
