### ISSUE TITLE
Error when simulating fake data

### ISSUE THREAD

**Issue by timothyjgraham** [OpenMx/OpenMx#17]
Hi OpenMX team,

I am trying to simulate fake data based on an existing dataframe. I have converted all the columns to ordered factors, as required. However, I receive the follow error when trying to create simulated data using the `mxGenerateData` function. Below is the code. Many thanks in advance for your help.

```
simulatedData <- mxGenerateData(projectDataSubset_for_simulation,nrow=100)

Calculating asymptotic summary statistics ...
Error: you must specify 'nrow' and 'ncol' arguments in mxMatrix(values = wlsData$thresholds, name = "thresh")

```

Cheers,

Tim

**Comment by jpritikin** [comment]
Please report the output from `mxVersion()`. Also, can you provide 2-3 rows of your data so that we may easily reproduce the problem? Thanks.

**Comment by timothyjgraham** [comment]
Hi @jpritikin,

Many thanks for your speedy reply. The output from `mxVersion()` is:

OpenMx version: 2.7.4 [GIT v2.7.4]
R version: R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 
MacOS: 10.11.6
Default optimiser: CSOLNP

Here is a link to the CSV file with 10 rows of the data:

https://www.dropbox.com/s/wtmzkl5vfiuwahj/example_data_for_generating_fake_data.csv?dl=0

I would also note that I am able to generate a different error when running `mxGenerateData` using this dataset:

```
Calculating asymptotic summary statistics ...
Error in chol.default(U) : 
  the leading minor of order 10 is not positive definite
```

**Comment by timothyjgraham** [comment]
Hi @jpritikin,

I believe I have identified the problem, which required coercing all the variables to `ordered` and also removing the period characters from the column names:
```

for (i in 1:ncol(exampleData)){
  exampleData[,i] <- ordered(exampleData[,i])
}

colnames(exampleData) <- gsub("\\.","",colnames(exampleData))
```

So my apologies for taking up your time, but I hope this comment might help other users.

**Comment by jpritikin** [comment]
Ah good, but those are conditions we ought to check for and provide helpful diagnostics.

**Comment by jpritikin** [comment]
Can you show that original code to load the file that didn't work?

**Comment by timothyjgraham** [comment]
The code I originally used was simply:

`simulatedData <- mxGenerateData(projectDataSubset_for_simulation,nrow=100)` ,

where `projectDataSubset_for_simulation` is the dataframe object as per the example data I provided a link to in an earlier comment.

I believe the problem was simply due to the columns being of the wrong type - I think numerical.

Congratulations on an excellent and highly useful piece of software.

**Comment by jpritikin** [comment]
Yeah but how did you load the data? read.csv or read.table or what?

**Comment by timothyjgraham** [comment]
Yes - `read.csv`

**Comment by jpritikin** [comment]
OK, I have pushed changes that would have made it much easier for you to diagnose these problems.

**Comment by timothyjgraham** [comment]
@jpritikin, I know this thread is now closed (thanks for your help again). However, can I also ask whether it is possible to simulate data using factors (not just ordered factors)? Is this something you are looking to implement?

**Comment by jpritikin** [comment]
Factors? Well, you need some kind of model. What model do you have in mind? OpenMx does not yet have great support for latent classes. We're looking at improving that with Hidden Markov models.

**Comment by timothyjgraham** [comment]
Even just a logistic model does the trick for this kind of data. The target variable is binary. If you have any links to tutorials or particular functions within the help file, that would be really appreciated.

**Comment by jpritikin** [comment]
On Wed, Feb 22, 2017 at 06:14:05PM -0800, Tim Graham wrote:
>    Even just a logistic model does the trick for this kind of data.

I'm confused. For binary variables, is there a difference between 
ordered and unordered?

>    The target variable is binary. If you have any links to tutorials 
>    or particular functions within the help file, that would be really 
>    appreciated.

Can you use rpf.sample from the rpf package?

  https://cran.r-project.org/web/packages/rpf/

It's pretty easy to build models for this,

  https://journal.r-project.org/archive/2016-1/pritikin-schmidt.pdf

**Comment by timothyjgraham** [comment]
Thanks - I will look into it and see how far I can get.
