### ISSUE TITLE
mxModel: name should check it is a string

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#171]
bit of an edge case, but we allow non-character input as a name for mxModel
```R
bob = "desiredName";
names(bob)= "I shouldnt be here"

m2 = mxModel(bob)
m2$name
I shouldnt be here 
     "desiredName" 
```

If the model is run, it generates these obscure warnings:

```R
m2 = mxRun(m2)
```

> Running desiredName with 9 parameters
> Warning messages:
1: In data.frame(model = modelName, matrix = matrix@name, row = rows,  :
  row names were found from a short variable and have been discarded
2: In data.frame(model = modelName, matrix = matrix@name, row = rows,  :
  row names were found from a short variable and have been discarded
3: In data.frame(model = modelName, matrix = matrix@name, row = rows,  :
  row names were found from a short variable and have been discarded
...

(FYI, this was encountered because `mxMakeNames` outputs an attributed string if given a length one input)

**Comment by RMKirkpatrick** [comment]
The man page for `mxModel()` says:

> 
model | This argument is either an MxModel object or a string. If 'model' is an MxModel object, then all elements of that model are placed in the resulting MxModel object. If 'model' is a string, then a new model is created with the string as its name. If 'model' is either unspecified or 'model' is a named entity, data source, or MxPath object, then a new model is created.
-- | --

The MxModel object created by the code in the OP looks like:
```
> str(m2)
Formal class 'MxModel' [package "OpenMx"] with 21 slots
  ..@ name             : Named chr "desiredName"
  .. ..- attr(*, "names")= chr "I shouldnt be here"
  ..@ matrices         : list()
  ..@ algebras         : list()
  ..@ constraints      : list()
  ..@ intervals        : list()
  ..@ latentVars       : chr(0) 
  ..@ manifestVars     : chr(0) 
  ..@ data             : NULL
  ..@ submodels        : list()
  ..@ expectation      : NULL
  ..@ fitfunction      : NULL
  ..@ compute          : NULL
  ..@ independent      : logi FALSE
  ..@ options          : list()
  ..@ output           : list()
  ..@ runstate         : list()
  ..@ .newobjects      : logi FALSE
  ..@ .resetdata       : logi FALSE
  ..@ .wasRun          : logi FALSE
  ..@ .modifiedSinceRun: logi FALSE
  ..@ .version         : chr "2.12.2.357"
```
What's the issue here?

**Comment by tbates** [comment]
try running that model....

It dumps a bunch of warnings into the console about short variable names or something. Because it didn't strip the attributes from the string when it stored it in the name slot.

**Comment by mcneale** [comment]
I tried:
```R
> library (OpenMx)
To take full advantage of multiple cores, use:
  mxOption(NULL, 'Number of Threads', parallel::detectCores()) #now
  Sys.setenv(OMP_NUM_THREADS=parallel::detectCores()) #before library(OpenMx)
> bob = "desiredName";
> names(bob)= "I shouldnt be here"
> 
> m2 = mxModel(bob)
> m2$name
I shouldnt be here 
     "desiredName" 
> m3<-mxRun(m2) 
> mxVersion()
OpenMx version: 2.12.0 [GIT v2.12.0]
R version: R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 
MacOS: 10.13.6
Default optimizer: CSOLNP
NPSOL-enabled?: Yes
OpenMP-enabled?: Yes
```
No warnings with the current release version that I can see.

**Comment by tbates** [comment]
I can't replicate this now: When I ran the  model is it generated these obscure warnings: Must have some how made the model into a cell in dataframe... closing
