### ISSUE TITLE
AnalyticConstraintJacobians--Eq_and_Ineq

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#174]
Error CSOLNP models/passing/AnalyticConstraintJacobians--Eq_and_Ineq.R
   ***
   [1] "In omxCheckCloseEnough(mxEval(Sigma, m2, T)[c(2, 3, 6)], c(0.5,
   0.5, 0.5), 0.05) : not equal to within 0.05 : '0.293623874607766
   0.467954918183402 0.420627560791117' and '0.5 0.5 0.5'"

**Comment by jpritikin** [comment]
Error CSOLNP models/passing/AnalyticConstraintJacobians--Eq_and_Ineq.R ***
[1] "In omxCheckCloseEnough(mxEval(Sigma, m2, T)[c(2, 3, 6)], c(0.5, 0.5, 0.5), 0.05) : not equal to within 0.05 : '0.293623874607766 0.467954918183402 0.420627560791117' and '0.5 0.5 0.5'"

**Comment by jpritikin** [comment]
Error CSOLNP models/passing/AnalyticConstraintJacobians--Eq_and_Ineq.R ***
[1] "In omxCheckCloseEnough(mxEval(Sigma, m2, T)[c(2, 3, 6)], c(0.5, 0.5, 0.5), 0.05) : not equal to within 0.05 : '0.293623874607766 0.467954918183402 0.420627560791117' and '0.5 0.5 0.5'"

Something is screwed up.

**Comment by RMKirkpatrick** [comment]
Happened again last night.  I cannot reproduce it on my local build machine.  Can anyone else?

I agree that it appears to be a regression, and that it's probably my fault.

**Comment by jpritikin** [comment]
Can you run the test with valgrind?

**Comment by RMKirkpatrick** [comment]
@jpritikin Will do.

**Comment by RMKirkpatrick** [comment]
valgrind didn't report anything, at least not with its default tool.

**Comment by RMKirkpatrick** [comment]
Can anyone on MacOS reproduce this test failure?  @mcneale ? @tbates ? @trbrick ?

**Comment by tbates** [comment]
It’s running fine for me from top to bottom
OpenMx version: 2.12.2.433 [GIT v2.12.2-433-gfc955de]
R version: R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 
MacOS: 10.14.5
Default optimizer: CSOLNP
NPSOL-enabled?: Yes
OpenMP-enabled?: Yes

~/bin/OpenMx/inst/models/passing/AnalyticConstraintJacobians--Eq_and_Ineq.R

**Comment by mcneale** [comment]
Works fine for  me too.  Even with CSOLNP!

m4$output$evaluations > m6$output$evaluations is true. 
> omxCheckCloseEnough(mxEval(Tau,m6,T)[1,],c(1.64,1.64,1.64),0.1)
mxEval(Tau, m6, T)[1, ] and c(1.64, 1.64, 1.64) are equal to within 0.1.
> omxCheckCloseEnough(mxEval(Sigma,m6,T)[c(2,3,6)],c(0.5,0.5,0.5),0.05)
mxEval(Sigma, m6, T)[c(2, 3, 6)] and c(0.5, 0.5, 0.5) are equal to within 0.05.
> omxCheckCloseEnough(diag(mxEval(Sigma,m6,T)),c(1,1,1),as.numeric(mxOption(NULL,"Feasibility tolerance")))
diag(mxEval(Sigma, m6, T)) and c(1, 1, 1) are equal to within 0.05.
> omxCheckCloseEnough(mxEval(Tau,m6,T)[1,],mxEval(Tau,m2,T)[1,],5e-4)
mxEval(Tau, m6, T)[1, ] and mxEval(Tau, m2, T)[1, ] are equal to within 5e-04.
> omxCheckCloseEnough(mxEval(Sigma,m6,T),mxEval(Sigma,m2,T),5e-4)
mxEval(Sigma, m6, T) and mxEval(Sigma, m2, T) are equal to within 5e-04.

> mxVersion()
OpenMx version: 2.12.2.411 [GIT v2.12.2-411-gd3af9d2a]
R version: R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 
MacOS: 10.13.6
Default optimizer: CSOLNP
NPSOL-enabled?: Yes
OpenMP-enabled?: Yes

**Comment by jpritikin** [comment]
Discussed in May 24 meeting
