### ISSUE TITLE
nightly/brooke.R

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#175]
Error SLSQP models/nightly/brooke.R ***
[1] "In omxCheckCloseEnough(c(mod1Res$ThMZf$values), c(0.732, 0.305), 0.01) : not equal to within 0.01 : '0.741404793201432 0.294936617500641' and '0.732 0.305'"

**Comment by jpritikin** [comment]
Error SLSQP models/nightly/brooke.R ***
[1] "`a` not equivalent to `b`.\n2/2 mismatches (average diff: 0.0692)\n[1] 0.684 - 0.732 == -0.0476\n[2] 0.214 - 0.305 == -0.0907"

**Comment by tbates** [comment]
Feels like the line `mod1Res <- mxRun(mod1)`, should just be rewritten as:

```R
mod1Res <- mxTryHard(mod1)
```

NPSOL (not generating fails) gets special help: it gets to `tryHard`.

```R
if (mxOption(NULL, "Default optimizer") == 'NPSOL' &&
	max(abs(c(mod1Res$ThMZf$values) - c(0.779, 0.341))) < .01) {
	# NPSOL can get stuck in a local minimum
	mod1Res <- mxTryHard(mod1Res)
}
```
Maybe `brooke.R` is just a case where SLSQP & NPSOL both benefit from tryHard (a common occurrence). Or if we think it's exposing a problem, should remove the special circumstance for NPSOL as well?

**Comment by RMKirkpatrick** [comment]
Looks like it failed again during last night's nightly run:

> travis_fold:end:NPSOL
Number of errors: 1 
Error NPSOL models/nightly/brooke.R ***
[1] "`a` not equivalent to `b`.\n2/2 mismatches (average diff: 0.0195)\n[1] 0.753 - 0.732 == 0.0205\n[2] 0.323 - 0.305 == 0.0184"

**Comment by tbates** [comment]
looks like some code added in August 2020 fixed this

```R
if (mxOption(NULL, "Default optimizer") == 'NPSOL' &&
	    max(abs(c(mod1Res$ThMZf$values) - c(0.779, 0.341))) < .01) {
	# NPSOL can get stuck in a local minimum
	mod1Res <- mxTryHard(mod1Res)
}
```
