### ISSUE TITLE
Make mxRAMModel a subclass of mxModel so that users can climb the tree

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#176]
@tbates brought this up in the OpenMx meeting.

From R/MxRAMModel.R:L

```
setClass(Class = "MxRAMModel",
	contains = "MxModel")
```

Also note this example,

```
require(OpenMx)

# A working example using OpenMx Path Syntax
data(HS.ability.data)  # load the data

# The manifest variables loading on each proposed latent variable
Spatial   <- c("visual", "cubes", "paper")
Verbal    <- c("general", "paragrap", "sentence")
Math      <- c("numeric", "series", "arithmet")

latents   <- c("vis", "math", "text")
manifests <-  c(Spatial, Math, Verbal)

HSModel <- mxModel(model="Holzinger_and_Swineford_1939", type="RAM", 
    manifestVars = manifests, # list the measured variables (boxes)
    latentVars   = latents,   # list the latent variables (circles)
    # factor loadings from latents to  manifests
    mxPath(from="vis",  to=Spatial),# factor loadings
    mxPath(from="math", to=Math),   # factor loadings
    mxPath(from="text", to=Verbal), # factor loadings

    # Allow latent variables to covary 
    mxPath(from="vis" , to="math", arrows=2, free=TRUE),
    mxPath(from="vis" , to="text", arrows=2, free=TRUE),
    mxPath(from="math", to="text", arrows=2, free=TRUE),

    # Allow latent variables to have variance
    mxPath(from=latents, arrows=2, free=FALSE, values=1.0),
    # Manifest have residual variance
    mxPath(from=manifests, arrows=2),   
    # the data to be analysed
    mxData(cov(HS.ability.data[,manifests]), type = "cov", numObs = 301))

class(HSModel)
#[1] "MxRAMModel"
# attr(,"package")
# [1] "OpenMx"
is(HSModel)
# [1] "MxRAMModel" "MxModel" 
```

These things indicate to me that `MxRAMModel` already is a subclass of `MxModel`.  @tbates, please provide your documentation that it isn't.  Once that is documented, we can assign someone else to resolve it.

**Comment by tbates** [comment]
I had an S3 function which when passed an MxRAMModel object threw the error that no S3 handler was defined for MxRAMModel, even though a handler was defined for MxModel.

That made me think that something is wrong in the inheritance tree that an object with no handler didn't get passed up the tree to find a level at which objects in that family were handled.

If that's actually R behavior and objects need S3 handlers defined for every sub-class, then I can solve the problem by just defining MxRAMModel handlers.

**Comment by mhunter1** [comment]
`OpenMx` has several S3 methods that are only defined for MxModel objects, and they work fine for MxRAMModel objects.  Examples: 

1. `anova.MxModel`
1. `simulate.MxModel`
1. `confint.MxModel`
1. `vcov.MxModel`
1. `summary.MxModel`
1. `logLik.MxModel`
1. `coef.MxModel`

All of these S3 methods inherit properly and follow the subclass structure without special intervention.

Perhaps this is a problem operating _across_ packages.  If `umx` tries to extend and subclass `OpenMx` classes, then I know R can be finicky about how `umx` defines its NAMESPACE and DESCRIPTION.

Here's another example:

```

require(OpenMx)

# Define new S3 method
bob <- function(model){
	UseMethod("bob")
}

# Define method for only the MxModel class
bob.MxModel <- function(model){
	model$name
}


# A working example using OpenMx Path Syntax
data(HS.ability.data)  # load the data

# The manifest variables loading on each proposed latent variable
Spatial   <- c("visual", "cubes", "paper")
Verbal    <- c("general", "paragrap", "sentence")
Math      <- c("numeric", "series", "arithmet")

latents   <- c("vis", "math", "text")
manifests <-  c(Spatial, Math, Verbal)

HSModel <- mxModel(model="Holzinger_and_Swineford_1939", type="RAM", 
    manifestVars = manifests, # list the measured variables (boxes)
    latentVars   = latents,   # list the latent variables (circles)
    # factor loadings from latents to  manifests
    mxPath(from="vis",  to=Spatial),# factor loadings
    mxPath(from="math", to=Math),   # factor loadings
    mxPath(from="text", to=Verbal), # factor loadings

    # Allow latent variables to covary 
    mxPath(from="vis" , to="math", arrows=2, free=TRUE),
    mxPath(from="vis" , to="text", arrows=2, free=TRUE),
    mxPath(from="math", to="text", arrows=2, free=TRUE),

    # Allow latent variables to have variance
    mxPath(from=latents, arrows=2, free=FALSE, values=1.0),
    # Manifest have residual variance
    mxPath(from=manifests, arrows=2),   
    # the data to be analysed
    mxData(cov(HS.ability.data[,manifests]), type = "cov", numObs = 301))

class(HSModel)
#[1] "MxRAMModel"

# Use method on MxRAMModel class
bob(HSModel)
# [1] "Holzinger_and_Swineford_1939"
```

Right now I cannot replicate the issue you described.  Is there a version of `umx` or a modification of `umx` that can reproduce the problem?

**Comment by tbates** [comment]
It only happens for users on RStudio, and is cured by reinstalling umx. So hard to test, but the people who get the error get it replicably.

**Comment by mhunter1** [comment]
Perhaps this example is related.  An RStudio user I was working with experienced the following issue.  They tried to run
```
summary(HSModel)
```
and it failed indicating there was no `summary` method for an object of class `MxRAMModel`.  I had them try
```
summary.MxModel(HSModel)
```
and it said that function did not exist.  Finally, I had them run
```
OpenMx:::summary.MxModel(HSModel)
```
and the worked.

To me this indicates some problem with loading the `OpenMx` namespace, generally.  In particular, it looks like it may have nothing to do with the `MxRAMModel` class being a subclass of `MxModel`.  I wonder if it has something to do with RStudio's namespace/package loading processes, or session restore defaults.  For example see

```
?lazyLoad
```

At this point, we have no reproducible example of the behavior.  I believe it occurs, but we have no way to generate it or fix it.  We can leave this issue open or close it, but I'm not doing any further work on it until someone can produce the behavior on demand.

**Comment by tbates** [comment]
I wonder if @RMKirkpatrick's commit about models in env prior to library(OpenMx) fixed this? (it's not yet released to CRAN, I think. Another reason to do that.

**Comment by RMKirkpatrick** [comment]
@tbates Yes, during the meeting this morning, we speculated that might be the case.  Yes, all the more reason to do another release soon.

**Comment by jpritikin** [comment]
So close this bug and re-open if issue reappears?

**Comment by tbates** [comment]
re-open if anyone re-reports this - but should be gone (yay! and thanks  @RMKirkpatrick!)
