### ISSUE TITLE
RAM: message when equated parameters have different bounds

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#178]
via Steve Boker:

If two paths are equated by label, mxRun grizzles if they don't agree on `lbounds`, and `ubounds`

```R
library(OpenMx)
mxVersion() # 2.12.2.398 [GIT v2.12.2-398-gcc4a908]
tData = data.frame(matrix(rnorm(300,0,1), nrow=100, ncol=3))
names(tData) = c("t1", "t2", "t3")

tModel = mxModel(model="Ubounds", type="RAM", 
	manifestVars = c("t1", "t2", "t3"),
	mxPath("t1", to = "t2", values = .1, labels = "b", ubound = .2),
	mxPath("t1", to = "t3", values = .1, labels = "b"),
	mxPath(c("t1","t2","t3"), arrows = 2, values = .5, connect = "single"),
	mxPath("one", to = c("t1","t2","t3"), values = 0),
	mxData(tData, type = "raw")
)
mxRun(tModel)

```
> Error: The free parameter 'b' has been assigned multiple upper bounds! See matrix 'A' at location (3, 1) and matrix 'A' at location (2, 1)

Problem: 
1. Path model users may well have no clue what the A matrix is.
2. One path lacks bounds so perhaps this model should just run.

## Expected/ideal message from RAM model:

> in mxPath "t1 to  t3", set `ubound = .2`

Parenthetically, I guess `omxAssignFirstParameters` should perhaps grizzle about this?

```R
tModel = omxAssignFirstParameters(tModel)
```

**Comment by jpritikin** [comment]
Somewhat related to #269

**Comment by RMKirkpatrick** [comment]
> Problem:
> 1.  Path model users may well have no clue what the A matrix is.
> 2.  One path lacks bounds so perhaps this model should just run.

(1) Quite a few RAM-related warning and error messages refer to the RAM matrices in a way that assumes the user is familiar with them.  (2) I disagree; the user has given OpenMx conflicting instructions about what to do w/r/t parameter bounds, and bounds are important.

> Parenthetically, I guess `omxAssignFirstParameters` should perhaps grizzle about this?

Well, FWIW...even though its man page doesn't say so, and the error message for conflicting bounds doesn't suggest it either, `omxAssignFirstParameters()` actually _does_ presently clear conflicting lbounds and ubounds, just as it does for conflicting start values!  Is that behavior something we would want users to know about?  If so, see for consideration a proposed diff for R/MxFlatModel.R and an accompanying new test (we would want to edit `omxAssignFirstParameters()`'s man page, too, of course).
[241218_issue178.diff.txt](https://github.com/user-attachments/files/18188217/241218_issue178.diff.txt)
[assignFirstParametersTest.R.txt](https://github.com/user-attachments/files/18188219/assignFirstParametersTest.R.txt)

**Comment by mcneale** [comment]
Yes, I think we should tell the users that whichever parameter is used to assign starting values to other elements that have the same label will also assign the bounds of that parameter.

IMO, the warning and error messages ought to provide information in mxPath() form as well as matrix form.  Using that approach, the users may get educated along the way.

**Comment by RMKirkpatrick** [comment]
> Yes, I think we should tell the users that whichever parameter is used to assign starting values to other elements that have the same label will also assign the bounds of that parameter.

Done!  See 131aa79.

> IMO, the warning and error messages ought to provide information in mxPath() form as well as matrix form. Using that approach, the users may get educated along the way.

I don't think that's practical: unlike MxMatrices, MxPaths do not have names.  As it is, the error message identifies the offending parameter by label, which makes it easy enough for the user to find in their syntax; I'm not sure what more someone (@tbates ?) would want.

With an improved error message and man page, perhaps we can close this issue now?

**Comment by RMKirkpatrick** [comment]
Good enough.
