### ISSUE TITLE
mxBootstrap: not bootstrapping algebras?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#182]
The `$result` for an algebra is identical to 8 decimals for the normal and bootstrapped versions of a model. I guess this means bootstrap doesn't bootstrap algebras, just free parameters?

If algebras are not being bootstrapped, this should be added, as a common need for bootstrapping is exactly to test model parameters like product terms for which the SEs can't be trusted.

```R
m3_boot_serial$i_1
mxAlgebra 'i_1' 
$formula:  a1 * b1 
$result:
           [,1]
[1,] 0.04340032

m3$i_1
mxAlgebra 'i_1' 
$formula:  a1 * b1 
$result:
           [,1]
[1,] 0.04340032

**Comment by RMKirkpatrick** [comment]
I think you want `mxBootstrapEval()` & company?

**Comment by tbates** [comment]
It would be nice to bootstrap everything in one command: which I'm guessing is what users would desire in most cases. -A bit misleading too, otherwise. 

I guess this emerges from our framework where algebras don't get SEs by default?

**Comment by mcneale** [comment]
The SEs can't be trusted in many circumstances.  Functions of parameters such as a^2 yield different t-statistics, e.g. (a^2/SE(a^2)) != (a/SE(a)).  This is unlike the behavior of likelihood-based CIs.  Whether a bootstrap or likelihood-based CI is more efficient to compute is less clear.  A likelihood-based CI for one parameter costs about double the time to fit the model in the first place.  Hence, as a rule of thumb, a bootstrap with 500 replications is more efficient if the model has more than 250 free parameters.  The mxBootstrapEval is a clever way of avoiding more bootstrap replications for whatever function of parameters next piques your interest.

**Comment by RMKirkpatrick** [comment]
@tbates What are you expecting / wishing `mxBootstrap()` to do?  AFAIK, it repopulates the MxModel with the data real data and the real-data parameter estimates, and not with the data and estimates from any of the bootstrap replications.

**Comment by tbates** [comment]
If we had a placeholder SE in summary for algebra results, then mxBootstrap(model) could replace the untrustworthy `mxSE`-style SEs with trustworthy bootstrapped SEs.

This would be a good 3.0 feature, and would integrate algebras as first-class parameters alongside matrix cells

I don't think we support likelihood-based estimation of algebras, do we? e.g.  mxCI(x) where x is an algebra?

**Comment by mcneale** [comment]
Possibly, an evalAlgebras=F argument could be added, but as models get bigger this is unlikely to be what users really want.  Two commands doesn't seem that big an ask of the user - it enables parceling to  focus on computed quantities of interest.  Computation time could climb rapidly with many and large algebras.

**Comment by RMKirkpatrick** [comment]
> I don't think we support likelihood-based estimation of algebras, do we? e.g. mxCI(x) where x is an algebra?

Yes, we absolutely do support that.  Profile-likelihood CIs for algebras have been doable since classic Mx.

**Comment by tbates** [comment]
OK: So bootstrapping is either of 
1. All parameters with `mxBootstrap` 
2. Arbitrary stuff, including algebras with `mxBootstrapEval` and `mxBootstrapEvalByName`
3. Custom stuff  like `mxBootstrapStdizeRAMpaths`

Will look at help and clarify if necessary. Might write up a blog about it too.

**Comment by tbates** [comment]
Improved the help pages to note users can boot parameters with `mxBootstrap`, arbitrary other stuff with `mxBootstrapEvalByName` and `mxBootstrapStdizeRAMpaths(mxBootstrap(model))` to boot standardized paths.

Maybe a higher-level function like `umxSummary` can add the necessary gubbins to automate bootstrapped SEs, bootstrapped algebras, reporting algebras along with matrix parameters etc.
