### ISSUE TITLE
mxBootstrapStdizeRAMpaths: alter error for model not yet bootstrapped

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#183]
repro script to run a model with `mxTryHard` and then pass to `mxBootstrapStdizeRAMpaths`

This fails with a message implying `mxBootstrapStdizeRAMpaths` was expecting a `MxComputeBootstrap` compute plan in the model already, and then asking if the model has been boot-strapped already.

```R
library("mlbench") # for data
data(BostonHousing2)

BostonHousing2$nox = BostonHousing2$nox*100
BostonHousing2$log_crim = log2(BostonHousing2$crim)

manipedi = c("rad", "cmedv", "log_crim", "nox")

m3 = mxModel("crime_model", type="RAM", manifestVars = manipedi,
	mxPath("one", to = manipedi),
	mxPath(manipedi, arrows=2),

	mxPath(c("nox", "log_crim"), to = "cmedv", labels = c("b1", NA)),
	mxPath(c("rad", "log_crim"), to = "nox", labels = c("a1","a2")),

	mxAlgebra(name = "i_1", a1 * b1),
	mxAlgebra(name = "i_2", a2 * b1),
	mxData(BostonHousing2, type="raw")
)

# Run model with mxTryHard
m3 = mxTryHard(m3)

# Now attempt to bootstrap the standardized paths...
ms = mxBootstrapStdizeRAMpaths(m3)
```
> Compute plan MxComputeSequence found in model 'crime_model' instead of MxComputeBootstrap. Have you run this model through mxBootstrap already?

**Comment by RMKirkpatrick** [comment]
Did you even read the man page for `mxBootstrapStdizeRAMpaths()`?  The description is 

> Uses the bootstrap distribution of a RAM model's free parameters to produce a bootstrap distribution of standardized path coefficients. Model must have already been run through `mxBootstrap()`.

And later on,

> mxBootstrapStdizeRAMpaths() ignores any submodels of `model`. That is, it must be able to find, in the MxModel it is provided, a RAM expectation and an MxComputeBootstrap object. It can be run on submodels directly,

`mxBootstrapStdizeRAMpaths()` is working as designed here.

**Comment by tbates** [comment]
You won't mind then if I change the error to the below? (I read the existing error as suggesting that running it through bootstrap might have caused the error.)

> PS: You need run a model through mxBootstrap() prior to calling mxBootstrapStdizeRAMpaths?

**Comment by RMKirkpatrick** [comment]
Oh, I see what you're saying now.  Yes, that's a better error message.

**Comment by mcneale** [comment]
Can we say ‘before’ not ‘prior to’ as the latter is more difficult for foreign users to parse?

**Comment by tbates** [comment]
Pushed a commit to say
> You need to run this model through mxBootstrap first.

Turns out the error comes from a deeper function, so we don't know what the user is doing, but do know whatever it is needs a booted model.
