### ISSUE TITLE
Catch new slots appearing that break backward compatibility

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#185]
If we store a model from a current OpenMx, then open it and run a few functions on it, we can automate catching backward compatibility issues related to new slots in objects.

**Comment by mcneale** [comment]
It's difficult to judge how often false negatives (runs ok in this specific case, but others are SNAFU'd) would occur.  But it seems better than nothing.

Developing software to port from prior versions' saved models is a big ask.  Perhaps another job for the proposed XML pipeline layer to address?

**Comment by tbates** [comment]
Not so much porting from prior versions, but just catching any times we don't check for new parameters etc.

**Comment by jpritikin** [comment]
Every time this is brought up in a meeting, it is rejected as being a heavy testing burden. The C++ code is generally pretty careful about checking whether a slot exists before accessing it.
