### ISSUE TITLE
Segmentation fault when using WLS fitfunction with acov data & missing arg

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#187]
See the attached script.  It is just models/passing/acov_regression_test.R , except with no value provided for argument `fullWeight` to `mxData()`.  It segfaults.
[acov_regression_test--faults.R.txt](https://github.com/OpenMx/OpenMx/files/3192115/acov_regression_test--faults.R.txt)

**Comment by tbates** [comment]
It does on MacOS too. 

```R
library(OpenMx)
S <- matrix(c(2,1,1,1,2,1,1,1,2), ncol=3,nrow=3, dimnames=list(c("V1","V2","V3"),c("V1","V2","V3")))
W <- diag(6)

mxdataobj <- mxData(S, numObs = 100, means = NA, type = "acov",acov=W)
factormod <- mxModel("1factor", mxdataobj,
	mxMatrix(type="Full",nrow=3,ncol=1,free=T,values=0.1,name="Lambda"),
	mxMatrix(type="Stand",nrow=1,ncol=1,free=F,values=1,lbound=-1,ubound=1,name="Rxx"),
	mxMatrix(type="Diag",nrow=3,free=T,values=diag(S),lbound=0.0001,name="Psi2"),
	mxAlgebra( (Lambda%*%Rxx%*%t(Lambda)) + Psi2, name="xpecCov"),
	mxAlgebra(sqrt(diag2vec(xpecCov)), name="SDs"),
	mxAlgebra(Lambda / SDs, name="standardizedLoadings"),
	mxExpectationNormal("xpecCov", dimnames=colnames(S)),
	mxFitFunctionWLS(type="WLS")
)
factorfit <- mxRun(factormod)

```

> *** caught segfault ***
address 0x2c, cause 'memory not mapped'
Traceback:
 1: runHelper(model, frontendStart, intervals, silent, suppressWarnings,     unsafe, checkpoint, useSocket, onlyFrontend, useOptimizer,   ...
 2: mxRun(factormod)

**Comment by jpritikin** [comment]
v2.12.2-438-gb55777073

**Comment by mcneale** [comment]
That was super-quick!

**Comment by RMKirkpatrick** [comment]
So now, providing a value for argument `fullWeight` is mandatory.  Does it have to be mandatory?  I thought the old functionality was to simply not calculate SEs, CIs, or a chi-square test statistic if no `fullWeight` was available.

**Comment by jpritikin** [comment]
> Does it have to be mandatory?

Oh, hm, it probably should be optional. You would need to specify `mxFitFunctionWLS(..., fullWeight=FALSE)`. Reopen this issue? Or is it good enough to support it in the new interface only?

**Comment by RMKirkpatrick** [comment]
It ought to be optional, so I'd say reopen this issue, but let's not let this issue hold up the next release.

**Comment by jpritikin** [comment]
Yeah, the previous fix I committed was wrong. Better version here, v2.12.2-454-g88b5fa747
