### ISSUE TITLE
mxData(type  = "acov")

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#192]
Some questions for mxData.Rd

- [x] 1. type = “acov” is still supported.
- [x] 2. Do we support type "sscp"?  (see #219)
- [x] 3. `numObs`, I guess, is required for type acov and cor/cov? (even though n may vary?)
- [x] 4. `acov` Deprecated. Suggest storing in `$observedStats$acov`.
- [x]  5. `fullWeight` Deprecated. Suggest storing in `$observedStats$fullWeight`.
- [x]  6. `thresholds` Deprecated. Suggest storing in `$observedStats$thresholds`.
- [x]  7. `$observedStats$fullWeight`  (note is mandatory if acov provided)
- [x] 8. Additional documentation of `$observedStats`

**Comment by jpritikin** [comment]
I guess `type="acov"` is still supported for now. However, we should encourage use of the new interface, `data$observedStats`. The same goes for `fullWeight` and `thresholds` which should be passed via `data$observedStats`.

**Comment by tbates** [comment]
`mxData$observedStats` isn't documented and has no example that I can see,  nor a test? 

Is this what `data$observedStats` takes?

```R
$observedStats = list(
    `acov` = nVar sumstat matrix?
   `fullWeight` = nVar*2 matrix,
   `thresholds` = maxThresh*nVar
)

```

Shall we mark this experimental until we see if it's really the stable way forward? (looks so)

The old/new/alternate WLS  thing is confusing enough, we might want to throw a big explanatory deprecation warning if people use acov or the `observed` slot, and set type = "raw" and move WLS content into observedStats for them. Then kill the old usage end of 2019.

 1. Is type (of data in the  argument) = “acov” is still supported, yes?

**Comment by tbates** [comment]
Should users set `type`= "raw" if they set `$observedStats` and leave `$observed` empty?

**Comment by RMKirkpatrick** [comment]
>  1. type (of data in the ‘observed’ argument) = “acov” is still supported.
>  2. Do we support type "sscp"?
>  3. numObs, I guess, is required for type acov and cor/cov? (even though n may vary?)
>  4. acov Deprecated. Suggest putting this into $observedStats$acov.
>  5. fullWeight Deprecated. Suggest putting this into $observedStats$fullWeight.
>  6. thresholds Deprecated. Suggest putting this into $observedStats$thresholds.
>  7. $observedStats$fullWeight (note is mandatory if acov provided)

1.  Yes.
2.  Not sure.
3.  I think so.
4.  I don't know about that.  Do we need to continue to support argument `acov`?
5.  I don't know about that.  Do we need to continue to support `fullWeight`?
6.  Maybe?
7.  You are correct it's mandatory if `type="acov"`.

This is an example of an `mxData()` call I'm currently using with GenomicSEM:
```
dataWLS <- mxData(S, numObs = 100, means = NA, type = "acov", acov=W, fullWeight=W)

**Comment by jpritikin** [comment]
> Should users set type= "raw" if they set $observedStats and leave $observed empty?

Maybe what makes sense is to use `type="cov"`, pass the covariance matrix as observed data and the rest of the WLS stuff in `$observedStats`. It doesn't make sense to use `type="raw"` and then not to provide raw data.

**Comment by jpritikin** [comment]
> `$observedStats$fullWeight` (note is mandatory if acov provided)

It was mandatory due to a bug. As of v2.12.2-454-g88b5fa747, it will correctly fail if you do not provide `fullWeight` and request SEs.

**Comment by RMKirkpatrick** [comment]
@jpritikin Do you really think it should be a fatal error, though?  Maybe a warning instead?

**Comment by jpritikin** [comment]
> mxData$observedStats isn't documented and has no example that I can see, nor a test?

See the example for mxFitFunctionWLS.

Also see mxData: "For reference, if type is acov, the ‘observed’ argument will contain raw data and the ‘observedStats’ slot – a list of observed statistics. This list is expected to contain a number of named objects: ‘cov’ is the (polychoric) covariance matrix of the continuous and ordinal variables. An error is raised if any variance is smaller minVariance. ‘means’ (optional) may be included for estimations involving means. ‘thresholds’ should be included for estimation involving thresholds and ordinal variables. ‘acov’ is the asymptotic covariance matrix. ‘acov’ can be diagonal for diagonally weighted least squares. ‘fullWeight’ (optional) is the complete asymptotic weight matrix (all entries non-zero). Data of this type typically use the mxFitFunctionWLS function." -- I admit that this is incomplete and would benefit from clarification.

> Is this what `data$observedStats` takes?

The complete list is: cov, slope, means, acov, fullWeight, and thresholds. The slope matrix is for exogenous predictors. See `inst/models/passing/exoPredWLS.R` and try `str(jointRAM1$data$observedStats)`

**Comment by jpritikin** [comment]
> Do you really think it should be a fatal error, though? Maybe a warning instead?

I copied the error from the old WLS implementation. I don't think it will break any user's code since this never worked.

**Comment by tbates** [comment]
It seems wrong to use type = "cov" for what is actually WLS data in acov or `$observedStats$acov`) - easy to mis-analyse the data. Better to use type="raw" and let the script either not be worried or realize that observed is empty and `acov` isn't 

I'm guessing that `$observedStats` should have `$minVariance` as this seems WLS specific? That way all the WLS-specific parameters should be moved under $observedStats

**Comment by jpritikin** [comment]
> It seems wrong to use type = "cov" for what is actually WLS data in acov

Why? WLS data consists of summary statistics.

> Better to use type="raw"

Even when there isn't any raw data?

> I'm guessing that $observedStats should have $minVariance as this seems WLS specific?

Yeah, that's a good idea.

**Comment by mcneale** [comment]
WLS summary data invariably need to be constructed from Raw data (by us or someone) - this would be the usual modus operandi.  As I noted on email, we should not put out a version with a known regression that breaks a pretty standard script.

**Comment by tbates** [comment]
It's a mess for consumers of OpenMx like umx or any of our down stream friends to have to look in multiple places to figure out what mxData actually are.

When acov changed to raw it took me a week to catch all the places umx just looked at type expecting to be able to trust it.

To have it change again, so that any of acov or raw or cov can be WLS and cov may not be cov is just asking for headaches and errors.

**Comment by tbates** [comment]
If we're now supporting front end creation of WLS objects and backward compatibility with the acov tag, so that we can stay on the genomic SEM train, I suggest we simply allow `acov` to mean "already acov".

For clarity in the mxData object itself, I would suggest that  we throw a message for objects using the multiple top-level WLS slots explaining how to convert these to calls to the newer-old $observedStats layout. 

This doesn't interfere with the newer method in which raw can speedily be processed into WLS in the backend, and that people should typically do that.

**Comment by RMKirkpatrick** [comment]
I think I agree with @tbates .  If the user is providing summary statistics via arguments `acov`, `fullWeight`, or `observedStats`, then s/he should use `type="acov"`.

**Comment by jpritikin** [comment]
> > I'm guessing that $observedStats should have $minVariance as this seems WLS specific?
> 
> Yeah, that's a good idea.

Oops, that can't work. `minVariance` is a control knob for the production of `observedStats`.

**Comment by tbates** [comment]
Updating the Rd file for mxData now. Can someone post here a description of what `observedStats$slope` is? (and it's optional, right?)

**Comment by jpritikin** [comment]
> Can someone post here a description of what observedStats$slope is? (and it's optional, right?)

`slope` contains the regression coefficients from all exogenous predictors to all observed variables. Whether it's optional depends on the model specification. If you have exogenous predictors then it's not optional.

**Comment by tbates** [comment]
updated docs
