### ISSUE TITLE
mxData$observedStats needs $ accessor

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#193]
Need $ interface to  mxData$observedStats (the new WLS interface for manually created mxData 

PS the following also don't appear as $ accessors:

@ .isSorted
@ .needSort
@ .parallel
@ .noExoOptimize

_Originally posted by @jpritikin in https://github.com/OpenMx/OpenMx/issues/192#issuecomment-493697032_

**Comment by RMKirkpatrick** [comment]
> PS the following also don't appear as $ accessors:
@ .isSorted
@ .needSort
@ .parallel
@ .noExoOptimize

They're not supposed to.  That's why they start with dots.

**Comment by tbates** [comment]
I think RStudio implements it's own object-digging routines to support their completion system.

In R.app on mac I see: 

![Screenshot 2019-05-21 16 27 51](https://user-images.githubusercontent.com/736156/58109354-6690be80-7be5-11e9-9e1b-5a5365c7c408.png)

OpenMx version: 2.12.2.433 [GIT v2.12.2-433-gfc955de] R version: R version 3.6.0 (2019-04-26)

**Comment by RMKirkpatrick** [comment]
Seems you're right about RStudio.  But, check to see if the object you made actually has something of nonzero length in the 'observedStats' slot: I see now that the object I made has an empty list in that slot.

**Comment by jpritikin** [comment]
If the slot is non-empty then it does show up,

![Screenshot from 2019-05-21 13-38-47](https://user-images.githubusercontent.com/2002771/58118006-ef9bfb80-7bcd-11e9-8fec-6ec3a9452f85.png)

**Comment by RMKirkpatrick** [comment]
@jpritikin Wait a sec.  That screenshot looks like it's from RStudio.  @tbates said earlier in this thread that RStudio has some magic of its own going on to facilitate its tab-completion.  Do you see the same thing if you're running R in terminal?  If not, this issue should be reopened.

**Comment by jpritikin** [comment]
Tab completion seems to work in the terminal as well,

```
> jointRAM1$data$observed
jointRAM1$data$observed       jointRAM1$data$observedStats
```

**Comment by RMKirkpatrick** [comment]
How about if you just create an MxData object, like without putting it into an MxModel and running it?

**Comment by jpritikin** [comment]
> How about if you just create an MxData object, like without putting it into an MxModel and running it?

`mxData(type='raw', ..)` will not have any observedStats. If R doesn't show observedStats as a possible completion, that's R's behavior.

**Comment by RMKirkpatrick** [comment]
Fair enough.

**Comment by tbates** [comment]
Slots show whether they are empty or not - a common reason wanting a tab completion is to fill the slot, after all

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
