### ISSUE TITLE
mxMatrix$values: (oops) could not find function mxMatrix

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#196]
Make a matrix
```R
 tmp = mxMatrix("Symm", 2, 2, values= c(1,0,0,1)) 
```
Now try and set values, offering up too many: the warning messages contains the text "oops could not find function mxMatrix"... 

```R
 tmp$values = c(1,0,1,1,1) # 1 too many

Warning message:
data length 5 is not a sub-multiple or multiple of the number of rows 2 for argument 
'values' in "(oops) could not find function mxMatrix" 
```

There's no `traceback()`, but the message is generated by `imxLocateFunction`

**Comment by tbates** [comment]
`imxLocateFunction` is called all over the place. It tries to look up the function generating a warning/error in the callstack. The "(oops) could not find function X" string happens when the function isn't in the callstack.

I think what this message should say is just the function name. It also shouldn't have quotation marks around it. So the message would be

> Warning message:
data length 5 is not a sub-multiple or multiple of the number of rows 2 for argument 
'values' in "mxMatrix"

Any objections to making this change?

**Comment by jpritikin** [comment]
Sounds good to me
