### ISSUE TITLE
mxSummary computation of AIC for WLS models

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#198]
Using wrong formula

```R
m1 = mxModel("my_first_WLS", type="RAM",
	manifestVars = c("x", "y"),
	mxPath(c("x", "y"), arrows=2, values=1),
	mxPath("x", to="y"),
	mxFitFunctionWLS(),
	mxData(tmpFrame, 'raw')
)

m1 = mxRun(m1)
mxCompare(m1,m1)
summary(m1)$AIC

```

**Comment by mhunter1** [comment]
Here's what we'd like to do.

1. Have `logLik(model)` report the chi-squared value: `model$output$chi`
1. Have `AIC(model)` report the chi-squared value plus 2 times the degrees of freedom: `model$output$chi + 2*model$output$chiDoF`

However, `AIC()` appears to be defined as `-2*logLik(model) + 2*DoF`

I'm working on a solution.

**Comment by mhunter1** [comment]
This should be fixed with a062c7d05ca78e84c627d5ac990c104300fe2ebd and fbf96b80861afb849ea2595d1c0b00bebd723a51

But please check before I close this.

**Comment by tbates** [comment]
looks good!
But the AIC is being returned as a logLik() object (should be a numeric, or data.frame if multiple models offered up to `AIC(m1, m2)`

```R
m1 = umxRAM("WLS_missing_path", data = mtcars, type="DWLS",
 	umxPath(var=c("mpg", "wt"))
)
```

|name         | Estimate|    SE|
|:------------|--------:|-----:|
|mpg_with_mpg |   36.324| 8.345|
|wt_with_wt   |    0.957| 0.242|
>  χ²(1) = 18.16, p < 0.001; CFI = NA; TLI = NA; RMSEA = 0.732

try logLik:

```R
logLik(m1) 
'log Lik.' 18.16277 (df=1)
```

`AIC` returns an object of class `logLik` (should be numeric)

```R
AIC(m1) 
'log Lik.' 20.16277 (df=1)
```

AIC should be able to handle more than one model (works for ML)

```R
AIC(m1,m1)
```

> Error in ll + k * attr(ll, "df") : 
  non-numeric argument to binary operator

should be, e.g.:
```R
      df      AIC
model  4 301.1578
..1    4 301.1578

```
> OpenMx version: 2.15.5.27 [GIT v2.15.5-27-gfbf96b8]

**Comment by mhunter1** [comment]
Thanks, @tbates !  I modified the implementation of `AIC.MxModel` with f94eab17be9a75aec6f32189e4f38c4a79752785 and 25f1c2e98e4d1b232f6df835ef2201f883b38f5b  to more closely match the rest of the `AIC` methods.  It now returns a `numeric` and should be able to handle multiple models.

However, note that the particular example you used will not work.

```
> AIC(m1, m1) 
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique value when setting 'row.names': ‘m1’ 
```

It fails similarly for regression models, so I think this is the desired behavior.

```
## Annette Dobson (1990) "An Introduction to Generalized Linear Models".
## Page 9: Plant Weight Data.
ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2, 10, 20, labels = c("Ctl","Trt"))
weight <- c(ctl, trt)
lm.D9 <- lm(weight ~ group)
AIC(lm.D9, lm.D9)
# Error in `.rowNamesDF<-`(x, value = value) : 
#  duplicate 'row.names' are not allowed
#  In addition: Warning message:
# non-unique value when setting 'row.names': ‘lm.D9’
```

**Comment by mhunter1** [comment]
Sorry.  It looks like all of the above applies to issue #186, not this one.  This one is about `mxSummary()` whereas #186 is about `AIC()`.

**Comment by tbates** [comment]
Nice! (& Makes sense to not include AIC in mxSummary for WLS given its pseudonymous nature)

```R
AIC(m1,m2)
```
|    | df | AIC      |
|:---|:---|:---------|
| m1 | 0  | 0.000000 |
| m2 | 1  | 2.017503 |
