### ISSUE TITLE
mxBootstrapStdizeRAMpaths: document `bq` and `method` parameters

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#200]
`bq` and `method` parameters of `mxBootstrapStdizeRAMpaths` are not explained.

- [x] Does bq stand for something?
- [x] What "quantiles" for `bq` correspond to a CI95? (default is bq=c(.25,.75)
- [x] What is `method = 'bcbci'`?
- [ ] What is `method = 'quantile'`?
- [x] What are citations for the bootstrap procedure, and for the 'bcbci' and `quantile` methods? (DuckDuckGo is silent, for instance, on "bcbci")

**Comment by jpritikin** [comment]
`bq` is bootstrap quantile. Default bq is a 50% interval because we have lots of samples to accurately estimate the 50% interval. The 95% interval cannot be estimated accurately without many more samples.

@RMKirkpatrick Can you remind us about `bcbci`? Wasn't that your method?

**Comment by jpritikin** [comment]
For CI95, you'd want `bq=c(.025,.0975)`

**Comment by tbates** [comment]
Rd updated now. Still needs `bcbci`

**Comment by RMKirkpatrick** [comment]
I think `bcbci` stands for "bias-corrected bootstrap confidence interval".  You can see how it's calculated in the R code, starting at line 836 of R/MxSummary.R .

**Comment by RMKirkpatrick** [comment]
Added references to man page with feecbff.

**Comment by tbates** [comment]
Do the citations document and explain both the  'bcbci' and 'quantile' methods? If so, could close this...

**Comment by RMKirkpatrick** [comment]
> Do the citations document and explain both the 'bcbci' and 'quantile' methods?
Yes, they do.
