### ISSUE TITLE
mxMatrix error type checking: Error in match.barg(type) : 'arg' must be NULL or a character vector

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#202]
probably nice to type check input parameters to mxMatrix. Would catch this:
```R
mxMatrix(name="parameters", 1, 1)
```
> Error in match.barg(type) : 'arg' must be NULL or a character vector

A helpful error would be
> Expecting type = (one of "Full", "Diag", etc...) but you gave me "1"

**Comment by RMKirkpatrick** [comment]
@mhunter1 , I think  bd1b027 broke something.  In the nightly run, there were 88, 91, and 91 errors with NPSOL, SLSQP, and CSOLNP, respectively.  Most are:
```
[1] "'arg' must be of length 1"
```
