### ISSUE TITLE
mxPower: Cannot generate a non-integral number of rows: 991.5

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#205]
Any thoughts about why mxPowerSearch fails and what "Cannot generate a non-integral number of rows: 991.5" means here?

```R
require(umx)
data(twinData) # ?twinData from Australian twins.
twinData[, c("ht1", "ht2")] = twinData[, c("ht1", "ht2")] * 10
mzData <- twinData[twinData$zygosity %in% "MZFF", ]
dzData <- twinData[twinData$zygosity %in% "DZFF", ]

m1 = umxACE(selDVs ="ht", sep = "", dzData = dzData, mzData = mzData)
m1 = umxModify(m1, update = "a_r1c1", name="no_a") 

# attempt to estimate power to distinguish m1 and m2
mxPower(trueModel=m1, falseModel=m2)
```
>Search n:power relationship for 'a_r1c1'
> R 1 init N 991.5Error in mxGenerateData(model, returnModel = TRUE, nrows = nrows, use.miss = use.miss,  : 
  Cannot generate a non-integral number of rows: 991.5
Error: Cannot generate data with trueModel 'ACE'

**Comment by jpritikin** [comment]
Your code example doesn't work,
```
> m1 = umxACE(selDVs = selDVs, sep = "", dzData = dzData, mzData = mzData)
Error in paste0(varNames, sep, ID) : object 'selDVs' not found
```

I suspect I'm missing a `round()` in the mxPowerSearch code.

**Comment by jpritikin** [comment]
This might be the correct fix,

```
diff --git a/R/MxCompare.R b/R/MxCompare.R
index 55370a172..99fd88125 100644
--- a/R/MxCompare.R
+++ b/R/MxCompare.R
@@ -795,7 +795,7 @@ mxPowerSearch <- function(trueModel, falseModel, n=NULL, sig.level=0.05, ...,
                                     values = nullInterestValue + curX)
     }
     simData <- try(gdFun(trueModel, returnModel=FALSE,
-                         nrows=ifelse(is.null(n), curX, origSampleSize)))
+                         nrows=ifelse(is.null(n), round(curX), origSampleSize)))
     if (is(simData, "try-error")) {
       stop(paste("Cannot generate data with trueModel",
                  omxQuotes(trueModel$name)), call.=FALSE)
```

**Comment by tbates** [comment]
made the test case run now (set `selDVs = "ht"`)

**Comment by jpritikin** [comment]
Yeah, the fix (above) worked. I pushed a commit. It would be nice to have a test, but maybe good enough, Tim, if you add the snippet above to `umx`.

**Comment by tbates** [comment]
Okey dokey: I'm adding a twin power function, so will be in that.

I've got another  for you #206 :-)

**Comment by tbates** [comment]
might be the same thing, but for models with def vars?

```R
mxPower(m1, m2)
Search n:power relationship for 'am_r1c1'
R 1 init N 190Error in generateNormalData(model, nrows, subname) : 
  Definition variable(s) found, but the number of rows in the data do not match the number of rows requested for data generation.
Error: Cannot generate data with trueModel 'G_by_E'
```

**Comment by jpritikin** [comment]
> might be the same thing, but for models with def vars?

The problem here is that we don't know how to generate data when there are definition variables because we don't know how def vars are distributed. You'll have to provide your own data generation function via the gdFun argument.

**Comment by mcneale** [comment]
We could just go with the **observed** distribution of definition variables, and only generate simulated data for the other variables.  There are still issues: if the definition variable moderates the association between two other variables, it is in the third moment that effects would be manifested.  However, the SEM itself with definition variables would, I think, generate data with such departures from mvn.

**Comment by tbates** [comment]
It could be quite helpful to go with the observed data for the def.Vars, and highlight in Rd that this can affect power, and that users might want to evaluate power at, for instance, different distributions of definition variable. 

If not, then should change error  from the above "R 1 init N 190Error in generateNormalData(model, nrows, subname)" to:

```R
if(hasDefVars){
   stop("sorry - mxPower can't simulate definition variables:
       either provide a generating function (gdFun =), or roll your own power loop")
}
```

**Comment by jpritikin** [comment]
> We could just go with the observed distribution of definition variables

What is the observed distribution? Are you suggesting we assume multivariate normal? Seems a bit dodgy to me.

> If not, then should change error from the above "R 1 init N 190Error in generateNormalData(model, nrows, subname)" to:

I like that.

**Comment by tbates** [comment]
Mike will speak for himself but I think it has to mean "use the actual def.var data"

**Comment by jpritikin** [comment]
> Mike will speak for himself but I think it has to mean "use the actual def.var data"

But we need to simulate data for different sample sizes. What if we need a larger sample size than is available from the original data?

**Comment by mcneale** [comment]
If we need a bigger (or smaller) N, then randomly sampling from the observed data.defs (with or without replacement optionally) seems reasonably in a bootstrappy or MCMCy sort of way.  Yes, there will be over-representation of some scores, and under-representation of others.   But in the long run, the statistics should settle down nicely.
