### ISSUE TITLE
mxPowerSearch lower/upper empty on help example?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#206]
`lower` and `upper` (CIs) from `mxPowerSearch` are NA with `method = "ncp"` Should they be?

```R
data(demoOneFactor)
manifests = names(demoOneFactor)
m1 = mxModel("One Factor", type="RAM",
    manifestVars = manifests, latentVars = "G",
    mxPath(from= "G", to= manifests, values= 0.8),
    mxPath(from= manifests, arrows= 2,values= 1),
    mxPath(from= "G", arrows= 2, free= FALSE, values= 1),
    mxPath(from= "one", to= manifests),
    mxData(demoOneFactor, type= "raw")
 )
m1 = mxRun(m1)

m2 = m1
m2$A$values['x1','G'] = 0.3
m2$A$free['x1','G'] = FALSE
m2 = mxRun(m2)

mxPowerSearch(m1, m2, method='ncp')
```

|   | N        | power     | lower | upper |
|:--|:---------|:----------|:------|:------|
| 1 | 16.22268 | 0.2524566 | NA    | NA    |
| 2 | 23.26247 | 0.3398249 | NA    | NA    |
| 3 | 30.30226 | 0.4227884 | NA    | NA    |
| 4 | 37.34205 | 0.4997667 | NA    | NA    |

**Comment by jpritikin** [comment]
Somebody would have to figure out the math to add upper and lower limits for `method='ncp'`. @RMKirkpatrick, do you know off the top of your head? The power is computed as (MxCompare.R line 717),
````
out$power <- 1 - pchisq(qchisq(1 - sig.level, diffdf), diffdf, avgNcp * out$x)
````

**Comment by RMKirkpatrick** [comment]
They're lower and upper confidence limits for the power at the given sample size, right?  Is there even a need for confidence limits if you're conditioning on a fixed sample size, noncentrality parameter, and Type I error rate, and are calculating the power more or less analytically from the chi-square CDF?  In other words, is there any sampling error to speak of when `method=ncp`?

**Comment by jpritikin** [comment]
@RMKirkpatrick Oh! So it's exact?

**Comment by RMKirkpatrick** [comment]
I believe so?

**Comment by tbates** [comment]
@neale theory here? Does ncp  power have a CI? Or exact?

**Comment by mcneale** [comment]
It’s as exact as the optimizer’s solution, I believe.

**Comment by tbates** [comment]
might make sense to leave as is (NAs in the lower/upper bounds columns), but print as plain text:
> Note: CI not given for method=ncp: The estimates are exact (to the precision of the true and null/false model solutions provided by the user)

Or if that's over kill, I could add something to that effect to the Rd?

**Comment by mcneale** [comment]
The Rd seems the place to make these notes.
