### ISSUE TITLE
mxPowerSearch: should falseModel be run first?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#207]
with the ncp method, does falseModel have to be run? Looks like the results change a lot after it's been run, but in that case, we should flag an error if `!umx_has_been_run(falseModel)`

```R
data(demoOneFactor)
manifests = names(demoOneFactor)
m1 = mxModel("One Factor", type="RAM",
    manifestVars = manifests, latentVars = "G",
    mxPath(from= "G", to= manifests, values= 0.8),
    mxPath(from= manifests, arrows= 2,values= 1),
    mxPath(from= "G", arrows= 2, free= FALSE, values= 1),
    mxPath(from= "one", to= manifests),
    mxData(demoOneFactor, type= "raw")
 )
m1 = mxRun(m1)

m2 = m1
m2$A$values['x1','G'] = 0.3
m2$A$free['x1','G'] = FALSE
```
Now: **Should this work** (when m2 has not been run?)

```R
mxPowerSearch(m1, m2, method='ncp')
```

|   | N         | power     | lower | upper |
|:--|:----------|:----------|:------|:------|
| 1 | 7.754559  | 0.2524566 | NA    | NA    |
| 2 | 11.119629 | 0.3398249 | NA    | NA    |
| 3 | 14.484699 | 0.4227884 | NA    | NA    |

If so, why is this output so different? Or is `ncp` not a precise tool?

```R
m2 = mxRun(m2)
mxPowerSearch(m1, m2, method='ncp')
```

|   | N        | power     | lower | upper |
|:--|:---------|:----------|:------|:------|
| 1 | 16.22268 | 0.2524566 | NA    | NA    |
| 2 | 23.26247 | 0.3398249 | NA    | NA    |
| 3 | 30.30226 | 0.4227884 | NA    | NA    |

**Comment by tbates** [comment]
This is a slick function!

I see the help says that for `method = "ncp"`, the models are assumed to be converged. 

Tricky - right, but I'm guessing a lot more users will be bitten by wrong values from a model that has been had a parameter fixed, but has not since been re-run, versus users who will set everything in place by hand? 

Perhaps good to change this require both to be run? Or to print a warning when using a non-run model? especially when for method = empirical, it's not required.

I can't think of many use-cases when one would know the state not just of the one parameter one is fixing, but where all the others will go too and have set them all there..

**Comment by jpritikin** [comment]
> Perhaps good to change this require both to be run? Or to print a warning when using a non-run model?

It looks like the code already checks,

```
    if (!trueModel@.wasRun || trueModel@.modifiedSinceRun) {
	    trueModel <- mxRun(mxModel(trueModel, mxComputeOnce('fitfunction','fit')))
    }
    if (!falseModel@.wasRun || falseModel@.modifiedSinceRun) {
	    falseModel <- mxRun(mxModel(falseModel, mxComputeOnce('fitfunction','fit')))
    }
```

**Comment by tbates** [comment]
Seems to me if a model comes into `mxPowerSearch`  with parameter x fixed at a new value and **all others left exactly where they were** (i.e., model modified but not run), then this should be an error: The question being asked is not the expected "_what's my power to detect the change in model fit when this model is estimated with parameter x set here_", but  "_what's my power to detect this (now) really badly fitting model_?".

Would allow people to report grossly inflated power.

**Comment by jpritikin** [comment]
> Seems to me if a model comes into mxPowerSearch with parameter x fixed at a new value and all others left exactly where they were (i.e., model modified but not run), then this should be an error:

I think an error is pretty harsh. It's a valid answer to a potential question.

Instead of that, I think we should recommend varying all of the parameters to obtain a distribution of power curves. For example, [https://openmx.ssri.psu.edu/node/4450](https://openmx.ssri.psu.edu/node/4450)

**Comment by RMKirkpatrick** [comment]
I'm starting to think @tbates has a point here.  I agree with @jpritikin that raising an error is too strict, but a warning might be appropriate.

**Comment by mcneale** [comment]
It's definitely worth a fairly strong warning.

**Comment by tbates** [comment]
> Polite but strong warning: You haven't re-run falseModel since modifying it, so all its parameters apart from from x are the same as in trueModel. You most likely want to mxRun falseModel, or your apparent power will be illusory. (Or perhaps you're an expert and wanted to do this - we said it polite, so go ahead: we're glad you chose OpenMx and mxPowerSearch for your advanced studies :sunglasses:)
