### ISSUE TITLE
SummaryCheck.R test failure

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#209]
In the course of converting our `omxCheck*` code to **testthat**, I found a bug in `omxCheckWithinPercentError`. The code was,

```
      check <- any(mapply(function(x,y) {
                      (abs(x - y)/x * 100) > percent },
                      as.vector(a), as.vector(b)))
```

This will do something inappropriate when `x<0`. With this bug fixed, line 229 of `inst/models/passing/SummaryCheck.R` fails. I'm going to comment out the failing test. If you know how to correct the test, please uncomment it and fix it.

**Comment by jpritikin** [comment]
@mhunter1 These tests were originally written by you.

**Comment by tbates** [comment]
So the failing lines are:

```R
omxCheckWithinPercentError(cov.sum$SaturatedLikelihood, 7.520532, percent=1e-4) 
# actual =  -2.464397
omxCheckWithinPercentError(covs.sum$SaturatedLikelihood, 7.520532, percent=1e-4)
# actual = 2.464397
```

2.464397 (which is what the cov model computes automatically) seems to be the correct answer.

```R
varnames = names(demoTwoFactor)
latnames = c("F1", "F2")
cov = mxModel("test", type="RAM", manifestVars=varnames, latentVars=latnames,
	mxPath(from=rep(latnames, each=vpf), to=varnames, values=.8, free=TRUE),
	mxPath(latnames, connect="unique.pairs", arrows=2, free=c(F, T, F), values=c(1, .5, 1)),
	mxPath(from=varnames, arrows=2, free=TRUE, values=.2),
	mxData(cov(demoTwoFactor), "cov", numObs=nrow(demoTwoFactor))
)

cov = mxRun(cov)
summary(cov)$SaturatedLikelihood
2.464397
```

Probably the 7.52 was entered in error as the buggy `omxCheckWithinPercentError` returned OK for any negative x
