### ISSUE TITLE
anova s3 for mxModels: handle case of one model offered up

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#21]
Currently (2.7.12.45) , `anova()` now accepts a model as input, but outputs an inscrutable error if that's all that's provided

    require(umx)
    data(twinData) ;  selDVs = c("ht1", "ht2")
    mzData <- twinData[twinData$zygosity %in% "MZFF", ]
    dzData <- twinData[twinData$zygosity %in% "DZFF", ]
    m1 = umxACE(selDVs = selDVs, dzData = dzData, mzData = mzData)

    anova(m1)
    Error in if (stats[i - 1, "m2ll"] > stats[i, "m2ll"]) { : 
      missing value where TRUE/FALSE needed

**Comment by jpritikin** [comment]
Fixed in 9e85875fcf
