### ISSUE TITLE
Wrong error message for WLS model with means + how to add means (now mxData type=raw)?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#210]
Without the means path, this model runs. But if you add means, if gives an error that seems wrong:

```R
# 1. Make a df with data y =  .2x+ε
x = rnorm(1000, mean = 0, sd = 1); y = 0.5*x + rnorm(1000, mean = 0, sd = 1)
tmpFrame = data.frame(x, y); varNames = names(tmpFrame)

# 2. Make RAM model "x->y"
m1 = mxModel("WLS", type="RAM",
	manifestVars = c("x", "y"),
	mxPath(c("x", "y"), arrows=2, values=1),
	mxPath("x", to="y"),
	mxFitFunctionWLS(),
	mxData(tmpFrame, 'raw'),
	# model means
	mxPath("one", to = c("x", "y"))
)

m1 = mxRun(m1)
```
> Error: The job for model 'WLS' exited abnormally with the error message: Observed means not detected, but expected means specified.
The model has no continuous variables. Do you did forget allContinuousMethod='marginals'?

The error message seems just wrong: Rather than no continuous variables, it has only continuous variables (and "do you" should be "did you". (I pushed a patch for the error message).

But the data offered up had means, they just were not preserved. Now that users offer up raw data and `mxFitFunctionWLS` is doing the processing, how *does* the user specify means to accompany processed WLS data?

Seems that they might need to fill out the `means=` parameter of mxData? In which case the help for that should say so as should this error? But then how could modeling means with a definition variable work (there are no longer any actual data to work with to compute a per-person expected mean.... confused.

**Comment by tbates** [comment]
Adding `allContinuousMethod='marginals'` does the right thing. Pushed a new error message that should be more helpful.

```R
omxRaiseError("Observed means not detected, but expected means specified.\n",
"To model means with all continuous data, you need to set allContinuousMethod='marginals'");
```

**Comment by jpritikin** [comment]
Looks good to me
