### ISSUE TITLE
mxPower upgrades cov models to raw?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#212]
This `mxPowerSearch` with a cov model reports an error - looks like mxPowerSearch is trying to upgrade it to a `type="raw"`? (works fine with `method="ncp"`)

I'm guessing `method="empirical"` only works with raw data: perhaps catch data != raw and suggest user tries ncp?

```R
# Make the front page model with cov data (m1), then modify 1 path to create m2
require(umx)
data(demoOneFactor)
m1 = umxRAM("OneFactor", data = demoOneFactor, type = "cov",
	umxPath("g", to = c('x1', 'x2', 'x3', 'x4', 'x5')),
	umxPath(var = c('x1', 'x2', 'x3', 'x4', 'x5')),
	umxPath(var = "g", fixedAt = 1)
)
m2 = umxModify(m1, "g_to_x1", value = .3, name = "drop_g_x1")

# 2. Now search across a range of n, measuring power
mxPowerSearch(trueModel= m1, falseModel= m2)

```
> Error: The job for model 'OneFactor' exited abnormally with the error message:  OneFactor.expectation: raw data observed but no expected means vector was provided.  Add something like mxPath(from = 'one', to = manifests) to your model.

**Comment by jpritikin** [comment]
v2.13.2-88-g52e711c52

**Comment by tbates** [comment]
Hi, As of 2.13.2.95 [GIT v2.13.2-95-g97d0676] this error still occurs with cov models as input to `mxPower` (i.e., it's creating raw data which then can't be used in the cov model.

Would actually be handy to be able to use empirical to work out power for models without means (which could then be sent in with no data). Easier to make these too. i.e., if no means, then just generate cov matrices instead of raw data for the empirical probes

```R
mxPower(trueModel = m1, falseModel = m2, n = 300, power=NULL)
```
> Error: The job for model 'm1' exited abnormally with the error message: m1.expectation: raw data observed but no expected means vector was provided. Add something like mxPath(from = 'one', to = manifests) to your model.
In addition: Warning message:
In mvtnorm::rmvnorm(nrows, theMeans, theCov) :
  sigma is numerically not positive semidefinite
```

**Comment by mcneale** [comment]
Yes, I think power applied to a script should generate and fit models to the type of data it has.  It seems that this could be difficult for an MAR case though.  MAR can be partially characterized by differences between list wise-deleted and fiml estimates, though some other prediction of missingness  may be more accurate.

**Comment by jpritikin** [comment]
> Hi, As of 2.13.2.95 [GIT v2.13.2-95-g97d0676] this error still occurs with cov models as input to mxPower (i.e., it's creating raw data which then can't be used in the cov model.

I ran the script from your Jun 23 comment and got an error,
```
Error in assertIsRawData(model) : 
  Model 'OneFactor' contains 'cov' data. Only type='raw' data is supported by mxPowerSearch(..., method='empirical')
```

> Would actually be handy to be able to use empirical to work out power for models without means (which could then be sent in with no data).

"use empirical"? Do you mean that mxGenerateData should use `empirical=TRUE` inside of `mxPower`?

> Easier to make these too. i.e., if no means, then just generate cov matrices instead of raw data for the empirical probes

Can't you do that already by passing in your own generate data function?

**Comment by tbates** [comment]
This seems to be due to student updating R but still having the old version in RAM (but seeing the new version from the version report...

Will close, but open a request for power on cov models, which I think would be a common use.
