### ISSUE TITLE
mxPower interface

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#213]
Couple of questions about mxPower interface

1. What does the console text mean? e.g. `R 1 init N 500`
Maybe make more plain-English, like we did with mxRun?

2. When a parameter is not active, should we report it as NA or blank? e.g. when method is "ncp", we still report probes, which is a bit misleading (none were done). Might be clearer to report `probes = NA`?

```R
mxPower(m3, m4, method = "ncp")
   method = ncp
        n = 80
    power = 0.8
   probes = 300
sig.level = 0.05
statistic = LRT

```

**Comment by jpritikin** [comment]
> What does the console text mean? Maybe make more plain-English, like we did with mxRun?

Good idea. Here's what each field means,

1. `R`
2. the probe index (from `1:probes)`
3. When `init` looking for upper and lower bounds on the intercept. `1p` fitting an intercept-only model. `2p` fitting a slope intercept model.
4. the thing that we're trying to estimate (e.g., `N` for power)
5. the value that is being probed

> When a parameter is not active, should we report it as NA or blank?

Yeah, v2.13.2-89-gbd28fe68b

**Comment by tbates** [comment]
Following ‘mxRun’ perhaps context, current evaluation , fit value, and the change in fit compared to the last status report. e.g.:
```R
estimating <N>: probe <p> trying <v>
```
which in terms of the current printing would be: 4, 2, 5

Not sure what `int` `1p` `2p` mean above. As it doesn't change (and isn't documented) perhaps omit along with header?

**Comment by jpritikin** [comment]
> Not sure what int 1p 2p mean above. As it doesn't change (and isn't documented) perhaps omit along with header?

It's the name of the model that we're currently fitting. There are 3 possible models.

**Comment by tbates** [comment]
I see now. so instead of current:

> R 81 2p N 121 


I'd vote for:

> estimating N fitting 2p probe 81 trying N= 121

**Comment by jpritikin** [comment]
Hm, that seems a bit redundant. Try v2.13.2-99-gff21bcd49
