### ISSUE TITLE
mxPowerSearch action of previousRun argument

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#214]
In what sense does previousRun  "extend" an `mxPowerSearch` search?

The output is the same length, and same power locations, but Ns at each location differ.
e.g. two equivalent lines from run 1 and extended run 2:

```R
           N     power     lower     upper
20 402.76149 0.9820138 0.9379451 0.9949551
20 320.17042 0.9820138 0.43310430 0.9997438
```

Running with no `previousRun` but twice the number of probes yields a different answer again, so not quite sure what `previousRun` is doing. (just wanting to document its behavior in .Rd)

**Comment by jpritikin** [comment]
When you use `previousRun` then the data from the probes is extended. There is some stochastic error involved in fitting the logistic model, hence the results may not exactly match from run to run.

**Comment by tbates** [comment]
OK: will add the use case of  when CI from run 1 is wider than you'd like, and this can improve it. Equivalent too (but stochastically varying around) running more probes in the first place.

**Comment by tbates** [comment]
done: [b96751c6]
