### ISSUE TITLE
mxPower: discrepancy with QIMR calculator?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#215]
The results from mxPower for an ACE model, dropping a, or c, seem discrepant from those provided by the GenEpi Twin power calculator accompanying Visscher et al (2008).

For A = .33, C = .3, E = .37, n=1000 for each of MZ and DZ pairs, an ncp `powerSearch` for dropping "A" says:
>    method = ncp
        n = 224
    power = 0.8
sig.level = 0.05

For dropping C, it suggests n = 260 (130 MZ pairs and 130 DZ pairs, as this n is total, not average)
  
QIMR calculator says (for dropping A and drop C on line 1 and 2):

|drop| All | MZ | DZ | 
|--|-- | -- | --|
|A | 28 | 14 | 14 | 
|C| 262 | 131 | 131

A bit odd: For `A`, we're giving more like the answer which would reflect power to drop `C`.

*PS*: Does the code take into account the mixture distribution at the zero boundary for variance (making p= .05 behave like .025 should)?

The power script is here: `OpenMx/inst/models/nightly/Power2.R`

*PPS*: The checks in `Power2.R` are simply that it does what it did when written: ie., they don't reference a known correct answer. Do we have known-correct cases to check against?

[Online calculator is here](https://genepi.qimr.edu.au//general/TwinPowerCalculator/twinpower.cgi)

**Comment by jpritikin** [comment]
> Does the code take into account the mixture distribution at the zero boundary for variance (making p= .05 behave like .025 should)?

No

> The checks in Power2.R are simply that it does what it did when written: ie., they don't reference a known correct answer. Do we have known-correct cases to check against?

Using `method='empirical'` is a large number of probes should produce a correct answer.

**Comment by mcneale** [comment]
It would be best to run the power calculation with the variance components not, not the path coefficient one.

**Comment by tbates** [comment]
@mcneale Looking at the [power2.R](https://github.com/OpenMx/OpenMx/blob/master/inst/models/nightly/Power2.R) example in /passing, it's a direct variance components model (no `a %*% t(a))`.

The QIMR calculator only takes variance as input. The code in the appendix shows it's a path-based ACE mode (i.e., `A= X*X'`).

In Visscher Gordon & Neale cite the Neale Eaves and Kendler 1994 code, saying the p-values reported there need to be doubled

**Mx Script from Visscher et al. (2008).**
* I made an Mx syntax highlighter for TextMate 2.0, but can't see one for github :-)&

```R
Mx Scripts for Power Calculations
! ACE Model for Power Calculations; false model AE fitted to ACE data
! #loop provides a large output to enable interpolation to find
! the optimal MZ:DZ sample size ratio. Proportions vary from 0 to 1 by
! .001 so 1000 outputs are generated per pairing of A and C variance
! components.
! A unix shell command such as
! grep ' .80 \| cannot \| NMZ \| ASQ \| CSQ ' falseAE.mxo > results.txt
! are useful to parse the output into readable form. They produce a list
! of power figures at the 80% level. Searching for CSQ or ASQ in the file
! makes it easy to find relevant sections. Note also that the cannot
! string is searched; this will detect errors. !
! Suitable for Mx versions 1.66b and later. !
#loop $a 1 8 1
#define r = 9 - $a
#loop $c 1 r 1
#define asq $a
#define csq $c
#define esq 10 - $c - $a
#loop $nmz 1 10001 10
#define nmz $nmz
#define ndz 10002 - nmz

! Simulate the data

#NGroups 1
G1: model parameters
Calculation
Begin Matrices;
	A Lower 1 1 Fixed ! genetic structure
	C Lower 1 1 Fixed ! common environmental structure 
	E Lower 1 1 Fixed ! specific environmental structure
	H Full 1 1
	Z full 1 2
End Matrices;
Matrix A asq
Matrix C csq
Matrix E esq
matrix Z nmz ndz
Matrix H .5
Begin Algebra;
	M = A+C+E | A+C _
	A+C | A+C+E /
	D = A+C+E | H@A+C _
	H@A+C | A+C+E /
End Algebra;
Options MXM = /tmp/mzsim.cov
Options MXD = /tmp/dzsim.cov
End

! Fit the wrong model to the simulated data
G1: model parameters
Calculation Ngroups=3
Begin Matrices;
	X Lower 1 1 Free ! genetic structure
	Y Lower 1 1 Fixed ! common environmental structure 
	Z Lower 1 1 Free ! specific environmental structure End Matrices;
Matrix X 2.2360
Matrix Z 2.2360
Begin Algebra; 
	A= X*X' ;
	C= Y*Y' ;
	E= Z*Z' ;
End Algebra;
Option no 
End

G2: MZ twin pairs
Data NInput_vars=2 NObservations= nmz 
CMatrix Full File=/tmp/mzsim.cov 
Matrices= Group 1
Covariances A+C+E | A+C _
A+C | A+C+E / Option No
End

G3: DZ twin pairs
Data NInput_vars=2 NObservations= ndz 
CMatrix Full File=/tmp/dzsim.cov
Matrices= Group 1
H Full 1 1
Covariances A+C+E | H@A+C _
H@A+C | A+C+E / 
Matrix H .5
Start .5 All
OPtion nO
Option Power= .10,1 ! .05 significance level & 1 df 
End
#end loop
#end loop
#end loop
```

**Comment by mcneale** [comment]
Actually halved not doubled… .025 not .05

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Jun 24, 2019, at 3:56 PM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcneale<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcneale&d=DwMCaQ&c=pOo6bKNCxsIK6eGC4MYY4A&r=asNt4APtUvtcPXbSf0CdL9zs5GRCR8_xJW4RgjV7wt4&m=3_vh_CkN6m5GdD4S0Jc_yxKFEcR00ngFI-PFRy1LNZg&s=fpBt0RppijiVc44oQHmVhkHAg0OumMxEE-5fRfJuqHg&e=> Looking at the power2.R<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_OpenMx_OpenMx_blob_master_inst_models_nightly_Power2.R&d=DwMCaQ&c=pOo6bKNCxsIK6eGC4MYY4A&r=asNt4APtUvtcPXbSf0CdL9zs5GRCR8_xJW4RgjV7wt4&m=3_vh_CkN6m5GdD4S0Jc_yxKFEcR00ngFI-PFRy1LNZg&s=KsdVmEACwXxDfxOHXmznAD_gtlPjtO8WBMrHE8po7a0&e=> example in /passing, it's a direct variance components model (no a %*% t(a)).

The QIMR calculator only takes variance as input. The code in the appendix shows it's a path-based ACE mode (i.e., A= X*X').

In Visscher Gordon & Neale cite the Neale Eaves and Kendler 1994 code, saying the p-values reported there need to be doubled

Mx Script from Visscher et al. (2008).

  *   I made an Mx syntax highlighter for TextMate 2.0, but can't see one for github :-)&

Mx Scripts for Power Calculations
! ACE Model for Power Calculations; false model AE fitted to ACE data
! #loop provides a large output to enable interpolation to find
! the optimal MZ:DZ sample size ratio. Proportions vary from 0 to 1 by
! .001 so 1000 outputs are generated per pairing of A and C variance
! components.
! A unix shell command such as
! grep ' .80 \| cannot \| NMZ \| ASQ \| CSQ ' falseAE.mxo > results.txt
! are useful to parse the output into readable form. They produce a list
! of power figures at the 80% level. Searching for CSQ or ASQ in the file
! makes it easy to find relevant sections. Note also that the cannot
! string is searched; this will detect errors. !
! Suitable for Mx versions 1.66b and later. !
#loop $a 1 8 1
#define r = 9 - $a
#loop $c 1 r 1
#define asq $a
#define csq $c
#define esq 10 - $c - $a
#loop $nmz 1 10001 10
#define nmz $nmz
#define ndz 10002 - nmz

! Simulate the data

#NGroups 1
G1: model parameters
Calculation
Begin Matrices;
        A Lower 1 1 Fixed ! genetic structure
        C Lower 1 1 Fixed ! common environmental structure
        E Lower 1 1 Fixed ! specific environmental structure
        H Full 1 1
        Z full 1 2
End Matrices;
Matrix A asq
Matrix C csq
Matrix E esq
matrix Z nmz ndz
Matrix H .5
Begin Algebra;
        M = A+C+E | A+C _
        A+C | A+C+E /
        D = A+C+E | H@A+C _
        H@A+C | A+C+E /
End Algebra;
Options MXM = /tmp/mzsim.cov
Options MXD = /tmp/dzsim.cov
End

! Fit the wrong model to the simulated data
G1: model parameters
Calculation Ngroups=3
Begin Matrices;
        X Lower 1 1 Free ! genetic structure
        Y Lower 1 1 Fixed ! common environmental structure
        Z Lower 1 1 Free ! specific environmental structure End Matrices;
Matrix X 2.2360
Matrix Z 2.2360
Begin Algebra;
        A= X*X' ;
        C= Y*Y' ;
        E= Z*Z' ;
End Algebra;
Option no
End

G2: MZ twin pairs
Data NInput_vars=2 NObservations= nmz
CMatrix Full File=/tmp/mzsim.cov
Matrices= Group 1
Covariances A+C+E | A+C _
A+C | A+C+E / Option No
End

G3: DZ twin pairs
Data NInput_vars=2 NObservations= ndz
CMatrix Full File=/tmp/dzsim.cov
Matrices= Group 1
H Full 1 1
Covariances A+C+E | H@A+C _
H@A+C | A+C+E /
Matrix H .5
Start .5 All
OPtion nO
Option Power= .10,1 ! .05 significance level & 1 df
End
#end loop
#end loop
#end loop

**Comment by jpritikin** [comment]
Is this fixed now that we sorted out the sample size problem?

**Comment by tbates** [comment]
I don't this is fixed. I'm also not sure mxPower is fixed.

In the previous version, n needed for  80% power to detect AA >0 was estimated at 224 pairs, total.

Version `2.13.2.167 [GIT v2.13.2-167-ge4adf85]` now suggests n= 446. To detect CC > 0, it suggests 520 total pairs...

I think the correct answers are 28, and 262 respectively. Something's not right?

**Comment by mcneale** [comment]
Sounds like a one-tailed to two-tailed test change.  Detecting AA>0 *when the true value is what exactly?*. It’s important to be clear, with statements like “The power to reject the hypothesis that AA=0 when the true value of AA is <value>.

The 28 sounds wrong to me.  Only 28 pairs for A and 262 for C?!  Is that a typo?  Have you compared with VIsscher’s power paper?

**Comment by tbates** [comment]
Good questions. mxPower doesn't have a 1-tailed/both control. 

“Power to reject the hypothesis at alpha=.05 that AA=0 when the true value of AA is .33"

Visscher's web site accompanying the paper, running the code from the paper says:

<img width="502" alt="Screenshot 2019-08-22 13 56 25" src="https://user-images.githubusercontent.com/736156/63516347-b765cb00-c4e4-11e9-8676-0b577e78072f.png">

**Comment by mcneale** [comment]
That says power of 44.6%, I was thinking of the dogmatic 80%...

**Comment by tbates** [comment]
Surely not? The table is "Sample size (pairs) needed to achieve 80% power"

The "power" cell beneath the "Noncentrality parameter" cell made no sense to me: it isn't linked to the ns that yield 80% power, and they isn't (likely) the power of the input trueModel (which included 1000 pairs of each of MZ and DZ). it doesn't change when one changes the N in the input model. Maybe it's some linking parameter used to scale out the n required to get the desired power?

Playing with the power calculator, I think it's broken: it always return n=28 even with AA=1, C=0, E=.00001....

https://genepi.qimr.edu.au//general/TwinPowerCalculator/twinpower.cgi

should tell peter?

**Comment by mcneale** [comment]
Checking against Visscher 2004, I think there's a problem with his website calculator  (ah, I see you discovered this while I'm writing).  There's a row in the attached table for a^2 .4, c^2 .3 e^2 .3,  with 50:50 MZ:DZ design that says 466 pairs for 95%  power,  which jives with my intuition.   Yes, let's let him know. 

![image](https://user-images.githubusercontent.com/2318093/63522435-54653b80-c4c6-11e9-9925-45a5b205cbc9.png)

**Comment by tbates** [comment]
So the discrepancy was in the online calculator: notified them now...
