### ISSUE TITLE
mxPower: handle multiple p-values well

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#216]
For `mxPower` where multiple p-values would be really helpful (returning a list of N, we could plot nicely), the result is rather odd...

```R
tmp = mxPower(factorModelFit, indModel, method='ncp',sig.level=c(.05,.01))
tmp
```
the pretty print contains a double label of sig.level

>   method = ncp
        n = 80
    power = 0.8
sig.level = 0.05 sig.level = 0.01
statistic = LRT

Only 1 n is returned, despite no error...

```R
as.numeric(tmp)
[1] 80
```

Also, be good to catch multiple values for sig.level for mxPowerSearch (given several things are vectorized, but not search across p-values).

```R
mxPowerSearch(factorModelFit, indModel, method='ncp', sig.level = c(.05, .01))
```
> Error in seq.default(center - 1 * width, center + 4 * width, length.out = 20) : 
  'from' must be of length 1

**Comment by jpritikin** [comment]
The code is already fairly complex. Can we just enforce `length(sig.level)==1` and not automatically vectorize?

**Comment by tbates** [comment]
sure: that would be fine. maybe if length(sig.level) != 1 {message("I can only evaluate 1 sig.level at a time: To evaluate power across a range of p-value, you need to call mxPower in a loop and accumulate estimates that way")

**Comment by jpritikin** [comment]
v2.13.2-93-g1a61d1d1c
