### ISSUE TITLE
bgen.cpp compiling error

### ISSUE THREAD

**Issue by rpool** [OpenMx/OpenMx#217]
Hi,
I receive the following error while compiling "bgen.cpp", upon invoking "source('https://openmx.ssri.psu.edu/software/getOpenMx.R')" from within R:

bgen.cpp:866:15: error: ‘streampos’ is not a member of ‘std::ios’ {aka ‘std::basic_ios<char>’}
     std::ios::streampos origin = m_stream->tellg() ;

> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.04

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.2 tools_3.5.2

**Comment by jpritikin** [comment]
Post an example of the complete compile line for bgen.cpp. For example,

```
g++-9 -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I"/opt/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include" -I"/opt/R/x86_64-pc-linux-gnu-library/3.6/RcppEigen/include" -I"/opt/R/x86_64-pc-linux-gnu-library/3.6/StanHeaders/include" -I"/opt/R/x86_64-pc-linux-gnu-library/3.6/BH/include" -I"/opt/R/x86_64-pc-linux-gnu-library/3.6/rpf/include"  -fopenmp -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-deprecated-declarations -Wno-unused-function -Wno-unused-variable -fdiagnostics-color=auto -DEXTRA_GCC_DIAG -Wno-misleading-indentation -Wno-pragmas -Wno-ignored-attributes -Wno-misleading-indentation -Wno-int-in-bool-context -Wclass-memaccess    -I. -Iinclude -Iinclude/zstd-1.1.0 -Iinclude/zstd-1.1.0/common -Iinclude/zstd-1.1.0/compress -Iinclude/zstd-1.1.0/decompress -D SQLITE_ENABLE_COLUMN_METADATA -D SQLITE_ENABLE_STAT4 -D SQLITE_MAX_EXPR_DEPTH=10000 -D SQLITE_USE_URI=1  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-SQC8bE/r-base-3.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bgen.cpp -o bgen.o
```

**Comment by rpool** [comment]
Here you go:

g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG  -I"/home/r.pool/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I"/home/r.pool/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include" -I"/home/r.pool/R/x86_64-pc-linux-gnu-library/3.5/StanHeaders/include" -I"/home/r.pool/R/x86_64-pc-linux-gnu-library/3.5/BH/include" -I"/home/r.pool/R/x86_64-pc-linux-gnu-library/3.5/rpf/include"   -fopenmp   -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe  -I. -Iinclude -Iinclude/zstd-1.1.0 -Iinclude/zstd-1.1.0/common -Iinclude/zstd-1.1.0/compress -Iinclude/zstd-1.1.0/decompress -D SQLITE_ENABLE_COLUMN_METADATA -D SQLITE_ENABLE_STAT4 -D SQLITE_MAX_EXPR_DEPTH=10000 -D SQLITE_USE_URI=1  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-el7SHG/r-base-3.5.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c bgen.cpp -o bgen.o

**Comment by jpritikin** [comment]
I pushed a potential fix, v2.13.2-94-g5c0c7c950. Can you build with this change included to test it?

**Comment by rpool** [comment]
Dear Joshua,

Yes, this compiles, thanks a lot!

I'm not very familiar with R. How would I install this development version from within R?

Best,
René

**Comment by jpritikin** [comment]
Try `make install` ?

**Comment by jpritikin** [comment]
Any progress here?

**Comment by rpool** [comment]
It's been a while ago, but I got it working. `make install` did not work. Eventually I edited `bgen.cpp` and installed from `tar`.
