### ISSUE TITLE
implement or remove sscp from mxData

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#219]
sscp is listed as a type for mxData, but (unlike cor which is treated as cov) sscp is not supported at all:

```R
mxData(mtcars, type="sscp")
Error in mxData(mtcars, type = "sscp") : 'sscp' is not yet implemented.
```

just remove this?

**Comment by RMKirkpatrick** [comment]
I dunno.  Wasn't SSCP supported in classic Mx?

**Comment by mcneale** [comment]
Not explicitly, no. At least not as far as I recall...  In January it’ll be 30 years since Mx dev started.

**Comment by tbates** [comment]
Wow: 30! Twin workshop will be 22 and OpenMx release 0.1 was August 2009: So 10 years.
Must warrant a "origins and state of the art of software" symposium at BGA (50th year) in LA :-)

**Comment by RMKirkpatrick** [comment]
I looked at the classic Mx manual yesterday, and no, it did not support SSCP input.  I say we get rid of it.

**Comment by tbates** [comment]
removed mention of sscp from code and docs
