### ISSUE TITLE
mxPower returns identical N for p = .05, .01, and .001

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#220]
mxPower solves for an identical N at p = .05, .01, and .001 - seems broken.

I made this loop solving for N at different target p values and was surprised to see N was invariant:

```R
ps = c(.05, .01, .001)
ns = rep(NA, length(ps))
for (i in 1:length(ps)) {
	ns[i] = mxPower(factorModelFit, indModel, method = 'ncp', sig.level=ps[i])
}
ns
```
> 80 80 80

Indeed it is, and this must be wrong:

```R
mxPower(factorModelFit, indModel, method = 'ncp', sig.level=.05)
#        n = 80
#   power = 0.8
# sig.level = 0.05

mxPower(factorModelFit, indModel, method = 'ncp', sig.level=.01)
#        n = 80
#   power = 0.8
# sig.level = 0.01

mxPower(factorModelFit, indModel, method = 'ncp', sig.level=.001)
#        n = 80
#   power = 0.8
# sig.level = 0.001
```

_Originally posted by @jpritikin in https://github.com/OpenMx/OpenMx/issues/216#issuecomment-505638560_

**Comment by jpritikin** [comment]
Good catch! v2.13.2-95-g97d067695

**Comment by tbates** [comment]
phew!

**Comment by tbates** [comment]
this error should be caught by us: perfectly reasonable to ask for p= .5

```R
mxPower(factorModelFit, indModel, method = 'ncp', sig.level = .5)
```
> Error in findInterval(p1, result$power, all.inside = TRUE) : 
  'vec' must be sorted non-decreasingly and not contain NAs
In addition: Warning message:
In pchisq(qchisq(1 - sig.level, diffdf), diffdf, avgNcp * out$x) :
  NaNs produced

**Comment by jpritikin** [comment]
> perfectly reasonable to ask for p= .5

Is it? If it produces NaNs then what should we return? Do you want a better error message?

**Comment by tbates** [comment]
I guess error message should be
> "Sorry, unable to solve for N at that sig.level .5 and power= .8. Consider trying method = 'empirical' "

p <= .5 is a common target, for instance, in genetic studies.

**Comment by jpritikin** [comment]
v2.13.2-98-g06a4940cb
