### ISSUE TITLE
mxGenerateData: Doesn't warn user if model has not been run... might be safer to do so

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#222]
Make a model with data and pass it, not-run, to `mxGenerateData`. 

`mxGenerateData` returns a data set matching the default parameter values (often all zeros), with no notice.

Might be nice to either run models if they contain data, or tell people:

> polite note: Your model with data has not been run yet: Simulated data may not fit the data you provided at all well.

repro:

```R
data(myFADataRaw, package="OpenMx")
manifests = names(myFADataRaw)

m1 = mxModel("m1", type="RAM",
	manifestVars = manifests, latentVars   = "G",
	mxPath("G", to = manifests),
	mxPath(manifests, arrows = 2),
	mxPath("G", arrows = 2, free = F, values = 1),
	mxData(cov(myFADataRaw, use="complete"), type = "cov", numObs = nrow(myFADataRaw))
)

simData = mxGenerateData(m1, nrows=1000)

str(simData)
'data.frame':	1000 obs. of  12 variables:
 $ x1: num  0 0 0 0 0 0 0 0 0 0 ...
 $ x2: num  0 0 0 0 0 0 0 0 0 0 ...
 $ x3: num  0 0 0 0 0 0 0 0 0 0 ...
 $ x4: num  0 0 0 0 0 0 0 0 0 0 ...
 $ x5: num  0 0 0 0 0 0 0 0 0 0 ...
 $ x6: num  0 0 0 0 0 0 0 0 0 0 ...
 $ y1: num  0 0 0 0 0 0 0 0 0 0 ...
 $ y2: num  0 0 0 0 0 0 0 0 0 0 ...
 $ y3: num  0 0 0 0 0 0 0 0 0 0 ...
 $ z1: num  0 0 0 0 0 0 0 0 0 0 ...
 $ z2: num  0 0 0 0 0 0 0 0 0 0 ...
 $ z3: num  0 0 0 0 0 0 0 0 0 0 ...
```

**Comment by jpritikin** [comment]
From the man page: "Please note that this function samples data from the model-implied distribution(s); it does not sample from the data object in the model. That is, this function generates new data rather than pulling data that already exist from the model."

I don't think warning is a good idea. At most, we might issue a message. So you think we should message if there is data in the model and the model hasn't been run?

**Comment by tbates** [comment]
yes, it's a tricky balance. I think for the nifty use case based on inputting the desired set of parameters, the warning or even a note is excessive.

But for the case where a person has data in their model, and the parameters bear no relationship to those parameters, it seems they almost always are making a mistake (i.e., why add data and then completely ignore it?). 

Perhaps if data exist, post a message?

**Comment by mcneale** [comment]
At **most** a message, given that the man page is explicit about it.  It seems to me more likely that the  user simply left some data in the model, and wants only the expected data based on the starting values provided.   Fitting to data first may well be exactly what the user does NOT want to do first.
