### ISSUE TITLE
mxGenerateData: Doesn't catch models with no means

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#223]
give `mxGenerateData` a cov-data model (no means paths) and you don't get a message about that, but instead see an error from the call to `rmvnorm`
> In mvtnorm::rmvnorm(nrows, theMeans, theCov) : sigma is numerically not positive semidefinite

Should preferably say:

> polite note: Your model has no means: data have been simulated assuming zero means

or at least
> Error: Your model has no means: data cannot be simulated.

repro:

```R
data(myFADataRaw, package="OpenMx")
manifests = names(myFADataRaw)

m1 = mxModel("m1", type="RAM",
	manifestVars = manifests, latentVars   = "G",
	mxPath("G", to = manifests),
	mxPath(manifests, arrows = 2),
	mxPath("G", arrows = 2, free = F, values = 1),
	mxData(cov(myFADataRaw, use="complete"), type = "cov", numObs = nrow(myFADataRaw))
)
m1 = mxRun(m1)
simData = mxGenerateData(m1, nrows=1000)
```

> Warning message:
In mvtnorm::rmvnorm(nrows, theMeans, theCov) : sigma is numerically not positive semidefinite

**Comment by RMKirkpatrick** [comment]
Why would a lack of model-specified means result in the covariance being non-PD?

**Comment by tbates** [comment]
Not sure: Model generates fine with raw data/means paths. Perhaps something about the `theMeans` being passed in when it is (likely) NA?

**Comment by jpritikin** [comment]
I can't reproduce this problem using the code you provided. There is already code to use a zero mean in this case,

```
		if (length(theMeans) == 0) {
			theMeans <- rep(0, nrow(theCov))
		}
```

**Comment by RMKirkpatrick** [comment]
I can't reproduce it either, but I'm running the 2.13 release.

**Comment by tbates** [comment]
Weird. Now on re-boot it doesn't repro here either. Must have been an unlucky occurrence in which  `rmvnorm` actually hit a bad covariance matrix in this model... Well, that's good news! 

It looked like #90 had snuck back in.
