### ISSUE TITLE
Errors when building on ARM in 2.13.2

### ISSUE THREAD

**Issue by jonathon-love** [OpenMx/OpenMx#226]
hi,

i've been building OpenMX on flathub for a while, but i recently updated to 2.13.2 from 2.11.5, and builds on arm and arm64 are failing:

https://flathub.org/builds/#/builders/51/builds/473

i appreciate there are probably steps i could do to resolve this, but i wanted to check-in to see if this could be fixed upstream. if it could be addressed upstream, it means i don't have to maintain custom rules for this package, reducing the maintenance burden for downstream projects.

let me know if there's any experiments you'd like me to perform.

with thanks

**Comment by jpritikin** [comment]
You could file an issue with [plink-ng](https://github.com/chrchang/plink-ng) but it would probably be easier to add an option to compile without plink. BTW, why are you building on arm?

**Comment by jonathon-love** [comment]
so plink-ng was something which was added more recently? i.e. the narrative forming in my head is "it used to work fine because it didn't include plink-ng, but now OpenMx does include plink-ng, and plink-ng introduces issues compiling for arm". let me know if i erred.

> it would probably be easier to add an option to compile without plink

is this something you guys could add?

> BTW, why are you building on arm?

that's a funny question isn't it? because i have users on ARM :)

with thanks

jonathon

**Comment by jpritikin** [comment]
> so plink-ng was something which was added more recently?

Yes

> is this something you guys could add?

Sure, it's a minor change. What compiler flag should I condition on? `#if ARM` or maybe `#if !AMD64` ?

> because i have users on ARM :)

OpenMx users? Or are you just packaging all CRAN packages in flatpak?

**Comment by jonathon-love** [comment]
> What compiler flag should I condition on?

in the absence of any flag, is it possible to read the output of `uname -p`? for me, it's super useful if the compilation "just works" without me needing to configure anything. so the way i resolve R dependencies is to recursively download all the dependencies, perform a topological sort, write out the directory names in a way that R will install them in an order which works (000_packageName, 001_packageName, etc.), and then use that as an installation blueprint. the R package i'm trying to support is `jmv`, and it has ~140 dependencies i think.

https://github.com/flathub/org.jamovi.jamovi/blob/master/jmv-deps-sources.json#L531

all this is necessary to build using flathub. so this is why i'm really trying to avoid any sort of manual arguments, etc. once i have to dive down and insert additional build arguments for individual packages, my life becomes a lot less fun.

> OpenMx users?

alas, no. `OpenMx` appears somewhere in the gargantuan dependency tree that feeds into `jmv`, which in turn is used by [jamovi](https://www.jamovi.org). it looks like `jmv` uses `semPlot` which in turn uses `OpenMx`.

with thanks

**Comment by jonathon-love** [comment]
although, i suppose using `uname -p` won't lead to a correct result if someone is cross-compiling.

it looks like [`__arm__`](https://sourceforge.net/p/predef/wiki/Architectures/) might be our friend ... but i guess whether that's useful or not will depend on whether the plink-ng inclusion is determined at the source level, or at the make level.

cheers

**Comment by jpritikin** [comment]
Cross-compiling, ick. I'd rather use `uname -p`. Can you try v2.13.2-120-g5e2450d0c ?

**Comment by jonathon-love** [comment]
hi, so i tried master, but this is what i get:

```
* installing *source* package ‘OpenMx’ ...
NOTE: ./.devmode exists; will enable extra compiler diagnostics
NOTE: ./configure is not an autoconf generated script.
Change default C/C++ compiler and default compile flags by editing ~/.R/Makevars
./configure: line 128: wget: command not found
sha1sum: src/libnpsol.a: No such file or directory
************ ************
WARNING: Cannot verify correct libnpsol.a version
sha1sum libnpsol.a => 
************ ************
src/libnpsol.a not found
ERROR: configuration failed for package ‘OpenMx’
* removing ‘/run/build/jmv/jmv/build/R/OpenMx’
]2;flatpak-builder: Cleanup jmvError: module jmv: Child process exited with code 1
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-1xdGDJ
```

**Comment by tbates** [comment]
We don't have a version of NPSOL for ARM processors, so that makes sense.
Perhaps need to switch to the CRAN make file (which doesn't try to include NPSOL)?

**Comment by jpritikin** [comment]
Yeah, use `make cran-install` instead of `make install`

**Comment by RMKirkpatrick** [comment]
I anticipate @jonathon-love will run into trouble with compiling pgenlib while building OpenMx from source, since that library uses AMD64-specific(?) code optimizations, and [conditioning pgenlib compilation on AMD64](https://github.com/OpenMx/OpenMx/commit/5e2450d0c0c1bd990577bf4ffb612bbb3feb2070) is newer than the v2.13 release.  Right?

Maybe we'll have an NPSOL armhf binary in a few months.

**Comment by jonathon-love** [comment]
OK, 32-bit arm builds now, but 64 bit arm fails with the following:

```
* installing *source* package ‘OpenMx’ ...
NOTE: ./configure is not an autoconf generated script.
Change default C/C++ compiler and default compile flags by editing ~/.R/Makevars
** libs
g++ -std=gnu++14 -I"/app/lib/R/include" -DNDEBUG  -I"/app/lib/R/library/Rcpp/include" -I"/run/build/jmv/jmv/build/R/RcppEigen/include" -I"/run/build/jmv/jmv/build/R/StanHeaders/include" -I"/run/build/jmv/jmv/build/R/BH/include" -I"/run/build/jmv/jmv/build/R/rpf/include" -I/usr/local/include  -fopenmp  -DWANT_PGENLIB=0   -I. -Iinclude -Iinclude/zstd-1.1.0 -Iinclude/zstd-1.1.0/common -Iinclude/zstd-1.1.0/compress -Iinclude/zstd-1.1.0/decompress -D SQLITE_ENABLE_COLUMN_METADATA -D SQLITE_ENABLE_STAT4 -D SQLITE_MAX_EXPR_DEPTH=10000 -D SQLITE_USE_URI=1  -fpic  -O2 -c Compute.cpp -o Compute.o
In file included from pgenlib_internal.h:74:0,
                 from Compute.cpp:44:
plink2_base.h:137:6: error: #error "64-bit builds currently require SSE2.  Try producing a 32-bit build instead."
 #    error "64-bit builds currently require SSE2.  Try producing a 32-bit build instead."
      ^~~~~
plink2_base.h:139:25: fatal error: emmintrin.h: No such file or directory
 #  include <emmintrin.h>
                         ^
compilation terminated.
make: *** [/app/lib/R/etc/Makeconf:168: Compute.o] Error 1
ERROR: compilation failed for package ‘OpenMx’
```

with thanks

**Comment by jpritikin** [comment]
Almost there. Please try v2.13.2-125-gd3ccfb822

**Comment by jonathon-love** [comment]
```
Compute.cpp:45:17: error: ‘plink2’ is not a namespace-name
 using namespace plink2;
                 ^~~~~~
Compute.cpp:45:23: error: expected namespace-name before ‘;’ token
 using namespace plink2;
```

**Comment by jpritikin** [comment]
v2.13.2-127-g4693e3b23 should do it

**Comment by jonathon-love** [comment]
it works!

**Comment by RMKirkpatrick** [comment]
BTW, @jonathon-love , which flavor of ARM were you compiling under?  AArch64? armel?  armhf?

**Comment by jonathon-love** [comment]
`aarch64` and `arm` ... (not sure if `arm` here might correspond to `armel` or `armhf`) ... whatever flathub uses.

**Comment by jonathon-love** [comment]
thanks for your work on this issue @jpritikin, helping out downstream projects can often feel a bit thankless, as your work is often not recognised by end-users, so i especially appreciate you helping us out here.

when do you expect to do a next CRAN release?

with thanks

**Comment by jpritikin** [comment]
> thanks for your work on this issue

Welcome. Thanks for testing!

> when do you expect to do a next CRAN release?

That's a good question. We don't really have a pre-release announcement built into our development process. How much lead time do you need?

**Comment by jonathon-love** [comment]
> How much lead time do you need?

oh it's no biggie. once it hits CRAN, i can tidy our build files up. until then, they're just a bit messy. so there's no pressure either way from us.

**Comment by RMKirkpatrick** [comment]
I second Joshua: thanks for testing, and for opening this issue!  It's really cool to hear about OpenMx being built on different CPU architectures.
