### ISSUE TITLE
mxGenerateData: Allow empirical

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#227]
In `generateNormalData` (called by `mxGenerateData`) we use `mvtnorm::rmvnorm(nrows, theMeans, theCov)` simulating draws from a population.

When generating data for a model, however, one often wants to treat the requested means and covariances as empirical. i.e., require that the generated data match this quasi-exactly.

Would be useful to switch to `MASS::mvrnorm` and add a parameter to `mxGenerateData` for `empirical= FALSE|TRUE`, passing this down to `generateNormalData`

**Comment by jpritikin** [comment]
Would it be enough to keep the current code as is except to add an empirical argument where `empirical=TRUE` calls `MASS::mvrnorm` and `empirical=FALSE` does the same thing as currently done? I'm just looking to minimize changes to current behavior.

**Comment by tbates** [comment]
yes, I think that would OK.

**Comment by jpritikin** [comment]
This option is to [change the divisor for the covariance matrix](https://stats.stackexchange.com/questions/11421/what-is-the-difference-between-empirical-variance-and-variance#11423)?

**Comment by RMKirkpatrick** [comment]
@jpritikin No.  With `empirical=FALSE`, data are randomly generated from a "population" having the input covariance matrix.  With `empirical=TRUE`, a dataset is generated that has a covariance matrix exactly equal to the input covariance matrix.

**Comment by mcneale** [comment]
@jpritikin No, it is so that simulated raw data have the property that their covariances and means exactly match those supplied to mvrnorm in the first place.  Usually, simulated raw data have sampling error, so that the match is only the expected value over many simulations.  empirical=TRUE means that there is zero variance in the calculated means and variances across datasets.   The actual values may vary though!

**Comment by jpritikin** [comment]
Huh, OK

**Comment by tbates** [comment]
Seems to generate the right output on the diagonal, but a smidgen off for covariances. Good as can been doubt, without doing injustice to the distributions.

```R
popCov <- cov(Bollen[, 1:8])*(nrow(Bollen)-1)/nrow(Bollen)
got <- mxGenerateData(Bollen[, 1:8], nrows=1000, empirical = TRUE)
round(cov2cor(cov(got)) - cov2cor(popCov), 4)

       y1      y2      y3      y4      y5      y6      y7      y8
y1  0.0000 -0.0671 -0.0165 -0.0240  0.0050 -0.0286 -0.0203 -0.0277
y2 -0.0671  0.0000 -0.0119  0.0036 -0.0441 -0.0176 -0.0274 -0.0069
y3 -0.0165 -0.0119  0.0000  0.0253 -0.0001 -0.0110 -0.0123  0.0128
y4 -0.0240  0.0036  0.0253  0.0000 -0.0266  0.0035 -0.0079  0.0061
y5  0.0050 -0.0441 -0.0001 -0.0266  0.0000 -0.0119 -0.0074  0.0087
y6 -0.0286 -0.0176 -0.0110  0.0035 -0.0119  0.0000  0.0043 -0.0003
y7 -0.0203 -0.0274 -0.0123 -0.0079 -0.0074  0.0043  0.0000  0.0142
y8 -0.0277 -0.0069  0.0128  0.0061  0.0087 -0.0003  0.0142  0.0000


```

**Comment by mcneale** [comment]
Whence the Bollen data?

**Comment by jpritikin** [comment]
Bollen is included with OpenMx

**Comment by jpritikin** [comment]
@tbates Obviously the diagonals are going to match exactly since you used `cov2cor`. Without `cov2cor`, the diagonals still match closely.

**Comment by tbates** [comment]
I only used cov2cor to give viewers some scale to interpret the off-diagonal deviations. (".6" is not helpful as a deviation for covariance that might be .1 or 100000). I think the issue is this is a jolly hard test: Hard to juggle 8 balls... 

Variances indeed deviate zero in the covariance.
