### ISSUE TITLE
mxGenerateData(returnModel) return data of the same type as input model 

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#228]
`mxGenerateData(..., returnModel = TRUE)`  doesn't return data of the same type as the model originally had. It would be nice if it did.

This would be a test case script:

```R
m1 = mxModel("testCovPower", type="RAM",
   mxData(observed = matrix(c(1, .3, .3, 1), nrow = 2, dimnames=list(c("X", "Y"), c("X", "Y"))), numObs = 200, type="cov"),
   manifestVars = c("X", "Y"),
   mxPath("X", to = "Y", value= .3),
   mxPath(c("X", "Y"), arrows=2, value= 1)
)

m2 = mxGenerateData(m1, nrows=200, returnModel=T)

# test type (e.g. m2 is "cov"
testthat::expect_true("cov"== m2$data$type)

# test `means` still = NA
m1$data$means
testthat::expect_true(ncol(m2$data$means)==1)

```

**Comment by jpritikin** [comment]
Hm, seems like a good idea, but the proposed change would break backward compatibility. Any suggestions about how to get the desired behavior without break existing scripts?

**Comment by mcneale** [comment]
I agree it should really generate data that 'match' those in the original model, and ideally this  should be the default behavior.  Some users might want the generated data type to change, and some existing scripts may already do that.   We should respect backward compatibility as a top priority because there are so many users out there.

How about adding an argument originalDataType=F which if true generates the original data type  instead?    We miss the default ideal, but this seems the least of the evils.

**Comment by jpritikin** [comment]
Hm, or maybe an argument `outputDataType='raw'` for the current behavior and `outputDataType='same'` for the proposed behavior?

**Comment by tbates** [comment]
Seems `returnModel` should respect the incoming data type by default.

`outputDataType` would be great for cases where `returnModel = FALSE` cases and especially cases where `returnModel = TRUE` and incoming model has no data (adding data to a model is a nice use case for this function). Very handy workflow for `mxPower` with method="ncp" - just spec the parameters, generate data without ever providing any, and then modify and submit to `mxPower` 

In that case, would be great if `outputDataType = c("raw", "cov")` and let that choice inform the returnModel case (no data: look at what outputDataType says and pop an object of that type into the data slot.

**Comment by jpritikin** [comment]
What is the correct way to generate cov data? Generate raw and then pass it through `cov()`?

**Comment by RMKirkpatrick** [comment]
Using `rWishart()` from base R is probably faster.

**Comment by jpritikin** [comment]
> Using rWishart() from base R is probably faster.

Yeah, I was wondering about that. I guess `Sigma` is the trueModel covariance. What about `df`?

**Comment by RMKirkpatrick** [comment]
`df` is the size of the sample from which the covariance matrix was calculated.  See https://en.wikipedia.org/wiki/Wishart_distribution#Definition .

**Comment by jpritikin** [comment]
> The current behavior is to return raw data inside a model that can't handle it... ie., a broken model, or a model that has silently changed its data type?

Good point.

**Comment by jpritikin** [comment]
> df is the size of the sample from which the covariance matrix was calculated.

Hm, are you sure? It doesn't seem like it works that way. Maybe I have to divide by the sample size too? Try v2.13.2-168-ge586d8806 with,

```
library(OpenMx)

m1 = mxModel("testCovPower", type="RAM",
             mxData(observed = matrix(c(1, .3, .3, 1), nrow = 2, dimnames=list(c("X", "Y"), c("X", "Y"))), numObs = 200, type="cov"),
             manifestVars = c("X", "Y"),
             mxPath("X", to = "Y", value= .3),
             mxPath(c("X", "Y"), arrows=2, value= 1)
)

m2 = mxGenerateData(m1, nrows=200, returnModel=T)
omxCheckEquals(m2$data$type, "cov")
omxCheckEquals(m2$data$numObs, m1$data$numObs)
c1 <- m2$data$observed - mxGetExpected(m3, 'covariance')
print(c1)
omxCheckCloseEnough(m2$data$means, rep(0,2))

m3 = mxGenerateData(m1, nrows=200, returnModel=T, empirical=TRUE)
omxCheckEquals(m3$data$type, "cov")
omxCheckEquals(m3$data$numObs, m1$data$numObs)
omxCheckCloseEnough(m3$data$observed, mxGetExpected(m3, 'covariance'))
omxCheckCloseEnough(m3$data$means, rep(0,2))
```

**Comment by RMKirkpatrick** [comment]
> Maybe I have to divide by the sample size too?

Correct.  `rWishart` generates a covariance matrix multiplied by sample size.

**Comment by jpritikin** [comment]
OK, maybe v2.13.2-173-g143e20f2c is enough?

**Comment by tbates** [comment]
thanks! Just one thing I see  - 173 adds means where there weren't any. Probably should test for that and only pass back means if there were some to start with?

```R
m1$data$means
     [,1]
[1,]   NA

m2$data$means
     [,1] [,2]
[1,]    0    0
```

**Comment by jpritikin** [comment]
Try v2.13.2-175-g4feef6364

**Comment by tbates** [comment]
perfect!
Thanks Josh!
