### ISSUE TITLE
Segfault when a data column is character type.

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#232]
See https://openmx.ssri.psu.edu/node/4525 .  At first I thought it had something to do with the data.table object class, but now I think it's an OpenMx bug (perhaps specific to state space expectation?).

**Comment by RMKirkpatrick** [comment]
@mhunter1 ?

**Comment by jpritikin** [comment]
I will take this one unless somebody else has some special insight.
