### ISSUE TITLE
mxPowerSearch not using n when provided by user

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#233]
`mxPowerSearch(trueModel, nullModel, n=100)` is supposed to search for power at varying effect sizes (values for the parameter that has been fixed in `nullModel` relative to `truModel`).

It appears to be ignoring the user's `n`, and instead using the average n of data found in `trueModel`

Here's a repro:  `mxPowerSearch`, solving for effect sizes & power, with fixed `n = 90`

We need to make some raw data with true XY correlation of .3, model it, and modify this model, setting "X_with_Y" to zero.

```R
# 1. make the data
tmp = umx_make_raw_from_cov(matrix(c(1, .3,.3, 1), nrow=2),
    n=2000,  varNames= c("X", "Y"), empirical= TRUE
)
# 2. model it
m1 = umxRAM("corXY", data = tmp, umxPath("X", with = "Y"), umxPath(var = c("X", "Y")))

# 3. Make null model X_with_Y == 0
m2 = umxModify(m1, "X_with_Y")
```
NOW, let's try fixing n and looking for where we'd have 80% power for our effect (𝛽= .3).
The correct answer for this question is known to be ~ our true effect size, i.e., we our true effect size is the effect that a study of 90 people will reliably detect.

```R
mxPowerSearch(m1, m2, n = 90)
```
Oops miles off...
> beta  power
> 0.058 0.80

What is `umxPowerSearch` doing? Let's estimate a model with beta = .058

```R
tmp = umx_make_raw_from_cov(qm(1, .058| .058, 1), n=2000, varNames= c("X", "Y"), empirical= TRUE)
cov(tmp)
#       X     Y
# X 1.000 0.058
# Y 0.058 1.000

m1 = umxRAM("corXY", data = tmp, umxPath("X", with = "Y"), umxPath(var = c("X", "Y")))
m2 = umxModify(m1, "X_with_Y")
```
And run `mxPower` to see our true power to detect this tiny effect with 90 subjects:

```R
mxPower(m1, m2, n= 90, power=NULL, method= "ncp")
```
>      n = 90
> power = 0.08540375

Yikes... `mxPowerSearch` was an order of magnitude off.

Let's put in the n used to build our trueModel:

```R
mxPower(m1, m2, n= 2000, power=NULL, method= "ncp")
```
>    n = 2000
> power = 0.738

Ahh: `mxPowerSearch` is using the n from the trueModel happens to have, not the n the user offers up :-(
	 
Here's some background testing other features. Be good to add tests for the power suite with known answers.

Ground truth from `pwr.r.test`: power at n= 90 for r=.3 is ~ 83%

```R
pwr::pwr.r.test(r = .3, n = 90)
              n = 90
              r = 0.3
      sig.level = 0.05
          power = 0.826
    alternative = two.sided
```

And showing that `mxPower` is working fine for other cases:

```R
mxPower(m1, m2, n= 90, power=NULL, method= "ncp")
mxPower(m1, m2, n= 90, power=NULL, method= "empirical")
# PS: Would be better if default for power was NULL...
```

Now test search for power across range of ns
Using ncp gets it correct (~90)
```R
mxPowerSearch(m1, m2, method="ncp")
N     power
 86.74 0.82
```

As does empirical

```R
mxPowerSearch(m1, m2)
# N     power
# 90.32 0.87
```

**Comment by jpritikin** [comment]
> It appears to be ignoring the user's n, and instead using the average n of data found in trueModel

Bingo. That's exactly what's happening.

**Comment by mcneale** [comment]
It’s not too difficult when the black box is open source, unlike most other SEM software.  And it’s a bug so let’s squash it.

**Comment by jpritikin** [comment]
Try v2.13.2-156-gb71a2ff20

I didn't try to preserve backward compatibility because the code was so completely broken.

**Comment by tbates** [comment]
Seems like this might be more off - or am I not using it correctly? 

`OpenMx version: 2.13.2.157 [GIT v2.13.2-157-gae06658]`

Comparing the free `X~~Y` m1  to `X~~0*Y` (zero correlation) (m2), `mxPowerSearch` now  claims that with n= 90 we'd have 89% power to detect a correlation of .007. True detectable correlation at power= .8 is ~0.3

```R
mxPowerSearch(m1, m2, n = 90)
Search X_with_Y:power relationship for n=90
X_with_Y     power     lower     upper              
0.00703   0.89          0.82       0.94
```

FYI, `pwr` implements plots we might want to emulate:

```R
tmp = pwr.r.test(n=90, power=.8)
plot(tmp)
```
![r power plot](https://user-images.githubusercontent.com/736156/63302644-911e1080-c2d5-11e9-9ad4-6e4a9add7637.png)

**Comment by tbates** [comment]
There's also, I think, something v.wrong with ncp searches now:

```R
mxPowerSearch(m1, m2, method="ncp")
N      power
0.043 0.816
```

What would an n of 0.043 be?

**Comment by mcneale** [comment]
Perhaps @tbates could offer some scripts with known results for testing?

**Comment by jpritikin** [comment]
> What would an n of 0.043 be?

That's 4.3% of the sample size given in m1.

**Comment by jpritikin** [comment]
> Comparing the free X~~Y m1 to X~~0*Y (zero correlation) (m2), mxPowerSearch now claims that with n= 90 we'd have 89% power to detect a correlation of .007. True detectable correlation at power= .8 is ~0.3

Sure, 90 times the sample size given in m1 is what? Pretty large?

**Comment by tbates** [comment]
**test empirical**
```R
# Make XY data with r = .3; model it, and build null m2
tmp = umx_make_raw_from_cov(matrix(c(1, .3,.3, 1), nrow=2),
    n=2000,  varNames= c("X", "Y"), empirical= TRUE
)
m1 = umxRAM("corXY", data = tmp, umxPath("X", with = "Y"), umxPath(var = c("X", "Y")))
m2 = umxModify(m1, "X_with_Y")

ps = mxPowerSearch(m1, m2, n = 90,probes=20)
      # X_with_Y     power     lower     upper
# 11 0.007073564 0.8363858 0.7668419 0.8882108

# test is beta @.8 is around .3
beta = ps[ps$power> .8 & ps$power<.85,"X_with_Y"]

abs(beta-.3) # should be near-zero

```

**test ncp**
```R
ncp = mxPowerSearch(m1, m2, method="ncp")
N = ncp[ncp$power> .8 & ncp$power<.83,"N"]

# test N is around 90
abs(N-90) # should be near-zero
```

_PS_: I note this only hits 1-core: might be possible to speed up with multi-core.

**Comment by tbates** [comment]
Oh... so n doesn't mean n, it means either multiple of Ns found in m1 or (as an output) % of m1 sample size.

I think people will expect it to mean n. Gets pretty error-prone to re-express a desired n to test in terms of a fraction of the n simulated?

**Comment by jpritikin** [comment]
> Oh... so n changed to multiple of Ns found in m1 or (as an output) % of m1 sample size.

Yes

> I think people will expect it to mean n. Will be error-prone to re-express a desired n in terms of a fraction of the n simulated?

As you pointed out, there could be different Ns in each group. So there isn't a single sample size.

I guess we could report sample size by group, but that could be a lot of Ns to report.

**Comment by tbates** [comment]
Hi Josh,
I think it's fine requesting and getting a single "total" n, knowing that it's up to the user to remember/see that this is divided into the groups in the model and in proportion to their size in trueModel.

The user had to build trueModel themselves, so they know exactly what ratio of subjects they put into each model.

**Comment by jpritikin** [comment]
> I think it's fine requesting and getting a single "total" n

Which one? What is there is no data is the container model?

**Comment by tbates** [comment]
If a model is built in the `container(top+submodels)` pattern that seems fine for an approach in which user sets n, no?

So if m1$submodels= c(top, mz, dz), the subject ratio is that found in mz and dz, and no subjects for either the `top` or `container` models, which makes sense, as they have no data.

I think too that any situation where n as "*% of total subjects in trueModel, to then be divided back into the submodels according to the proportions in each in trueModel*" made sense, also makes sense for `n` as "*total subjects, to be divided back into the submodels according to the proportions in each in trueModel*" Or am I misunderstanding?

**Comment by jpritikin** [comment]
Oh, so just report total N summing across all submodels?

**Comment by mcneale** [comment]
I think it would be better for the user experience to put in an n= in terms of number of subjects.  n= as a scaling by which to multiply the original N requires more thought.  That said, power search is effectively varying n to find places where power is at particular critical values -  or do I misunderstand its intent?

**Comment by tbates** [comment]
yes, report `n` as `sum(subjects in each submodel)`
When n is specified as an input, treat is as a total, to be apportioned among submodels, if any, as in `trueModel`.

In the case where the user didn't specify any data in `trueModel` (legit with `method = "empirical"`) and `length(submodels with data) > 1`,  we should `message("Polite note: As there were no data in your trueModel, n is assumed to be divided equally among the ", <N> " submodels")

**Comment by jpritikin** [comment]
OK, try v2.13.2-160-gcc9ad5d60

**Comment by tbates** [comment]
cool, will try when it builds

**Comment by mcneale** [comment]
I built & tried, it’s looking much better:

> # Make XY data with r = .3; model it, and build null m2
> tmp = umx_make_raw_from_cov(matrix(c(1, .3,.3, 1), nrow=2),
+     n=2000,  varNames= c("X", "Y"), empirical= TRUE
+ )
> m1 = umxRAM("corXY", data = tmp, umxPath("X", with = "Y"), umxPath(var = c("X", "Y")))
0 latent variables were created:. 
You have raw data, but no means model. I added
mxPath('one', to = manifestVars)
Running corXY with 5 parameters
?umxSummary std=T|F', digits, report= 'html', filter= 'NS' & more
Running Saturated corXY with 5 parameters
Running Independence corXY with 4 parameters


|name     | Estimate|    SE|
|:--------|--------:|-----:|
|X_with_X |    0.999| 0.032|
|X_with_Y |    0.300| 0.023|
|Y_with_Y |    0.999| 0.032|
|one_to_X |    0.000| 0.022|
|one_to_Y |    0.000| 0.022|
[1] "χ²(0) = 0, p = 1.000; CFI = 1; TLI = 1; RMSEA = 0"
> m2 = umxModify(m1, "X_with_Y")
Running corXY with 4 parameters
?umxSummary std=T|F', digits, report= 'html', filter= 'NS' & more
Running Saturated corXY with 5 parameters
Running Independence corXY with 4 parameters


|name     | Estimate|    SE|
|:--------|--------:|-----:|
|X_with_X |    0.999| 0.032|
|Y_with_Y |    0.999| 0.032|
|one_to_X |    0.000| 0.022|
|one_to_Y |    0.000| 0.022|
[1] "χ²(1) = 188.62, p < 0.001; CFI = 0; TLI = 0; RMSEA = 0.306"
TLI is worse than desired
RMSEA is worse than desired
> 
> ps = mxPowerSearch(m1, m2, n = 90,probes=20)
Search X_with_Y:power relationship for n=90
                                                         
>       # X_with_Y     power     lower     upper
> # 11 0.007073564 0.8363858 0.7668419 0.8882108
> 
> # test is beta @.8 is around .3
> beta = ps[ps$power> .8 & ps$power<.85,"X_with_Y"]
> 
> abs(beta-.3) # should be near-zero
[1] 0.0346952
> ncp = mxPowerSearch(m1, m2, method="ncp")
> N = ncp[ncp$power> .8 & ncp$power<.83,"N"]
> 
> # test N is around 90
> abs(N-90) # should be near-zero
[1] 3
> 
> ps
    X_with_Y     power      lower     upper
1  0.1203461 0.2689414 0.03510713 0.7881171
2  0.1417810 0.3236951 0.06721967 0.7606997
3  0.1632160 0.3837446 0.12104710 0.7379195
4  0.1846509 0.4475620 0.19691642 0.7280253
5  0.2060858 0.5131549 0.27544939 0.7450551
6  0.2275207 0.5782978 0.32334982 0.7973799
7  0.2489556 0.6408252 0.33121454 0.8653659
8  0.2703905 0.6989084 0.31415449 0.9216499
9  0.2918254 0.7512450 0.28581586 0.9579654
10 0.3132603 0.7971249 0.25347885 0.9784793
11 0.3346952 0.8363858 0.22082842 0.9892708
12 0.3561301 0.8692947 0.18978659 0.9947323
13 0.3775650 0.8964042 0.16134165 0.9974371
14 0.3989999 0.9184186 0.13593801 0.9987602
15 0.4204348 0.9360885 0.11368542 0.9994024
16 0.4418697 0.9501390 0.09448707 0.9997127
17 0.4633046 0.9612285 0.07812478 0.9998621
18 0.4847395 0.9699297 0.06431735 0.9999339
19 0.5061744 0.9767254 0.05276008 0.9999684
20 0.5276093 0.9820138 0.04315046 0.9999849

**Comment by tbates** [comment]
that looks good!

fyi, travis build is failing
Error NPSOL models/passing/fm-example2-2.R ***
[1] "`a` not equivalent to `b`.\n1/1 mismatches\n[1] 0.0123 - 0 == 0.0123"

**Comment by mcneale** [comment]
Travis fail seems to be something  to do  with gradients.  Maybe due to  Eigen changes?  There are lots of checks, so I'm not sure which one it is.  
<code>
omxCheckCloseEnough(max(abs(m2$output$gradient)), 0, .011)
</code>
seems possible as zero is one of the arguments.

**Comment by jpritikin** [comment]
@tbates @mcneale Yeah, `models/passing/fm-example2-2.R` is totally unrelated to these changes. Maybe the tolerance is too strict.

**Comment by mcneale** [comment]
@jpritikin However, _something_ related must have changed as it wasn't failing before.  Quite likely that the tolerance is too strict, imo.

**Comment by mcneale** [comment]
Incidentally, I can't reproduce the Travis failure on my  OS  X box  -  runs error free.   So it's system  specific - oh joy.
<code>
> source("~/git/openmx/inst/models/passing/fm-example2-2.R")
Running gm with 12 parameters
Running ex with 12 parameters
> mxVersion()
OpenMx version: 2.13.2.160 [GIT v2.13.2-160-gcc9ad5d6]
R version: R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 
MacOS: 10.13.6
Default optimizer: CSOLNP
NPSOL-enabled?: Yes
OpenMP-enabled?: Yes
</code>

**Comment by RMKirkpatrick** [comment]
I can't reproduce the failure of models/passing/fm-example2-2.R , either.

**Comment by tbates** [comment]
Perhaps pull `models/passing/fm-example2-2.R` into failing to get travis up.

And have the author (it's not attributed) have a look at it? (it's got comments about not getting SEs right, and TODOs etc. so likely needs a clean up?)

**Comment by mcneale** [comment]
I agree it would be nice to aid the graphical display of power analyses.  The pwr package example above is much prettier than this, but it's perhaps better than nothing to start.  Using the above example:
<code>
ggplot(ps, aes(x=ps$X_with_Y, y=ps$power)) +
  geom_line( color="red", size=.5, alpha=0.9) +
  theme_ipsum() +
  ggtitle("Statistical power to detect X_with_Y at alpha=.05")
</code>
