### ISSUE TITLE
How to just print model as pdf？how to import model into microsoft visio?

### ISSUE THREAD

**Issue by wanglu2014** [OpenMx/OpenMx#235]
Thank for your suggestion.

**Comment by mcneale** [comment]
You don’t say which operating system you are using, but I am guessing Windows, which I’ve not used for a delightful decade, in which case this might help:

1. Use mxPath statements (or umx) to build model
2. Use umx R package to plot.MxModel to plot(model, file=‘mydotfile.dot’)
3. Maybe use graphvizio to import dot file https://www.calvert.ch/graphvizio/ 
4. To print to pdf, I would hope that there’s a print to pdf file in Windows somewhere, it’s built into OS X almost as default.

**Comment by wanglu2014** [comment]
Thank you for your reply. However, using this code
plot(dcm.math.fit, file="mydotfile.dot") 
mydotfile.dot can not import in Graphvizio in visio (windows)
An error occurs: "port specifications not supported, sorry" It also appeared in other people.
https://www.calvert.ch/maurice/2010/05/11/graphvizio-a-graphviz-addin-for-visio/
Could you kindly share your advice?

**Comment by wanglu2014** [comment]
Both gz and dot file type were tried and failed with the same error.
[dot.zip](https://github.com/OpenMx/OpenMx/files/3584279/dot.zip)

**Comment by tbates** [comment]
Thanks for posting the graph files from `umx`

First, if you just want to view the sem diagram, out of the box, umx `plot(m1)` will display the model in your web browser.

There are some additional layout controls in plot now, to control splines, and group objects on the same level with `max`, `min` and `same`

If you want to edit the graphviz layout, you need a program that support the `dot` language. I thought Visio did this natively?

The files you posted are syntactically legal, and open fine in graphviz on MacOS.

If your plugin is needed, and is complaining about not supporting head notes, then you might try just removing the "headport"  commands from the file (it's just a text file: drop it onto your favorite text editor) and see if your plugin opens it then.

Here's how it renders for me in graphviz on Mac: It would be cleaner if you use `plot(m1, mean=F)` but be sure in that case to let users know the model has a means model as well.

![Screenshot 2019-09-06 15 57 28](https://user-images.githubusercontent.com/736156/64438626-57fce300-d0c0-11e9-902b-b4cf6f7cc76f.png)

**Comment by wanglu2014** [comment]
Your answer on deleting headport has solved the error smoothly. Thank you for your detailed suggestion!

**Comment by tbates** [comment]
glad that did it!
