### ISSUE TITLE
Could us apply sensitivity analysis to openmx(RAM style) model？

### ISSUE THREAD

**Issue by wanglu2014** [OpenMx/OpenMx#236]
Any tutorial or programming function is helpful.

**Comment by tbates** [comment]
you'll need to say more about what you want, but this doesn't feel like a code issue - post it on the [forums](https://openmx.ssri.psu.edu/forums/opensem-forums/general-sem-discussions) instead, with a link to a definition of what a sensitivity analysis is/what the model is.

**Comment by wanglu2014** [comment]
Thank for your suggestion~
