### ISSUE TITLE
Workaround recommended in #203 exposes new error.

### ISSUE THREAD

**Issue by bokov** [OpenMx/OpenMx#238]
> I don't have a file or directory called .R/Makevars
>
> Yeah, you need to create it. Try `mkdir $HOME/.R`
>
> Then `cp util/gcc7.conf $HOME/.R/Makevars`

_Originally posted by @jpritikin in https://github.com/OpenMx/OpenMx/issues/203#issuecomment-498041457_

I did as above (I am using gcc-5.5.0 on Ubuntu, so I copied gcc5.conf), after getting same error as OP above.  After that, when trying to install GitHub master I get a new error:

```
$/tmp; R CMD INSTALL OpenMx
* installing to library ‘/home/a/R/x86_64-pc-linux-gnu-library/3.4’
* installing *source* package ‘OpenMx’ ...
NOTE: ./.devmode exists; will enable extra compiler diagnostics
NOTE: ./configure is not an autoconf generated script.
Change default C/C++ compiler and default compile flags by editing ~/.R/Makevars
************ ************
WARNING: Cannot verify correct libnpsol.a version
sha1sum libnpsol.a => 76b086a3bf82fe28e95953df5049c3b441d76a3c
************ ************
** libs
make: *** No rule to make target `omxSymbolTable.h', needed by `Compute.o'.  Stop.
ERROR: compilation failed for package ‘OpenMx’
```

When I tried `install.packages()` I got hundreds of lines of errors, I can reproduce and send if you need that. When I tried `devtools::install_github('OpenMx/OpenMx')` I got the same error as when I tried it from the command line.

**Comment by jpritikin** [comment]
What are you trying to do?

**Comment by bokov** [comment]
Wow, you're fast! I was editing the post. :-)

I'm trying to install OpenMx so I can get the `codebook` package to install.

**Comment by jpritikin** [comment]
Try `make cran-install` instead of `R CMD INSTALL`

**Comment by bokov** [comment]
Uh oh. Did so and that revealed that my R version is behind. I'm on 3.4.4. I realize that the obvious next step is to upgrade R and try again.

I'm just wondering, though, which release number was the last one known to be compatible with 3.4.4? I tried 2.14.0 and 2.13.2, and got errors on both of them.

The reason I would like to use an older version of OpenMx (if this is even possible), rather than upgrade, is that I try to keep my own packages and course materials backwards compatible older versions of R so that I don't force my users/students to unexpectedly have to update half their whole toolchain just to try my package or script. 

I'll upgrade if need be, just figured it wouldn't hurt to ask.
Thanks again.

**Comment by jpritikin** [comment]
I use 3.6.1, but 3.5 should work too.

**Comment by RMKirkpatrick** [comment]
Per the OpenMx DESCRIPTION file, OpenMx requires R 3.1.0 or newer.  On my Windows laptop, I just checked that the most recent release of OpenMx installs and runs with R 3.1.1.

**Comment by jpritikin** [comment]
Reopen if you are still finding some problem.
