### ISSUE TITLE
Better error messages for mxGetExpected

### ISSUE THREAD

**Issue by mcneale** [OpenMx/OpenMx#242]
If you try to get expected for a submodel that isn't in the model, the  error message is unlikely to be understood by anyone other than an expert:

> mxGetExpected(xTarget[[1]]$fit$beween,'covariance',subname='other')
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘genericGetExpected’ for signature ‘"NULL"’

While I'm here, I note that 'means' and 'covariance' are inconsistent in their singular/plural senses, and that requesting 'mean' by mistake generates the cryptic output:

> mxGetExpected(xTarget[[1]]$fit,'mean')
list()

**Comment by RMKirkpatrick** [comment]
I was just using `mxGetExpected()` as well.  We should just partial-match the value of argument `component`.

> If you try to get expected for a submodel that isn't in the model, the error message is unlikely to be understood by anyone other than an expert:

What do you propose?  Check to see if `model` has length 0, and if so, give an error message specific to that case?

**Comment by jpritikin** [comment]
> I note that 'means' and 'covariance' are inconsistent in their singular/plural senses

Yeah, annoying. How about we accept `mean` and `means`?

> We should just partial-match the value of argument

I don't support this idea. It makes it harder to add new component names in the future.

**Comment by mcneale** [comment]
> What do you propose? Check to see if model has length 0, and if so, give an error message specific to that case?

Yes, how about "I'm terribly sorry, but I've hunted around in your model for the submodel name you requested, and I just could not find it.  Perhaps there was a typo in the model or subname arguments?"

**Comment by mcneale** [comment]
>I don't support this idea. It makes it harder to add new component names in the future.

How much harder?  And how so, exactly?

**Comment by jpritikin** [comment]
> >   I don't support this idea. It makes it harder to add new component names in the future.
>
> How much harder? And how so, exactly?

If I can write `mxGetExpected(model, "m")` then we can't easily add another component that begins with `m`.

**Comment by jpritikin** [comment]
> Yes, how about "I'm terribly sorry, but I've hunted around in your model for the submodel name you requested, and I just could not find it. Perhaps there was a typo in the model or subname arguments?" :+1: 

I love your error messages. Feel free to improve the message that I checked in.

**Comment by RMKirkpatrick** [comment]
If we accept "mean" and "means", then should we accept both "covariance" and "covariances" as well?

> Yes, how about "I'm terribly sorry, but I've hunted around in your model for the submodel name you requested, and I just could not find it. Perhaps there was a typo in the model or subname arguments?"

That only really makes sense in the present motivating case.  There are plenty of other reasons why the value of `model` might have zero length.

**Comment by mcneale** [comment]
Sure, but if we require "mean*" we have only reserved words beginning with mean, where we currently have "means" exclusively.    I would not be in favor of abbreviation, but allowing consistent singular/plural for means and covariances seems reasonable, just to smooth the user experience.  Not to mention a human-readable error that at least lists the legal options for that argument (which ought to be standard).
