### ISSUE TITLE
mxRun: let user know what parameter cropped up in the ... slot

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#245]
User reports umx model halting, but the stop text is from `mxRun`

> mxRun does not accept values for the '...' argument

There's no traceback() because mxRun just calls stop() when it sees things in `...` 

It would be helpful for `mxRun` to give feedback about what appeared in that slot.

PS: this error occurs on a machine running OpenMx 2.12.2 and R 3.5, but not on a machine running OpenMx 2.14.11  and R 3.6.1

I wonder if OpenMx 2.12 and above should require R 3.6? Or if something was fixed in OpenMx between 2.12 and 2.14?

perhaps some code similar to this to tell users the name of the bad parameter if provided, and the value offered up?

```R
tmp <- function(x, ...){
	garbageArguments <- list(...)
	if (length(garbageArguments) > 0) {
		garbageNames = names(garbageArguments)
		warning("the first parameter in ...  was ", omxQuotes(garbageNames[1]), 
			" with value: ", garbageArguments[garbageNames[1]])
		stop("mxRun does not accept values for the '...' argument")
	}
}
tmp(x, badArg = "oops")
```

> Error in tmp(x, badArg = "oops") : 
  mxRun does not accept values for the '...' argument
In addition: Warning message:
In tmp(x, badArg = "oops") :
  the first parameter in ...  was 'badArg' with value: oops
>

**Comment by mcneale** [comment]
​Hi Tim

It looks like we don’t know if it’s an R version thing or an OpenMx version thing.  Does the error occur with 2.14 when run on the earlier version of R?

I certainly agree that the error message should be as informative as possible re: exactly what the bad argument to mxRun was.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral GeneticsIPBG
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 MCV Richmond VA 23298-0126
Telephone: (804) 828-3369  Email: michael.neale@vcuhealth.org
________________________________

**Comment by RMKirkpatrick** [comment]
@tbates When I try `tmp(x, "oops")`, I get

> Error in tmp(x, "oops") : 
  mxRun does not accept values for the '...' argument
In addition: Warning message:
In tmp(x, "oops") : the first parameter in ...  was NULL with value: 

Maybe change the warning syntax to be 
```
warning("the first parameter in ...  was ", omxQuotes(garbageNames[1]), 
						" with value: ", garbageArguments[[1]])
```
instead.

**Comment by jpritikin** [comment]
Yeah, let's figure out a good error message and apply it globally. There are lots of functions that reject `...` arguments.

**Comment by mcneale** [comment]
This is excellent:
`> require(OpenMx)
> data(demoOneFactor)
> manifests <- names(demoOneFactor)
> latents <- c("G")
> factorModel <- mxModel("One Factor",
+       type="RAM",
+       manifestVars = manifests,
+       latentVars = latents,
+       mxPath(from=latents, to=manifests,values=0.8),
+       mxPath(from=manifests, arrows=2,values=1),
+       mxPath(from=latents, arrows=2,
+             free=FALSE, values=1.0),
+       mxData(cov(demoOneFactor), type="cov",
+             numObs=500))
> summary(factorModelFit <- mxRun(factorModel,data='bananas'))
Error: mxRun does not accept ... arguments. The first parameter in ... was named 'data' with value 'bananas'
`
