### ISSUE TITLE
bug in ordering of manifest variables with RAM-type models of cov data

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#247]
See https://openmx.ssri.psu.edu/node/4543 .

**Comment by jpritikin** [comment]
Yeah, I'm on it. @RMKirkpatrick, thanks for creating an issue.

**Comment by jpritikin** [comment]
D'oh, the data was permuted the opposite way. Fixed in v2.14.11-25-gcd9a95ca3
