### ISSUE TITLE
mxFactorScores bug with type="ML"

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#251]
This code (from Niels Waller) reveals an issue with `mxFactorScores` where it gives this error and stops:

> Error in res[, , 2] <- got[, paste0(names(coef(fit)), "SE")] :                  
>  incorrect number of subscripts

```R
library(fungible)
library(umx)

probMiss = rep(.1, 20)

out = fungible::simFA(Model = list(NFac = 5, NItemPerFac = 4, Model = "orthogonal"),
	Missing    = list(Missing = TRUE, Mechanism = "MCAR", MSProb = probMiss),
	MonteCarlo = list(NSamples = 1, SampleSize = 500, Raw = TRUE), Seed = 1
)

# =================
# = 1. Run an EFA =
# =================

perScales = out$Monte$MCData[[1]]
# Run factor analysis, extracting five common factors
faPers = umxEFA(name = "model", x = perScales, factors = 5, rotation = "none", return = "model")
umx_time(faPers)# EFA: 04 minutes & 10 secs

# might save this if you're working on the bug, which is below
save(faPers, file="faPers.rda");

# ========================================================
# = 2. Compute regression factor scores (encounter bug ) =
# ========================================================
faPerScores = mxFactorScores(model = faPers, type = "ML", minManifests = 10)
```
>Error in res[, , 2] <- got[, paste0(names(coef(fit)), "SE")] :                  
>  incorrect number of subscripts

```R
# Work-around: Runs fine with type = "Regression"
x = umxFactorScores(faPers, type = 'Regression', minManifests = 3) # takes 3 minutes
```

**Comment by tbates** [comment]
One issue is that `mxFactorScores` reads `wantSE` from defaults, but if that’s turned off, prints a message about SEs being off for this model, which isn’t right.
The second issue is that

```R
wantSE <- tolower(mxOption(NULL,"Standard Errors")) == "yes"
Perhaps it should be saying
wantSE <- tolower(mxOption(model = model, "Standard Errors")) == "yes"
```
 
The second issue is that some result-checking is needed on what “got” ended up with before this line:
 
> res[,,2] <- got[,paste0(names(coef(fit)), 'SE')]
 
Perhaps a check on fit$compute$steps$CP$log to see if it contains all the “coefSE” columns requested, then not try and access them if they were not created? Or should the columns exist by be NA?
 
 ```R
if (wantSE) {
	namesNeeded = paste0(names(coef(fit)), 'SE')
	namesFound = (namesNeeded %in% names(got))
	if (any(!namesFound)) {
		stop("Not all SEs appear to have been computed. Missing were:\n",  
		paste(namesNeeded[!namesFound], collapse = "; "),
		"You can turn off requesting SEs for this model so this isn't a dealbreaker
		for getting factor scores:\n",
		"mxOption(model,'Standard Errors')) == 'yes'")
	}else{
		res[,,2] <- got[,paste0(names(coef(fit)), 'SE')]
	}
}
```

**Comment by jpritikin** [comment]
This was fixed by v2.14.11-87-g6af1bf6fe, yes? I even added a line item in the NEWS.

**Comment by jpritikin** [comment]
Why wouldn't all the SEs be present? I don't want to add error checking for code paths that are impossible.

**Comment by tbates** [comment]
Great! As of  OpenMx version: 2.14.11.88 [GIT v2.14.11-88-ge18132e] it is fixed.
I tested at home and the error still appeared but maybe travis hadn't rebuilt a version containing the fix at that time.

```R
faPerScores = mxFactorScores(model = faPers, type = "ML", minManifests = 10)
Running FactorScoresEFA with 5 parameters
> 
```

**Comment by RMKirkpatrick** [comment]
> The second issue is that
```
wantSE <- tolower(mxOption(NULL,"Standard Errors")) == "yes"
Perhaps it should be saying
wantSE <- tolower(mxOption(model = model, "Standard Errors")) == "yes"
```
I think this part is still unresolved.  It seems to me that if the user has bothered to set the "Standard errors" option locally (i.e., to the given MxModel), then that should override the global value of that option.

**Comment by jpritikin** [comment]
Thanks Rob. I committed the proposed fix.

**Comment by tbates** [comment]
That commit looks good (and interesting to know that the models inherit default prefs even if the user didn't actively choose a setting):

```R
mxOption(NULL  , "Standard Errors")
[1] "Yes"
mxOption(faPers, "Standard Errors")
[1] "Yes"
```R
