### ISSUE TITLE
Algebraic RAM matrices

### ISSUE THREAD

**Issue by mcneale** [OpenMx/OpenMx#252]
From the help page I read:
"Expectation functions define the way that model expectations are calculated. The mxExpectationRAM calculates the expected covariance and means of a given MxData object given a RAM model. This model is defined by reticular action modeling (McArdle and McDonald, 1984). The 'A', 'S', and 'F' arguments must refer to MxMatrix objects with the associated properties of the A, S, and F matrices in the RAM modeling approach."

It would be useful if A, S and M matrices could be mxAlgebras rather than mxMatrices.  Then paths could be, e.g, functions of parameters.

**Comment by mcneale** [comment]
Um the counterexample is the documentation, where it says more than once that the objects have to be mxMatrix() with no mention of mxAlgebra():
 'A', 'S', and 'F' arguments must refer to MxMatrix objects...
The MxMatrix objects included as arguments may be of any type, but should have the properties described above

**Comment by tbates** [comment]
That could be useful! Would need algebras to support label (#128), lbound, ubound, and free layers
?

**Comment by jpritikin** [comment]
> Would need algebras to support label (#128), lbound, ubound, and free layers

Is that relevant to this issue? Please open a separate issue.

**Comment by RMKirkpatrick** [comment]
@mcneale Have you tried providing an MxAlgebra for one of those 3 matrices?  Because if that works, then this is only an issue with the documentation.

**Comment by tbates** [comment]
it "runs"

```R
mtcars$litres = mtcars$disp/61.02
m1 = umxRAM("test", data = mtcars,
 	umxPath(c("wt", "litres"), to = "mpg"),
 	umxPath("wt", with = "litres"),
 	umxPath(v.m. = c("wt", "litres", "mpg"))
 )

m1$A = mxAlgebra(Asrc, name= "A")
m1$Asrc$name="Asrc"
m1$A=null
m1$A = mxAlgebra(Asrc, name= "A")
m2 = mxRun(m1)
Running test with 9 parameters
```

But of course the model A matrix in this example now lacks labels, bounds, any ability to fix or free values, and breaks attempts to set these. Also lacks values slot (algebras have result).

Does that support the use-case you had in mind Mike?

**Comment by mcneale** [comment]
Yep, my example works too... I know we undersell OpenMx features a lot, but documentation that does so is something that shouldn't be hard to fix.

**Comment by mcneale** [comment]
@tbates - there never should be a way to free an algebra element.  Labels for columns/rows/elements could be useful.

I have never liked the different slot names for the numerical values of algebras and matrices.  It frustrates interactive use and makes general higher level programming (ala umx or anything) more challenging.  As in, it's a PITA.
