### ISSUE TITLE
Standard errors depend upon number of threads

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#254]
[4x4--biometrical--Nov2019--noSStwins.R.txt](https://github.com/OpenMx/OpenMx/files/3880485/4x4--biometrical--Nov2019--noSStwins.R.txt)

See the attached script.  Per my 11/20/19 email, the standard errors are different depending upon whether the script is run with 1 or 2 threads.  The discrepancy is especially pronounced in the `summary()` output of `run1`, where with 1 thread some of the standard errors are greater by an order of magnitude than with 2 threads.  I strongly suspect that the SEs calculated with 2 threads are correct, since (1) this script analyzes correlation matrices calculated from a sample of more than 80,000 families, meaning the SEs should be small; and (2) we have a test script, models/passing/multinomSE.R , in which OpenMx's calculation of the sampling covariance matrix fails to match the analytically correct result when using a single thread.

**Comment by RMKirkpatrick** [comment]
This issue appears to be specific to cases involving MxConstraints.

**Comment by jpritikin** [comment]
MxConstraints, hm! As a stopgap, we can disable threads when MxConstraints are present?

**Comment by mcneale** [comment]
Disable standard errors would be less performance debilitating, if the estimates are ok.  Might be a difficult debug but somewhat high priority.

**Comment by jpritikin** [comment]
> I strongly suspect that the SEs calculated with 2 threads are correct,

Whoa, I thought I misread this. So you're saying that it works better with more than 1 thread?

**Comment by jpritikin** [comment]
Looks like `omxCalcFinalConstraintJacobian` does not restore the `fc->est` parameter vector in the single thread case. Looks like the last parameter has been incremented by some offset. Want to fix it?

**Comment by jpritikin** [comment]
Rob, I trust you will look into this? It seems to be your code.

**Comment by RMKirkpatrick** [comment]
> @RMKirkpatrick , I trust you will look into this? It seems to be your code.

Yes, will do.

**Comment by tbates** [comment]
Be good to add a test script checking that SE1thread == SE2thread to make sure we don't have a release where SEs are off for all 1-thread or multithread users.

**Comment by jpritikin** [comment]
@tbates In theory, sure. In practice, we'd have to run every test twice and check whether everything is equal, conditional on the use of threads. It would be a big project.

**Comment by RMKirkpatrick** [comment]
@jpritikin Once this issue is resolved, then at minimum we should have a regression test for it.

**Comment by jpritikin** [comment]
> Once this issue is resolved, then at minimum we should have a regression test for it.

Sure, I'm just pushing back against the idea that we can have a regression test for everything imaginable. I mean, it would be nice, but without funding, it's an annoying suggestion.

**Comment by mcneale** [comment]
The doubt expressed in "it seems to be your code" makes me think that there should be more explicit credit given to code authors, so that we can trace who did what without, e.g.,  a load of binary searches through the repository.  As the team grows, this will become more important.

**Comment by jpritikin** [comment]
> The doubt expressed in "it seems to be your code"
@mcneale The authorship of the code is not in question. GIT can unambiguously tell us that @RMKirkpatrick  wrote `omxCalcFinalConstraintJacobian`. I expressed doubt because the location of the bug is not yet precisely known. It seems to be within `omxCalcFinalConstraintJacobian`, but we won't know for sure until it's fixed.

**Comment by mcneale** [comment]
@jpritikin Fair point - tbh I'm just grumbling about the shortage of comments in the code.  A few notes here and there about _what_ is being done and _why_ can help tremendously in future.  I know, I know, coding comes before documenting... and I broadly support that perspective in the short term.  The longer term is another matter.

**Comment by RMKirkpatrick** [comment]
> Looks like `omxCalcFinalConstraintJacobian` does not restore the `fc->est` parameter vector in the single thread case. Looks like the last parameter has been incremented by some offset. Want to fix it? Try this around line 400:
> 
> ```
> 	if(c_n){
> 		fc->log(FF_COMPUTE_ESTIMATE);
> 		omxCalcFinalConstraintJacobian(fc, numParams);
> 		fc->log(FF_COMPUTE_ESTIMATE);
> 	}
> ```

I tried that, and I changed the step size on line 357 of src/omxHessianCalculation.cpp to 1e-4.  I can see from the printing that the last free parameter is indeed being shifted by an offset, with both 1 thread _and_ with 2 threads.  With 1 thread and the larger offset, the SEs are smaller than they should be.  But, with 2 threads and the larger offset, they match what I get with the default step size of 1e-7.  So, there's something else going on that's affect by multithreading.

**Comment by jpritikin** [comment]
> with both 1 thread and with 2 threads

@RMKirkpatrick  My recollection from a week ago, when I looked at this code, is that the failure to restore the last parameter to it's correct location doesn't matter when there is more than 1 thread because that value isn't used in subsequent calculations. It does screw up subsequent calculations in the single threaded case.

> So, there's something else going on that's affected by multithreading.

Yes, that is possible. There is often more than 1 bug wrecking havoc, but the failure to restore the parameter vector is the bug we know about. Let's fix that first.

**Comment by RMKirkpatrick** [comment]
> There is often more than 1 bug wrecking havoc, but the failure to restore the parameter vector is the bug we know about. Let's fix that first.

I believe I just did, with f43f300 .  I'm recompiling with ATLAS on my laptop right now.

**Comment by jpritikin** [comment]
@RMKirkpatrick That's not a really great fix. `setEstFromOptimizer` updates all the parameters in the model. It could take a long time if there are many parameters. If you look at `src/finiteDifferences.h`, you can see how I've taken care to restore only the 1 or 2 parameters that are actually changed. I guess your fix is good enough for now, but I'm not very happy about your approach.

**Comment by RMKirkpatrick** [comment]
@jpritikin You're welcome to suggest a better fix.  Where in src/finiteDifferences.h in particular should I be looking?  For that matter, why doesn't the finite-differences subroutine for jacobians reset each parameter as needed?

**Comment by RMKirkpatrick** [comment]
At any rate, the commit I pushed resolves the bug that SEs are wrong when OpenMx is single-threaded.

**Comment by jpritikin** [comment]
> For that matter, why doesn't the finite-differences subroutine for jacobians reset each parameter as needed?

It does. That's what makes me think that you have something mucked up.

**Comment by RMKirkpatrick** [comment]
> It does. That's what makes me think that you have something mucked up.

I see.  Maybe I'm misusing the API someplace.

> Do you obtain exactly the same vcov matrix regardless of the number of threads? It really should match to 1e-9 at least.

Yes.

**Comment by jpritikin** [comment]
> Maybe I'm misusing the API someplace.

Maybe you're passing two views that are backed by the same memory when it should be backed by different memory. I'm not sure. That's just a guess.

> Yes.

Well, that's reassuring.

**Comment by RMKirkpatrick** [comment]
I'll have to take a closer look into my code to figure out why this bug existed in the first place, and figure out a better fix.

**Comment by RMKirkpatrick** [comment]
I looked into this issue again today, and I still can't figure out what the problem is.  I think I'm going to have to walk through the code under a debugger.

**Comment by RMKirkpatrick** [comment]
I spent some time today wading through the relevant backend code under gdb.  The relevant code, starting at line 216 of src/finiteDifferences :
```
struct central_difference_jacobi {
	template <typename T1, typename T2, typename T3, typename T4>
	void operator()(T1 ff, Eigen::MatrixBase<T4> &refFit, Eigen::MatrixBase<T2> &point,
			double offset, int px, int numIter, Eigen::MatrixBase<T3> &Gaprox)
	{
		double orig = point[px];
		Eigen::MatrixXd result1(refFit.rows(), refFit.cols());
		Eigen::MatrixXd result2(refFit.rows(), refFit.cols());
		for(int k = 0; k < numIter; k++) {
			point[px] = orig + offset;
			ff(point, result1);
			point[px] = orig - offset;
			ff(point, result2);
			Eigen::Map<Eigen::MatrixXd> Gaprox1(&Gaprox.coeffRef(0,k), refFit.rows(), refFit.cols());
			Gaprox1 = (result1 - result2) / (2.0 * offset);
			offset *= .5;
		}
		point[px] = orig;
	}
};
```
This code does indeed store the optimum (e.g., MLE) value of the current parameter w/r/t which the constraint functions are currently being differentiated (`double orig = point[px];`), and restore the optimum value at the end (`point[px] = orig;`).  The problem is that each `ff()` call invokes the `allconstraints_functional` 2-argument operator, which in turn copies `point` into the FitContext's `est` array, via `fc.setEstFromOptimizer()`.  At the end of this codeblock, the optimum parameter values have been restored to `point`, but the offset value is still in the FitContext.  For every parameter except the last, the first call to `ff()` will restore to the FitContext the optimum value of the previous parameter for which this codeblock was run.  But, for the last parameter, the offset value will still remain in the FitContext.  With a9cedab , the optimum value of the last parameter is restored before the numerical calculation of the gradient and Hessian begin.

If there are no objections, this issue can be closed.

**Comment by jpritikin** [comment]
That doesn't sound like an explanation. If I was going to research the issue, I'd turn on enough logging to get a detailed trace of what each thread is doing (DEBUGMX, maybe DEBUGMX_ALGEBRA) and look for the first difference. Changing how many threads are running should not affect the results.

**Comment by jpritikin** [comment]
Okay, I read your report again. Are you saying that `fc->est` is being reused twice?

**Comment by RMKirkpatrick** [comment]
@jpritikin Thanks for the clarification in 78ebc43 .
