### ISSUE TITLE
Inscrutable error message when requesting CIs for something nonexistent in namespace

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#266]
[See here](https://openmx.ssri.psu.edu/comment/8660#comment-8660).  Briefly summarized, a user's `mxCI()` statement requested CIs for a matrix or algebra that was not actually in the model, which raised an error with an inscrutable and thoroughly unhelpful message.  It looks like we need to somehow catch that kind of user blunder, and give an appropriate error message.

**Comment by jpritikin** [comment]
If I try, here's what I get,

```
Error in eval(result, envir = env) : object 'Q' not found
Calls: mxRun ... eval -> eval -> mxEval -> EvalInternal -> eval -> eval

 Error in eval(result, envir = env) : object 'Q' not found 
11.
eval(result, envir = env) 
10.
eval(result, envir = env) at MxEval.R#57
9.
EvalInternal(expression, model, modelvariable, compute, show, 
    defvar.row, cache, cacheBack, 2L) at MxEval.R#25
8.
mxEval(Q, flatModel, compute = TRUE) 
7.
eval(substitute(mxEval(x, flatModel, compute = TRUE), list(x = as.symbol(entityName)))) 
6.
eval(substitute(mxEval(x, flatModel, compute = TRUE), list(x = as.symbol(entityName)))) at MxInterval.R#206
5.
FUN(X[[i]], ...) 
4.
lapply(flatModel@intervals, generateIntervalListHelper, flatModel, 
    modelname, parameters, labelsData) at MxInterval.R#144
3.
generateIntervalList(flatModel, model@name, parameters, labelsData) at MxRun.R#201
```

Why is "object 'Q' not found" a bad error message?

**Comment by RMKirkpatrick** [comment]
> Why is "object 'Q' not found" a bad error message?

I'd say it's a fine error message, but this is the message the user reported in their OP:
```
Error in as.vector(data) : 
  no method for coercing this S4 class to a vector
```
@jpritikin , what is the script you used to get that error message and traceback?  I ask because there are two details about the user's script that may be relevant here.  First, their script requests CIs for specific elements of the nonexistent object, e.g. "SD[1,1]".  Second, their script does create an object with R symbol `SD` in R's workspace (but not in the MxModel's namespace).

**Comment by jpritikin** [comment]
Ah, OK. We can catch that specific case.
