### ISSUE TITLE
povRAM.cpp:218:42:   required from here

### ISSUE THREAD

**Issue by j4jes** [OpenMx/OpenMx#267]
Ive been trying desperately to install OpenMx via install.packages("OpenMx") and Bioconductor inside R3.6.1 and R3.6.2. I'm using scl enable devtoolset-8 to get GCC8 compiler and I have set my CXX14 flags accordingly inside Makevars / Makeconf:

```
CXX14 = g++ -std=c++1y
CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -fPIC
CXX14FLAGS+=-flto -Wno-unused-local-typedefs
```
and the compilation always ends with:

```
 al::Assignment<DstXprType, Eigen::Solve<DecType, RhsType>, Eigen::internal::assign_op<Scalar, Scalar>, Eigen::internal::Spar  se2Sparse>::run(DstXprType&, const SrcXprType&, const Eigen::internal::assign_op<Scalar, Scalar>&) [with DstXprType = Eigen:  :SparseMatrix<double>; DecType = Eigen::SparseLU<Eigen::SparseMatrix<double>, Eigen::COLAMDOrdering<int> >; RhsType = Eigen:  :SparseMatrix<double>; Scalar = double; Eigen::internal::Assignment<DstXprType, Eigen::Solve<DecType, RhsType>, Eigen::inter  nal::assign_op<Scalar, Scalar>, Eigen::internal::Sparse2Sparse>::SrcXprType = Eigen::Solve<Eigen::SparseLU<Eigen::SparseMatr  ix<double>, Eigen::COLAMDOrdering<int> >, Eigen::SparseMatrix<double> >]’
/data1/apps/Rlibrary/RcppEigen/include/Eigen/src/SparseCore/SparseAssign.h:38:16:   required from ‘Derived& Eigen::SparseMat  rixBase<Derived>::operator=(const Eigen::SparseMatrixBase<OtherDerived>&) [with OtherDerived = Eigen::Solve<Eigen::SparseLU<  Eigen::SparseMatrix<double>, Eigen::COLAMDOrdering<int> >, Eigen::SparseMatrix<double> >; Derived = Eigen::SparseMatrix<doub  le>]’
/data1/apps/Rlibrary/RcppEigen/include/Eigen/src/SparseCore/SparseMatrix.h:1124:27:   required from ‘Eigen::SparseMatrix<_Sc  alar, _Options, _StorageIndex>& Eigen::SparseMatrix<_Scalar, _Flags, _StorageIndex>::operator=(const Eigen::SparseMatrixBase  <OtherDerived>&) [with OtherDerived = Eigen::Solve<Eigen::SparseLU<Eigen::SparseMatrix<double>, Eigen::COLAMDOrdering<int> >  , Eigen::SparseMatrix<double> >; _Scalar = double; int _Options = 0; _StorageIndex = int]’
povRAM.cpp:218:42:   required from here
/data1/apps/Rlibrary/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:960:8: warning: ignoring attributes on template argum  ent ‘Eigen::internal::packet_traits<double>::type {aka __vector(4) double}’ [-Wignored-attributes]
make: *** [povRAM.o] Error 1
ERROR: compilation failed for package ‘OpenMx’
* removing ‘/data1/apps/Rlibrary/OpenMx’
```

I need this library as a dependency for a few other libraries. Thanks!

**Comment by jpritikin** [comment]
The last few lines you posted are warnings. The real error happened earlier. Can you attach a complete log of the failure?

**Comment by RMKirkpatrick** [comment]
Just a guess, but how up-to-date is your installation of RcppEigen?

**Comment by j4jes** [comment]
https://pastebin.com/H6SL9Q5E

**Comment by j4jes** [comment]
I just reinstalled RcppEigen now, so going to try again :


> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /data1/apps/R/3.6.1/lib64/R/lib/libopenblas.so.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] RcppEigen_0.3.3.7.0

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_3.6.1      Matrix_1.2-18
[4] tools_3.6.1         Rcpp_1.0.3          grid_3.6.1
[7] lattice_0.20-38

**Comment by j4jes** [comment]
hmm just tried this on two different Centos7 servers with same results. I reinstalled libraries Rcpp, RcppEigen, StanHeaders, but still returns the exact same as before. Looking at the output, which does not fit entirely in my scrollback buffer, I am seeing many informational warning but where the exact error is, is not clear.

**Comment by jpritikin** [comment]
Yeah, the pastebin thing is incomplete and useless. Redirect the output to a file so you don't have to rely on the scrollback buffer.

**Comment by j4jes** [comment]
I think I got something relevant. I did the following:

```
/share/bin/R --vanilla --slave -e "install.packages('OpenMx', repo='http://cran.r-project.org')" > R.out 2>&1
jstacey@cortex:~ $ grep error R.out
povRAM.cpp:150:3: error: ‘typeof’ was not declared in this scope
povRAM.cpp:153:4: error: ‘curProd’ was not declared in this scope
```

Do let me know if you still need the entire R.out

**Comment by jpritikin** [comment]
Maybe you didn't pass `-std=gnu++14` to the compiler? This needs to be in your R's Makevars.

**Comment by j4jes** [comment]
http://www.meaney.lab.mcgill.ca/R.out

**Comment by jpritikin** [comment]
Yeah `-std=c++1y` doesn't cut it. You gotta go to `gnu++14` or better.

**Comment by jpritikin** [comment]
See https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Customizing-package-compilation

**Comment by j4jes** [comment]
new error. Missing rpm's ?

```
ate.o omxStateSpaceExpectation.o omxSymbolTable.o omxWLSFitFunction.o optimize.o options.o povRAM.o sadmvn.o slsqp.o ssMLFit.o stop.o -fopenmp -lopenblas -lgfortran -lm -lquadmath -lgfortran -lm -lquadmath -L/share/apps/R/3.6.1/lib64/R/lib -lR
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lgfortran
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lquadmath
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lgfortran
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lquadmath
collect2: error: ld returned 1 exit status
make: *** [OpenMx.so] Error 1
ERROR: compilation failed for package ‘OpenMx’
* removing ‘/data1/apps/Rlibrary/OpenMx’
```

**Comment by jpritikin** [comment]
> Missing rpm's

Yes, seems likely

**Comment by mcneale** [comment]
FORTRAN & quadmath libraries, it seems, see perhaps
https://rpmfind.net/linux/RPM/Development_Languages_Fortran.html

**Comment by RMKirkpatrick** [comment]
Slightly off-topic, but it just occurred to me that if we require GNU extensions beyond the C++ Standard, that might explain why I had no luck building OpenMx with the Intel compiler.

**Comment by j4jes** [comment]
alright so as I am using centos7 I was using scl to get the newer GCC but I must also use the SCL package that includes gfortan and libquadmath

yum install devtoolset-8-gcc-gfortran.x86_64
scl enable devtoolset-8 bash

Then I get a new error from install.packages "... can not be used when making a shared object; recompile with -fPIC"

https://pastebin.com/5U1m2yPc

**Comment by jpritikin** [comment]
Yeah, so follow the instructions. Add `-fPIC` to C++FLAGS and LDFLAGS

**Comment by mcneale** [comment]
make clean may help too: 
https://stackoverflow.com/questions/40678423/final-link-failed-nonrepresentable-section-on-output-collect2-error-ld-return

I'm not sure why -fPIC isn't a compiler flag we set by default.  Seems to be on OS X systems though nothing in my Makevars mentions it.

**Comment by j4jes** [comment]
For administrators that recompile R with every new release, there is a Makeconf file in the lib64/R/etc that has these flags, but then I suppose they could be overridden if I placed a ~/.R/Makevars inside /etc/skel/ or something like that. This would only ensure new users have the preferred CFLAGS. It's frustrating these flags need to be respecified with every R install. Maybe I can just export the flags as variables in the bashrc_global that I get everyone to source at login.


```
jstacey@cerebra:/share/apps/R/3.5.3/lib64/R/etc $ cat Makeconf
# etc/Makeconf.  Generated from Makeconf.in by configure.
#
# ${R_HOME}/etc/Makeconf
#
# R was configured using the following call
# (not including env. vars and site configuration)
# configure  '--prefix=/opt/R/3.5.3' '--enable-R-shlib' '--with-blas' '--with-lapack'

## This fails if it contains spaces, or if it is quoted
include $(R_SHARE_DIR)/make/vars.mk

AR = ar
BLAS_LIBS = -L"$(R_HOME)/lib$(R_ARCH)" -lRblas
C_VISIBILITY = -fvisibility=hidden
CC = gcc -std=gnu99
CFLAGS = -g -O2 $(LTO)
CPICFLAGS = -fpic
CPPFLAGS = -I/usr/local/include
CXX = g++
CXXCPP = $(CXX) -E
CXXFLAGS = -g -O2 $(LTO)
CXXPICFLAGS = -fpic
CXX98 = g++
CXX98FLAGS = -g -O2
CXX98PICFLAGS = -fpic
CXX98STD = -std=gnu++98
CXX11 = g++
CXX11FLAGS = -g -O2
CXX11PICFLAGS = -fpic
CXX11STD = -std=gnu++11
CXX14 =
CXX14FLAGS =
CXX14PICFLAGS =
CXX14STD =
CXX17 =
CXX17FLAGS =
CXX17PICFLAGS =
CXX17STD =
CXX_VISIBILITY = -fvisibility=hidden
## NB, set FC before F77 as on Solaris make, setting FC sets F77
## FC is the compiler used for free-form Fortran, exts .f90/.f95
FC = gfortran
FCFLAGS = -g -O2 $(LTO)
```

**Comment by jpritikin** [comment]
Yeah. So is your problem solved?

**Comment by jpritikin** [comment]
Great to hear!
