### ISSUE TITLE
Ignorable code 5 with active box constraints

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#273]
In the attached script, with SLSQP or NPSOL, `factorModel2` gets a warning about status code 5, but one of its free parameters is at its lower bound at the solution.  `factorModel3` shows that it's the post-optimization check on the Hessian that is producing the code 5, and that the optimizer believes it has found a solution.  `factorModel4` shows that the solution is the correct one when the free parameter in question is fixed to its lower-bound value, and there is no warning.

In other words, the Hessian at a local minimum can be non-PD if there are active bounds.  I suggest either of two remedies to this issue.  One is to give the user a message saying that the warning about status Red may be spurious when there are active bounds, if such is the case.  The other is for the post-optimization PD-Hessian check to only check the Hessian w/r/t the free parameters for which no bounds are active at the solution.

[200211--active_bounds.R.txt](https://github.com/OpenMx/OpenMx/files/4320286/200211--active_bounds.R.txt)

**Comment by mcneale** [comment]
It seems that we should check for active bounds if a code 5 or 6 is found, and only issue this note if a bound is seen to be active, right?

**Comment by RMKirkpatrick** [comment]
> It seems that we should check for active bounds if a code 5 or 6 is found, and only issue this note if a bound is seen to be active, right?

Yes, that's what I had in mind.

**Comment by jpritikin** [comment]
Similar to src/omxHessianCalculation.cpp line 508 ?

**Comment by RMKirkpatrick** [comment]
It looks like we do have safeguards against this issue causing a spurious status 6, but as my script in the OP demonstrates, we do not have safeguards against spurious status 5.

**Comment by RMKirkpatrick** [comment]
I think we'll be able to close this issue soon, maybe even now.  As of fb69fe4, `mxTryHard*()` no longer reports code 5 due to active box constraints.  As of 0ce7e98, the MxComputeHessianQuality backend no longer reports code 5 due to active box constraints.  Three subsequent commits add and update tests in light of this new behavior.

Recall that these are "spurious" code 5s because the optimizer has indeed reached a local minimum, but one or more active bounds make the Hessian non-PD at the solution.  The resolution is to drop the rows and columns of the Hessian that correspond to parameters with active bounds, and assess the eigenvalues of the "filtered" Hessian to determine if second-order optimality conditions are met.

I can think of only two outstanding points on this matter.  One is that parts of my new test script condition on which optimizer is in use, and I am not sure why the results are not the same for all 3 optimizers, since the new behavior is in the ComputeHessianQuality step, not the ComputeGradientDescent step.  The other is that standard errors are not currently corrected for active bounds (and the non-PD status of the Hessian can make some of them `NA`), but that seems to be a separate issue for a new issue thread.

**Comment by RMKirkpatrick** [comment]
> One is that parts of my new test script condition on which optimizer is in use, and I am not sure why the results are not the same for all 3 optimizers

Benign edge case, revealed by use of a specific custom compute plan.  The backend only writes to the 'infoDefinite' element of the MxModel's output slot if `fc->wanted & (FF_COMPUTE_HESSIAN | FF_COMPUTE_IHESSIAN)` is nonzero, and the SLSQP-specific block of `omxComputeGD::computeImpl()` never flips the relevant bits in `fc->wanted`.
