### ISSUE TITLE
model$matrix$name="x" should fail with error 

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#276]
```R
m1 = mxModel("test", mxMatrix("Full", 1, 1, name="old"))

# update name (fails silently)
m1$old$name = "this_fails"

# Old matrix is unchanged:
m1$old$name # "old"

```

EXPECTED: EITHER: name change fails with error “you can’t change the name of matrices within a model. Use mxModel(remove=TRUE) and then add a new matrix with the name you want"

OR, the matrix is replaced with one with the new name, so in the example, this would not be NULL

**Comment by RMKirkpatrick** [comment]
This is trickier than I initially thought.  It's not just a matter of adjusting the `$<-` method for MxMatrices; it's also a matter of the MxModel namespace.

Interestingly, this ugly code actually does work:
```
m1 <- mxModel("test", mxMatrix("Full", 1, 1, name="old"))
names(m1@matrices) <- "not_old"
m1$not_old$name <- "not_old"
m1$not_old$name
m1$not_old
```

**Comment by RMKirkpatrick** [comment]
I took another look at this issue today.  First of all, the `$<-` methods defined for different OpenMx objects use a lot of the same `imx*` functions in a way that's agnostic as to what the object's class is, as long as it has slots.  I don't think it's wise to try to modify those functions to special-case the 'name' slot of MxMatrices.

Second of all, it doesn't seem possible to condition the behavior of `$<-` for MxMatrices on whether or not the matrix is in an MxModel object or not.  I thought it might work for the `$<-` method for MxMatrices to behave according to its parent and grandparent environments.  However, nested use of the `$` accessor/mutator don't work that way.  In both of these lines of code, the MxMatrix `$<-` is considered to have been called from the global environment:
```
om <- mxMatrix("Full", 1, 1, name="old"); om$name <- "not_old"
m1 <- mxModel("test", mxMatrix("Full", 1, 1, name="old")); m1$old$name <- "this_fails"
```

There is a workaround for this issue:
```
m1 <- mxModel("test", mxMatrix("Full", 1, 1, name="old"))
names(m1@matrices)[1] <- "not_old"
m1$not_old$name <- "not_old"
m1$not_old$name
m1$not_old
```
So, I'm going to close it.

**Comment by tbates** [comment]
thanks for looking into this!
