### ISSUE TITLE
mxTryHard does not perserve wls relavent information in model$output

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#277]
What output info do you need to exclude? Maybe you can copy everything and replace/remove the other stuff?

**Comment by RMKirkpatrick** [comment]
I think this issue is resolved with 03b29e4 .  At least, the bug is no longer apparent when I run the code that first led me to discover it.  I don't yet know if my breaks something else.

**Comment by jpritikin** [comment]
Looks good to me

**Comment by RMKirkpatrick** [comment]
My change didn't appear to break anything during the nightly run.
