### ISSUE TITLE
In version 2.17.3 mxRun(wlsTest4) did not throw an error on armhf running Ubuntu 20.10

### ISSUE THREAD

**Issue by rbalint** [OpenMx/OpenMx#278]
Other architectures run the tests fine, but armhf started failing:

http://autopkgtest.ubuntu.com/packages/r/r-cran-openmx/groovy/armhf

I suspect this is an accuracy issue, but have not fully triaged the problem.

From https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-groovy/groovy/armhf/r/r-cran-openmx/20200617_131354_6b10a@/log.gz :

```
...
> library(testthat)
> library(OpenMx)
To take full advantage of multiple cores, use:
  mxOption(key='Number of Threads', value=parallel::detectCores()) #now
  Sys.setenv(OMP_NUM_THREADS=parallel::detectCores()) #before library(OpenMx)
> 
> test_check("OpenMx")
── 1. Failure: (unknown) (@test-wls-binary.R#43)  ──────────────────────────────
`mxRun(wlsTest4)` did not throw an error.

Error: testthat unit tests failed
══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 567 | SKIPPED: 4 | WARNINGS: 0 | FAILED: 1 ]
1. Failure: (unknown) (@test-wls-binary.R#43) 
...
```

**Comment by rbalint** [comment]
This is probably just https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962794 , will reopen if not.

**Comment by rbalint** [comment]
Apparently it is not just due to broken r-cran-stanheaders, fixing it in Ubuntu did not make r-cran-openmx armhf error go away.

**Comment by jpritikin** [comment]
Yeah, I think you're probably right. The check is on omxData.cpp line 3207
````
					if (fabs(fabs(innerCor(rx,cx)) - 1.0) > 1e-6) continue;
````

If you change that to `1e-5` then what happens?

**Comment by rbalint** [comment]
Still failing :-(

**Comment by jpritikin** [comment]
OK, try `1e-4`?

**Comment by rbalint** [comment]
Still passing :-\

**Comment by rbalint** [comment]
(I mean failing the same way)

**Comment by jpritikin** [comment]
Let's just skip that test on arm. It's not very important. It just provides diagnostic info to the user.

What condition can we use in `skip_if`?

**Comment by rbalint** [comment]
In 2.18.1 this seems to be fixed

**Comment by jpritikin** [comment]
Wow, great news! I wonder what changed?
