### ISSUE TITLE
error instead of warn when LISREL means unavailable

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#28]
This is currently a warning, `Means requested, but model has no means.
     Add appropriate TX, TY, KA, and/or KA matrices to get real means.`

It should probably be an error, but there is some other code that would need some slight reorganization to make this change.

**Comment by mhunter1** [comment]
I think a warning is fine, but am willing to change it to an error.

I could just add right before returning a check  of any of the elements of `ret` having length zero or dimension zero.  Add an error message like
```
stop(paste('Requested component', acomp, "had dimension or length 0. Requested component not in model.  All I have is yours, but I ain't got no", acomp))
```

**Comment by mhunter1** [comment]
@jpritikin Bump

**Comment by jpritikin** [comment]
Sounds good to me. Are you saying that I should make the change?

**Comment by mhunter1** [comment]
@jpritikin  No.  You opened the issue, so I wanted to make sure this satisfied you as a solution.  I'll make the fix.
