### ISSUE TITLE
omxReadGRMBin

### ISSUE THREAD

**Issue by dleopold** [OpenMx/OpenMx#280]
I believe there is an error in the function `omxReadGRMBin()`. In the function the line:

`GRM <- matrix(0, nrow = N, ncol = N, dimnames = list(id$V1 + id$V2, id$V1 + id$V2))`

should be:

`GRM <- matrix(0, nrow = n, ncol = n, dimnames = list(id$V1 + id$V2, id$V1 + id$V2))`

**Comment by RMKirkpatrick** [comment]
You are correct.  See dcfc6f9 .  Thanks for the bug report!

If you need a workaround until the next release, you can use `omxReadGRMBin()` with `returnList=TRUE`, and construct the GRM from the elements of the output.  See [this script](https://github.com/RMKirkpatrick/mxGREMLdemos/blob/master/AGES2017/GREML_Factor_demo.R) for an example of that.
