### ISSUE TITLE
imxGetNumThreads hard coded to return 2 cores, ignoring true core count from omxDetectCores

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#283]
Whatever number of cores is, `imxGetNumThreads` returns 2 for any value that is not NA

Greatly slows machines with more than 2 cores and OpenMp

The `else detect <- 2L` should be deleted.

OpenMx version: 2.17.4 [GIT v2.17.4]

```R
imxGetNumThreads <- function () {
    if (imxSfClient()) {
        return(1L)
    } else {
        thrlimit <- as.integer(Sys.getenv("OMP_NUM_THREADS"))
        if (!is.na(thrlimit)) {
            return(thrlimit)
        }else {
            detect <- omxDetectCores()
            if (is.na(detect)) 
                detect <- 1L
            else detect <- 2L
            return(detect)
        }
    }
}
```

**Comment by jpritikin** [comment]
Yeah, we do this because it is CRAN policy. As a user, you have to specifically request more than 2 cores if that's what you want.

**Comment by tbates** [comment]
OK: I used it in umx thinking it was a useful way to ask how many threads are available... Will replace with something else
