### ISSUE TITLE
Multithread support for confidence interval calculations

### ISSUE THREAD

**Issue by khusmann** [OpenMx/OpenMx#286]
Would be nice to have!

Looks like confidence intervals are calculated on a single thread -- mxRun takes all cores to find solution, but then when I get to `[0/5] MxComputeGradientDescent(SLSQP) evaluations...` usage drops to a single core.

**Comment by tbates** [comment]
https://github.com/OpenMx/OpenMx/issues/77

**Comment by khusmann** [comment]
Ah, didn't see that. Thanks @tbates!

**Comment by jpritikin** [comment]
duplicate
