### ISSUE TITLE
No binaries for R 4.0 for mac and win on ssri?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#291]
FYI: Just went to install NPSOL version and got:

```R
source("https://openmx.ssri.psu.edu/getOpenMx.R")
```
> Error in eval(ei, envir) : Binaries have not been prepared for R 4.x yet.

Just checking that the hard-coded fail for windows and macos is still supposed to be in getOpenMx.R

https://vipbg.vcu.edu/vipbg/OpenMx2/software//getOpenMx.R?q=software/getOpenMx.R

**Comment by RMKirkpatrick** [comment]
Resolved today.
