### ISSUE TITLE
Smarter behavior for rowwiseParallel = NA (not always pick TRUE)

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#292]
Suggestion: change the default for `rowwiseParallel` to FALSE

The default for `rowwiseParallel=TRUE` is NA. This seems to get treated as TRUE when a model is optimised or a CI is computed. But TRUE is much (>=2x) slower than FALSE for models which have a small number of data-summary patterns. Only models with many ordinal or missingness patterns or def vars benefit from the current default.

See also #77

Example showing benefit of moving to `rowwiseParallel= FALSE`  for common models

```R
umx_set_cores(4)

data(twinData)
twinData= umx_scale_wide_twin_data(data=twinData,varsToScale="wt",sep= "")
obLevels   = c('normal', 'overweight', 'obese')
cuts       = quantile(twinData[, "bmi1"], probs = c(.5, .2), na.rm = TRUE)
twinData$obese1=cut(twinData$bmi1,breaks=c(-Inf,cuts,Inf),labels=obLevels)
twinData$obese2=cut(twinData$bmi2,breaks=c(-Inf,cuts,Inf),labels=obLevels)
twinData[, ordDVs] = umxFactor(twinData[, c("obese1", "obese2")])
mzData = twinData[twinData$zygosity %in% "MZFF",] 
dzData = twinData[twinData$zygosity %in% "DZFF",]
m1 = umxACE(selDVs= c("wt","obese"), dzData= dzData, mzData= mzData, sep='', autoRun=F)

# slow
m1$MZ$fitfunction$rowwiseParallel = TRUE
m1$DZ$fitfunction$rowwiseParallel = TRUE
m2 = mxRun(m1)

# fast
m1$MZ$fitfunction$rowwiseParallel = FALSE
m1$DZ$fitfunction$rowwiseParallel = FALSE
m3 = mxRun(m1)

umx_time(c(m2,m3))
ACE: 00.46 sec , 
ACE: 00.25 sec (Δ: -0.205), 55.807%

```

**Comment by jpritikin** [comment]
Yeah, this is a good idea. I have to think about how to accomplish it technically.

**Comment by mcneale** [comment]
Possibly, we should do what we do for joint continuous & ordinal, and figure out which way will be quicker ahead of time, and then use it.  It seems likely that if rowwiseParallel=T results in faster processing for a specific problem, then it should be used during model-fitting optimization.  It could then be switched off for computing the CIs, which could be executed in parallel.  Again, to be smart, we should ensure that the number of CIs requested is sufficient to 'fill' the nodes available.  If, say, only 2 CIs are requested = 4 optimizations, and if 20 threads are available, it may be better to leave rowwiseParallel=T and to do the CIs sequentially.   A bunch of this is automagical, so we obviously need to leave the users the option to set autoParallelize=F so that control is in their hands.  But to default to the fastest computational path seems to me to be a reasonable bit of automagic.

**Comment by tbates** [comment]
Testing what `rowwiseParallel` mode is best for CIs for a GxE twin model (so with a definition variable).

CIs run fastest in serial (`rowwiseParallel = FALSE`), .exactly the same as for a model *without* definition variables...

Question: Does anyone  have a model where CIs benefit from `rowwiseParallel = TRUE` (the default? or more accurately, what the default NA is converted to currently?).

>  mRowWise_default_NA: 44.82 sec , 
mParallel: 44.54 sec (Δ: -0.274), 99.388%
mSerial: 32.24 sec (Δ: -12.576), 71.942%


Setup model
```R
require(umx)
data(twinData) 
umx_set_optimizer("SLSQP")
twinData$age1 = twinData$age2 = twinData$age
selDVs  = "bmi"
selDefs = "age"
mzData  = subset(twinData, zygosity == "MZFF")
dzData  = subset(twinData, zygosity == "DZFF")
m1 = umxGxE(selDVs= "bmi", selDefs= "age", sep= "", dzData= dzData, mzData= mzData, tryHard= "yes")
```

1. Run with **default** values for rowwiseParallel
```R
mDefault = mxRename(m1, "mRowWise_default_NA")
mDefault = umxConfint(mDefault, parm= "all", run=T)
```

2. Run with `rowwiseParallel` in parallel mode (TRUE)
```R
mParallel = mxRename(m1, "mParallel")
mParallel$MZ$fitfunction$rowwiseParallel = TRUE
mParallel$DZ$fitfunction$rowwiseParallel = TRUE
mParallel = umxConfint(mParallel, parm= "all", run=T)
```

3. Run with `rowwiseParallel` set to serial mode (FALSE)

```R
mSerial   = mxRename(m1, "mSerial")
mSerial$MZ$fitfunction$rowwiseParallel = FALSE
mSerial$DZ$fitfunction$rowwiseParallel = FALSE
mSerial = umxConfint(mSerial, parm= "all", run=T)
```

#### timings
```R
umx_time(c(mDefault, mParallel, mSerial))
```
>  mRowWise_default_NA: 44.82 sec , 
mParallel: 44.54 sec (Δ: -0.274), 99.388%
mSerial: 32.24 sec (Δ: -12.576), 71.942%

**Comment by mcneale** [comment]
If age is a continuous random variable, every row will get evaluated fully, with no speed-ups from using already-computed expected means and covariance matrices. However, blocks of rows of the dataset should get allocated to different threads. So there should be some advantage to parallel - without CIs -  if there are many rows.  Where ‘many’ is sufficient to give an advantage to parallel, I don’t know, but it could be explored.

Here age has 68 different Values and the missingness patterns are limited mostly to whether or not twin 2 is present. There are 3808 records. Seems like parallel should offer some speed up just on the way to minimum, no CIs.

**Comment by jpritikin** [comment]
> Does anyone have a model where CIs benefit from `rowwiseParallel = TRUE`

Try any model with 10-12 ordinal indicators.

**Comment by tbates** [comment]
Just to store some more numbers: For GxE model execution, setting `rowwiseParallel` to FALSE is a big win:

# parallel model run
```R
umx_set_cores(4)
m1 = umxGxE(selDVs= "bmi", selDefs= "age", sep= "", dzData= dzData, mzData= mzData, autoRun=F)
m1$MZ$fitfunction$rowwiseParallel = TRUE; m1$DZ$fitfunction$rowwiseParallel = TRUE
m1 = mxTryHard(m1); umx_time(m1)
G_by_E: 2 cores: 02.23 sec 4 cores: 03.00 sec
```

# serial model run

```R
m1 = umxGxE(selDVs= "bmi", selDefs= "age", sep= "", dzData= dzData, mzData= mzData, autoRun=F)
m1$MZ$fitfunction$rowwiseParallel = F; m1$DZ$fitfunction$rowwiseParallel = F; m1 = mxTryHard(m1)
umx_time(m1)
G_by_E: 2cores: 01.48 sec; 4 cores = 01.00
```

**Comment by jpritikin** [comment]
Let's try v2.18.1-15-gd52c23140

**Comment by tbates** [comment]
With OpenMx version: 2.18.1.16 [GIT v2.18.1-16-gbb41e46c], the GxE model is still running twice as fast if I set `rowwiseParallel = FALSE` than if I leave it at the default NA.

Oddly, diagnostics says `rowwiseParallel = FALSE` was chosen internally… I don't really get what's going on, however, as this is on a 4 physical core machine with `umx_set_cores(4)`, but the diagnostics are talking about 1 core... Is it just internally restricting itself to 1 core?

MZ.fitfunction: openmpUser = 0
DZ.fitfunction: openmpUser = 0
Beginning initial fit attemptFitContext::createChildren(G_by_E.fitfunction, 1)
MZ.fitfunction: openmpUser = 1
DZ.fitfunction: openmpUser = 1
FitContext::createChildren: MZ.fitfunction is an OpenMP user
FitContext::createChildren: DZ.fitfunction is an OpenMP user
FitContext::createChildren: create 4 FitContext for parallel processing; OpenMP user=1
MxComputeGradientDescent(SLSQP) evaluations 312 fit 9340.52 change -11.63MZ.fitfunction: rowwiseParallel used 1 threads; recommend rowwiseParallel=FALSE
DZ.fitfunction: rowwiseParallel used 1 threads; recommend rowwiseParallel=FALSE
JacobianGadget: not used (analytic?)
Gradient used 1/1 threads for 9 free parameters
FitContext::createChildren(G_by_E.fitfunction, 0)
MZ.fitfunction: openmpUser = 0
DZ.fitfunction: openmpUser = 0
FitContext::createChildren: create 4 FitContext for parallel processing; OpenMP user=0

**Comment by jpritikin** [comment]
That's because there was a typo in my change. Thanks for testing. See v2.18.1-17-g376f0e1b3

**Comment by tbates** [comment]
one less = fixed it - A nice 2x speed up!

**Comment by tbates** [comment]
Bingo! models now smart and > 2x faster.

PS, great that these downloads have lost so much weight too! (down from 40+MB to 9.5 MB or so)
