### ISSUE TITLE
Asymptotic Covariance Matrix of Polychoric Correlations and Thresholds

### ISSUE THREAD

**Issue by gabriellajg** [OpenMx/OpenMx#298]
Hello! 

Is there a way to extract the Asymptotic Covariance Matrix (ACM) of Polychoric Correlations and Thresholds when fitting CFA models to ordinal data? 

Thanks!

**Comment by mcneale** [comment]
Yes, see ?mxDataWLS.  It's deprecated and perhaps should not be, but the ACM should also be available within the mxData object after the model has been run (so that mxData generates the ACM).

**Comment by jpritikin** [comment]
After `mxRun`, the summary statistics are available from `model$data$observedStats`.

`mxDataWLS` is deprecated because it is slow. The summary stats are computed in R. Better to use `mxData` as usual and let the C++ code compute the summary stats.
