### ISSUE TITLE
Document new and noteworthy features

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#30]
I'll start

# Handy S3 methods
* `logLik` to get the log likelihood from a model
* `confint` for Wald-type confidence intervals on free parameters
* `anova` for comparing nested models
* `coef` to extract free parameters
* `simulate` to generate data from a model

# More functions
* `mxFitFunctionMultigroup` for multiple group models.
* `mxFitFunctionMixture` for (independent) mixture models
* `mxFitFunctionHiddenMarkov` for Markov dependent mixture models
* `mxFitFunctionWLS` & `mxDataWLS` for weighted least squares estimation
* `mxGenerateData` to generate data from a model
* `mxSE` to get standard errors on arbitrary algebraic expressions
* `mxGetExpected` to extract expected means, covariances, and/or thresholds from models
* `mxMI` to get modification indicies
* `mxTryHard` & `mxTryHardOrdinal` to repeatedly fit a model until it behaves
* `mxAutoStart` for automatic starting values
* `omxDefaultComputePlan` to generate a default compute sequence, for editing.
* `mxBootstrap` for nonparametric bootstrapping to get SEs and CIs
* `mxParametricBootstrap` for parametric bootstrapping to get marginal p-values for parameters
* `mxComputeNelderMead` for a general-purpose, derivative-free alternative to the GD optimizers
* `imxRobustSE` for robust standard errors in non-multilevel FIML analysis of raw data
* `mxCompare` for model comparison, which is now smart about detecting invalid comparisons, and which can do the bootstrap LRT
* `mxCompareMatrix` is a variation of `mxCompare`
* `mxFactorScores` to estimate regression, ML, or weighted ML factor scores
* `mxCheckIdentification` to check if a model is locally identified
* `mxRefModels` for fitting saturated and independence models

**Comment by RMKirkpatrick** [comment]
`omxDefaultComputePlan()` to generate a default compute sequence, for editing.
`mxBootstrap()` for nonparametric bootstrapping to get SEs and CIs
`mxParametricBootstrap()` for parametric bootstrapping to get marginal _p_-values for parameters
`mxComputeNelderMead()` for a general-purpose, derivative-free alternative to the GD optimizers
`imxRobustSE()` for robust standard errors in non-multilevel FIML analysis of raw data

**Comment by RMKirkpatrick** [comment]
`mxCheckIdentification()` to check if a model is locally identified.
`mxCompare()` for model comparison, which is now smart about detecting invalid comparisons, and which can do the bootstrap LRT.
`mxCompareMatrix()` is a variation of `mxCompare()`.

**Comment by mhunter1** [comment]
I edited my original post to include @RMKirkpatrick 's suggestions.

**Comment by tbates** [comment]
perhaps close this one, and open a new item for next release?

**Comment by RMKirkpatrick** [comment]
> perhaps close this one, and open a new item for next release?

OK with me.
