### ISSUE TITLE
npsol.a linux

### ISSUE THREAD

**Issue by rpool** [OpenMx/OpenMx#304]
Dear madam/sir,
Could you provide npsol.a linux libraries compiled with gcc 7.5.0 and compiled with gcc 9.3.0?
Thank you in advance.
Best,
René

**Comment by jpritikin** [comment]
For gcc 7.5, can you try [libnpsol.a](https://vipbg.vcu.edu/vipbg/OpenMx2/software/packages/npsol/linux/x86_64/947c218861254b5737a91c61c8d8ed82684e413f)? Let us know if it works.

As for gcc 9.3, we haven't tried [libnpsol.a](https://vipbg.vcu.edu/vipbg/OpenMx2/software/packages/npsol/linux/x86_64/a21b02cfe4d55dacd70408182becd0170b060423), but you could try and report back.

**Comment by rpool** [comment]
Thanks for the links.!

The compilation is working using the suggested libnpsol.a libraries.

- For the system running gcc9.3:
> mxVersion()
OpenMx version: 2.18.1.227 [GIT v2.18.1-227-g7c4b713e-dirty]
R version: R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu
Default optimizer: SLSQP
NPSOL-enabled?: Yes
OpenMP-enabled?: Yes

- For the system running gcc7.5:
> mxVersion()
OpenMx version: 2.18.1.227 [GIT v2.18.1-227-g7c4b713e-dirty]
R version: R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu
Default optimizer: SLSQP
NPSOL-enabled?: Yes
OpenMP-enabled?: Yes

**Comment by RMKirkpatrick** [comment]
Good to hear.  Thanks for testing.

**Comment by jpritikin** [comment]
Note to self: To close this bug, add the appropriate data to `inst/npsol/checksum`
