### ISSUE TITLE
tell people how to estimate the hessian when vcov() fails?

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#31]
re commit 7a12549559a1ecd4cfa763574fc014986fd5139a

Be nice to tell people how to estimate the hessian when `vcov()` fails?

    if(mxOption(model, "Calculate Hessian")== "No"){
    	stop(paste("Can't get vcov, as you have Hessian calculation turned off:",
    	    	"Turn on with mxOption(model, 'Calculate Hessian', 'Yes')")
    } else {
    	stop(paste("Parameter variance covariance matrix is not available:",
    	    	"Perhaps the Hessian could not be calculated?")
    }

**Comment by mcneale** [comment]
I think Hessian calculation is off when there are non-linear constraints. We could offer the optimizer's vcov instead then (and compute approximate SE's for our own summary). Conor Dolan remarked that NPSOL's are usually pretty good, but it would take some testing.

Cheers
Mike

From iPad - brief

Michael C. Neale, Ph.D.
Professor, Departments of Psychiatry & Human Genetics
Virginia Commonwealth University  VIPBG
Shipping Address: 800 East Leigh St. Suite 1-114, Richmond VA 23219-1534
Mailing Address : Box 980126 MCV Richmond VA 23298-0126
Telephone: (804) 828-3369  Fax: (804) 828-1471 Email: neale@vcu.edu<mailto:neale@vcu.edu>

On Sep 19, 2017, at 6:21 AM, Tim Bates <notifications@github.com<mailto:notifications@github.com>> wrote:


re commit 7a12549<https://github.com/OpenMx/OpenMx/commit/7a12549559a1ecd4cfa763574fc014986fd5139a>

Be nice to tell people how to estimate the hessian when vcov() fails?

if(mxOption(model, "Calculate Hessian")== "No"){
        stop(paste("Can't get vcov, as you have Hessian calculation turned off:",
                "Turn on with mxOption(model, 'Calculate Hessian', 'Yes')")
} else {
        stop(paste("Parameter variance covariance matrix is not available:",
                "Perhaps the Hessian could not be calculated?")
}

**Comment by RMKirkpatrick** [comment]
It's a good suggestion.  The code would need to check the global value of mxOption 'Calculate Hessian', and use that unless the option happens to be locally set (i.e., specifically to 'model').

> We could offer the optimizer's vcov instead then (and compute approximate SE's for our own summary). Conor Dolan remarked that NPSOL's are usually pretty good, but it would take some testing.

For NPSOL only, we populate the MxModel's 'hessian' slot with the optimizer's final Hessian if 'Calculate Hessian' is set to 'No'.  Ideally, our S3 `vcov` method should detect that and warn about it.

While I'm thinking about it: the `vcov` method should also allow the user to provide their own sampling covariance matrix, such as from bootstrapping or from  `imxRobustSE()`.

**Comment by jpritikin** [comment]
See 5c74f7b1aef

> While I'm thinking about it: the vcov method should also allow the user to provide their own sampling covariance matrix, such as from bootstrapping or from imxRobustSE().

Huh? You mean you can pass the matrix you want returned to vcov? Why even use vcov then?

**Comment by RMKirkpatrick** [comment]
> Huh? You mean you can pass the matrix you want returned to vcov? Why even use vcov then?

Oh, yeah, you're right.
