### ISSUE TITLE
improve hessian error message

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#311]
In a 09 Feb 2021 email to the openmx mailing list, Mike Neale suggested that,

```
Warning message:
In model 'GxE Correction' Optimizer returned a non-zero status code 5. The
Hessian at the solution does not appear to be convex. See ?mxCheckIdentification
for possible diagnosis (Mx status RED).
```

- We should probably omit the ?mxCheckIdentification bit of this warning when the model contains definition variables.
- Or fix the problem with the definition variables!  For anything linear that the
def vars are doing, generate expCov expMean for two differing values of each
definition variable.  Internally make them additional groups maybe? The user
could request either a number of such different values, or ‘all’ where every
differing value gets the expected stats generated.

**Comment by mhunter1** [comment]
This is mislabeled as "improve hessian error message".  It's really a request for a new feature: add identification checks for models with definition variables.  I'm creating a new issue for this.
