### ISSUE TITLE
mxRename not updating names in mxFitFunctionMultigroup  fitfunctions

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#314]
Updating model names using `mxRename` should also update all references to the new name.

This works for algebras etc. within updated submodels, but if the model contains an `mxFitFunctionMultigroup`, the groups are not updated (thus leaving the model broken).

Here's a reproducible example of the bug, showing the m1$fitfunction$groups

```R
# 1. Make a twin model
data(GFF)
mzData = subset(GFF, zyg_2grp == "MZ")
dzData = subset(GFF, zyg_2grp == "DZ")
selDVs = c("gff", "fc", "qol") 
m1 = umxCP("g1", selDVs = selDVs, sep = "_T", nFac = 1, dzData = dzData, mzData = mzData,  autoRun=F)

# 2. Rename submodels using mxRename
m1 = mxRename(m1, "top1", oldname = "top")
m1 = mxRename(m1, "MZ1" , oldname = "MZ")
m1 = mxRename(m1, "DZ1" , oldname = "DZ")

# Bug: Fitfunction not updated for the new group names
m1$fitfunction$groups
[1] "MZ" "DZ"  # should be "MZ1", "DZ1"

# Example of where mxRename does the right thing: MZ expectation IS updated to use new names

m1$MZ1$expectation$covariance
[1] "top1.expCovMZ"
```

**Comment by jpritikin** [comment]
5471f441c

**Comment by tbates** [comment]
I think a side effect of this change is that `mxRename` is now greedily renaming substrings matching old model name that it finds, e.g. in algebras (not the name, but the algebra formula itself)

It's a show stopper, as renaming a model called "ACE" to "foo" also updates `mxAlgebra(rbind(ACE, AC))` to `mxAlgebra(rbind(foo, AC))`

I only stumbled over it as `power.ACE.test()` does this, leaving the `expCov` algebra broken at run time…

Slight chance it was the change in #318, but I think it was this fix...

**Comment by tbates** [comment]
Here's a test which builds a model with a matrix referenced in an algebra. Then testing that `mxRename` doesn't reach inside the algebra formula too greedily (it does).

```R
data("twinData", package="OpenMx")
selVars <- c('bmi1','bmi2')
aceVars <- c("A1","C1","E1","A2","C2","E2")
mzfData <- subset(twinData, zyg==1, selVars)
dzfData <- subset(twinData, zyg==3, selVars)

share2 <- mxModel(share,
	mxPath(from=c("C1"), to="bmi1", arrows=1, free=FALSE, values=0, label="c"),
	mxPath(from=c("C2"), to="bmi2", arrows=1, free=FALSE, values=0, label="c")
)

MZ = mxModel(share2, name="MZ",
    mxPath(from="A1", to="A2", arrows=2, free=FALSE, values=1),
    mxData(mzfData, type="raw")
)

DZ = mxModel(share2, name="DZ",
    mxPath(from="A1", to="A2", arrows=2, free=FALSE, values=.5),
    mxData(dzfData, type="raw") 
)

model <- mxModel("twinAE", MZ, DZ,
    mxFitFunctionMultigroup(c('MZ','DZ'))
)

# test that we are not renaming algebra formulae too greedily
tmp = mxModel(model, mxMatrix(name="bob", "Full", 2,2,values=1), mxAlgebra(name="tmp", bob %*% bob))
tmp2 = mxRename(tmp, oldname = "bob", newname = "buggered")
tmp2 = mxRun(tmp2)
```
> Error: Unknown reference 'buggered' detected in the entity 'tmp' in model 'twinAE'

**Comment by jpritikin** [comment]
Oh, hm, interesting. Investigating

**Comment by tbates** [comment]
thanks!
