### ISSUE TITLE
Updating OpenMx failed

### ISSUE THREAD

**Issue by rs-aesi** [OpenMx/OpenMx#316]
I'm running Slackware-14.2/x86_64 and R-4.0.2-x86_64-1_SBo.
Updating OpenMx failed:
omxState.cpp:1230:82:   required from here
omxState.cpp:1229:17: error: cannot call member function ‘void ConstraintVec::eval(FitContext*,  double*, double*)’ without object
                eval(fc2, result.data(), 0);
                *

**Comment by jpritikin** [comment]
Install a newer version of `gcc` or wait for the next bug fix release, currently pending with the CRAN team.

**Comment by rs-aesi** [comment]
On Sun, 11 Apr 2021, Joshua Pritikin wrote:

> Install a newer version of `gcc` or wait for the next bug fix release,
> currently pending with the CRAN team.

Thanks, Joshua. I'll wait for the next release.

Rich
