### ISSUE TITLE
Column in CI details for change in fit

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#32]
The change in -2logL between the point-estimate solution and the solution for a confidence limit is a pretty important piece of information for gauging the validity of a CI, but it doesn't appear in the 'CI details' table.  Sure, the user can calculate it him/herself, but the change in fit is important enough that the user shouldn't have to.

**Comment by mcneale** [comment]
Agreed!

Cheers
Mike

On Sep 19, 2017, at 11:50 AM, RMKirkpatrick <notifications@github.com<mailto:notifications@github.com>> wrote:


The change in -2logL between the point-estimate solution and the solution for a confidence limit is a pretty important piece of information for gauging the validity of a CI, but it doesn't appear in the 'CI details' table. Sure, the user can calculate it him/herself, but the change in fit is important enough that the user shouldn't have to.

**Comment by RMKirkpatrick** [comment]
It looks like this issue can be closed: [962472e](https://github.com/OpenMx/OpenMx/commit/962472e071eafc4d7d9d2814f81f96f46aa76d59)
