### ISSUE TITLE
models/nightly/CSOLNP_segfault_regression_test--unidentifed_EFA.R takes too long

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#323]
On my laptop, both CSOLNP and SLSQP can complete this test in a reasonable amount of time. However, on the light cluster, CSOLNP takes hours. I'm not sure what's going on. Can we limit the number of major iterations to some small number?

Once this is fixed, can we close #99 ?

**Comment by RMKirkpatrick** [comment]
Let's discuss at the meeting tomorrow?

**Comment by RMKirkpatrick** [comment]
The nightly run on the cluster is currently dead in the water, so this issue is not of present concern.  Once the nightly run is restored to working order, we can reopen this issue if/when the test script in question causes problems again.
