### ISSUE TITLE
Restore old behavior of MxFitFunctionML with MxExpectationGREML

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#33]
Previously, using the ML fitfunction with the GREML expectation would fit a GREML-type model by ML rather than REML.  The GREML expectation knew it was talking to an ML fitfunction, and knew how to present the backend FIML fitfunction with a single row of data, a covariance matrix, and a mean vector (the regression yhats).  It was not the recommended way to fit a GREML-type model, but a user who really wanted to do it that way could.

The recent overhaul of the backend fitfunction API was sorely needed and will go a long way toward making the code easier to maintain.  But, it changed the behavior so that now using the ML fitfunction with a GREML expectation ends up using the GREML fitfunction in the backend.

**Comment by mhunter1** [comment]
I believe this same overhaul killed the row diagnostics feature noted in issue #53

**Comment by mhunter1** [comment]
@RMKirkpatrick Is this resolved yet?

**Comment by RMKirkpatrick** [comment]
It is not.  I haven't had a chance to work on it.

**Comment by mcneale** [comment]
From the end of the github thread it looks like Joshua fixed it in v2.9.4-23-g4ff9e9b63

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Apr 5, 2018, at 9:31 AM, RMKirkpatrick <notifications@github.com<mailto:notifications@github.com>> wrote:


It is not. I haven't had a chance to work on it.

**Comment by RMKirkpatrick** [comment]
> From the end of the github thread it looks like Joshua fixed it in v2.9.4-23-g4ff9e9b63

Row diagnostics, yes.  But not the original issue of restoring ML fit with GREML expectation.

**Comment by RMKirkpatrick** [comment]
Done as of ea4d3e4 .
