### ISSUE TITLE
openmx3.9 mulponly.c mpi error

### ISSUE THREAD

**Issue by davidshisui** [OpenMx/OpenMx#330]
I encountered a problem while running mpirun -np 4 ./kSpin Au111Surface_MO.dat

shows: invalid root during MPI_Bcast.

It seems that the program try to use process 5 to broadcast to other processes. But there are only 4 processes.

**Comment by mcneale** [comment]
I think this issue may be about the lowercase version of OpenMx (completely different software), not this one.  We don't have a 3.9 version.
