### ISSUE TITLE
R unresponsive, model stalled (9 binary variable ACE)

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#335]
I've been running some ACE models with binary variables.

With four variables, take ~ 20 minutes using 4 cores, but completes fine.

With nine variables, left for 19 hours overnight, it stalls at some point, still consuming 1 core, with a couple of what seem like abandoned daughter processes also running (see image), but with R unresponsive, no console progress updates and has to be quit.

If anyone wants to investigate, I could share the model.

> OpenMx version: 2.19.8.84 [GIT v2.19.8-84-gb588e240-dirty]
R version: R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 
MacOS: 12.3
Default optimizer: SLSQP
NPSOL-enabled?: Yes
OpenMP-enabled?: Yes

<img width="909" alt="Screen Shot 2022-02-22 at 12 44 58" src="https://user-images.githubusercontent.com/736156/155138045-eb36ef51-cf78-47e0-96a2-7d6368cea81f.png">

**Comment by mcneale** [comment]
Might as well share it.  Quite possibly, 9 binary variables are beyond the numerical precision of the integration routine, especially if one or more of them is rarely endorsed/low prevalence, like 2% or less.  One way to debug is, of course, to use checkpointing to see where it has got to and what, if anything, it is still trying to do.  mxOption(NULL, "Always Checkpoint", "Yes") upfront should do the trick.

**Comment by RMKirkpatrick** [comment]
The running time for the integration routine scales very poorly with dimension; I believe it's actually exponential in dimension.  If I'm right, then the running time for a 9-dimensional integral should be about 150x that of a 4-dimensional integral.  That's probably part of the explanation for this issue, but I'm not sure why R is running hard on only 1 thread.

**Comment by jpritikin** [comment]
Yeah, it's working on estimating the gradient. Once there is an estimate of the gradient then it can try taking a step.
