### ISSUE TITLE
'https://vipbg.vcu.edu/vipbg/OpenMx2/software/bin/macosx/travis/OpenMx_latest.tgz': Timeout of 60 seconds was reached

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#336]
trying to install OpenMx from the travis url, but it always times out.

```R

trying URL 'https://vipbg.vcu.edu/vipbg/OpenMx2/software/bin/macosx/travis/OpenMx_latest.tgz'
Content type 'application/x-gzip' length 40774465 bytes (38.9 MB)
==================================
downloaded 27.1 MB

Error in download.file(p, destfile, method, mode = "wb", ...) : 
  download from 'https://vipbg.vcu.edu/vipbg/OpenMx2/software/bin/macosx/travis/OpenMx_latest.tgz' failed
In addition: Warning messages:
1: In download.file(p, destfile, method, mode = "wb", ...) :
  downloaded length 28409856 != reported length 40774465
2: In download.file(p, destfile, method, mode = "wb", ...) :
  URL 'https://vipbg.vcu.edu/vipbg/OpenMx2/software/bin/macosx/travis/OpenMx_latest.tgz': Timeout of 60 seconds was reached
```

**Comment by mcneale** [comment]
Can you try it again?  Simply clicking on the link downloads in seconds here.  Possibly, try that as an intermediate step and install from the local file if R is fiddling about with its internet connection.

**Comment by tbates** [comment]
hmm... CRAN version comes in fine 
but ssri/NPSOL version is also timing out...  (PS: the NPSOL version looks a bit out of date? ( 2.19.8 ? )

```R
trying URL 'https://openmx.ssri.psu.edu/software/bin/macosx/contrib/4.1/OpenMx_2.19.8.tgz'
Content type 'application/x-gzip' length 40295303 bytes (38.4 MB)
===============================================
downloaded 36.5 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://openmx.ssri.psu.edu/software/bin/macosx/contrib/4.1/OpenMx_2.19.8.tgz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 38223872 != reported length 40295303
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://vipbg.vcu.edu/vipbg/OpenMx2/software//bin/macosx/contrib/4.1/OpenMx_2.19.8.tgz?q=software/bin/macosx/contrib/4.1/OpenMx_2.19.8.tgz': Timeout of 60 seconds was reached
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘OpenMx’ failed
> 
```

**Comment by tbates** [comment]
> Can you try it again? Simply clicking on the link downloads in seconds here. Possibly, try that as an intermediate step and install from the local file if R is fiddling about with its internet connection.

Yeah.. looks like it's up, but just too slow to slip under the default 60second time out (e.g. still slow in Safari). 
I'll look and see if there's a tweak to ask for more time... 

<img width="575" alt="Screen Shot 2022-02-23 at 15 49 57" src="https://user-images.githubusercontent.com/736156/155355454-665a7070-3042-4d11-be73-9c7404520847.png">

**Comment by tbates** [comment]
OK, `umx:::install.OpenMx()` now sets `options(timeout=60*3)` so users won't see this behavior.

**Comment by tbates** [comment]
Has Josh got another job? That’s a loss.

Looks like a travis.com paid membership is only $30/month for 50,000 credits a month….Probably a bargain for VIPBG.

Just started the 9 binary job to leave over night with checkpointing: After 7 minutes (R unresponsive the whole time) it hasn’t written to the checkpointing file yet :-(

Oh well.. see what it looks like in the morning I guess :-) Hope springs eternal :-)

Hope all’s well!

t
