### ISSUE TITLE
omxParallelCI()

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#34]
`omxParallelCI()` provides a way for users to get CIs without redoing the primary optimization to find the point estimates, and without using a custom compute plan.  Unfortunately, getting the CI details table in verbose summary output isn't possible with `omxParallelCI()`.  With argument `run=FALSE`, the user would have to run the returned MxModel object and look at each independent submodel's CI details table, and with `run=TRUE`, there doesn't seem to be a way to get CI details at all.  The problem is that the CI details are stored in the output slot of the MxComputeConfidenceInterval object.  With `run=FALSE`, each independent submodel has its own compute plan containing a CI step, and with `run=TRUE`, there is no CI step in the compute sequence of the returned MxModel object.

I propose that CI details instead be stored in the MxModel's output slot, and that `omxParallelCI()` be modified to assemble the CI details table in the returned MxModel's output slot when `run=TRUE`.

`omxParallelCI()` was apparently thus named based on the idea that OpenMx would run independent submodels in parallel (via 'snowfall'?), which isn't implemented, and isn't really a priority to be implemented.  Perhaps we should create an alias function with a less misleading name--say, `omxRunCI()`?--and use that as the recommended interface (while of course retaining `omxParallelCI()` for backward compatibility).

**Comment by jpritikin** [comment]
1. `omxRunCI` seems like a better name.

2. "The problem is that the CI details are stored in the output slot of the `MxComputeConfidenceInterval` object." -- We could transfer the information in the submodels' compute plans to a synthetic compute plan that we create in the top model.

**Comment by RMKirkpatrick** [comment]
> We could transfer the information in the submodels' compute plans to a synthetic compute plan that we create in the top model.

I was thinking about something similar: an additional argument--say, `useIndeSubs`--which would let the user decide which behavior s/he wants.  If `useIndeSubs=TRUE`, then `omxParallelCI()` uses independent submodels as it always has.  If `useIndeSubs=FALSE`, then `omxParallelCI()` creates a compute plan consisting only of a CI step and places it in the MxModel object provided as `model` (and runs the model if `run=TRUE`).  I guess that compute plan should have its '.persist' slot set to `FALSE`.  

For the sake of backwards compatibility, `useIndeSubs` would default to `TRUE`.  But, we could could create `omxRunCI()` as a wrapper to `omxParallelCI()`, using `useIndeSubs=FALSE`.

**Comment by jpritikin** [comment]
Yeah, sounds reasonable. Except I suggest the argument be called `independentSubmodels=TRUE` instead of `useIndeSubs`

**Comment by RMKirkpatrick** [comment]
> Except I suggest the argument be called independentSubmodels=TRUE

OK by me.  I'll assign the implementation to myself.

**Comment by RMKirkpatrick** [comment]
See [6f512b2](https://github.com/OpenMx/OpenMx/commit/6f512b2d2d76c87fd46c52e2ad82d3160ad99fed).
