### ISSUE TITLE
Friendlier readme.md?

### ISSUE THREAD

**Issue by lf-araujo** [OpenMx/OpenMx#340]
Hi devs,

I think a longer readme.md with minimal code examples is important to help new users immediately understand what the package is about. The minimalism of the current readme requires that the user click out of github to obtain the smallest definition of what this package does.

I generated a readme with two examples, removed broken badges, added the official mascot, etc to the readme [here](https://github.com/lf-araujo/OpenMx)

Let me know if this is something devs want at all, or make suggestions (typos guaranteed since, you know, English is not my main language).  

Best,

luis

**Comment by tbates** [comment]
looks good to me, and the links work, no obvious typos -- I'd say ago ahead and commit/pull request.
