### ISSUE TITLE
Do not count thresholds as observed statistics

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#344]
This commit 24072d3f5493da0c9fdfbac701f42779a4644a48 (originally this commit dd2adac311d7393f5194436d1a0d0e0f4c3457ef then reverted with 8591294c05776179fbec51bdc36fee01d63fb5b7 before re-applying) appears to count raw data thresholds as observed statistics.

```
     auto &allTh = getThresholdInfo();
     for (auto &col : allTh) stats += col.numThresholds;
```

Here's the full function from src/omxExpectation.cpp:

```
int MVNExpectation::numObservedStats()
{
  if (strEQ(data->getType(), "raw")) {
    if (data->hasSummaryStats()) return numSummaryStats();

    auto &dc = getDataColumns();
    // More accurate to use sufficient statistics for each missingness pattern? TODO
    int stats = 0;
    for (int cx=0; cx < int(dc.size()); ++cx) {
      stats += data->countObs(dc[cx]);
    }

    auto &allTh = getThresholdInfo();
    //for (auto &col : allTh) stats += col.numThresholds;

    return stats;

  } else if (strEQ(data->getType(), "cov") || strEQ(data->getType(), "cor")) {
    omxMatrix *cov = omxDataCovariance(data);
    int size = cov->rows;
    if (strEQ(data->getType(), "cor")) size -= 1;
    int stats = triangleLoc1(size);
    omxMatrix *means = omxDataMeans(data);
    if (means) stats += means->rows * means->cols;
    return stats;
  } else {
    return NA_INTEGER;
  }
}
```

Am I missing something?  Thresholds are not observed statistics for raw data.  Is this a WLS-related problem?

I'm still working on a minimal reproducible example, but I have encountered a model that reports one additional observed statistic for each threshold.

**Comment by jpritikin** [comment]
> Thresholds are not observed statistics for raw data. Is this a WLS-related problem?

Oops, this is probably my fault.

**Comment by jpritikin** [comment]
Your fix looks reasonable.
