### ISSUE TITLE
Better error from mxRun when given something other than an mxModel

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#35]
mxRun doesn't seem to check that `class(model == "MxModel")` so the error is a bit confusing: Says the input **was** a model, just an old one.

    mxRun(1)

>  in lapply(model@matrices, findSquareBrackets) : 
>   trying to get slot "matrices" from an object of a basic class ("numeric") with no slots
> In addition: Warning message:
> In mxRun(1) :
>   You are using OpenMx version 2.7.16 with a model created by an old version of OpenMx. This 
> may work fine (fingers crossed), but if you run into trouble then please recreate your model with the current version of OpenMx.

**Comment by RMKirkpatrick** [comment]
That's a pretty basic input check, so I'm surprised we don't do it.  But the check should actually be
```splus
is(model,"MxModel")
```
because `is()` knows about class hierarchies.

**Comment by jpritikin** [comment]
deb4ff3520
