### ISSUE TITLE
Plus operator overloading

### ISSUE THREAD

**Issue by lf-araujo** [OpenMx/OpenMx#355]
This is not an issue, and it can be closed if the devs prefer. I wanted to discuss with a wider reach what we discussed some meetings ago regarding my proposal of overloading the plus operator.  I will also include some ideas that appeared in the meeting regarding new functionality. Back from holidays, hence the delaied notes.

My proposal, however, is not adding functionality, but rather allowing an optional syntax. The idea comes from ggplot2, which is a package that does not need introduction. One syntax element it adds is the plus operator, that allows for code like the following:

```r
ggplot(data = dat, aes(x=time, y=total_bill, fill=time)) +
  geom_bar(colour="black", width=.8, stat="identity") +
  guides(fill=F) +
  xlab("Time of day") + ylab("Total bill") +
  ggtitle("Average bill for 2 people")
```
source: https://flowingdata.com/2016/03/22/comparing-ggplot2-and-r-base-graphics/

Now who else is radically modular as ggplot is?

```r
model <- twinData |>
  dplyr::select(ht1, bmi1, zygosity) |>
  mxData(type = "raw") |>
  mxModel(name ="test", manifestVars = c("ht1", "bmi1"), type = "RAM") +
    mxPath( from="ht1", to="bmi1", arrows=1,  free=TRUE, values=1) +
    mxPath( from=c("ht1","bmi1"), arrows=2,  free=TRUE, values = c(1,1) ) 
```

Yes, this is possible with three lines of code:

```r
`+.MxModel`  <- function (e1, e2) { 
  mxModel(e1, e2)
}
```

Nobody asked for this new syntax, it isn't really needed. But it can easy the transition for zoomers ;-) , it is logical for them, it is logical for me too due to my previous training.

The group seemed to be happy with the proposal, but I wanted to reach a larger audience and collect the grievances that may arise.

# Discussion on new functionality

Tim suggested an operator that simplified the addition of a new path, but using the rlang (R formula) interface, of the type:

```r
mod += mx(Y ~ X, labels=Bob, value=4) 
```

This is an interesting suggestion, however maybe it is already too easy with the new plus interface with code of the type:

```r
model <- model +   mxPath( from="one", to=c("ht1","bmi1"), arrows=1,  free=TRUE,  values=c(1,1) )
```

What is missing there is only the rlang interface.

A second suggestion by Tim was re multiple groups in OpenMx. Multiple groups are excessively verbose in mx, agreed. My attempts to allow transparent treatment of raw data in OpenMx always fail in the first initial lines of the mxModel function, as it has a very particular way of managing the arguments. His suggestion was:

```r
modelTree <- mod *4
```

Which is simple enough and can be easily achieved (I think) using overloading too. I had a solution for this in the case of raw data, that uses purrr and functional programming to detect grouped data and generate the models for each group. Not widely tested, as it was used in a personal project:

```r
library(umx)
library(dplyr)
library(purrr)

#Simulate Data
require(MASS)
#group 1
set.seed(200)
xy1 <- mvrnorm (1000, c(0,0), matrix(c(1,.5,.5,1),2,2))
colnames(xy1) <- c("X", 'Y')
#group 2
set.seed(200)
xy2 <- mvrnorm (1000, c(0,0), matrix(c(1,.4,.4,1),2,2))
colnames(xy2) <- c("X", 'Y')
xy1 <- mutate(as.data.frame(xy1), zygosity = "um")
xy2 <- mutate(as.data.frame(xy2), zygosity = "dois")
dt <- rbind(xy1, xy2)
dt <- as_tibble(dt)

named_group_split <- function(.tbl, ...) {
  # Little helper to split a tibble by group and name the groups
  grouped <- group_by(.tbl, ...)
  names <- rlang::inject(paste(!!!group_keys(grouped), sep = " / "))
  grouped %>% 
    group_split() %>% 
    rlang::set_names(names)
}

mb <- dt %>%
  # pass the data, group it
  named_group_split(zygosity) %>% 
  # map mxData over the groups
  map(~ mxData(.,type = "raw")) %>%
  # map over the data, this results in one model per data group
  imap(~ mxModel(., name=.y,type = "RAM",
            manifestVars = c('X','Y')) +
          mxPath( from=c('X','Y'), arrows=2, free=T, values=1, lbound=.01 ) +
          mxPath( from="X", to="Y", arrows=2, free=T, values=.2, lbound=.01) +
          mxPath( from="one", to=c("X", 'Y'), arrows=1, free=T, values=c(0.1,-0.1),
            ubound=c(NA,0), lbound=c(0,NA)) ) %>%
  # merge models for each group into one container model
  mxModel(name = "bivariate Heterogeneity Path Specification" ) + 
  # this unecessary, just trying to annoy the devs. In real life I would just do in another line listing
  # the groups explicitly, which is preferred
    mxFitFunctionMultigroup(groups=names(named_group_split(dt, zygosity)))

out <- mxRun(mb)
summary(out)
```

The code above seems long, but in reality it can reduce hundreds of lines of code specifying paths for each of the groups.

A final note I want to make is that these large chunks are not good for teaching. Separating the objects is preferred, the style above aims at reducing typing while writing multiple groups in OpenMx.

- I will make the PR for the overloading soonish, then have a go at the multiplication operator.

**Comment by lf-araujo** [comment]
@mhunter1, @RMKirkpatrick  I need help on finalizing the pull request, I was about add a test unit for the PR, but I noticed that if i add:



```r

`+.MxModel`  <- function (e1, e2) { 
  mxModel(e1, e2)
}
```

to MxModel.R, then build with `make install` and then run my tests, the new overloading is not being picked up and the test errs. Am I adding that code to the wrong place?


My test file looks like the following:


```r
library(OpenMx)
library(testthat)
context("Plus operator")


mb <- mxModel("bivariate Heterogeneity Path Specification",
  type = "RAM",
  manifestVars = c("X", "Y")
) +
  mxPath(from = c("X", "Y"), arrows = 2, free = T, values = 1, lbound = .01) +
  mxPath(from = "X", to = "Y", arrows = 2, free = T, values = .2, lbound = .01) +
  mxPath(
    from = "one", to = c("X", "Y"), arrows = 1, free = T, values = c(0.1, -0.1),
    ubound = c(NA, 0), lbound = c(0, NA)
  )

mb <- mxGenerateData(mb, nrows = 1000, returnModel = T)
out <- try(mxRun(mb))

omxCheckEquals(is(out, "try-error"), FALSE)
```

The error:

![image](https://user-images.githubusercontent.com/10139950/192855204-3d89e82a-a3e7-451d-b09e-58a3ed17e362.png)

**Comment by lf-araujo** [comment]
On a second thought, I remember in R one needs to export a new function in order to be available to the user, otherwise it is just for internal use, is that it?

**Comment by RMKirkpatrick** [comment]
> On a second thought, I remember in R one needs to export a new function in order to be available to the user, otherwise it is just for internal use, is that it?

Yes, I think you'll need to add the appropriate line to the NAMESPACE file.

**Comment by lf-araujo** [comment]
Ok, done.

Will move on to https://github.com/OpenMx/OpenMx/issues/351 and then back. Thanks for the help.

**Comment by tbates** [comment]
You can also use roxygen to document, handle the namespace etc. in-line. Some OpenMx functions use this, most hand-write it all. It's a bit of a doctrinaire issue :-)

This is a stub I use, but you can learn more by searching #' in the code or https://roxygen2.r-lib.org

#' TITLE
#'
#' @description myfunc is a function which
#'
#' @details If any
#'
#' @param param a something to DO WHAT?
#' @return - what i return
#' @export
#' @family
#' @seealso - [omxSimilarFunction()]
#' @references - if any
#' @md
#' @examples
#' myfunc(param)
#' \dontrun{
#' 
#' }

**Comment by lf-araujo** [comment]
Thanks, this will be very useful in future PRs.
