### ISSUE TITLE
ERROR: compilation failed for package ‘OpenMx’

### ISSUE THREAD

**Issue by crawfordwsc** [OpenMx/OpenMx#362]
I am running an EC2 instance (Amazon Linux 2) and can't seem to get OpenMx installed. Here's what i see when trying to install:

R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Amazon Linux 2

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RcppParallel_5.1.7 psych_2.2.9       

loaded via a namespace (and not attached):
[1] compiler_4.2.2  parallel_4.2.2  tools_4.2.2     nlme_3.1-160    mnormt_2.1.1    grid_4.2.2     
[7] lattice_0.20-45`

ERROR: compilation failed for package ‘OpenMx’
* removing ‘/local/home/wcrawfrd/R/x86_64-pc-linux-gnu-library/4.2/OpenMx’
Warning in install.packages("OpenMx") :
  installation of package ‘OpenMx’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpXFtsWp/downloaded_packages’
`

**Comment by RMKirkpatrick** [comment]
Just for the sake of other users with encountering this same problem: @crawfordwsc , did this have something to do with `CXX14STD = -std=gnu++14` needing to be set somewhere?

**Comment by crawfordwsc** [comment]
@RMKirkpatrick  yes - you nailed it....the ~/.R/Makevars file needed the change.
