### ISSUE TITLE
Option to build libnpsol from source?

### ISSUE THREAD

**Issue by barracuda156** [OpenMx/OpenMx#366]
It seems from configure that currently only pre-built static lib is supported. This cannot work for other archs and will not work nicely with different prefix and/or toolchain. Is it possible to add support for building from source?

**Comment by RMKirkpatrick** [comment]
Sorry, no.  NPSOL is proprietary software; our license agreement does not permit us to distribute its source code.  That's why CRAN doesn't provide NPSOL-enabled builds of OpenMx.

> This cannot work for other archs

*sigh* Yes, I know, and it is something I regret.

**Comment by barracuda156** [comment]
@RMKirkpatrick Thank you for responding. I just did not know it is not open-source.

(I was specifically interested in macOS PPC, but I well realize it is too demanding to ask for: it will likely require to build a modern toolchain, and needs at least 10.6.8 if not 10.5.8, to build for ppc to begin with.)
