### ISSUE TITLE
lavaan-like syntax for OpenMx RAM-type models

### ISSUE THREAD

**Issue by jhorzek** [OpenMx/OpenMx#372]
Hi,

I really enjoy the flexibility of OpenMx and am always surprised by how powerful the package is! That said, when working with simpler models I often find myself going back and forth between OpenMx and lavaan due to the simple syntax of lavaan. Because I had some code snippets laying around from another project, I decided to implement a lavaan-like syntax for OpenMx in the [mxsem](https://github.com/jhorzek/mxsem/tree/main) package. In general, it allows for "RAM"-type models that fit within the lavaan syntax. But by extending this syntax, I've also implemented definition variables and univariate algebras. If there is interest, I am happy to add further features to the syntax or contribute the code to OpenMx.

Best,
Jannik

## Example

Here is an example using a latent growth curve model with person-specific measurement occasions:

```` r
model <- "
  # specify latent intercept
     I =~ 1*y1 + 1*y2 + 1*y3 + 1*y4 + 1*y5
  # specify latent slope
     S =~ data.t_1 * y1 + data.t_2 * y2 + data.t_3 * y3 + data.t_4 * y4 + data.t_5 * y5
    
  # specify means of latent intercept and slope
     I ~ int*1
     S ~ slp*1
  
  # set intercepts of manifest variables to zero
     y1 ~ 0*1; y2 ~ 0*1; y3 ~ 0*1; y4 ~ 0*1; y5 ~ 0*1;
  "
````

**Comment by RMKirkpatrick** [comment]
Interesting! 

You may already know this, but the [umx package](https://github.com/tbates/umx) has a function, `umxLav2RAM()`, that takes lavaan syntax and outputs a list of MxPaths; umx also has support for MxAlgebras.  However, your extension of lavaan syntax to accommodate definition variables is a novel contribution!

I'll discuss the matter with the rest of the OpenMx Team.  But, I expect that at least for now, we'll leave the functionality you've developed outside of OpenMx itself, as part of your separate package, mxsem.  The idea behind OpenMx's design has always been to maintain core functionality as part of OpenMx, but maintain an API that other packages can use for high-level "wrapper" functionality (e.g., umx, ctsemOMX, EasyMx, metaSEM, tidySEM, gwsem).

**Comment by jhorzek** [comment]
Oh, I wasn't aware of the `umxLav2RAM` function! Many thanks for the hint and sorry for not seeing that earlier! 

Another thing that may be interesting is that mxsem can create new parameters using the `! new_par` syntax:

``` r
library(mxsem)
model <- '
ind60 =~ x1 + x2 + x3
dem60 =~ y1 + a1*y2 + b1*y3 + c1*y4
dem65 =~ y5 + a2*y6 + b2*y7 + c2*y8
dem60 ~ ind60
dem65 ~ ind60 + dem60

# create new variable to repesent
# change in loading b:
!delta_b
# define b2 as b1 plus the change:
b2 := b1 + delta_b
'

mxsem(model = model,
      data  = OpenMx::Bollen) |>
  mxTryHard() |>
  summary()
```
However, what is supported by `umxLav2RAM` but not mxsem are things like `b1 > exp(b2 + b3)`.

**Comment by mikewlcheung** [comment]
It is great to have another parser for lavaan syntax in the OpenMx community. The [metaSEM](https://github.com/mikewlcheung/metasem) can already handle equality and inequality constraints as well as functions of parameters. I am currently expanding its capabilities to include multiple-group and two-level models.

```
library(metaSEM)

model1 <- '
ind60 =~ 1*x1 + x2 + x3
dem60 =~ 1*y1 + a1*y2 + b1*y3 + c1*y4
dem65 =~ 1*y5 + a2*y6 + b2*y7 + c2*y8
dem60 ~ ind60
dem65 ~ ind60 + dem60

## create a new variable to repesent change in loading b:
delta_b := b2 - b1

## impose an equality constraint
a1 == a2

## impose an inequality constraint
c1 < c2
'

# Plot the model
plot(model1)

# Create a RAM representation
RAM1 <- lavaan2RAM(model1, obs.variables=names(Bollen), std.lv=FALSE)

# Fit the model in OpenMx
fit1 <- create.mxModel(RAM=RAM1, data=Bollen)
summary(fit1)

## Get the delta_b
mxEval(delta_b, fit1)


## A model with a definition variable (meta-analysis)
model2 <- '
f =~ 1*yi
f ~ mu*1          ## Average effect
f ~~ tau2*f       ## Heterogeneity variance
yi ~~ data.vi*yi  ## Known sampling variance'

plot(model2)

## Do not standardize the latent variable (f): std.lv=FALSE 
RAM2 <- lavaan2RAM(model2, obs.variables="yi", std.lv=FALSE)

## Use likelihood-based CI 
fit2 <- create.mxModel(RAM=RAM2, data=Hox02, intervals="LB")
summary(fit2)
```

**Comment by jhorzek** [comment]
Very cool! metaSEM does make mxsem mostly redundant, sorry for not seeing that earlier. Is there an easy way to create new parameters? My example above was probably not too useful as the `delta_b` parameter could also be implemented with `delta_b := b2-b1`. Here is a better example, where a moderated nonlinear factor analysis is created. The parameter `a` is predicted with covariate `k` using an intercept (`a0`) and slope (`a1`) parameter:

```
set.seed(123)
dataset <- simulate_moderated_nonlinear_factor_analysis(N = 2000)

model <- "
  xi  =~ x1 + b*x2 + x3
  eta =~ y1 + b*y2 + y3
  eta ~ a*xi
  
  # create new parameters:
  !a0; !a1
  # predict a
  a := a0 + data.k*a1
  "

mod <- mxsem(model = model,
             data = dataset) |>
  mxTryHard()

omxGetParameters(mod)
```

I've tried implementing the same model with metaSEM, but I seem to need a few tricks to do so:

```
library(metaSEM)
model <- "
  xi  =~ 1*x1 + b*x2 + x3
  eta =~ 1*y1 + b*y2 + y3
  eta ~ a*xi
  # specify intercepts:
  x1~1;x2~1;x3~1;y1~1;y2~1;y3~1
  
  # Specify two latent variables without any measurements to
  # create the two new parameters (a0 and a1)
  pseudo_var_1 =~ 0*x1
  pseudo_var_2 =~ 0*x1
  pseudo_var_1 ~~ 0*pseudo_var_1
  pseudo_var_2 ~~ 0*pseudo_var_1 +0*pseudo_var_2
  # create new  parameters
  pseudo_var_1 ~  a0*1
  pseudo_var_2 ~  a1*1
  
  # predict a
  a := a0 + data.k*a1
  "
mx_mod <- metaSEM::lavaan2RAM(model = model, 
                              std.lv = FALSE)
# Change the label of a
mx_mod$A["eta", "xi"] <- ".1*a[1,1]"

mx_meta <- metaSEM::create.mxModel(RAM = mx_mod, 
                                   data = dataset) 
omxGetParameters(mx_meta)
```

**Comment by mikewlcheung** [comment]
The following code works.

By the way, the -2 log-likehoods are different in mxsem and metaSEM. I cannot find `a0` and `a1" in mxsem. I also do not know what `xi→x3` and `eta→y3` are.

```
library(metaSEM)
model <- "
  xi  =~ 1*x1 + b*x2 + x3
  eta =~ 1*y1 + b*y2 + y3
  eta ~ a*xi
  
  # predict a
  a == a0 + data.k*a1
  
  # add the intercepts
  x1 + x2 + x3 + y1 + y2 + y3 ~ 1
  "
mx_mod <- lavaan2RAM(model = model, std.lv = FALSE, auto.fix.first=TRUE)
mx_meta <- create.mxModel(RAM = mx_mod, data = dataset) 

omxGetParameters(mx_meta)
summary(mx_meta)
```

**Comment by jhorzek** [comment]
Awesome! That's better than my approach :)! 
I get exactly the same -2log-Likelihood from mxsem and metaSEM in the models above. The parameters `a0` and `a1` are also shown in the summary and `omxGetParameters`-output. I'll test it with a few other models; maybe there is a bug that prevents the variables being parsed correctly on different operating systems or R versions. 
mxsem only distinguish between directed and undirected effects. If no label is given to a directed effect, I use, for instance `eta→y3`, to indicate that there is an effect of `eta` on `y3`.
