### ISSUE TITLE
Installing Documentation for Users

### ISSUE THREAD

**Issue by cesarhenrq** [OpenMx/OpenMx#379]
Good afternoon. I tried to install OpenMx from this source https://www.openmx-square.org/download.html and i ended up with some troubles. Could someone help me with the installation or improve the documentation? Hope some help.

**Comment by mcneale** [comment]
Hi!  I think you're trying to get a different openmx than the OpenMx for statistical modeling, because we haven't gone to a 3.0 release yet.  There's a materials science package of the same name.  https://openmx.ssri.psu.edu is the link for OpenMx and it should be clear how to download from there.

**Comment by cesarhenrq** [comment]
Hi. Thank you so much, @mcneale! Sorry for this confusion. I'll close the issue.
