### ISSUE TITLE
omxRunCI ought to force SLSQP

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#38]

**Comment by RMKirkpatrick** [comment]
How about an additional argument, say, `use.SLSQP=TRUE`, to make use of SLSQP the overrideable default?

**Comment by jpritikin** [comment]
How about `optimizer="SLSQP"` ?

**Comment by jpritikin** [comment]
Or rather `optimizer="auto"` which implies SLSQP

**Comment by RMKirkpatrick** [comment]
I like `optimizer="SLSQP"`, since it's more explicit what the default behavior is.

**Comment by jpritikin** [comment]
> I like optimizer="SLSQP", since it's more explicit what the default behavior is.

Yeah but what if we find an optimizer that does better than SLSQP on confidence intervals? It would be nice if users could specify 'auto' to get the best optimizer.

**Comment by jpritikin** [comment]
Hm, OK :+1:

**Comment by tbates** [comment]
Best to do this in a way that is both auto, and shows what that will resolve to? (and how the user can get it)

Would involve adding a new option to the options list, which has the side benefit that this is accessible directly:

    optimizer = getOption("Default optimizer for CI")

**Comment by RMKirkpatrick** [comment]
`omxRunCI()` has been defaulting to SLSQP for a while.
