### ISSUE TITLE
mxRename to give more informative error when name found somewhere in model (or bug?)

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#39]
mxRename appears to be checking objects that are not models in deciding if a new name is legal.
Here's a model, called `ADE`, which I want to rename to `ACE`.  Should be legal, IMHO, but isn't:
    m1$name
    [1] "ADE"
    > m2 = mxRename(m1, "ACE")
    Error in mxRename(m1, "ACE") : 
      The name 'ACE' is already used in the model
The issue turns out to be that there's an algebra called `ACE` in a submodel of ADE.

1. I wouldn't have thought that algebras, matrices etc would be checked.
2. Inconsistently, there's no problem _creating_ a model called "ACE" in the same circumstances. And it runs fine.

It would be helpful to change the `mxRename` error to include where the first instance of the clash was found. So `"The name 'ACE' was already used in the model (m1$top$algebras$ACE)"`

BUT, should this even be illegal? If so, should it also be illegal to use the name of an algebra as a model name? I can't see why.

**Comment by jpritikin** [comment]
v2.9.9-193-g8423a04b6
