### ISSUE TITLE
Cannot install OpenMx

### ISSUE THREAD

**Issue by vvader24** [OpenMx/OpenMx#390]
> install.packages("OpenMX")
Error: package 'OpenMX' is not available

> sessionInfo()
R version 4.3.3 (2024-02-29)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.4.1

**Comment by RMKirkpatrick** [comment]
R is case sensitive.  The package name is "OpenMx", with a lower-case "x".

**Comment by vvader24** [comment]
Yes, thanks! Sorry I missed that. 
Also had to uninstall Rcpp and other Rcpp packages for removing conflicts.

**Comment by vvader24** [comment]
I can see that there have been mentions of gfortran in the past with OpenMx. I am having the same issues. Is there an easy way to resolve this? Any help is greatly appreciated! I am prepping for teaching this class tomorrow and I need this package to work!

--------------
R was unable to find the gfortran binary.
gfortran is required for the compilation of FORTRAN source files.
Please check that gfortran is installed and available on the PATH.
Please see https://stackoverflow.com/q/35999874 for more information.

Reason(s):
- 'sh: /opt/gfortran/bin/gfortran: No such file or directory'
- 'make: /opt/gfortran/bin/gfortran: No such file or directory'
install of package 'OpenMx' failed [error code 1]

**Comment by RMKirkpatrick** [comment]
Is there a reason you're trying to build the package from source instead of installing a prebuilt binary from CRAN?

**Comment by vvader24** [comment]
I think there were conflicting R version library folders that were confusing RStudio - it couldn't perhaps decide where to pick information from (not sure though). I started a new project and it all went smoothly. Definitely not an issue with the package. Thank you so much for your prompt responses.
