### ISSUE TITLE
Enhance print method for mxPath

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#45]
`mxPath` currently prints by showing their list of components (see below). It would be more informative to show the paths these will create. SO:

    mxPath(letters[1:3], connect="unique.pairs")

Would be helpfully displayed something like:

```
	# Single arrow paths
	a -> a [label="NA"];
	a -> b [label="NA"];
	b -> b [label="NA"];
	a -> c [label="NA"];
	b -> c [label="NA"];
	c -> c [label="NA"];
	# Covariances...

```
current print method
```
mxPath 
$from:  'a', 'b', and 'c' 
$to:  NA 
$arrows:  1 
$values:  NA 
$free:  TRUE 
$labels:  NA 
$lbound:  NA 
$ubound:  NA 
$connect:  unique.pairs 
$joinKey:  NA 
```

**Comment by jpritikin** [comment]
I love this idea

**Comment by jpritikin** [comment]
See v2.8.3-58-ge64f9e0bb
