### ISSUE TITLE
mxStandardizeRAMpaths include M as well as A & S

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#50]
It would be useful if mxStandardizeRAMpaths also reported standardized means (M paths). It currently ignores them.

**Comment by RMKirkpatrick** [comment]
I'm not sure how useful this would be.  Either the paths in M would be unconditional means, and therefore zero when all variables are standardized, or they would involve definition variables, and therefore vary by row.  Am I missing something.

**Comment by mcneale** [comment]
Uh, if there are definition variables, then the standardized covariance/regression paths may also vary by row.  The documentation says ‘not intended for use with models that contain definition variables.’   Do we warn or error if so used?  Should we add a defvar.row=1 argument to the function?  This last might be useful, e.g., if one wanted to get a look at the distribution of a particular standardized path across the sample.

**Comment by RMKirkpatrick** [comment]
> Uh, if there are definition variables, then the standardized covariance/regression paths may also vary by row. 

Exactly my point--the function wasn't designed to work with definition variables in the first place.

> Do we warn or error if so used?

Yes; it's a warning.

**Comment by tbates** [comment]
Hi,
I get the standardized means being 0. Mt rational for being surprised the means aren't returned is three-fold.

1. Not returning M paths implies there aren't any. By default, we should give the user all paths.
2. Even though std.means == zero, std.SEs on those will still be valuable, just like any other path, no?
3. `mxStandardizeRAMpaths` is how users get a table of SEs (both standardized and un-scaled) from a model. Not including the M paths makes it a 2-stage manual effort to extract the means paths (with no std.SEs)

**Comment by RMKirkpatrick** [comment]
> Not returning M paths implies there aren't any. By default, we should give the user all paths.

The very first sentence in the man page says that the function reports "standardized values of all nonzero path coefficients that appear in the A and S matrices".

> Even though std.means == zero, std.SEs on those will still be valuable, just like any other path, no?

No, they'll be zero, too!  The same is true for paths in the S matrix that connect a variable to itself.  The standard error for those standardized paths is always (computationally) zero, and correctly so, since over repeated sampling, the value of the standardized path never changes from 1.

> `mxStandardizeRAMpaths` is how users get a table of SEs (both standardized and un-scaled) from a model. Not including the M paths makes it a 2-stage manual effort to extract the means paths (with no std.SEs)

The point I'm trying to make here is that users have no reason to care about the standardized M paths or their SEs...at least when definition variables aren't involved.  Mike's suggestion of something like a `defvar.row` argument might be worthwhile.

**Comment by tbates** [comment]
I'll close this, but will just note that I get that the function currently doesn't inform people about non zero paths in the M matrix now. I was asking that it would. Also, the function computes SEs for non-standardized paths, so having those in the output would be helpful. I'll close here and write a wrapper to suit people's needs wanting to have a standardized model summary and get back no-standardized SEs for all paths in a model. cheers, t

**Comment by RMKirkpatrick** [comment]
Ah, OK.  I think I better understand what you're getting at.  But don't most users look at `summary()` before looking at `mxStandardizeRAMpaths()`?

**Comment by tbates** [comment]
The means thing only occurred to me writing up umx-based assumption testing scripts where some key output is how fit changes when means are equated, and I realized "oh, we aren't seeing the means in the first place, and now can't see the new value the equated path takes"

re asking users to look at summary().  The goal here (in `umx`)  is reproducible, therefore automated journal-style (markdown/latex/web) tabular and graphic output for writing papers in 1-shot, rather than looking at one thing, looking at another, pasting those into a text file or word, making errors, and having to repeat all that manual stuff when analyses are redone. So while summary, requesting SEs, followed by `mxStandardizeRAMpaths` is possible, it's not reproducible without hidden steps.
