### ISSUE TITLE
genericGenerateData not implemented for MxExpectationMixture

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#51]
See [this forums thread](https://openmx.ssri.psu.edu/node/4329).  Apparently, the generic for generating data has no method defined for the MxExpectationMixture class.  That means it's not possible to do the bootstrap LRT via `mxCompare()` for mixture models, which was the whole motivating use case for the bootstrap LRT implementation in the first place!

What an embarrassing oversight...

**Comment by jpritikin** [comment]
Hm, and I guess we require data to generate data for mxExpectationHiddenMarkov?

**Comment by RMKirkpatrick** [comment]
?
I don't see that we have a method defined for MxExpectationHiddenMarkov, either.  Am I missing something?

**Comment by jpritikin** [comment]
First part done, v2.9.2-10-g39d2e4c2f

**Comment by jpritikin** [comment]
Is there a better way to test mxGenerateData for a per-row mixture? I included a poor test in my commit. Maybe there is a better way?

**Comment by RMKirkpatrick** [comment]
It would be more efficient to first generate a random proportion _u_ from Unif(0,1), and use it to pick the mixture component to simulate from.  For example, suppose there are 3 mixture components, with proportions 0.3, 0.5, and 0.2.  If 0 < _u_ < 0.3, generate from the first component; if 0.3 < _u_ < (0.3+0.5), generate from the second component; and if (0.3+0.5) < _u_ < 1, generate from the third component.  That way, you are doing 67% fewer calls to the multivariate-normal random-number generator, and there's no need for a subsequent loop to discard unused results.

**Comment by RMKirkpatrick** [comment]
As for the test, I'll think about it.  What's in your commit looks minimally good enough.

**Comment by jpritikin** [comment]
> Edit: 67% fewer in the example case of 3 mixture proportions. The relative efficiency improvement is better still the more mixture components there are.

Yeah, I agree. However, that would require re-structuring the data generation API to do 1 row at a time.

It's definitely work a comment in the source code though.

**Comment by mcneale** [comment]
I also think that 1000’s of calls to mvrnorm/mvtnorm (even if done with apply) would be a lot more overhead than 3 (N components) calls.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Feb 26, 2018, at 4:10 PM, Joshua Pritikin <notifications@github.com<mailto:notifications@github.com>> wrote:


Edit: 67% fewer in the example case of 3 mixture proportions. The relative efficiency improvement is better still the more mixture components there are.

Yeah, I agree. However, that would require re-structuring the data generation API to do 1 row at a time.

It's definitely work a comment in the source code though.

**Comment by RMKirkpatrick** [comment]
> I also think that 1000’s of calls to mvrnorm/mvtnorm (even if done with apply) would be a lot more overhead than 3 (N components) calls.

Actually, you might be right about that, as long as the covariance matrix is the same for every row, within a mixture component.  Each call to `rmvnorm` would involve a new Eigen-decomposition (default) of the covariance matrix, plus some matrix multiplication.

**Comment by mcneale** [comment]
Inevitable if there are continuous definition variables, but presumably a saving if not.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Feb 27, 2018, at 9:38 AM, RMKirkpatrick <notifications@github.com<mailto:notifications@github.com>> wrote:


I also think that 1000’s of calls to mvrnorm/mvtnorm (even if done with apply) would be a lot more overhead than 3 (N components) calls.

Actually, you might be right about that, as long as the covariance matrix is the same for every row, within a mixture component. Each call to rmvnorm would involve a new Eigen-decomposition (default) of the covariance matrix, plus some matrix multiplication.

**Comment by jpritikin** [comment]
> I don't see that we have a method defined for MxExpectationHiddenMarkov, either.

Do people actually want to do that? Consider `mxGetExpected(model, 'weights', def.var=200)`. The weights at row 200 depend on the data from all previous rows. We'd probably need a different API because it would be so inefficient to get the weights row-by-row. Maybe leave this for future work when somebody requests it?

**Comment by jpritikin** [comment]
Let's open a new issue if data generation is needed for MxExpectationHiddenMarkov.
