### ISSUE TITLE
CSOLNP enters endless loop

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#52]
CSOLNP can enter a closed loop, such as when running the second and third MxModels in the attached script.
[180209--CSOLNP.R.txt](https://github.com/OpenMx/OpenMx/files/1764093/180209--CSOLNP.R.txt)

**Comment by jpritikin** [comment]
Is this resolved?

**Comment by zaherym** [comment]
Yes.

Best,
Mahsa
