### ISSUE TITLE
Extend data generation to models that reach outside themselves for model objects

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#56]
Basically all of the `umx` functions do this, and thus we cannot generate data for them.  The `mxGetExpected` functions handle this.  It shouldn't be too hard to fix it for data generation too.

**Comment by mhunter1** [comment]
This commit d31aa76d1c97a4f61363074e25eda3cea58761db should make this work.  However,

1. @tbates please test this.  When I ran the first `umxACE` help page model, it worked great but I haven't tested it against all the `umx` models.
1. This code seems to pass all tests on my machine, but I'm concerned that we are not testing everthing related to data generation particularly with (a) state space models and (b) relational/RAMPart models. @jpritikin could you do some testing with this (assuming the nightly tests pass)?

**Comment by tbates** [comment]
I'll run some tests on umxCP, umxSimplex etc. and add this as an example to umxACE

**Comment by jpritikin** [comment]
Nightly tests passed so I guess things are in good shape. I'm not sure what else to test. All tests that I've written are part of the test suite.

**Comment by mhunter1** [comment]
I'll check it on a multilevel BG model and a 3- or 4-level model I've used before.  I'm nervous when things seem to work this easily ...

**Comment by jpritikin** [comment]
It's probably done.
