### ISSUE TITLE
Alias imxJiggle as mxJiggle

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#58]
Sarah Medland believes putting `imx` in front of jiggle makes it sad.  Why don't we just alias `imxJiggle` as `mxJiggle`.

```
mxJiggle <- imxJiggle
```

**Comment by RMKirkpatrick** [comment]
OK by me, but the man page for it needs a bit more detail if it's going to be prefixed with 'mx'.  I'll take care of it.

**Comment by RMKirkpatrick** [comment]
If the requested feature is literally just to alias `imxJiggle()` as `mxJiggle()`, then all that's needed is to make the documentation page a bit more detailed so to be appropriate for an 'mx*'.  But if the requested feature is something more like what keyword `JIGGLE` did in classic Mx (see attachment), then a new function seems warranted.
[Classic Mx Jiggle.pdf](https://github.com/OpenMx/OpenMx/files/1880300/Classic.Mx.Jiggle.pdf)

**Comment by mcneale** [comment]
Right, classic Mx's THard option is covered by mxTryHard() if the scale parameter is set to zero - it should refit from the previous "solution," with no jiggling.

**Comment by RMKirkpatrick** [comment]
See c57b152.

**Comment by tbates** [comment]
Would it be helpful to build a man page for `?mx2OpenMx` commands? (not sure how many people are using Mx now?, might be diminishing returns?)

Here's a starter:

| Mx          | OpenMx      |
|:------------|:-----------------|
| TH          | mxTryHard  |
