### ISSUE TITLE
Alias mxTryHard as mxTHard

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#59]
This preserves the old naming, and gives Sarah one less thing to complain about.

**Comment by RMKirkpatrick** [comment]
Yeah, but the classic Mx manual explains that keyword `THard` (of which the first two characters is enough to distinguish it) stands for "try hard".

**Comment by tbates** [comment]
+1 for adding:
`#' @aliases THard`

**Comment by RMKirkpatrick** [comment]
Done.
