### ISSUE TITLE
Use match.arg in mxMatrix to partially match the type argument

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#63]
We want `mxMatrix('Sdiag')`, `mxMatrix('Sd')`, and `mxMatrix('sd')` to all produce matrices of type `Sdiag`.  Likewise of course for `Symm` and the other matrix types.

**Comment by tbates** [comment]
Good idea! Also nice as it lists all the options in the parameter.
Users have to get the case right (and be unambiguous), so `sd` won't match.
```
    match.arg(c('Sdiag', 'Sd', 'sd'), c("Sdiag"), several=T)
    [1] "Sdiag" "Sdiag"
```

**Comment by mhunter1** [comment]
That's fixable.

```
simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ")
}
match.arg(simpleCap(tolower('sd')), c("Sdiag", "Stand", "Symm"))
```

**Comment by tbates** [comment]
Unless we want to train people to do the right thing. Maybe say "did you mean "Sd" ?

**Comment by mhunter1** [comment]
Change the default value of `type` to e.g. `c('Full', 'Symm', 'Sdiag', 'Diag')`

**Comment by jpritikin** [comment]
Maybe done in v2.9.6-13-g82a90c82f
