### ISSUE TITLE
Add an ssri-based url for travis, share secure links with users

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#69]
1. durable travis link
  * We should add an ssri url which redirects to wherever the travis builds are stored.
  * e.g. https://openmx.ssri.psu.edu/software/travis
2. Make the getOpenMx.R url we share with users should a secure (https) link.
  * Many services (including CRAN) are deprecating non-secure connections

**Comment by RMKirkpatrick** [comment]
+1 for https

**Comment by jpritikin** [comment]
Fixed since when? Not sure but closing
