### ISSUE TITLE
More information on non-conformable algebra errors

### ISSUE THREAD

**Issue by mcneale** [OpenMx/OpenMx#72]
This error:
Error in runHelper(model, frontendStart, intervals, silent, suppressWarnings,  : 
  Non-conformable matrices in horizontal concatenation (cbind). First argument has 11 rows, and argument #2 has 4 rows.
is helpful, but it would be _even more useful_ if it reported which mxAlgebra in which mxModel gave rise to it.

**Comment by jpritikin** [comment]
We already provide the information about which algebra is involved when we evaluate the algebra in the back-end. What your seeing is the error message from the front-end, over which we have no control. So perhaps the issue should be a call to move all evaluation of algebras from the front-end to the back-end.

**Comment by mcneale** [comment]
Fair enough... I am not sure that back-ending everything is worth it though.  I suppose using try() with a suitably informed error branch isn't going to help the front end out either.  Or be inefficient or tedious to code.
