### ISSUE TITLE
Error when running MxAutoStart

### ISSUE THREAD

**Issue by ShawnVIPBG** [OpenMx/OpenMx#80]
Following error that was not present as of last Thursday (05/08/2018): 

Error in omxSetParameters(model, values = newparams, labels = names(oldparams)) : 
  'labels' argument must be a character vector

Any help appreciated.

Thanks!

**Comment by RMKirkpatrick** [comment]
Gonna need some context and more detail here.  Can you provide a minimal R script that reproduces the issue?  How were objects `newparams` and `oldparams` created?  What is your `mxVersion()` output now?  What version were you running last Thursday?

**Comment by RMKirkpatrick** [comment]
I see. `newparams` and `oldparams` are created internally to `mxAutoStart()`. Could you run `traceback()` right after the error is thrown, and post the output?

**Comment by ShawnVIPBG** [comment]
> traceback()
3: stop("'labels' argument must be a character vector")
2: omxSetParameters(model, values = newparams, labels = names(oldparams))
1: mxAutoStart(model)

**Comment by tbates** [comment]
looks like room for improvement in `mxAutoStart` input checking and reporting.

From the example you gave, mike (thanks), it runs fine (after the data are given names)

Perhaps something like this is what is tripping up mxAutoStart - getting a nothing burger when expecting a list of labels?

**Comment by ShawnVIPBG** [comment]
So I tried running the mxAutoStart in its totality from the GitHub website.  It appears as though the labels are assigned the names of the coefficients from the original model:

oldparams <- coef(model)
model <- omxSetParameters(model, values=newparams, labels=names(oldparams))

I'm wondering if I'm now getting this error because my original model is just not producing coefficients.  This is clearly a change from last week when it was producing coefficients which allowed me to run the mxAutoStart function which does not solve my quandary but does answer the mxAutoStart questions.  Thanks for the help and sorry for the confusion!

**Comment by mhunter1** [comment]
I made a tweak to `mxAutoStart`.  It now does all the checking the `mxRun` does prior to itself running.  So in response to @mcneale 's model it now produces

```
Error: The dataset associated with the RAM expectation function in model 'Correlated_Mediation_ML' does not contain column names (use dimnames).
```

instead of

```
Error in model[[subname]]$data$observed[, useVars] : 
  subscript out of bounds
```

This is friendlier, but still an error.  And I think the error is appropriate.

With regard to what is happening with @ShawnVIPBG 's model, I have no idea.

@ShawnVIPBG can you run the following modified script and report back what it says?

```
require("OpenMx");
modelData <- read.table("LEAUdat.csv", sep=",", header = TRUE) 
manifests<-c("AUDIT_Tot","PCL5_Tot","MaxTRD","DMQ_COPE")
latents<-c("ErrorAUD","ErrorTRD","ErrorDMQ")
model <- mxModel("Correlated_Mediation_ML", 
                 type="RAM",
                 manifestVars = manifests,
                 latentVars = latents,
                 mxPath(from="PCL5_Tot",to=c("MaxTRD","DMQ_COPE","AUDIT_Tot"), free=c(TRUE,TRUE,TRUE), value=c(0.03,0.1,-0.02) , arrows=1, label=c("PCL5_Tot__MaxTRD","PCL5_Tot__DMQ_COPE","PCL5_Tot__AUDIT_Tot") ),
                 mxPath(from="MaxTRD",to=c("AUDIT_Tot"), free=c(TRUE), value=c(1.4) , arrows=1, label=c("MaxTRD__AUDIT_Tot") ),
                 mxPath(from="DMQ_COPE",to=c("AUDIT_Tot"), free=c(TRUE), value=c(0.45) , arrows=1, label=c("DMQ_COPE__AUDIT_Tot") ),
                 mxPath(from="ErrorAUD",to=c("AUDIT_Tot"), free=c(TRUE), value=c(4.5) , arrows=1, label=c("Error__AUDIT_Tot") ),
                 mxPath(from="one",to=c("PCL5_Tot","MaxTRD","DMQ_COPE","AUDIT_Tot"), free=c(TRUE,TRUE,TRUE,TRUE), value=c(15.14,1.1,7.07,1.18) , arrows=1, label=c("const__PCL5_Tot","const__MaxTRD","const__DMQ_COPE","const__AUDIT_Tot") ),
                 mxPath(from="ErrorTRD",to=c("MaxTRD"), free=c(TRUE), value=c(0.79) , arrows=1, label=c("ErrorTRD__MaxTRD") ),
                 mxPath(from="ErrorDMQ",to=c("DMQ_COPE"), free=c(TRUE), value=c(3.71) , arrows=1, label=c("ErrorDMQ__DMQ_COPE") ),
                 mxPath(from="PCL5_Tot",to=c("PCL5_Tot"), free=c(TRUE), value=c(290.83) , arrows=2, label=c("VAR_PCL5_Tot") ),
                 mxPath(from="MaxTRD",to=c("DMQ_COPE"), free=c(TRUE), value=c(1.5) , arrows=2, label=c("COV_MaxTRD_DMQ_COPE") ),
                 mxPath(from="ErrorAUD",to=c("ErrorAUD"), free=c(FALSE), value=c(1.0) , arrows=2, label=c("VAR_Error") ),
                 mxPath(from="ErrorTRD",to=c("ErrorTRD"), free=c(FALSE), value=c(1.0) , arrows=2, label=c("VAR_ErrorTRD") ),
                 mxPath(from="ErrorDMQ",to=c("ErrorDMQ"), free=c(FALSE), value=c(1.0) , arrows=2, label=c("VAR_ErrorDMQ") ),
                 #mxCI(c("name of path", "SSS"),
                 mxData(modelData, type = "raw")
)

### MODIFICATION HERE
coef(model)
names(coef(model))
# Please report what these result in.
### END MODIFICATION

result <- mxAutoStart(model)
result1 <- mxRun(result)
summary(result1)
```

**Comment by jpritikin** [comment]
No progress since June. Is this issue still open? Re-open if so.
