### ISSUE TITLE
models/nightly/thresholdModel1Factor5VariateWLS.R fails sometimes

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#81]
Can prevent nightly tests from passing,

```
Number of errors: 1 
Error NPSOL models/nightly/thresholdModel1Factor5VariateWLS.R ***
[1] "'0.838354961060759' does not estimate '0.653720195588709' within 16 percent"
```

**Comment by jpritikin** [comment]
Fixed with new backend code?

**Comment by mcneale** [comment]
Under OS X, seems ok with CSOLNP:
> omxCheckCloseEnough(omxGetParameters(wrun2), omxGetParameters(wrun2a), 1e-4)
omxGetParameters(wrun2) and omxGetParameters(wrun2a) are equal to within 1e-04.
> omxGetParameters(wrun2) - omxGetParameters(wrun2a)
thresholdModel2.L[1,1] thresholdModel2.L[2,1] thresholdModel2.L[3,1] thresholdModel2.L[4,1] thresholdModel2.L[5,1] 
         -1.224248e-08           2.922817e-08          -7.362718e-09           2.083658e-08           2.510078e-09 
thresholdModel2.R[1,1] thresholdModel2.R[2,2] thresholdModel2.R[3,3] thresholdModel2.R[4,4] thresholdModel2.R[5,5] 
         -3.344936e-08           7.786195e-08           1.947371e-08           2.563260e-09          -8.627271e-08 
thresholdModel2.M[1,1] thresholdModel2.M[1,2] thresholdModel2.M[1,3] thresholdModel2.M[1,4] thresholdModel2.M[1,5] 
          5.453259e-08           4.463217e-08           2.124393e-08           5.640436e-08          -9.700219e-09 
> mxVersion()
OpenMx version: 2.12.1 [GIT v2.12.1]
R version: R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 
MacOS: 10.12.6
Default optimizer: CSOLNP
NPSOL-enabled?: Yes
OpenMP-enabled?: Yes

**And with NPSOL:**

> omxCheckCloseEnough(omxGetParameters(wrun2), omxGetParameters(wrun2a), 1e-4)
omxGetParameters(wrun2) and omxGetParameters(wrun2a) are equal to within 1e-04.
> omxGetParameters(wrun2) - omxGetParameters(wrun2a)
thresholdModel2.L[1,1] thresholdModel2.L[2,1] thresholdModel2.L[3,1] thresholdModel2.L[4,1] thresholdModel2.L[5,1] 
         -3.283891e-10          -1.338756e-10           3.161753e-10           2.016488e-10          -5.831700e-10 
thresholdModel2.R[1,1] thresholdModel2.R[2,2] thresholdModel2.R[3,3] thresholdModel2.R[4,4] thresholdModel2.R[5,5] 
         -2.845939e-10           7.551180e-10           6.096457e-12           3.298301e-10           5.437045e-10 
thresholdModel2.M[1,1] thresholdModel2.M[1,2] thresholdModel2.M[1,3] thresholdModel2.M[1,4] thresholdModel2.M[1,5] 
         -1.380440e-11           4.335972e-10           3.656844e-10          -2.881592e-10           3.334373e-10 

**And with SLSQP**
> omxCheckCloseEnough(omxGetParameters(wrun2), omxGetParameters(wrun2a), 1e-4)
omxGetParameters(wrun2) and omxGetParameters(wrun2a) are equal to within 1e-04.
> omxGetParameters(wrun2) - omxGetParameters(wrun2a)
thresholdModel2.L[1,1] thresholdModel2.L[2,1] thresholdModel2.L[3,1] thresholdModel2.L[4,1] thresholdModel2.L[5,1] 
         -1.812106e-12           1.880496e-12           3.733236e-12           4.224066e-12          -1.522560e-12 
thresholdModel2.R[1,1] thresholdModel2.R[2,2] thresholdModel2.R[3,3] thresholdModel2.R[4,4] thresholdModel2.R[5,5] 
         -4.430012e-12          -5.405010e-12           1.786304e-11          -3.933520e-12           2.746803e-12 
thresholdModel2.M[1,1] thresholdModel2.M[1,2] thresholdModel2.M[1,3] thresholdModel2.M[1,4] thresholdModel2.M[1,5] 
         -1.179279e-12           3.089529e-12          -3.697265e-12           1.112888e-12           6.339484e-12 

There seems to be some (minor) numerical precision differences between the solutions: CSOLNP around e-09, NPSOL  e-10, SLSQP e-12.

I don't see an issue here, though.  "Sometimes fails in the test suite" suggests something untoward within the test suite context - maybe a prior memory leak or something?

**Comment by RMKirkpatrick** [comment]
Maybe replace `mxRun()` with `mxTryHardOrdinal()` and set the RNG seed in the line before?

**Comment by tbates** [comment]
under CSOLNP, I'm getting code RED for thresholdModelAutoRun
```RSplus
thresholdModelAutoRun <- mxRun(thresholdModelAuto)
```
Yields code RED (status code 6 for CSOLNP & NPSOL, and 5 for SLSQP).

Interestingly, the time to run `mxAutoStart(thresholdModel)` appears to have dropped from 2 seconds (on an unspecified laptop on some earlier version of OpenMx) to ~.07 Seconds (as of 2.12.2.169 [GIT v2.12.2-169-gb745620] on my 3.3 GHz Intel Core i7 iMac).

AutoStarts, however, are providing a net loss in speed:

```R
# time for finding auto plus run from their
(b-a) + summary(thresholdModelAutoRun)$wallTime
Time difference of 13.62882 secs

# time for running from default starts
summary(thresholdModelrun)$wallTime
Time difference of 10.38402 secs
```

I wonder about some of the accuracy checks - they seem designed to let the results pass rather than to meet some external criteria.  Like, why accept 10% and 16% here? likewise for several other values...

```R
omxCheckWithinPercentError(wls.sum$Chi, 0.653, percent=10)
omxCheckWithinPercentError(ml.sum$Chi, wls.sum$Chi, percent=16)
```

**Comment by mcneale** [comment]
Is this problem only occurring on a Linux box or something?  Can't reproduce.  

The code red for ML - which involves numerical integration - is to be expected.  Most uses of numerical integration in a fit function seem to end with this error. IME almost all are ignorable as they are at or very close indeed to the correct solution.  A code red with continuous data, on the other hand, often indicates that the model is (at least locally) under-identified.

**Comment by RMKirkpatrick** [comment]
> Is this problem only occurring on a Linux box or something? Can't reproduce.

I only recall ever seeing it occur during the nightly run.  I can't reproduce on my Debian laptop.

**Comment by jpritikin** [comment]
I can't reproduce it either.

**Comment by mcneale** [comment]
With what frequency does it fail during the nightly runs?

**Comment by jpritikin** [comment]
> With what frequency does it fail during the nightly runs?

I'm not sure. Maybe once a month?

**Comment by jpritikin** [comment]
Failed today,

```
travis_fold:end:NPSOL
Number of errors: 1 
Error NPSOL models/nightly/thresholdModel1Factor5VariateWLS.R ***
[1] "'0.768248189991027' does not estimate '0.638483471397956' within 16 percent"

```

**Comment by mcneale** [comment]
Is that due to a commit?  Or just some random ghost in the machine?

**Comment by jpritikin** [comment]
> Is that due to a commit? Or just some random ghost in the machine?

I'm pretty sure that it's the ghost.

**Comment by jpritikin** [comment]
Error NPSOL models/nightly/thresholdModel1Factor5VariateWLS.R ***
[1] "'0.771790669889015' does not estimate '0.638483471397956' within 16 percent"

**Comment by jpritikin** [comment]
Error NPSOL models/nightly/thresholdModel1Factor5VariateWLS.R ***
[1] "'0.196631915119724' does not estimate '0.638483471397956' within 16 percent"

**Comment by jpritikin** [comment]
Error NPSOL models/nightly/thresholdModel1Factor5VariateWLS.R ***
[1] "'0.760691067542211' does not estimate '0.638483471397956' within 16 percent"

**Comment by jpritikin** [comment]
Hm, only NPSOL fails. Maybe skip the test when using NPSOL?

**Comment by RMKirkpatrick** [comment]
> Hm, only NPSOL fails. Maybe skip the test when using NPSOL?

Perhaps.  Don't we have at least one other WLS test that consistently fails with NPSOL?

**Comment by jpritikin** [comment]
>  Don't we have at least one other WLS test that consistently fails with NPSOL?

Yeah, at least one.
