### ISSUE TITLE
mxRun with no free parameters shall do mxComputeOnce('fitfunction', 'fit')

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#83]
This behavior is probably better than Error: The job for model exited abnormally with the error
message: MxComputeGradientDescent: model has no free parameters

**Comment by jpritikin** [comment]
Hey wait, this is already implemented,

```
	if (numParam == 0 && defaultComputePlan && !is.null(model@fitfunction)) {
		compute <- mxComputeSequence(list(CO=mxComputeOnce(from=paste(model@name, 'fitfunction', sep="."),
								   'fit', .is.bestfit=TRUE),
						  RE=mxComputeReportExpectation()))
```

I'm puzzled how Steve Aggen got error message: MxComputeGradientDescent: model has no free parameters. Surely he wasn't use a custom compute plan?

**Comment by mcneale** [comment]
No, he was not… but the error message must be in the code somewhere!

On May 24, 2018, at 10:33 AM, Joshua Pritikin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey wait, this is already implemented,

        if (numParam == 0 && defaultComputePlan && !is.null(model@fitfunction)) {
                compute <- mxComputeSequence(list(CO=mxComputeOnce(from=paste(model@name, 'fitfunction', sep="."),
                                                                   'fit', .is.bestfit=TRUE),
                                                  RE=mxComputeReportExpectation()))


I'm puzzled how Steve Aggen got error message: MxComputeGradientDescent: model has no free parameters. Surely he wasn't use a custom compute plan?

**Comment by jpritikin** [comment]
>  but the error message must be in the code somewhere!

Oh, I know where the error message comes from. It's from mxComputeGradientDescent, but that compute step should not have been in the model's compute plan. I can't imagine how it got there.

**Comment by RMKirkpatrick** [comment]
What's the context for this issue being opened?

**Comment by jpritikin** [comment]
@RMKirkpatrick There was an email exchange that Mike Neale forwarded to me. I'll copy it here.

**Comment by mcneale** [comment]
Yeah, a bit.  Can we tell if they are using a custom compute plan?  It seems that that should be the only way to get to the error, right?  Anything else, better call Saul, or Josh in this case :)

**Comment by mcneale** [comment]
I just used some basic syntax to apply the starting values from a different run to the same model fit with a different precision setting... The version of OpenMx that ran the model and was saved as an R environment was different from the OpenMx version that I ran in the interactive session to reestimate the model with the applied values that were fixed. Here is the code and the OpenMx versions:


testm001 <- omxSetParameters(model1fRefit, labels=names(pe_model001), values=pe_model001, free=F)
Run(testm001)
> testm001Fit <- mxRun(testm001)
Running refit1f with 0 parameters
Error: The job for model 'refit1f' exited abnormally with the error message: MxComputeGradientDescent: model has no free parameters

Looks like if the version for the R interactive session is a newer one, things are ok:

OpenMx version R environment was saved under:
OpenMx version: 2.8.3 [GIT v2.8.3-dirty]

OpenMx version that was called for the interactive session:
OpenMx version: 2.9.9.190 [GIT v2.9.9-190-g24a42eb-dirty]



________________________________

**Comment by jpritikin** [comment]
Good idea, v2.9.9-199-gc355423ce
