### ISSUE TITLE
add adaptive simulated annealing

### ISSUE THREAD

**Issue by jpritikin** [OpenMx/OpenMx#84]
Should be fairly straightforward. Well tested BSD licensed C library is available.

**Comment by jpritikin** [comment]
Link here, https://sourceforge.net/projects/asa-caltech/

**Comment by mcneale** [comment]
Good.  Any issues with bundling BSD licensed software with our current licensing?

**Comment by jpritikin** [comment]
Re license compatibility, I don't think there is any problem. See https://softwareengineering.stackexchange.com/questions/40561/is-bsd-license-compatible-with-apache#40571

**Comment by jpritikin** [comment]
v2.9.9-204-g44983e1e8
