### ISSUE TITLE
Add scale='none' option for mxExpectationMixture 

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#87]
This augments the existing options: 'softmax' and 'sum'.  The value `scale='none'` wouldn't do any scaling at all.  It let's the user do whatever they please.  The use-case here is a user that has a fixed set of weights they want to use.

**Comment by jpritikin** [comment]
You want a mixture that doesn't sum to 1.0?

**Comment by mhunter1** [comment]
It could be a mixture that doesn't sum to 1.0, or one that the user has scaled themselves and doesn't want summed for whatever reason.
