### ISSUE TITLE
add standardized intercepts to mxStandardizeRAMpaths() output

### ISSUE THREAD

**Issue by TDJorgensen** [OpenMx/OpenMx#89]
Hello, and thanks for a great software package!

I maintain the semTools package, which had some utility functions, such as fit indices and standardized coefficients for OpenMx fitted models, which are now available in OpenMx proper.  I am deprecating/removing these from semTools, but I noticed that `mxStandardizeRAMpaths()` only provides standardized estimates of covariance structure parameters.  Would you consider adding standardized intercepts?  Expressing the distance of a mean/intercept from zero in units of _SD_ has some utility, allowing Cohen's _d_ to be easily calculated as differences between groups or occasions. 

I think this would be straight-forward to add, conditional on the existence of `(sub)model$expectation$M`, and perhaps an argument along the lines of `meanstructure=TRUE` (so that `FALSE` would preserve the current behavior).  The `.mxStandardizeRAMhelper()` function would have to similarly create `Mpos` so that `.standardizeParams()` can return standardized estimates calculated as `InvSD %*% M`.

I'm not part of your development team, but if you are willing to add this enhancement, let me know if you prefer me to work out an example and make a pull request to try and save you time.  You can see our implementation here:

https://github.com/simsem/semTools/blob/master/semTools/R/standardizeMx.R

**Comment by RMKirkpatrick** [comment]
More or less the same feature [has been discussed in the past ](https://github.com/OpenMx/OpenMx/issues/50), and ultimately not implemented.  I still don't understand how such a feature would be useful in core OpenMx.  Could you provide a use-case example where it's actually helpful to have such a feature?

**Comment by tbates** [comment]
I agree this is useful: if only to avoid the oddity of having means in raw units alongside parameters in z units. Also avoids error, as currently the user has to figure out a way to separately replace the now-invalid means.

**Comment by TDJorgensen** [comment]
I wondered whether this would be the objection somebody raised :-)  Sorry in advance for the long post. 

I understand that strictly speaking, standardized estimates are meant to refer to estimates that would be obtained if all variables were standardized (_M_ = 0, _SD_ = 1), in which case all unconditional means and intercepts would be zero. But Cohen's _d_ is a "standardized mean difference" that is not tautologically zero because all that is meant by "standardized" in this case is that the outcome variable has unit variance.  So instead of imagining we converted all variables to _z_ scores, imagine that we only divide variables by their _SD_s.  Slopes, then, would still be expressed as effects in units of _SD_, and standardized mean structure would also express means/intercepts in units of _SD_.  

Again, the utility of this is primarily in easy calculation of differences/changes in (un)conditional means between groups / across repeated measures, where differences in units of _SD_ can be interpreted as Cohen's _d_.  Adapting the `?mxFitFunctionMultigroup` help-page example to have different intercepts and non-unit variance provides a simple example:
```
set.seed(11235)
N1=100
x=rnorm(N1, mean=0, sd=2)
y= -0.5 + 0.5*x + rnorm(N1, mean=0, sd=1)
ds1 <- data.frame(x, y)
dsNames <- names(ds1)

N2=150
x=rnorm(N2, mean=0, sd=2)
y= 0.5 + 0.5*x + rnorm(N2, mean=0, sd=sqrt(1.5))
ds2 <- data.frame(x, y)

M1 <- mxMatrix(type = "Full", nrow = 1, ncol = 2, values=0,
              free=TRUE, labels=c("Mx", "My1"), name = "M")
M2 <- mxMatrix(type = "Full", nrow = 1, ncol = 2, values=0,
              free=TRUE, labels=c("Mx", "My2"), name = "M")
S1 <- mxMatrix(type = "Diag", nrow = 2, ncol = 2, values=1, 
              free=TRUE, labels=c("Vx", "ResidVy1"), name = "S")
S2 <- mxMatrix(type = "Diag", nrow = 2, ncol = 2, values=1, 
              free=TRUE, labels=c("Vx", "ResidVy2"), name = "S")
A <- mxMatrix(type = "Full", nrow = 2, ncol = 2, values=c(0,1,0,0), 
              free=c(FALSE,TRUE,FALSE,FALSE), labels=c(NA, "b", NA, NA),
              name = "A")
I <- mxMatrix(type="Iden", nrow=2, ncol=2, name="I")
expect <- mxExpectationRAM('A', 'S', 'I', 'M', dimnames=dsNames)
fitFunction <- mxFitFunctionML(rowDiagnostics=TRUE)
mgFitFun <- mxFitFunctionMultigroup(c('g1model', 'g2model'))
m1 <- mxModel(model="g1model", M1, S1, A, I, expect, fitFunction, 
              mxData(observed=cov(ds1), type="cov", numObs=nrow(ds1),
                     means=colMeans(ds1)))
m2 <- mxModel(model="g2model", M2, S2, A, I, expect, fitFunction, 
              mxData(observed=cov(ds2), type="cov", numObs=nrow(ds2),
                     means=colMeans(ds2)))
mg <- mxModel(model='multipleGroup', m1, m2, mgFitFun)
mgOut <- mxRun(mg)
summary(mgOut)$parameters
```
Because the effect of `x` is constrained to equality across groups (homogeneity of slopes), we can say that controlling for `x`, the adjusted-mean difference is the difference between intercepts: `-0.305 - 0.489 = 0.794`.  Using `semTools::standardizeMx()` to obtain "standardized" mean-structure estimates:
```
semTools::standardizeMx(mgOut)
```
The same difference in a "standardized" metric (Cohen's _d_) is `-0.218 - 0.318 = -0.536`.  This is commonly relied on as a measure of effect size, and in the case where we want to compare means of latent common factors with arbitrary scales/locations, this standardized mean difference might be all that is of interest.

A related but separate issue with the standardization currently provided by `mxStandardizeRAMpaths()` is that residual covariances among (e.g.) the same indicators measured on repeated occasions are not expressed as residual correlations, because they are not scaled by the residual _SD_s but by the total _SD_s.  It is substantively interesting to scale residual variances by total variances, resulting in proportions of unexplained variance (1 minus R-squared), as other SEM software report.  But Mplus and lavaan report residual _co_covariances as scaled by residual _SD_s because residual correlations are what people are generally interested in.  I don't see how it would be interesting to interpret a residual covariance in units of the variables' _SD_s instead of units of the residuals' _SD_s, but someone brought it up on the lavaan board in the past, leading @yrosseel to add a `cov.std` argument to choose which way users want to standardize off-diagonal elements of the LISREL Theta matrix:

https://github.com/yrosseel/lavaan/blob/master/R/lav_standardize.R

I am not arguing that you adopt the same convention for RAM parameterization, because I am not sure this generalizes to models other than the common-factor model (although I expect it does).  I just bring it up because the term "standardized" is used more loosely than "the observed variables are _z_ scores", depending on the context.  Honestly, I have trouble calling these standardized at all when we don't use population parameters, but sample estimates of them (perhaps studentized is a more appropriate term?).  I think it is more useful to simply refer to "scaling" estimates by useful quantities that make the scaled estimate interpretable without reference to particular units of measurement.  I expect there are OpenMx users besides myself who would like to be able to see mean structure estimates expressed in units of _SD_, but at the very least, as @tbates points out, there are programmers who want to store unstandardized and standardized estimates side-by-side, so it would be useful if `mxStandardizeRAMpaths()` returned objects of the same size as `summary(...)$parameters`.

Thanks for reconsidering this issue.

**Comment by mcneale** [comment]
Seems reasonable to me.  

Have you thought about the consequences are for multi-group analyses?  The same mean difference, e.g., could have a different Cohen's D in different groups.

**Comment by TDJorgensen** [comment]
Yes, and I think they are the same issues that would arise in the context of simple _t_ tests when the groups have different variances.  The solution there has been to calculate a pooled variance for the denominator of the test statistic, which we can also use to calculate Cohen's _d_, but the criticism is that the pooled sample variance does not really corresponded to a population parameter.  I think scaling the group means separately by their own _SD_ before calculating the difference suffers from the same problem.   Personally, when populations have different variances, I prefer to use Glass' Delta, which uses the control group's _SD_ (or a reasonably chosen reference group, more generally) as the reference scale for calculating a standardized mean difference, although this avoids rather than solves the issue.  This hasn't received a lot of attention in the context of structured means modeling, e.g., Hancock ([2001](https://link.springer.com/article/10.1007/BF02294440)) merely stated the homogeneity assumption when defining Cohen's _d_ in the context of factor and MIMIC models, and he later ([2012](http://journals.sagepub.com/doi/abs/10.3102/1076998610396897)) investigated the effect of heteroskedasticity on different robust test statistics, but without giving further discussion to standardized mean differences in this context.

**Comment by RMKirkpatrick** [comment]
> So instead of imagining we converted all variables to z scores, imagine that we only divide variables by their _SD_s. Slopes, then, would still be expressed as effects in units of SD, and standardized mean structure would also express means/intercepts in units of SD.

OK, based on your OP, I suspected that's what you had in mind, but wasn't sure.  I can see now why a feature that behaves as you describe could be useful.

While I'm thinking about it...in a multilevel RAM model, `mxStandardizeRAMpaths()` doesn't include results for the between-level paths (since they don't exist in the _A_ or _S_ matrices).  Should it (@jpritikin ? @mhunter1 ?) ?

> as @tbates points out, there are programmers who want to store unstandardized and standardized estimates side-by-side, so it would be useful if mxStandardizeRAMpaths() returned objects of the same size as summary(...)$parameters

In OpenMx v1.x, standardized RAM coefficients were actually reported in `summary()`'s 'parameters' table.  There are very good [reasons](https://openmx.ssri.psu.edu/thread/2833) why `mxStandardizeRAMpaths()`'s output table has one row for every nonzero path coefficient, rather than one row per free parameter.  It was a deliberate design decision for `mxStandardizeRAMpaths()`'s output _not_ to be the same length as `summary()`'s 'parameters' table.

**Comment by TDJorgensen** [comment]
> There are very good reasons why mxStandardizeRAMpaths()'s output table has one row for every nonzero path coefficient, rather than one row per free parameter

Oh, right, to see standardized analogs of the fixed parameters (e.g., factor loadings fixed to 1 for identification).

**Comment by tbates** [comment]
@TDJorgensen  And also because if the user has equated paths, the 1 row per masks all but one of the equated parameters. 

I miss-spoke when I said same size as summary$parameters. I'd say summary should do this as well, but that's history. A common use of `mxStandardizeRAMpaths` in `umx` is to get the complete list of free paths for passing to S3 `plot` methods.

**Comment by RMKirkpatrick** [comment]
@TDJorgensen , @tbates : See beba16f.  Please test and let me know if I can close this issue.

**Comment by TDJorgensen** [comment]
Yes, using the multigroup example I posted above, I get the same standardized estimates from OpenMx as from the semTools function.  Unless @tbates has something to add, I think you can close this issue.

Thanks!

**Comment by RMKirkpatrick** [comment]
OK, great!
