### ISSUE TITLE
allow mxGenerateData to assume means = 0

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#90]
Given a RAM model with no means model, `mxGenerateData` currently returns the error below.
It would be a nice help for researchers wanting to generate data to just add means = 0 for them and return a warning that this happened, instead of an error.

```splus
m2 = mxGenerateData(m1, nrows=100)
# Error in generateNormalData(model, nrows, subname) : 
#  Cannot generate data from model 'OneFactor' where means are not specified
```

**Comment by jpritikin** [comment]
v2.9.9-234-g157739bce

**Comment by tbates** [comment]
Thanks!

FYI, I made a [little blog post](http://tbates.github.io/technical/1950/06/10/practical-simulation.html)  on `mxGenerateData`, as well as `umx_make_TwinData` and making data for Mendelian Randomization using `umx_make_MR_data`

**Comment by mcneale** [comment]
Nice Blog post!  I saw the growth curve one in progress too.  Perhaps you could add links to the OpenMx youtube channel offerings on the same?  Ideally, there would be a good correspondence between the two.

**Comment by tbates** [comment]
Good idea! I'll add links
