### ISSUE TITLE
mxPower output a structure

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#91]
`mxPower` just outputs a number. This is ambiguous, and allows users to make errors.
We should output a structure, similar to that output by `power.t.test`, which is self-documenting:

```splus
   x= power.t.test(n = 20, delta = 1)
                 n = 20
             delta = 1
                sd = 1
         sig.level = 0.05
             power = 0.8689528
       alternative = two.sided
```

For mxPower, the output could be:

```splus
               n= 1000
          power = .8
      sig.level = 0.05
 parameterDelta = .02
  parameterName = ."One Factor.A[1,6]”
```

Users can then see this whole output with `print`, or  extract the element they think they computed from the resulting object with $ accessor:

```splus
x = mxPower(...) 
x$power # 0.8689528
```

It might be useful to allow coercion (`as.numeric(foo)`) to reduce this to a number, but that's ambiguous and it's easier to just type the accessor

### Example of confusion
```splus
data(demoOneFactor); manifests <- names(demoOneFactor); latents <- c("G")
m1 <- mxModel("One Factor”,  type="RAM”, manifestVars = manifests, latentVars = latents,
                       mxPath(from=latents, to=manifests, values=0.8),
                       mxPath(from=manifests, arrows=2,values=1),
                       mxPath(from=latents, arrows=2, free=FALSE, values=1.0),
                       mxPath(from="one", to=manifests),
                       mxData(demoOneFactor, type="raw”)
)

m1 <- mxRun(m1)
 
m2 <- m1
m2$A$values['x1','G'] <- 0
m2$A$free['x1','G'] <- FALSE

# does the model need to be run?
m2 <- mxRun(m2)
 
mxPower(trueModel= m1, falseModel= m2, n = 1000)
Search One Factor.A[1,6]:power relationship for n=1000
[1] 0.02529609

```
I thought this was computing power, and the answer was the completely-off `.02`. But in fact by adding `n`, the function tries to compute something quite different, namely:

> How different from 0 (falseModel value for `One Factor.A[1,6]'`  ) does `One Factor.A[1,6]` have to be to give the user 80% power to  detect that difference, at a sample size 1000.

**Comment by jpritikin** [comment]
Try v2.9.9-233-gefa6457c8 or newer
