### ISSUE TITLE
Return (squared) Mahalanobis distance with rowDiagnostics=TRUE

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#92]
In `mxFitFunctionML(..., rowDiagnostics=TRUE)` we currently return the row likelihoods (really row probability density values).  We should also return 

1. The number of observed variables for each row (`numObsVars`)
1.  The squared Mahalanobis distance

The latter is distributed chi-square with the former degrees of freedom.  Thus a chi-square mixture QQ plot could be constructed to see if something is going awry.

**Comment by mcneale** [comment]
Right, good idea.  Note, however, that the distribution may vary not only with the number of observed variables but also with which ones have been assessed.  That info is preserved in the data, though we have to be careful about the sort order being the same for both.

Cheers
Mike

Michael C. Neale, Ph.D.
Professor, Virginia Institute for Psychiatric and Behavioral Genetics
Virginia Commonwealth University
Shipping Address: 800 East Leigh St. Suite 1-156, Richmond VA 23219-1534
Mailing Address : Box 980126 Richmond VA 23298-0126
Telephone: (804) 828-3369

On Jul 15, 2018, at 8:07 PM, Michael Hunter <notifications@github.com<mailto:notifications@github.com>> wrote:


In mxFitFunctionML(..., rowDiagnostics=TRUE) we currently return the row likelihoods (really row probability density values). We should also return

  1.  The number of observed variables for each row (numObsVars)
  2.  The squared Mahalanobis distance

The latter is distributed chi-square with the former degrees of freedom. Thus a chi-square mixture QQ plot could be constructed to see if something is going awry.

**Comment by mhunter1** [comment]
I think this is not correct:

> the distribution [of the squared Mahalanobis distance] may vary not only with the number of observed variables but also with which ones have been assessed

The squared Mahalanobis distance (SMD) basically whitens the data.

For `r = S^(-.5) (y - m)`, the variable `r` will have mean of 0 and identity covariance matrix where `m` is the mean, `S` is the covariance matrix, and `S^(-.5)` one of several possible "square root" inverses such that `t(S^(-.5)) %*% S^(-.5) == solve(S)`.

The SMD is `t(r) %*% r`.

I suppose there could be differences in the distribution because we aren't using the saturated means and covariance matrix, but rather the model-implied ones and there could be differential misfit.  If the model-implied mean for `x1` is very close to the saturated one and the mean for `x2`is very far from the saturated one, then the distribution of the SMD will not be chi-square but rather will be generalized chi-square.  Without also having the saturated means and covariance I don't think we could correct for this.  

In this case, it's not so much that the SMD depends on the data distribution, but rather depends on how well the model approximates the saturated model.  Moreover, if the data aren't multivariate normal, all bets are off wrt the distribution of the SMD.

**Comment by mcneale** [comment]
So you would say that the Mahalanobis distance of a point in the space of two standardized variables is equally distributed to that of two variables with variances .1 and 10, means -3 and 5, and covariance .8?  The math is there for taking into account the differences in scale of the variables.  But indeed if model misfit differs then they may depart from being equally scaled.

**Comment by mhunter1** [comment]
Yep.

```
require(mvtnorm)

d <- rmvnorm(1000, mean=c(-3, 5), sigma=matrix(c(.1, .8, .8, 10), 2, 2))
m <- mahalanobis(d, colMeans(d), cov(d))
qqplot(qchisq(ppoints(1000), df = 2), m,
       main = expression("Q-Q plot for" ~~ {chi^2}[nu == 2]))
qqline(m, distribution = function(p) qchisq(p, df = 2),
       prob = c(0.1, 0.6), col = 2)
```

**Comment by mhunter1** [comment]
@jpritikin what is the relative merit of changing `omxFIMLFitFunction->rowLikelihoods` to be an Nx3 matrix from an Nx1, versus adding two more `omxMatrix* ` objects to the `omxFIMLFitFunction` object class definition?  If that's not clear, I can elaborate.

**Comment by mhunter1** [comment]
What do we want to do about all ordinal, joints, and all continuous cases.

Super strict:
1. All Ordinal: all NA
1. Joint: all NA
1. All Continuous: report number of observed variables and (squared) Mahalanobis distance

Less strict:
1.  All Ordinal: all NA
1. Joint: report number of continuous variables and (squared) Mahalanobis distance for continuous variables
1. All Continuous: report number of observed variables and (squared) Mahalanobis distance

Something smarter?

**Comment by mhunter1** [comment]
This?

<a href="https://www.codecogs.com/eqnedit.php?latex=\int_{-\infty}^{\infty}&space;x_i&space;~\Phi({x_i})&space;~dx_i" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\int_{-\infty}^{\infty}&space;x_i&space;~\Phi({x_i})&space;~dx_i" title="\int_{-\infty}^{\infty} x_i ~\Phi({x_i}) ~dx_i" /></a>

where Phi(x_i) is the (univariate) normal density, and x_i is the candidate observed variable, and you do this for each candidate observed variable separately.

This is definition of the mean (i.e. expected value) of x_i when x_i has probability density function Phi().

For ordinal variables we'd want something (ideally) that is chi-square distributed.

**Comment by mcneale** [comment]
Yes, except that the average Mahalanobis distance is what is desired, which I believe requires a multiple integral over all the dimensions (observed variables).  If some or all are independent you can cheat a bit by doing the independent blocks separately.
