### ISSUE TITLE
allow logLik.MxModel to handle list input

### ISSUE THREAD

**Issue by tbates** [OpenMx/OpenMx#94]
I am wanting a list of AICs, but offering up a vector of models reveals logLik.MxModel doesn't handle lists? Be good if it did. Other classes do.

```splus
AIC(c(m1,m1))
# Error in UseMethod("logLik") : 
#  no applicable method for 'logLik' applied to an object of class "list" 
```

**Comment by jpritikin** [comment]
I don't think it is feasible to handle a list, but we can certainly handle more than 1 model at a time. See v2.9.9-271-gd06d746e9

**Comment by mcneale** [comment]
It doesn’t seem to like the same object twice in the c().  Does it work with different ones?

**Comment by tbates** [comment]
who'd a thunk it.. !

Works:

```
AIC(HSModel, m1, m2)
        df        AIC
HSModel 21 11012.9032
m1       9   687.5976
m2       3   294.7967
Warning message:
In AIC.default(HSModel, m1, m2) :
  models are not all fitted to the same number of observations
```

fails:

```
AIC(m1, m1, m2)
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning messages:
1: In AIC.default(m1, m1, m2) :
  models are not all fitted to the same number of observations
2: non-unique value when setting 'row.names': ‘m1’ 
> AIC(HSModel, m1, m2)

```

**Comment by jpritikin** [comment]
So we can leave this issue closed?

**Comment by RMKirkpatrick** [comment]
@tbates : `AIC(m1, m1, m2)` fails because the 'logLik' method for MxModels is trying to make an output table the rownames of which are the names of the MxModel objects.  It chokes on duplicate rownames.

Also, note that `c(m1,m2)` is going to return a list, not a vector.  [Vectors can only contain elements of the six basic R datatypes.](https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Vector-objects)

**Comment by mcneale** [comment]
We could, I suppose, automagically rename duplicate rows with _1 _2 etc.  How useful that would be I'm not sure.

**Comment by tbates** [comment]
I guess for OpenMx, users quite often have models they don't bother to rename - so it will bite people doing `AIC(c(m1, m2, m3))` ... Probably handy if our `logLik` method appends a number to disambiguate duplicate row names `omxUniquify` :-)
