### ISSUE TITLE
Re-arrange columns of 'CI details' table

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#95]
I've been helping users troubleshoot their confidence intervals recently, and I have found that the free-parameter values at each confidence limit are almost never of interest.  They should still be there, but their quantity varies with the number of explicit free parameters in the model.  They should all be to the right of the most important 7 columns: the "parameter", "side", "value", "fit", "diagnostic", "statusCode", and "method" columns, in that order.

This way, users can always just print the first seven columns to get the most important information.  And, if they want the vector of free parameters at the confidence limit, they can always just take elements 8 thru ncol(myFitSumm$CIdetail) of the row for that limit.

This is related to, but distinct from, #78 , which concerns the formatting of the main CI table.

**Comment by jpritikin** [comment]
v2.9.9-278-g96c3ed8d6

**Comment by RMKirkpatrick** [comment]
Thanks, @jpritikin !

**Comment by jpritikin** [comment]
Yeah, I recall that you mentioned this a few times, but you really made it easy by suggesting the exact new column ordering.
