### ISSUE TITLE
Create 'auto' option for 'Default optimizer'

### ISSUE THREAD

**Issue by mhunter1** [OpenMx/OpenMx#96]
For example, ```mxOption(NULL, ''Default optimizer, 'auto')``` would be the on-load default.  This will be settable by the user.

The idea is to change the optimizer depending on the model being run.  We'd set the optimizer to whichever one we think is best.

* For unconstrained problems use the current default: CSOLNP
* For unconstrained problems with CIs, use CSOLNP for the MLE and use SLSQP for the CIs
* For problems with constraints use SLSQP
 
and so on.

**Comment by RMKirkpatrick** [comment]
I'll take this one.  I think it will mesh nicely with some code streamlining I've been thinking about.

**Comment by tbates** [comment]
Does this still appear a good idea? Seems default SLSQP is working best, users with twins grab the NPSOL binary, and the exceptions being solved model by model?

**Comment by RMKirkpatrick** [comment]
> Does this still appear a good idea?

I no longer think it's a good idea.  Let's close this issue.
