### ISSUE TITLE
Different behaviour when loading or attaching

### ISSUE THREAD

**Issue by ToMul09** [OpenMx/OpenMx#98]
I'm using the package "metaSEM" and encountered a different behaviour depending on whether the package is loaded or attached. I posted the issue in the "OpenMx" repository since I'm assuming it is related to "OpenMx". If I just load "metaSEM" (and thereby also load "OpenMx"), the following code
```{r}
example_data <- data.frame("y" = 1:5, "v" = 1 / 5:1)
loadNamespace("metaSEM")
ml_fit <- metaSEM::meta(y = y, v = v, data = example_data, intervals.type = "LB")
ml_fit_summary <- summary(ml_fit)$coefficients["Intercept1", ]
c("pointEst_effect" = ml_fit_summary$Estimate, 
  "CI_lower" = ml_fit_summary$lbound, 
  "CI_upper" = ml_fit_summary$ubound)
```
produces:
```{r}
pointEst_effect        CI_lower        CI_upper
       2.820254              NA              NA
```
However, if I _attach_ the package (after restarting the R session), the following code
```{r}
example_data <- data.frame("y" = 1:5, "v" = 1 / 5:1)
library(metaSEM)
ml_fit <- meta(y = y, v = v, data = example_data, intervals.type = "LB")
ml_fit_summary <- summary(ml_fit)$coefficients["Intercept1", ]
c("pointEst_effect" = ml_fit_summary$Estimate, 
  "CI_lower" = ml_fit_summary$lbound, 
  "CI_upper" = ml_fit_summary$ubound)
```
produces:
```{r}
pointEst_effect        CI_lower        CI_upper
       2.820255        1.439689        4.388500
```
For other example data, I even get non-NA CI bounds when loading the package (but not attaching it) which differ slightly from the CI bounds when attaching the package (making it even harder to tell that there's a difference when looking at the results at a first glance).
After inspecting the source code of "metaSEM" and "OpenMx", I think the problem might be the definition of .onLoad() in "OpenMx": In .onLoad(), default options are set which somehow seem to be overwritten when attaching the package. You can tell that by running
```{r}
example_data <- data.frame("y" = 1:5, "v" = 1 / 5:1)
library(metaSEM)
OpenMx::mxSetDefaultOptions()
ml_fit <- meta(y = y, v = v, data = example_data, intervals.type = "LB")
ml_fit_summary <- summary(ml_fit)$coefficients["Intercept1", ]
c("pointEst_effect" = ml_fit_summary$Estimate, 
  "CI_lower" = ml_fit_summary$lbound, 
  "CI_upper" = ml_fit_summary$ubound)
```
which produces the same result as when loading the package (but not attaching it). So my question is: Is this intentional behaviour or might this be a bug?

**Comment by tbates** [comment]
Seems to have the same behavior

`OpenMx version: 2.9.9.291 [GIT v2.9.9-291-g3f03ad96-dirty]`

```Splus
> example_data <- data.frame("y" = 1:5, "v" = 1 / 5:1)
> loadNamespace("metaSEM")
<environment: namespace:metaSEM>
> ml_fit <- metaSEM::meta(y = y, v = v, data = example_data, intervals.type = "LB")
> ml_fit_summary <- summary(ml_fit)$coefficients["Intercept1", ]
> c("pointEst_effect" = ml_fit_summary$Estimate, 
+   "CI_lower" = ml_fit_summary$lbound, 
+   "CI_upper" = ml_fit_summary$ubound)
pointEst_effect        CI_lower        CI_upper 
       2.820254              NA              NA 

> example_data <- data.frame("y" = 1:5, "v" = 1 / 5:1)
> library(metaSEM)
"SLSQP" is set as the default optimizer in OpenMx.
mxOption(NULL, "Gradient algorithm") is set at "central".
mxOption(NULL, "Optimality tolerance") is set at "6.3e-14".
mxOption(NULL, "Gradient iterations") is set at "2".
> ml_fit <- meta(y = y, v = v, data = example_data, intervals.type = "LB")
> ml_fit_summary <- summary(ml_fit)$coefficients["Intercept1", ]
> c("pointEst_effect" = ml_fit_summary$Estimate, 
+   "CI_lower" = ml_fit_summary$lbound, 
+   "CI_upper" = ml_fit_summary$ubound)
pointEst_effect        CI_lower        CI_upper 
       2.820255        1.439689        4.388500 
> 
```

**Comment by ToMul09** [comment]
I can't install the current GitHub version. Running `devtools::install_github("OpenMx/OpenMx")` gives:
```{r}
fatal error: omxSymbolTable.h: No such file or directory
```

**Comment by jpritikin** [comment]
Oh wait, this difference is probably due to MetaSEM picking different defaults depending on whether it is loaded or attached.

**Comment by ToMul09** [comment]
Oh yes, there is no .onLoad() but only an .onAttach() function in "metaSEM". Sorry for any inconvenience that I caused.

**Comment by ToMul09** [comment]
I guess your commit 3f03ad9 is redundant then. Sorry.
