### ISSUE TITLE
Redundant constraints

### ISSUE THREAD

**Issue by RMKirkpatrick** [OpenMx/OpenMx#99]
[180816--oneACEo.R.txt](https://github.com/OpenMx/OpenMx/files/2294228/180816--oneACEo.R.txt)

I'm attaching a simple script adapted from one of Hermine's Boulder scripts.  It's a monophenotype ACE model with an ordinal trait, and uses an equality MxConstraint to identify the model.  The script deliberately puts the MxConstraint into the container MxModel, the MZ submodel, and the DZ submodel, thereby making it redundant.  A few remarks:

1. The constraint should only contribute one observed statistic.  But, due to the redundancy, it is counted thrice, and therefore contributes 3.  That bogus increase in the degrees of freedom is benign in many cases where raw data are being analyzed, but it could actually make a difference in analysis of covariance data, or even in analysis of raw data with very small samples.
2.  NPSOL uses a "working set," which is a subset of the set of active constraints, such that the constraint derivatives are linearly independent.  So, redundant equality constraints are no problem for NPSOL.  Joshua's API to SLSQP has code to check for redundant equality constraints every time the constraint functions are evaluated; a constraint is considered redundant for an evaluation if it has the same function value and Jacobian row as another.  CSOLNP appears to have code meant to detect redundant constraints (involving the SVD of the Jacobian?), but whatever it's doing doesn't appear to be adequate.  In the attached script, CSOLNP chokes on the model when it has the redundancy, but is OK when it doesn't.
3.  My Nelder-Mead implementation won't work properly if there are redundant equality constraints.  Nelder-Mead needs to know the correct number of equality constraints to know how many vertices the simplex should have.

**Comment by RMKirkpatrick** [comment]
Unrelated to redundant constraints...take a look at the CI details for the model when run with NPSOL, versus when run with CSOLNP after the redundant constraints have been removed.  NPSOL is reaching confidence-limit solutions that violate the lower bound on parameter `c11`, but all of its confidence limits are diagnosed as "success."  In contrast, CSOLNP is reaching confidence-limit solutions that are on, and not beyond, the lower bound for `c11`, and yet those confidence limits are diagnosed as "active box constraint".  Something's wrong here.  I already alerted @jpritikin about this.

**Comment by RMKirkpatrick** [comment]
[180816--dependentconstraints.R.txt](https://github.com/OpenMx/OpenMx/files/2295159/180816--dependentconstraints.R.txt)

Consider also the attached script.  It uses two equality constraints, where one of the constraint functions is a linear function of the other.  That's not something SLSQP can handle (nor CSOLNP), but NPSOL gets the right answer.

**Comment by tbates** [comment]
Is the answer to
1. Stop writing scripts that include the same objects multiple times (seems wise)
2. Detect redundant constraint objects and warn the user (seems helpful)
3. Develop new methods to cope with this (seems hard and unnecessary given 1?)

**Comment by RMKirkpatrick** [comment]
@tbates 

1. I agree it would be wise to stop writing scripts that include the same object more times than necessary.  But we can also make OpenMx a bit smarter about counting equality constraints.  Recall that I'm planning to make some changes to allow OpenMx to calculate standard errors appropriately when there are MxConstraints.  One of those changes is for the constraint Jacobian to always be calculated as part of the MxComputeNumericDeriv step.  That step could also determine how many linearly independent equality constraints there actually are at the solution, and thereby adjust the degrees-of-freedom.
2.  Even better: change CSOLNP and the SLSQP API so that they detect and ignore redundant constraints in the same way that NPSOL does.
3.  I was thinking about this recently.  I should make a change to my Nelder-Mead such that it requests the Jacobian of the equality constraints at the start values, determines its rank, and warns the user if there appear to be redundant equality constraints.

I typed this assuming that your 1, 2, and 3 were meant to refer to the 1, 2, and 3 in my OP.  But I just realized now maybe that's not right.  Oh well.

**Comment by RMKirkpatrick** [comment]
I put some thought into this issue this afternoon.  Nelder-Mead just needs to be taught to ask for the rank of the equality-constraint Jacobian at the start values, and warn if the Jacobian is not full-rank.  That's a warning and not an error because, while it's true that my Nelder-Mead implementation doesn't work properly when there are redundant equality constraints, it is intended for use with non-differentiable constraint functions, and there may appear to be spurious linear dependence amongst such constraints at the start values.

SLSQP (really, our API to SLSQP) and CSOLNP both need to learn to deal with redundant MxConstraints.  Our API to SLSQP currently tries to detect redundant equality constraints only, and is able to detect identical equality constraints but not linearly dependent equality constraints.  I'm not sure if SLSQP itself has some way of dealing with redundant INequality constraints.  CSOLNP has some code to detect an ill-conditioned Jacobian, but it is currently hard-coded to be switched off, and ill-conditioning is not the same thing as rank-deficiency.  Neither NPSOL's documentation nor either of the Gill, Murray, & Wright books I have on my office bookshelf explain how to drop Jacobian rows to get a full-rank Jacobian.

So, we need to choose some way of identifying a maximal linearly independent subset of Jacobian rows, using features of the Eigen library (and/or BLAS subroutines?).  I am not sure what the best way of doing that would be.  Any suggestions?  @mhunter1 ?

**Comment by mhunter1** [comment]
Do we really need to do anything in terms of modifying the constraints?  Or is this just a counting problem at the end?

If it is the latter, then we only need to compute the constraint Jacobian once (after optimization) and get its numerical rank (e.g. via a QR factorization).  The rank of the constraint Jacobian gives the number of linearly independent constraints.

**Comment by RMKirkpatrick** [comment]
@mhunter1 So, this issue is actually a matter of 3 related but distinct issues.  Number 1 is the "counting problem at the end"; we want OpenMx to correctly adjust the degrees-of-freedom if there are redundant equality constraints.  Number 2 is the fact that SLSQP and CSOLNP choke on some optimization problems involving redundant constraints (whereas NPSOL does not).  Number 3 is specific to Nelder-Mead and redundant equality constraints, and I already have a fix planned for it.

Number 2 is the one that calls for modifying the constraint Jacobian, _during optimization_, such that it is full rank.  That is, we want to retain only a maximal linearly independent subset of its rows.

**Comment by mcneale** [comment]
I think if we automagically change the df based on the number of linearly independent (non-redundant) constraints, we stand a chance of df ending up a function of the covariance structure of the data.   Empirical (local) underidentification can happen for parameters, so I figure it can happen for non-linear constraints as well.  At the very least, we should put in large letters that the df were altered.   I think this should transfer to summary, so that the user gets notified if df adjustment of this sort has happened.

I think the math behind eliminating  some of the constraints a la NPSOL is likely not too hard to employ in other optimizers.  Taking the Cholesky of the Hessian and looking for zeroes on the diagonal should get some of the way there...

**Comment by RMKirkpatrick** [comment]
Just for the record: as I explained [here](https://github.com/OpenMx/OpenMx/issues/108#issuecomment-473469531), I believe this issue is related to issue #108 .

Also, this issue seems to be specific to redundant INequality constraints.  Concerning #(1) in my OP, inequalities don't affect the df because they don't reduce the dimension of feasible space.  Concerning #(2) in my OP, redundant inequalities don't seem to bother the gradient-based optimizers (see next paragraph).  And concerning #(3) in my OP, since inequalities don't reduce the effective dimensionality of the free-parameter space, they don't affect how many vertices the Nelder-Mead polytope has.

I just ( 5c01942 ) added a test for the robustness of all 3 gradient-based optimizers to redundant inequalities; in the next commit, I changed the test to start at infeasible parameter values.  Additionally, we've had a test for a long time that involves redundant inequalities, models/passing/AnalyticConstraintsJacobians--Eq_and_Ineq.R .  However, unlike the new Bukin N2 test, that test neither starts at an infeasible point nor ends at a solution where the inequalities are active.

**Comment by RMKirkpatrick** [comment]
#(3) from my OP (specific to Nelder-Mead) is as resolved as it'g going to get as of 12ca163 .

**Comment by RMKirkpatrick** [comment]
As of cd50601 , CSOLNP no longer hangs when running [180926--CSOLNP_hangs.R.txt](https://github.com/OpenMx/OpenMx/files/2424588/180926--CSOLNP_hangs.R.txt) (which uses redundant equality constraints).  I can tell its not getting stuck in a closed loop because the non-persistent backend printing does update the number of function evaluations, meaning that control is periodically passing to the global state (which does the printing).  However, CSOLNP doesn't make any progress.  The number of function evaluations just goes up, but the fitfunction value is reported as nan.  I'm a little surprised the optimization doesn't get stopped, with status code 10.

Still, it's an improvement over CSOLNP silently entering a closed but interruptible loop, which itself is an improvement over CSOLNP silently entering an uninterruptible loop and making the user force-kill R.

**Comment by mcneale** [comment]
Good work Rob; on behalf of OpenMx users everywhere, thank you!

**Comment by RMKirkpatrick** [comment]
The ideal fix for issue (2) in my OP would be to teach SLSQP and CSOLNP to detect and work around redundant equality constraints.  Our API to SLSQP already has code to detect and workaround equality constraints that are redundant in the sense that they are identical to at least one other equality constraint.  The detected redundant constraints are "masked".  That is, their Jacobian rows are set to zero, and their function values simply aren't put into the array of constraint-function values that SLSQP sees (I suspect that array is initialized as all zeroes).  That's enough to accomplish the goal of filtering them without confusing SLSQP.  However, it does not detect equality constraints that are redundant in the sense of being linearly dependent on one or more others.

CSOLNP currently has no executable code to detect and work around redundant equality constraints.  Interestingly, it has disabled code that tries to detect redundancy from the condition number of the Jacobian, and throws a fatal error if the condition number is too small.  I find it notable that apparently, at least at one point, Mahsa considered redundant constraints to be a failure condition for CSOLNP.  I have no idea how much work it would be to teach CSOLNP how to deal with redundant equality constraints.

We should discuss as a team what to do about issue (1) in my OP: degrees-of-freedom reporting when there are redundant equalities..

**Comment by RMKirkpatrick** [comment]
Interestingly, Mplus also chokes on redundant equality constraints:
http://www.statmodel.com/discussion/messages/13/24676.html?1509391097
http://www.statmodel.com/discussion/messages/13/20479.html?1551835675

**Comment by tbates** [comment]
I wonder if we should just leave users to control redundancy, just like we allow them to add more paths than they have df in a RAM model.

**Comment by mcneale** [comment]
I think at the very least we should detect them and notify the user.  No need to drift down to the lowest  common denominator's behavior.

**Comment by RMKirkpatrick** [comment]
> I think at the very least we should detect them and notify the user.

That's currently the plan, at least in the case where the model _df_ needs to be adjusted.  But I would really like it if CSOLNP and SLSQP could both work properly in the general case of linearly dependent equalities, and I'd still be happy if CSOLNP worked as well as SLSQP in the special case of equivalent equalities.

I'm uncomfortable that (1) only the proprietary optimizer copes with the general case of redundant equalities, and (2) the on-load default optimizer is currently the most inept of the three at dealing with them.

**Comment by mcneale** [comment]
I have the same two discomforts.

**Comment by RMKirkpatrick** [comment]
See 3a30d62 and 9f29afa .  The MxComputeNumericDeriv step now checks to see if the equality-constraint Jacobian is full rank, and if not, stores the count of extraneous equality constraints and warns the user.  What we could do now is export the count of redundancies to the frontend one way or another, and redefine `summary.MxModel` or whatever to use it to adjust the model df.  But first, we ought to make sure that the new behavior correctly identifies rank-deficient systems of equalities, and _doesn't_ misidentify full-rank systems as rank-deficient.  Computationally, the system can only be full-rank within a certain tolerance.  I'm currently using the Eigen library's default tolerance, which seems reasonable.

Please test a few constrained MxModels to see if the new code gives false alarms.  I already verified that it gives true positives to the two redundant-equality models in our test suite.

**Comment by RMKirkpatrick** [comment]
I have a reasonably clear idea how I might change our interface to SLSQP to make it robust to linearly dependent equalities generally.  But, after trying today to improve CSOLNP in a similar regard, I'm pretty discouraged about it.  CSOLNP makes it tough, because it doesn't separately handle equalities and inequalities, and I'm not sure what can be safely assumed about the dimensions of its Jacobian matrix.

**Comment by RMKirkpatrick** [comment]
> Please test a few constrained MxModels to see if the new code gives false alarms. I already verified that it gives true positives to the two redundant-equality models in our test suite.

Has anyone else done any such testing?  I just found that the new code does give a false alarm for models/passing/AnalyticConstraintJacobians--Eq_and_Ineq.R .  I'm not sure what to do about that.

**Comment by RMKirkpatrick** [comment]
Look at 570eb68 .  It's a failed attempt to get CSOLNP to filter out redundant rows of the constraint Jacobian, and set the redundant constraint functions to zero.  However, a variation on its code might work in our API to SLSQP, as a way to get SLSQP working in the general case of linearly dependent equalities.

I fear the best I'm going to be able to do with CSOLNP is to teach it to warn if the Jacobian is rank-deficient at the start values.

**Comment by RMKirkpatrick** [comment]
See d400ab6 .  I disabled the warning about excess equalities that's raised during the ComputeNumericDeriv step.  Eigen's 'FullPivHouseholderQR' class gives false alarms about rank-deficiency, at least at its default threshold (which seems to be a reasonable value).  The backend has to get the number of extraneous equality constraints right if we're going to use that information to adjust the number of observed statistics.

See beb4182 .  CSOLNP now warns if the constraint Jacobian is rank-deficient at the start values.   Since CSOLNP also no longer gets stuck in uninterruptible endless loops, that's going to have to be good enough.

Since our interface to SLSQP deals with the most common form of linearly dependent equality constraints--namely, identical equality constraints--I am not sure if it is worth it to try to get SLSQP to handle the general case.

**Comment by RMKirkpatrick** [comment]
#323 is now closed.  This issue can be closed, too.
